### ISSUE TITLE
Refactor code to remove liberal use of the `var` keyword

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1007]
The MSDN guidelines state that `var` should only be used when the information on the right of the assignment is identifiable as a specific type.

e.g.

### Correct
 * `var mydata = 1f` is fine because it's obvious it's a float
 * `var mydata = true` is fine because it's obvious it's a bool
 * `var mydata = "string"` again is acceptable
 * `var mything = GetComponent<MyThing>()` is obvious you're getting a component of type MyThing

### Incorrect
 * `var mything = SomeFunctionThatReturns()` is not correct as it's not obvious what the type will be
 * `var mydata = 2` is not correct because it's not obvious what type 2 is supposed to be

**Comment by ajjohnston** [comment]
Not sure if you're looking for help on this (noticed replacements for `var` => explicit type in another PR you made), but I'm willing to help if needed. Been wanting to learn this codebase better.

**Comment by thestonefox** [comment]
@ajjohnston yeah I'm just doing it a bit at a time, every time i touch a piece of code i just make sure to clean it up :)

**Comment by virror** [comment]
Thank you! I hate var : p

**Comment by bddckr** [comment]
I agree with @virror here, even though I hate lines like `Dictionary<MyWayTooLongTypeName, SomethingSomethingValueType> myWayTooLongDictionary = new Dictionary<MyWayTooLongTypeName, SomethingSomethingValueType>();`

**Comment by dantman** [comment]
Is there no way to make VS/the IDE help out? For example in JS we have eslint which is pluggable, has fully customizable rules, has a `--fix` mode, and popular editors like Sublime Text and Atom have linter plugins that integrate warnings, errors, and line indicators into the editor.

**Comment by bddckr** [comment]
Visual Studio allows one to set this stuff up, it also has auto formatting. There's also Resharper.
Both have per-project settings files that can and actually are included in this repo, but are probably just too old and weren't updated to force most of the current style.

**Comment by virror** [comment]
Not everyone is using VS either.
