### ISSUE TITLE
NullreferenceException in TransformFollow

### ISSUE THREAD

**Issue by proepkes** [thestonefox/VRTK#1017]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (67ac22f)
 * Version of Unity3D (5.5.0)

### Steps to reproduce

Example 010 TerrainTeleport. Try to teleport somewhere, the pointer gets stuck at (0,0,0). Console outputs Nullpointerexception at VRTK_TransformFollow.CacheTransforms line 136

Changing line 130 with 

`if (gameObjectToFollow == null || gameObjectToChange == null)`

fixed it for me

**Comment by thestonefox** [comment]
Does this PR fix it for you?

https://github.com/thestonefox/VRTK/pull/1016

**Comment by proepkes** [comment]
Yep

**Comment by thestonefox** [comment]
Ok cool I've merged that PR in now

https://github.com/thestonefox/VRTK/pull/1016
