### ISSUE TITLE
TwoHandObjects  Ungrab-Event

### ISSUE THREAD

**Issue by Proktologe** [thestonefox/VRTK#1021]
Starting situation: you hold a TwoHandObj (one like in the last new scene-examples) with both controllers.

when you let a "TwoHandObj" down with the first Grabbed Controller there will no ControllerUngrabInteractableObject-Event fired for the 2nd-Grabbed-Controller. So the 2nd Controller will not be informed. (No matter
whether "HoldButtonToGrab" is True or False.)

**Comment by thestonefox** [comment]
Check out this Pull Request for a proposed fix:

https://github.com/thestonefox/VRTK/pull/1041

**Comment by Proktologe** [comment]
Thanks a lot, now it works as expected!
