### ISSUE TITLE
Dynamically load VRTK through code

### ISSUE THREAD

**Issue by jhurlbut** [thestonefox/VRTK#1026]
Is there an example anywhere of dynamically loading VRTK through code instead of setting up through the inspector? My app sets everything up in code based on whether Oculus or Vive is detected and I can't VRTK to update the system type appropriately unless I change it through the inspector.

**Comment by bddckr** [comment]
I actually worked on exactly that the last day and will push it to [my PUN Test project](https://github.com/bddckr/VRTK-PUN-NetworkTest) sometime tomorrow.

My work on that project resulted in #1024 and #1025, that should simplify things a bit. After updating the project I'll probably work on #817 which expands on the idea of using the SDK Manager at runtime. More tomorrow!

**Comment by mcgi5sr2** [comment]
@bddckr how are you getting the VRTK sdk_manager to work in multiplayer? I am struggling to get multiple instances of it running (when attached to a player prefab). I have tried spawning local versions with the player but get similar issues. Which led me here with the idea of dynamically adding the steamVR components to the manager on player spawn, which requires runtime usage.

**Comment by bddckr** [comment]
@mcgi5sr2 Yeah, don't use multiple ones, just set up a single one for your usage. I'm 90% finished on my test project linked above and will post here when done. You can also watch that repository to get notifications when I do something (you can set GitHub's settings to even email you then).

**Comment by mcgi5sr2** [comment]
Thanks man, been driving me up the wall. If I could just call the sdk setup functions on player join && if player is VR it would be fine.

**Comment by bddckr** [comment]
@mcgi5sr2 The project does include an "SDK Chooser" now. Have a look.

**Comment by mcgi5sr2** [comment]
@bddckr the latest version of VRTK allowing for run time population/assignment of VR controllers etc is excellent, but I am struggling to find a method of calling it before the GameObject the VRTK_sdkManager is attached is activity (thus causing unity to crash due to the headset etc variables not being defined).

**Comment by bddckr** [comment]
@mcgi5sr2 I just start with the SDK Manager game object being disabled and then enable it after setting everything up. You can see that in the example project [here](https://github.com/bddckr/VRTK-PUN-NetworkTest/blob/master/Assets/Scripts/SDKChooser.cs#L104).

**Comment by bddckr** [comment]
@mcgi5sr2 I also suggest you to join our [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) for these back and forth discussions 😄

**Comment by thestonefox** [comment]
This will be resolved with this: https://github.com/thestonefox/VRTK/issues/817

(i assume)

**Comment by bddckr** [comment]
Yup!
