### ISSUE TITLE
Expose VRTK_DestinationPoint Collider(s?) to Editor

### ISSUE THREAD

**Issue by SK83RJOSH** [thestonefox/VRTK#1027]
Currently Destination Points create a Collider / use the first Collider available in the objects children. It'd be very helpful to allow us to specify what Collider to use through the inspector so we have more fine grain control.

**Comment by thestonefox** [comment]
The Destination Point only really works with 1 collider. If you were to have multiple colliders then the script would not work as intended because it would enable/disable the specified collider but all other colliders would not be affected.

What use case is there for a destination point needing multiple colliders?

**Comment by SK83RJOSH** [comment]
In my case I'd like to parent multiple colliders to the bones of my agents, but it's quite an edge case. I'd be perfectly happy just to be able to specify what collider is used when there's multiple in the hierarchy, though. 😄

**Comment by thestonefox** [comment]
but if there are multiple colliders then the destination point would fail as it turns on/off the specific collider to prevent being able to activate itself when you're standing on that specific destination point.

If you specified a collider but there were still other colliders, then it would turn off the specified collider but the other colliders would still be active and that would break the destination point functionality.

**Comment by SK83RJOSH** [comment]
Okay, I understand the problem now. For some reason I assumed you were checking for collisions with specific colliders, and not any collider on the object.

**Comment by thestonefox** [comment]
It's just the raycast from the pointer that hits the collider. So there's no internal checking for collisions within the destination point script. It's just all standard Unity collisions.
