### ISSUE TITLE
Knob uses global rotation

### ISSUE THREAD

**Issue by MarshallNystrom** [thestonefox/VRTK#1030]
The VRTK_Knob script uses global rotation even when it attached to an object, meaning that rotating the object changes the value even when the knob is not rotated with respect to its parent. It should use local rotation only.

**Comment by thestonefox** [comment]
Have you tried using a `VRTK_Wheel` control instead?

**Comment by thestonefox** [comment]
This seems like the same issue as this:

https://github.com/thestonefox/VRTK/issues/524

I'll merge this into that issue
