### ISSUE TITLE
(forced) Snap Drop Zones do not play nice with Parenting Type

### ISSUE THREAD

**Issue by Fewes** [thestonefox/VRTK#1031]
### Environment

VRTK from Github, 5ddd1ef7df4b192393e5bb1f380177f0cc10d45f
Unity 5.5.2f1

### Steps to reproduce

Create a Snap Drop Zone with Snap Type set to Parenting, create an interactable object, FORCE snap it to the drop zone. Grab the object, release it and then try to grab it again.

### Expected behavior

Should be able to grab the object like normal.

### Current behavior

Cannot grab the object. IsGrabbable has been set to false because VRTK_InteractableObject calls LoadPreviousState from ResetDropSnapType. Because the object was force snapped to the drop zone on game start, no previous state for previousIsGrabbable has been set and it defaults to false, rendering the object ungrabbable.

Fix by adding "previousIsGrabbable = isGrabbable;" to VRTK_InteractableObject, in Awake().

Cheers

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/96239c0278cd84e399246e29a7461fc944bc8874

This issue only affected interactable objects that had a non swappable secondary grab action.
