### ISSUE TITLE
OnControllerUngrabInteractableObject event fires on startup.

### ISSUE THREAD

**Issue by alexhofer** [thestonefox/VRTK#1038]
### Environment

 * Source of VRTK - Unity Asset Store
 * Version of VRTK - 3.1.0
 * Version of Unity3D - 5.5.2f1

### Steps to reproduce

1. Add the VRTK_InteractGrab_UnityEvents script to an already setup script alias object.
2. Populate the OnControllerUngrabInteractableObject list with a script that fires a debug log.
3. Press the play button.
4. Observe the event is fired off instantly when the game starts.

### Expected behavior

The event should only fire when a valid interact-able object is released. 

### Current behavior

The event is firing on start automatically.

**Comment by thestonefox** [comment]
Fixed in https://github.com/thestonefox/VRTK/commit/b4b81713803f98b81291b94321087067af8e8272
