### ISSUE TITLE
Bug: UI "pressed" event

### ISSUE THREAD

**Issue by michidk** [thestonefox/VRTK#1045]
### Environment

 * Source of VRTK: GitHub (thestonefox/VRTK)
 * Version of VRTK: https://github.com/thestonefox/VRTK/commit/c7867b1b2beb7958766f737acee7166b4b426ebb
 * Version of Unity3D: 5.5.2f1
 * SDK: SteamVR
 * Hardware: Oculus & Touch

### Steps to reproduce

Play the "034_Controls_InteractingWithUnityUI"-scene of the examples.
Click on a button, which has a different color for the "pressed"-event.

### Expected behavior

Button changes to the "pressed color" and keeps it as long you keep pressing the trigger (Unity's default behavior).

### Current behavior

The color is shown one frame. After one frame the color changes back to the hover/highlight color.
If you use animations instead of colors, the pressed animation will not trigger (probably because the event is too short).

### Notes
The logic for this misbehaviour can be found in VRTK_VRInputModule.cs (line 186 to 230) respectively VRTK_UIPointer.cs (line 306 to 312).
The easiest fix is to change line 198 from `pointer.pointerEventData.eligibleForClick = (forceClick ? true : pointer.ValidClick(true));` to `pointer.pointerEventData.eligibleForClick = (forceClick ? true : pointer.ValidClick(false));`. But then the OnClick events are called multiple times.

**Comment by thestonefox** [comment]
This isn't a bug. This is because the `Click Method` option is set to `Click On Button Down` so as soon as you press the button the event fires.

If you set it to `Click On Button Up` it will not fire the event until you release the button.

**Comment by michidk** [comment]
Awesome, didn't know that! Since that's the default behavior in Unity, imo the example scene should use it as well.

**Comment by thestonefox** [comment]
It used to be the default behaviour, but the consensus was that vr controls should fire on down and not on up as they're not the same as mouse controls.

**Comment by michidk** [comment]
It is kinda useless to have animations/colors which are not showing up or only showing up one frame which looks buggy.

**Comment by thestonefox** [comment]
That's why it's an option to provide both mechanisms
