### ISSUE TITLE
layers to ignore in VRTK_HeadsetControllerAware

### ISSUE THREAD

**Issue by Anton-Tril** [thestonefox/VRTK#1054]
It would be nice to be able to ignore some layers in this script.

        protected virtual void RayCastToController(..)
        {
.........
                if (Physics.Linecast(headset.position, destination, out hitInfo, ~pleaseAddLayersToIgnoreHere))

**Comment by thestonefox** [comment]
Pull Request with solution: 

https://github.com/thestonefox/VRTK/pull/1058
