### ISSUE TITLE
Add Snap events to InteractableObject

### ISSUE THREAD

**Issue by quintesse** [thestonefox/VRTK#1055]
It would be useful to have a drop zone's snap events reflected on the `InteractableObject`s as well. So that would mean at least `InteractableObjectSnapped` and `InteractableObjectUnsnapped`.

My use-case is networking where one wants to sync objects being snapped/unsnapped across clients. Now one could just use the Drop Zone events themselves but that would mean adding network components to each of the drop zones as well, which certainly is a possibility. But my thinking was that the `InteractableObject`s already tend to have network components associated with them so it would be more efficient to be able to re-use those.

This can still be done with the current code of course by adding scripts on both the object and on the drop zone that would just pass those events from one to the other, but it would be nicer if it was supported by default.

Wdyt? Would that be a worthwhile change in your opinion?

**Comment by bddckr** [comment]
Hmmm... I always tend to stay away from integrating stuff that is easily separated. But given that the interactable objects are already handling snap zone stuff I think that would be fine 😄
