### ISSUE TITLE
DestinationPoint, add optional seperate destination point

### ISSUE THREAD

**Issue by MrJigs** [thestonefox/VRTK#1063]
By adding an additional (optional) destination point this function could be used to simulate teleport portals, magic mirrors and the like. Activating (clicking on) a destination point would then take you to a different location (different room) all together. Alignment of the user along the transform of the destination point.

**Comment by bddckr** [comment]
Listen to the teleport event and load the other scene while fading the headset or just move the camera rig altogether?

**Comment by MrJigs** [comment]
I think I could work out how to listen for the teleport event and work things out from there. I probably should do that as well if only to improve my C# skills :-) but adding a separate transform as the teleport destination seems such a natural extension of this function. When using an object as a DestinationPoint most of the time you wouldn't want to end up inside of the object now would you but just outside of it.

**Comment by thestonefox** [comment]
Yeah the idea of having another child of the Destination Point prefab as being the actual destination location is a good idea.

**Comment by thestonefox** [comment]
Done in https://github.com/thestonefox/VRTK/commit/061af40ed41e2c2ce99e3460b482d4112f2b4571
