### ISSUE TITLE
Provide a set of default animated hand models

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1078]
A set of basic default hand models for use within VRTK with basic animations based on button presses.

![image](https://cloud.githubusercontent.com/assets/1029673/24545372/ce214a6e-15fe-11e7-825b-c55ed70be669.png)

**Comment by paulc755** [comment]
I'll have a look at all my animation programs and see if I can come up with anything useful.

**Comment by dantman** [comment]
Make sure that all the fingers are rigged separately and can be controlled individually.

It looks like the new Knuckles controllers have individual analogue values for every finger, including individual curl sensing for each of the 3 fingers on the grip.

![Knuckles Controller Diagram](https://steamuserimages-a.akamaihd.net/ugc/847089117790677890/EC0CF3744132AEE54770B1F51644BDA80A839AB4/)
https://steamcommunity.com/sharedfiles/filedetails/?id=943406651

![Finger Tracking Demo Scene](http://cloud-3.steamusercontent.com/ugc/863978009991617455/FAC41151D48371FB7B53BD98B4D90BD549827A65/)
https://www.youtube.com/watch?v=kovhtH3r9o0

**SteamVR Knuckles Driver / Demo Scene**
https://steamcommunity.com/sharedfiles/filedetails/?id=953648265

**Comment by projectonegames** [comment]
This might be helpful: 
"Get them from this dropbox here: https://www.dropbox.com/s/v71kr0p5ooaxvhz/HumanHands.zip?dl=0
https://www.blendswap.com/blends/view/17297
In the zip file you should find the following items:
r_hand_skeletal.fbx  <-- replace the identical item in your OvrTouch/Content/Hands/Models/ folder with this
l_hand_skeletal.fbx  <-- replace the identical item in your OvrTouch/Content/Hands/Models/ folder with this
humanHand_3D_COLOR.jpg  <-- put this wherever you prefer to keep textures
humanHand_3D_NRM.jpg  <-- put this wherever you prefer to keep textures
humanHandSkin.mat  <-- put this wherever you prefer to keep materials
These hands come from a blender model created by SuperDasil: http://www.blendswap.com/blends/view/81285 licensed under the Creative Commons. I have remodeled them a bit to match the Oculus touch sample joint proportions and capped the ends to be a little more pleasing to the eye. Should updated Oculus Touch samples come along with significant changes I can update these to match."

**Comment by thestonefox** [comment]
we already have hand models that were built specifically for VRTK, so no need to worry about license issues
