### ISSUE TITLE
Deprecation messages confusing

### ISSUE THREAD

**Issue by cameronoltmann** [thestonefox/VRTK#1080]
> **NOTE:** Any issue that does not follow the below template will be immediately closed and not re-opened until the template structure is adhered to.

### Precheck

 * Don't see any mention of this in docs or issues

### Environment

 * Current Github (e719f44) Vive SteamVR Unity 5.5.2

### Steps to reproduce

Try to use most deprecated methods or properties

### Expected/current behavior

Message that describes what to use instead.  Or a document somewhere (in documentation.md etc) that describes what's been replaced with what.  As it is some deprecated items have documentation good enough to point you in the right direction, but a lot don't.

Examples:
 * `VRTK_ControllerEvents.grabPressed` is no longer used. This parameter will be removed in a future version of VRTK.

**Comment by thestonefox** [comment]
PR to update the messages and provide alternative methods/variables for deprecated ones:

https://github.com/thestonefox/VRTK/compare/chore/obsolete-messages?expand=1

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/pull/1083
