### ISSUE TITLE
[BoundarySDK] Allow querying and setting show playspace bounds

### ISSUE THREAD

**Issue by cameronoltmann** [thestonefox/VRTK#1081]
> **NOTE:** Any issue that does not follow the below template will be immediately closed and not re-opened until the template structure is adhered to.

### Precheck

 * Don't see this anywhere

### Environment

 * Github e719f44 Unity 5.5.2f Vive/SteamVR

### Steps to reproduce

Try to query, or enable/disable, `SteamVR_PlayArea.drawInGame` with VRTK

### Expected behavior

`SDK_BaseBoundaries` contains methods and/or properties that give access to this functionality

### Current behavior

Write a hacky piece of code that invokes SteamVR directly

**Comment by bddckr** [comment]
I think only SteamVR offers this, but maybe VRTK could offer its own play area drawing in the future?

If you set `SteamVR_PlayArea.drawInGame` at runtime you'll have to work around a design problem with the current `SteamVR_PlayArea`:
- `drawInGame` is only checked in `OnEnable`, so toggle the component off and then on again.

**Comment by cameronoltmann** [comment]
Yeah, I currently set the property and then enable the component. SteamVR disables it promptly after.

**Comment by thestonefox** [comment]
So just so I understand, you want an `SDK_BaseBoundaries.Draw(true/false)` method that just toggles the `SteamVR_PlayArea.drawInGame` bool?

**Comment by cameronoltmann** [comment]
Yeah, that and a way to read the same property

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/1084

**Comment by thestonefox** [comment]
this automatically enables the SteamVR Playarea so you can just call the method to toggle it on and off

**Comment by cameronoltmann** [comment]
Looks good!

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/pull/1084
