### ISSUE TITLE
InteractableObjects gives NullExceptions when touching multiple objects

### ISSUE THREAD

**Issue by relmgren** [thestonefox/VRTK#1088]
### Environment

 * Source of VRTK == Unity Asset Store
 * Version of VRTK ==Unity Asset Store as of 2nd April 2017
 * Version of Unity3D == Unity 5.5.2f1
 * Hardware used == Vive
 * SDK used == OpenVR

### Steps to reproduce

When using the VRTK_InteractableObject on multiple objects and I start touching/using two objects with one controller I get NullException from StartTouching, StopTouching, IsGrabbed. 

I think the reason is that GetGrabbing() can return a null, which is then assigned to grabbingObjects in stopGrabbingInteractions. Then when StartTouching uses StartTouching we get null.

I added nullchecks before the use of grabbingObjects, touchingObjects when they are used in StartTouching etc as such:
            if (grabbingObjects == null)
            {
                grabbingObjects = new List<GameObject>();
            }
This removed the problem. I think a better solution is to not return null in GetGrabbing, instead return a empty list.

### Expected behavior
No null exceptions lol
### Current behavior
Null exceptions.

**Comment by thestonefox** [comment]
Have you tried this in the latest github master version?

**Comment by relmgren** [comment]
No, I have not. But when I look at the latest master version on git the same functions should produce the error.

On row 517:
`public virtual GameObject GetGrabbingObject()
 {
        return (IsGrabbed() ? grabbingObjects[0] : null);
 }`
The above can return null, and then when it is called on row 883 it assigns grabbingObject as null:

`        protected virtual void ForceReleaseGrab()
        {
            var grabbingObject = GetGrabbingObject();
            if (grabbingObject)
            {
                grabbingObject.GetComponent<VRTK_InteractGrab>().ForceRelease();
            }
        }`

Later when we try to use grabbingObjects e.g in IsGrabbed we try to get Count from grabbingObjects, which is null.

`public virtual bool IsGrabbed(GameObject grabbedBy = null)
        {
            if (grabbingObjects.Count > 0 && grabbedBy != null)
            {
                return (grabbingObjects.Contains(grabbedBy));
            }
            return (grabbingObjects.Count > 0);
        }`

**Comment by thestonefox** [comment]
Can you provide steps to reproduce in an example scene

**Comment by relmgren** [comment]
Hmm. I tried but to no success. I probably fiddled with the parameters in my own project. Thanks for quick answers anyway!
