### ISSUE TITLE
VRTK_InteractUse.ManageInteractTouchListener is never used

### ISSUE THREAD

**Issue by bddckr** [thestonefox/VRTK#1093]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: fc51ae54c5b8b11bdbd9c6b7d551c4a58bdb47e6
 * Version of Unity3D: 5.4.4f1
 * Hardware used: Vive
 * SDK used: SteamVR

### Steps to reproduce

This is a code problem, but also probably an issue when overriding the use button on Interactable Objects. Therefore one should test the example scenes and test whether overriding the use button on the IO works correctly (see below).

### Expected behavior

`VRTK_InteractUse.ManageInteractTouchListener` is used or removed from the code base.

### Current behavior

`VRTK_InteractUse.ManageInteractTouchListener` is never used. It looks like it should be, though. Since the listener method it adds to the `VRTK_InteractTouch` script's events do some stuff with regard to the used button for using.
I guess overriding the use buttons in `VRTK_InteractableObject` is currently broken because of this.

**Comment by bddckr** [comment]
Note: I'm logging this here to remember @thestonefox. I've not checked whether the mentioned override bug is really there.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/80520da1c0821cdfc5239652686828e192cea73c
