### ISSUE TITLE
Need a way to set Snap Positions for TwoHandetObject 

### ISSUE THREAD

**Issue by Proktologe** [thestonefox/VRTK#1095]
I would like to have a way to set the position of both controllers by a TwoHandedObject. So for example for wheelbarrow handles ... on the left and right side or by guns on specific positions. 

I think it's more realistic to define the the position of the first and the second grabbed hand and not for left and right Hand.

Or is it already possible to determine the snap positions for first grabbed hand(controller) and sencend grabbed hand?

**Comment by thestonefox** [comment]
I don't think it would be possible to have a snap position for two controllers unless you're snapping the actual controller model somewhere that the real controller doesn't exist

you can't snap an object between two controllers that you can move apart in the real world.

At best you could do something like a pool cue where it snaps in a world location and then the other controller just controls it's motion.

But a gun wouldn't work with two snapping points I don't think

**Comment by Proktologe** [comment]
Ok.

But the VRTK_ControlDirectionGnapAction-Script will snap a contoler at a position and i would like to set this position by a Snap-Transform. So like all other snap-able Scripts. Is there a way?

**Comment by thestonefox** [comment]
I think this issue and this one https://github.com/thestonefox/VRTK/issues/1224

Are very similar, so I'm going to merge them
