### ISSUE TITLE
VRTK_Pointer activateOnEnable doesn't initialize interaction

### ISSUE THREAD

**Issue by claytmcneil** [thestonefox/VRTK#1103]
### Environment

 * GitHub 
 *  Unity3D 5.5.0f3

### Steps to reproduce

When using VRTK_Pointr configured for:
    Hold Button to Activate = False
    Activate on Enable = True
    Interact with Objects = True

the pointer starts out as activated but does not interact with objects. After toggling the pointer, interact-ability begins.

After some debugging, a theory about the problem is that OnEnable() is being called before Start() which results in SetupRenderer() being called before FindController(). The result is that when InitializePointer() is called on VRTK_BasePointerRenderer.cs, controllingPointer.controller is still null and therefore the ObjectInteractor doesn't get created.

There also appears to be a second issue, CreatePointerObjects() in VRTK_StraightPointerRenderer.cs is called in OnEnable() in VRTK_BasePointerRenderer.cs, which results in the interaction of the pointer being toggled off.

Current hack is to change SetupController() in VRTK_Pointer.cs OnEnable to FindController() and move the activateOnEnable condition down to Start().

**Comment by thestonefox** [comment]
PR to fix the issue: https://github.com/thestonefox/VRTK/pull/1115
