### ISSUE TITLE
Head fade on Rift still allows you to see through walls

### ISSUE THREAD

**Issue by quintesse** [thestonefox/VRTK#1105]
### Environment

 * GitHub
 * f46a07aa6455d4c0c59349f346b50aaad2cc55d4
 * 5.5.1f1
 * Oculus
 * Oculus Utilities

### Steps to reproduce

Using Example 11 HeadSetCollisionFading putting your head inside the wall ever so slightly (putting your head in sideways works even better) still allows you to see through to the other side of the wall.

### Expected behavior

You should not be able to see through the wall

### Current behavior

You can see through the wall

The headset collider might need to be a little bigger to prevent this from happening.

**Comment by thestonefox** [comment]
What version of Oculus Utilities are you using?

**Comment by thestonefox** [comment]
First issue seems to be the headset collider is too small for the rift so it doesn't fade before you start clipping.

Second issue seems to be it doesn't fade completely to black and  you can still faintly see through,

**Comment by thestonefox** [comment]
Fix for the not completely fading to black issue.

https://github.com/thestonefox/VRTK/commit/dcd69452ec2f2daade5654510263910c7ef978a1

As for the collider being too small, you can change the size of the collider radius on the headset collision script, I recommend 0.2f for the rift.

**Comment by quintesse** [comment]
> As for the collider being too small, you can change the size of the collider radius on the headset collision script, I recommend 0.2f for the rift.

But wouldn't it be better if this was something that would work without "tweaking"? Otherwise switching between SDKs (like we'll be able to do very easily with @bddckr 's PR in the near future) will always cause these slight "imperfections", right?

Perhaps an idea would be to have each headset come with a "recommended size" and have a "multiplication factor" on the headset collision script (which would default to "1.0f"?

**Comment by thestonefox** [comment]
Maybe we could have it where if you set the headset collider radius to 0f then it defaults to the headset default?

**Comment by quintesse** [comment]
Sure, we could do that too.
