### ISSUE TITLE
Snapped objects have wrong orientation on the Rift

### ISSUE THREAD

**Issue by quintesse** [thestonefox/VRTK#1106]
### Environment

 * GitHub
 * f46a07aa6455d4c0c59349f346b50aaad2cc55d4
 * 5.5.1f1
 * Oculus
 * Oculus Utilities

### Steps to reproduce

Using example 14 Controller SnappingObjectsOnGrab the grab the gun and the sword. They will be held in "unnatural" positions.

### Expected behavior

The should snap to the hand in more or less the same position as the would for the Vive, relative to your hand! You should have the feeling you're actually holding the gun or sword.

### Current behavior

When grabbing those objects the gun points down while the sword points straight forward as an extension of your arm.

Probably the attach points are not oriented in a similar way compared to the Vive. Not sure if this is something that can be solved generically or that each application needs to solve this for itself, but at least the examples should show "correct behaviour" so people can learn from that.

**Comment by bddckr** [comment]
Probably related: #876

**Comment by quintesse** [comment]
I skimmed that one looking for previous issues but it looked like a feature request so I didn't look into it any further. It's probably good to have any problems separated from feature requests (even if the solution would work for both), right?

**Comment by bddckr** [comment]
Yeah I can see us at least improving the example scenes to work with all devices without implementing the things in that issue. So an example scene only solution for now.

**Comment by thestonefox** [comment]
I don't think this should be categorised as a bug.

But potentially when we redo the example scenes in the new re-imagination we should consider how multiple controller systems works.

Even the rift controllers in SteamVR have a different orientation to the Vive wands :/

**Comment by thestonefox** [comment]
Can I close this one too if I link here?

https://github.com/thestonefox/VRTK/issues/763
