### ISSUE TITLE
Examples often put objects just out of reach

### ISSUE THREAD

**Issue by quintesse** [thestonefox/VRTK#1107]
### Environment

 * GitHub
 * f46a07aa6455d4c0c59349f346b50aaad2cc55d4
 * 5.5.1f1
 * Oculus
 * Oculus Utilities

### Steps to reproduce

Have a smallish 2x2 playspace
Start any of the examples that use interactable objects like 005, 006, 014
Try to manipulate the objects

### Expected behavior

Being able to easily manipulate the objects

### Current behavior

Objects are often just inside, overlapping or even completely outside the play boundaries making them impossible to reach.

I think all examples that have interactable objects should enable teleporting.

**Comment by claytmcneil** [comment]
I tend to agree with this assessment. Not including teleportation may make the minimum required scripts/setting in the examples more apparent, but there is a usability issue in smaller playspaces.

**Comment by KavanBahrami** [comment]
I had to go through and manually add teleportation to the play space (create play space) for a ton of them..  as well as add the current "update poses" script ...  

Took so much time :/ but I became an expert at vrtk teleportation implementation (;

**Comment by bddckr** [comment]
Also of interest with regard to adding teleport to every scene: #763

@KavanBahrami Good news is VRTK now fixes Valve's bugs, too: https://github.com/thestonefox/VRTK/commit/0b3b18535515f6208f780bacf955d3dd87810637

**Comment by thestonefox** [comment]
I think again this is a candidate for the new example scene thoughts.

I'm thinking some form of locomotion you can toggle.

I'm going to link these issues to this one: https://github.com/thestonefox/VRTK/issues/763

You ok for me to close this as it's now linked?
