### ISSUE TITLE
VRTK Simulator - hardcoded Script object names for controllers??

### ISSUE THREAD

**Issue by f3flight** [thestonefox/VRTK#1109]
### Environment

 * Source of VRTK - Unity Asset Store
 * Version of VRTK - Unity Asset Store - 3.1.0
 * Version of Unity3D - 5.6.0f3
 * Hardware used - none
 * SDK used - Simulator

### Steps to reproduce

Create new scene
create empty game object, rename it to "n1"
assign VRTK_SDKManager script to object n1
Use "Quick Select SDK" -> Simulator
create empty object, rename it to "n2"
assign VRTK_InteractGrab to object n2
create cube
add VRTK_InteractableObject to the cube
add VRTK_FixedJointGrabAttach to the cube
cube -> VRTK_Interactable Object -> Grab Attach Mechanic Script: assign to VRTK_Fixed Joint Grab
cube -> VRTK_Interactable Object: tick "Is Grabbable" 
add VRSimulatorCameraRig to the scene
n1 -> VRTK_SDK Manager-> Auto populate linked objects
n1 -> SDK Manager settings -> Script Alias Right Controller: assign to n2
Run
Try to grab the cube with a simulated hand

### Expected behavior

Grab works

### Current behavior

Grab does not work

### Workaround
rename "n2" to "RightController" - grab starts to work. Why? YouTube tutorials do not mention that specific naming is mandatory (and it should not be imo).

What is interesting is that highlight works, but grab does not.

**Comment by bddckr** [comment]
You need to attach InteractTouch, too.

Naming doesn't matter, it matters what you set to the fields on the SDK Manager, therefore

> n1 -> SDK Manager settings -> Script Alias Right Controller: assign to n2

is fine.

**Comment by f3flight** [comment]
> You need to attach InteractTouch, too. This is documented on the InteractGrab class:
It is automatically attached as a dependency.
> n1 -> SDK Manager settings -> Script Alias Right Controller: assign to n2
>is fine
It does not work. Please try to follow the repro steps.
As soon as I rename "n2" to "RightController" everything starts to work - no need to re-assign anything or add additional scripts.

**Comment by f3flight** [comment]
Moreover, if I open Example 005 (as shown here https://www.youtube.com/watch?v=-3nKbwF93G4) and *rename* RightController there to anything else, it also stops working!

**Comment by bddckr** [comment]
Try the latest GitHub master. The Asset Store version is pretty old.

**Comment by f3flight** [comment]
ok I will. Are there plans to regularly update Asset Store version?

**Comment by bddckr** [comment]
Of course, but Unity actually reviews Asset Store assets and each update which takes days to weeks. We also make sure to only push updates out to it when enough changes are in or an important bugfix is needed. You'll have to ask @thestonefox about updating it.

**Comment by f3flight** [comment]
Bug is reproduced in master branch.

**Comment by f3flight** [comment]
[vrtk-sim-test.zip](https://github.com/thestonefox/VRTK/files/915338/vrtk-sim-test.zip)
Atteched a Unity project with repro scene "test".
1. run, try grab - will not work. stop.
2. Rename "n2" to "RightController", run -> grab starts working.

**Comment by bddckr** [comment]
Thank you for you work. This should be fixed with #1112. 😄

**Comment by thestonefox** [comment]
This was auto closed by the merge of the PR

Lemme know if this needs re-opening
