### ISSUE TITLE
Dragging the slider is useless.

### ISSUE THREAD

**Issue by BensonZheng1987** [thestonefox/VRTK#1110]
### Environment

 * Source of VRTK  :Git hub
 * Version of VRTK  :e719f44ff7112a947bc84c082237187409229035
 * Version of Unity3D :Unity 5.5.0f3
 * Hardware used: Vive
 * SDK used : SteamVR

### Steps to reproduce
1).use example 034_Controls_InteractingWithUnityUI.unity
2).Modify  VRTK_Pointer script of RightController game object
i).Set "Activate Button" to  undefined
i).Click off "Hold Button To Activate"
ii).Click on  "Activate On Enable"
3)Modify  VRTK_UIPointer script of RightController game object
i).Set "Activation Button" = Trigger Press
ii).Set "Activation Mode" = Always On
iii).Set "Click Method" = Click On Button Up
4).Modify game object ExampleObjects:
i).Copy ExampleObjects/Canvas and paste it.
ii). move it to ExampleObjects/Canvas(1)
iii).Set ExampleObjects/Canvas(1) hide
iv).Add two OnClick events of ExampleObjects/Canvas/Scroll View/Viewport/Content/Button (1)
  The first OnClick event is setting ExampleObjects/Canvas hide
  The first OnClick event is setting ExampleObjects/Canvas(1) display
5).Now click the button (ExampleObjects/Canvas/Scroll View/Viewport/Content/Button (1))
   and then drag the slider of ExampleObjects/Canvas(1), The result is error.

### Expected behavior
I think that the handle of slider will follow the pointer .

**Comment by thestonefox** [comment]
Could you probably update the github issue title to something that describes the issue?

**Comment by thestonefox** [comment]
It seems the issue is caused with the unity `Graphic Raycaster` on the secondary enabled canvas isn't being set up cleanly when the canvas is enabled.

A work around is to set the `Graphic Raycaster` on the disabled canvas (e.g. Canvas(1)) to disabled (i.e. untick the component).

Then have another OnClick event that enables the `Graphic Raycaster`

**Comment by thestonefox** [comment]
I think i've found the issue.

The drag event isn't cancelled when the other canvas is hidden (because you're in the drag event of the scroll window)

**Comment by thestonefox** [comment]
PR with fix: https://github.com/thestonefox/VRTK/pull/1117

**Comment by Bhash6244** [comment]
hii 
problem about scrollview vrtk
i use vrtk and create scrollview list, first time scrolling wrok perfect but when i deactive and  active that  i click touchpress button and scrollview go up  but list view already finish.     i want to find solution. 
 please help me.

advance thank you
