### ISSUE TITLE
Controller Tooltip Lines Point to the Wrong Place

### ISSUE THREAD

**Issue by phr00t** [thestonefox/VRTK#1113]
### Environment

 * Github build (from 1-2 days ago)
 * Unity 5.6.0f3
 * Vive
 * SteamVR SDK, latest

### Steps to reproduce

Open the Controller Tooltips example. Either use it with your Vive, or force model override for Vive Controller 1.5 with Tooltips.

### Expected behavior

Tooltips should point to the correct locations on the Vive wand.

### Current behavior

Only the trigger seems to be accurate. All other tooltip lines point to the wrong place -- probably the controllers origin. The incorrect tooltip lines may not be finding the components correctly...

Here is a screenshot of the current behavior:

http://i.imgur.com/KOiSG5H.png

**Comment by thestonefox** [comment]
I'm not seeing this behavior in the example scene.

![image](https://cloud.githubusercontent.com/assets/1029673/25040749/3db40362-2103-11e7-9f48-1c715a80979b.png)

**Comment by thestonefox** [comment]
Can you provide steps to reproduce the issue?

**Comment by phr00t** [comment]
I think I have isolated the issue to the VRTK_DeviceFinder.GetHeadsetType() function. I have a Vive "Pre" that I don't think is detected correctly with that function. The GetControllerElementPath() function simply returns "trigger", which is why the trigger tooltip works for me. However, other buttons require detecting the headset, which is why they fail in my case. Having more loose checks for containing "Vive" in GetHeadsetType if an exact match isn't found would likely fix this... better than returning null.

**Comment by phr00t** [comment]
This GetHeadsetType() function should work much better:

`        public static Headsets GetHeadsetType(bool summary = false)
        {
            string checkValue = VRDevice.model.ToLower();
            if( checkValue.Contains("oculus") || checkValue.Contains("rift") ) {
                if( !summary && checkValue.Contains("cv1") ) {
                    return Headsets.OculusRiftCV1;
                }
                return Headsets.OculusRift;
            } else if( checkValue.Contains("vive") ) {
                if( !summary && checkValue.Contains("mv") ) {
                    return Headsets.ViveMV;
                }
                return Headsets.Vive;
            }
            return Headsets.Unknown;
        }`

**Comment by thestonefox** [comment]
What is the output you get from the `string checkValue = VRDevice.model.ToLower();` call?

**Comment by phr00t** [comment]
Not at my Vive at the moment, and my development machine is separate from my Vive machine (which isn't ideal, I know) -- so I can't get that value in a timely manner. I can put a Debug.Log for next time I run it, though.

**Comment by thestonefox** [comment]
ok cool, just post when you have it :)

**Comment by phr00t** [comment]
Apologies for taking so long to get back. My GetHeadsetType() function fixed the problem for me. Tooltips point to the correct locations with it.

VRDevice.model returns "Vive DVT" for me.

**Comment by phr00t** [comment]
Is this still waiting for feedback? If so, what feedback?

**Comment by thestonefox** [comment]
@phr00t no, sorry I just hadn't updated the ticket.

We're still discussing the best appropriate fix. At the moment we're leaning to identifying the Pre specifically and then acting accordingly, reason being future vives may also need to be distinguished so grouping them together now may not be the best solution.

**Comment by phr00t** [comment]
With the current system, future Vive's (and Rift's) will definitely not work at all. I recommend first checking exact matches. If that fails, fallback to fuzzy matches (e.g. contains("vive")), print a Debug.Log message with a warning & the proper device name. I wouldn't have even noticed a problem if this is how it worked... if there was a problem, I could look back at the logs for hints (e.g. "not an exact match!").

**Comment by thestonefox** [comment]
i think there were some concerns with using the `contains`

i'm waiting for @bddckr to get back from his holiday to discuss options

**Comment by phr00t** [comment]
"Contains" would only be called after an exact match failed to potentially avoid an unknown return value (which nothing will work with). When "contains" is called, a Debug.Log would be printed notifying the developer of the exact name and fuzzy detection. You might be able to use a StartsWith instead, but if you're already in fuzzy territory, might as well err on the side of matching _something_.

**Comment by thestonefox** [comment]
Yeah falling back to the contains is a good idea along with the debug message

**Comment by bddckr** [comment]
Let me know if #1151 fixes this for you 😄

**Comment by potatoWootu** [comment]
I'm having the same problem with oculus rift controller. I don quite get how to solve the problem
