### ISSUE TITLE
Allow all static controller methods to use an index or a given controller game object

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1118]
At the moment there is a mish-mash of ways of calling static methods for a specific controller

Some methods require the controller index, whilst others can simply use the actual or script alias game object.

It's a good idea for any method that uses index to also have a game object equivalent and any one that uses a game object to have an index equivalent.

Then it's developer preference on how it works.

**Comment by bddckr** [comment]
Instead of providing three methods everywhere (index + script alias game object + actual game object) we could introduce a new type `VRTK_ControllerReference`:

```C#
public class VRTK_ControllerReference
{
    public readonly uint index = uint.MaxValue;
    public readonly GameObject scriptAliasGameObject;
    public readonly GameObject actualGameObject;

    public VRTK_ControllerReference(uint index)
    {
        this.index = index;
        scriptAliasGameObject = VRTK_DeviceFinder.GetControllerByIndex(index, false);
        actualGameObject = VRTK_DeviceFinder.GetControllerByIndex(index, true);
    }

    public VRTK_ControllerReference(GameObject gameObject)
        : this(VRTK_DeviceFinder.GetControllerIndex(gameObject))
    {
    }
}
```

**Comment by bddckr** [comment]
Maybe `VRTK_ControllerReference` should provide a `Refresh` method for the case of not yet assigned indexes/left/right controller objects?

**Comment by thestonefox** [comment]
Some examples of where a controller index is currently being used:

 * https://github.com/thestonefox/VRTK/blob/ff673191846f755677158795b5c7ead2861818fe/Assets/VRTK/Scripts/Interactions/VRTK_InteractHaptics.cs#L44
 * https://github.com/thestonefox/VRTK/blob/8eca6ece8838a58422610132048a2900af6c9279/Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs#L178
 * https://github.com/thestonefox/VRTK/blob/5757c74c3ab4dcc14effbe6278bf2b1e98d31fa7/Assets/VRTK/Scripts/Presence/VRTK_HeadsetControllerAware.cs#L175
 * https://github.com/thestonefox/VRTK/blob/15bf58d2f99db5d19b0a6586a1091daca28df271/Assets/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs#L239
 * https://github.com/thestonefox/VRTK/blob/ff673191846f755677158795b5c7ead2861818fe/Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs#L121
 * https://github.com/thestonefox/VRTK/blob/ff673191846f755677158795b5c7ead2861818fe/Assets/VRTK/Scripts/UI/VRTK_UIDraggableItem.cs#L129
 * https://github.com/thestonefox/VRTK/blob/566c41896dfd1d175e29ebcc81e27b0c414dc58f/Assets/VRTK/Scripts/UI/VRTK_UIPointer.cs#L263
 * https://github.com/thestonefox/VRTK/blob/15bf58d2f99db5d19b0a6586a1091daca28df271/Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs#L47-L61
 * https://github.com/thestonefox/VRTK/blob/fb896bca9342bbb777bbc4b53f042f07f9278eb5/Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs#L197
 * https://github.com/thestonefox/VRTK/blob/fb896bca9342bbb777bbc4b53f042f07f9278eb5/Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs#L197
 * https://github.com/thestonefox/VRTK/blob/566c41896dfd1d175e29ebcc81e27b0c414dc58f/Assets/VRTK/Scripts/Interactions/VRTK_ControllerEvents.cs#L1107
 * https://github.com/thestonefox/VRTK/blob/5029a89c95d3c20c57a3f0e352f10a9d48fb24ba/Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs#L14
 * https://github.com/thestonefox/VRTK/blob/15bf58d2f99db5d19b0a6586a1091daca28df271/Assets/VRTK/Scripts/Internal/InstanceMethods/VRTK_Haptics.cs#L11
 * https://github.com/thestonefox/VRTK/blob/8f9393307f245f4f9e8cadede41526f2dad2737e/Assets/VRTK/SDK/VRTK_SDK_Bridge.cs#L18

**Comment by thestonefox** [comment]
@bddckr I like the idea of a new generic class.

I think we should do that as standard for anywhere requiring a controller reference then have the existing method available but deprecated.

Perhaps the class could have a bunch of contstructors like:

 * new ControllerReference(uint index)
 * new ControllerReference(GameObject actualOrScriptAlias)
 * new ControllerReference(ControllerHand hand)
 * new ControllerReference(GameObject modelAlias) (maybe?)

This would then get you the reference of a controller object, then any script that current accepts a `uint index` or a `GameObject actual/script` would be updated to accept a `VRTK_ControllerReference`

The constructors would just need to all do the same thing which would be to store the script alias game object, then any of the getter methods would just use the relevant SDK_Bridge calls to get the relevant output (id, actual, script, model) as we cache all that stuff anyway.

And we would just need simple getter methods like:

 * GetIndex()
 * GetActual()
 * GetScriptAlias()
 * GetModel()

**Comment by thestonefox** [comment]
I also think perhaps we should have a static method on the ControllerReference script like:

 * IsValid(ControllerReference reference)

And it checks to see if the game object is null and if the index is under the uint max value

Because at the moment we do a bunch of checks for things like this all over the place.

I thought we may not need it static and the constructor would just set up a null object which IsValid would return false, but this may then get out of sync if the caches change.

I prefer validity checks to not require state.

**Comment by bddckr** [comment]
> Perhaps the class could have a bunch of contstructors like:
> 
> - new ControllerReference(uint index)
> - new ControllerReference(GameObject actualOrScriptAlias)
> - new ControllerReference(ControllerHand hand)
> - new ControllerReference(GameObject modelAlias) (maybe?)

Model alias game object and `ControllerHand` should be added, I agree. 😄
Sadly having two constructors using the same parameter type (`GameObject` above) is not possible in C#, therefore these should probably be factory methods instead of constructors?!

> The constructors would just need to all do the same thing which would be to store the script alias game object, then any of the getter methods would just use the relevant SDK_Bridge calls to get the relevant output (id, actual, script, model) as we cache all that stuff anyway.

I initially did it like that, but instead I only stored the thing I got passed in the constructors. This made it difficult to return all the other data in the property getters.
With your idea of only storing the script alias game object it should work just fine, though. 👍

> And we would just need simple getter methods like:
> 
> - GetIndex()
> - GetActual()
> - GetScriptAlias()
> - GetModel()

Instead of getter methods I'd prefer readonly getter properties.

> I also think perhaps we should have a static method on the ControllerReference script like:
> 
> - IsValid(ControllerReference reference)

I agree we should add that method, but I'd just add this as an instance method on `ControllerReference`.

> I thought we may not need it static and the constructor would just set up a null object which IsValid would return false, but this may then get out of sync if the caches change.

Yeah we would need to make sure things always are correct when the constructor (or factory method, see above) is called... I think it's fine to just check the current index in that method. It's fast enough anyway.

---

Would `ControllerReference` work like that, or do we need to handle index changes somehow? Do the script/model/alias objects swap when SteamVR switches left+right index, or do the objects stay as is and only the indexes swap?

**Comment by thestonefox** [comment]
Yeah good point on the constructor, I'm not sure if you need to get reference based on the model anyway (it's a nice to have i suppose).

I'm fine with readonly getter properties too. is there a standard in C# for this?

---

I don't think we need to handle index changes if we don't do any logic in the ControllerReference script. If we just hand everything off to the SDK_Bridge then that deals with the caching and refreshing on our behalf anyway.

**Comment by thestonefox** [comment]
Work in progress branch: https://github.com/thestonefox/VRTK/commit/be89b420757c71ed365fad49ce3c134ec0135486

**Comment by thestonefox** [comment]
Updated branch to check: https://github.com/thestonefox/VRTK/commit/b724edc3ad5ea2d193a9e757313e46cb50c1e682

I think it may be ready for a PR

**Comment by thestonefox** [comment]
At the moment, the ControllerReference object stops at the SDK Bridge with all SDK implementations still not using the controller reference.

This is because a number of the SDK scripts require to use the low level objects (especially to create the high level ControllerReference object).

I think actually, some of the SDK methods could be switched over to use the ControllerReference.

**Comment by bddckr** [comment]
I guess that could come later (if at all).

**Comment by thestonefox** [comment]
I'm going to look into it today, see what can be replaced.

I quite like the new simplified GetControllerButtonState/GetControllerAxis/GetControllerHairlineDelta methods that are on the SDK Bridge

These could potentially be filtered down into the SDK implementations rather than the large chunk of methods we have now.

**Comment by thestonefox** [comment]
PR !

https://github.com/thestonefox/VRTK/pull/1129
