### ISSUE TITLE
New SteamVR breaks UI interaction pointer

### ISSUE THREAD

**Issue by noorbeast** [thestonefox/VRTK#1120]
Github build & Asset Store Build
    Unity 5.6.0f3, 5.5.2f1
    Vive
    SteamVR SDK, latest

Steps to reproduce

Open the UI interaction example. 

Expected behavior

Pointer intersects with canvas to allow use.

Current behavior

Pointer does not intersect with canvas.

Reverted to the old Steam 1.1.1 and pointer works as expected, so while adding SteamVR_Update Poses works with most things, events are still broken with the latest SteamVR and UI demo.

**Comment by thestonefox** [comment]
I've tried the latest github master with Steam 1.21 and Unity 5.6.0f3 and it works fine for me.

Can someone else confirm if it's working fine for them too?

**Comment by bddckr** [comment]
I just tested scene 034 with the latest GitHub master, SteamVR 1.2.1, Unity 5.6.0f3 and Rift+Touch. Works fine for me.

**Comment by bddckr** [comment]
I suggest updating VRTK. (Remove old VRTK copy, copy in new one.)

**Comment by claytmcneil** [comment]
I had an old scene that I opened in new version of Unity (5.6.x) and found that pointers weren't working. Updating SteamVR and VRTK (from Git) solved my issue.

**Comment by noorbeast** [comment]
Ignore my stupidity, with a clean 5.6 project and Github VRTK it does work, so it is something in the existing project I am working on that is causing the issue. 

Sorry for wasting your time Thersone and others :-(

**Comment by nixtwiz** [comment]
I had the same issue, I was using VRTK 3.1.0 (the latest release that is also on the Asset Store). When you use the VRTK Master it all works fine.

**Comment by gregcotten** [comment]
@wilg
