### ISSUE TITLE
event OnObjectEnteredSnapDropZone is firing every frame

### ISSUE THREAD

**Issue by KospY** [thestonefox/VRTK#1121]
Hello,

It seem that there is a bug in VRTK_SnapDropZone, the event "OnObjectEnteredSnapDropZone" is firing every frame instead of only once. 

I'm using the last version on Github, Unity 5.6, HTC Vive and steamVR SDK.
To reproduce, simply add a debug.log on the OnObjectEnteredSnapDropZone method.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/f2869bed8726079914ccdc1399f624b4d27e4f3f
