### ISSUE TITLE
SnapDropZones and multiple objects

### ISSUE THREAD

**Issue by quintesse** [thestonefox/VRTK#1122]
### Environment

 * GitHub
 * f2869bed8726079914ccdc1399f624b4d27e4f3f
 * Unity not relevant
 * Any hardware
 * All SDKs

### Steps to reproduce

In any example that uses object snapping grab a snappable object in each hand and hold them both in the snap drop zone. Let go of the object that was moved into the snap drop zone *last*.

### Expected behavior

The object that you let go of first (whichever that is) should snap.

### Current behavior

Only the object that was first placed in the snap drop zone will actually be able to snap. Letting go of the second object will either let it fall to the ground or it will stay in your hand (depending on the object's drop settings).

**Comment by thestonefox** [comment]
PR with fix: https://github.com/thestonefox/VRTK/pull/1123
