### ISSUE TITLE
VRTK Gizmos All Black

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/VRTK#1127]
I get black gizmos on vrtk objects in scenes.

Github VRTK c56e207
Unity 5.4
In editor only

Disabling them in the drop down will remove the black circle from the objects. 

![image](https://cloud.githubusercontent.com/assets/7003769/25157114/183e00ca-2454-11e7-93db-9328630b82a0.png)

![image](https://cloud.githubusercontent.com/assets/7003769/25157117/1e12c71a-2454-11e7-96df-9b9dadbf8077.png)

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/420d8445107e60a54f4311274430354fba5a9a77
