### ISSUE TITLE
Wrong rotation for isolated InteractGrab

### ISSUE THREAD

**Issue by KospY** [thestonefox/VRTK#1130]
Grabbing an object from a interact_grab not directly parented to a controller do not set the correct rotation on snap.
I'm using the last version on Github, Unity 5.6, HTC Vive and steamVR SDK.
To reproduce, add a child gameobject to VRTK\LeftController, move components vrtk_interact_grab and vrtk_interacttouch on this child and add any attachpoint reference. Grab an object and see the result.

**Comment by thestonefox** [comment]
You're not supposed to put InteractTouch on a child component, it's supposed to go on the top level script alias game object
