### ISSUE TITLE
VRTK_Drawer Collision Issue

### ISSUE THREAD

**Issue by avotas** [thestonefox/VRTK#1131]
When a held object is pressed against a door with the VRTK_Door script applied, and the door is not permitted to move, the held object will pass through the door. This causes the held object to be knocked out of the players hand and the door to violently swing open. This can be demonstrated by removing the yellow ball from the demonstration scene and pressing against the 'Normal Door -> Door' while it's in the closed state.

The better solution would be to force the held object out of the players hand once it comes in contact with the door collider.

**Comment by avotas** [comment]
When a held object is pressed against a door with the VRTK_Door script applied, and the door is not permitted to move, the held object will pass through the door. This causes the held object to be knocked out of the players hand and the door to violently swing open. This can be demonstrated by removing the yellow ball from the demonstration scene and pressing against the 'Normal Door -> Door' while it's in the closed state.

**Comment by thestonefox** [comment]
This is down to unity physics and how unity deals with joints.

If you don't want that outcome, then don't use the joint grab mechanic, use the track object or child of controller grab mechanic instead.
