### ISSUE TITLE
Entire SDK Broken on Fresh Install, Tried Multiple Machines

### ISSUE THREAD

**Issue by peterichterIGT** [thestonefox/VRTK#1133]
### Precheck

Normally I'd consider this a support issue, but its way too easy to recreate on:
- a totally new machine
- a new unity install (where one never existed)
- a new, fresh project
- freshly downloaded SteamVR and VRTK Plugins
- I've installed your toolkit a dozen times; this has never happened.
- should also mention the QuickSelectSDK dropdown doesn't seem to do anything on the VRTK object

### Environment

Came from Unity Asset Store, assuming it's 3.1.0
Tried Unity 5.5.0f3 as well as 5.6.0f3
Vive
SteamVR, a note about that...
Downloading SteamVR on it's own works fine.  When you install VRTK on top of it, not only is VRTK completely busted (won't detect handsets), but it in turn breaks the SteamVR scene, and then nothing works.

### Steps to reproduce

- Delete your existing SteamVR and VRTK asset packages in your AppData/Roaming folders (assuming windows) just to be sure (or just find a fresh machine like I did on the third try today, install Unity)
- Make a new, empty project, do not include any asset packs
- Open asset store, install SteamVR
- Open SteamVR example scene, notice the controllers are visible
- Open asset store, install VRTK
- Open any scene at all, get a bunch of fallback errors and no tracked controllers

### Expected behavior

- Follow all the aforementioned steps
- Use all included VR scenes without any errors, as I have done thus far without any issue
(just a quick moment to say, up until today, your toolkit has been amazingly effortless)

### Current behavior

Run any included scene, including the SteamVR example AFTER installing VRTK, get this:

Fallback Controller SDK is being used. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.SDK_FallbackController:Awake() (at Assets/VRTK/SDK/Fallback/SDK_FallbackController.cs:678)
UnityEngine.ScriptableObject:CreateInstance()
VRTK.VRTK_SDKManager:GetControllerSDK() (at Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs:146)
VRTK.VRTK_SDK_Bridge:GetControllerSDK() (at Assets/VRTK/SDK/VRTK_SDK_Bridge.cs:452)
VRTK.VRTK_SDK_Bridge:IsControllerLeftHand(GameObject, Boolean) (at Assets/VRTK/SDK/VRTK_SDK_Bridge.cs:75)
VRTK.VRTK_DeviceFinder:GetScriptAliasController(GameObject) (at Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs:222)
VRTK.VRTK_TrackedController:OnEnable() (at Assets/VRTK/Scripts/Internal/VRTK_TrackedController.cs:60)
UnityEngine.GameObject:AddComponent()
VRTK.VRTK_SDKManager:SetupControllers() (at Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs:218)
VRTK.VRTK_SDKManager:Awake() (at Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs:200)

Fallback Boundaries SDK is being used. Have you selected a valid Boundaries SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Boundaries SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.SDK_FallbackBoundaries:Awake() (at Assets/VRTK/SDK/Fallback/SDK_FallbackBoundaries.cs:72)
UnityEngine.ScriptableObject:CreateInstance()
VRTK.VRTK_SDKManager:GetBoundariesSDK() (at Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs:175)
VRTK.VRTK_SDKManager:Awake() (at Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs:201)

Fallback Headset SDK is being used. Have you selected a valid Headset SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Headset SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.SDK_FallbackHeadset:Awake() (at Assets/VRTK/SDK/Fallback/SDK_FallbackHeadset.cs:89)
UnityEngine.ScriptableObject:CreateInstance()
VRTK.VRTK_SDKManager:GetHeadsetSDK() (at Assets/VRTK/Scripts/Utilities/VRTK_SDKManager.cs:117)
VRTK.VRTK_SDK_Bridge:GetHeadsetSDK() (at Assets/VRTK/SDK/VRTK_SDK_Bridge.cs:443)
VRTK.VRTK_SDK_Bridge:GetHeadsetCamera() (at Assets/VRTK/SDK/VRTK_SDK_Bridge.cs:377)
VRTK.VRTK_DeviceFinder:HeadsetCamera() (at Assets/VRTK/Scripts/Utilities/VRTK_DeviceFinder.cs:305)
VRTK.VRTK_SharedMethods:AddCameraFade() (at Assets/VRTK/Scripts/Utilities/VRTK_SharedMethods.cs:101)
VRTK.VRTK_BasicTeleport:Awake() (at Assets/VRTK/Scripts/Locomotion/VRTK_BasicTeleport.cs:130)

No play area could be found. Have you selected a valid Boundaries SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Boundaries SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.VRTK_BodyPhysics:CreateCollider() (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:600)
VRTK.VRTK_BodyPhysics:EnableBodyPhysics() (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:581)
VRTK.VRTK_BodyPhysics:OnEnable() (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:250)

NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_PositionRewind.OnEnable () (at Assets/VRTK/Scripts/Presence/VRTK_PositionRewind.cs:42)

No default collider prefab could be found. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.VRTK_InteractTouch:CreateTouchCollider() (at Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs:468)
VRTK.VRTK_InteractTouch:OnEnable() (at Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs:207)

No model container could be found. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.VRTK_ControllerActions:GetElementTransform(String) (at Assets/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:537)
VRTK.<WaitForModel>c__Iterator0:MoveNext() (at Assets/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:471)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
VRTK.VRTK_ControllerActions:OnEnable() (at Assets/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:466)

NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_BodyPhysics.CalculateVelocity () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:385)
VRTK.VRTK_BodyPhysics.FixedUpdate () (at Assets/VRTK/Scripts/Presence/VRTK_BodyPhysics.cs:273)

No model container could be found. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.VRTK_ControllerActions:GetElementTransform(String) (at Assets/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:537)
VRTK.<WaitForModel>c__Iterator0:MoveNext() (at Assets/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:471)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by bddckr** [comment]
Use the latest GitHub master of VRTK instead of the Asset Store version. That should fix it for you I think.
We do more clever tricks recognizing the installed vendor SDKs on the master.

**Comment by bddckr** [comment]
Also: if you remove all your scripting define symbols that begin with VRTK_DEFINE it should automatically add the needed ones for SteamVR afterwards and then your SDK manager should be fine. (Assuming you didn't uncheck the auto manage function of it with regard to the scripting define symbols.)

**Comment by thestonefox** [comment]
Sounds like an installation issue.

I tried VRTK from the asset store yesterday on Unity 5.6 and it worked fine. Also many others are using it without this issue, so I assume it's isolated only to your situation.

**Comment by tuesy** [comment]
I can confirm that 5.0.6f3 and the latest Unity asset store version doesn't work out-of-the-box. I had to delete the entire folder and copy in the latest master. Not sure if it was exactly this error message but no big deal for me.

**Comment by thestonefox** [comment]
Unity 5.0.6?

Do you mean 5.6? If so, the asset store version doesn't support 5.6 yet, version 3.1.0 of vrtk is 5.4 and 5.5 only

**Comment by thestonefox** [comment]
Also, are you clicking on the [VRTK] object so the SDK Manager can do its setup?

**Comment by masterchop** [comment]
github master is the solution unity 2017.3.1f1
Oculus utilities 1.24.0
didnt test all the samples but the error went away.
