### ISSUE TITLE
Dash Teleport emits teleporting and teleported events as though you did a standard teleport

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#1135]
### Environment

 * Source of VRTK (Unity Asset Store or Github) -  Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash) 3.1.0
 * Version of Unity3D (e.g. Unity 5.4.4f1) 5.5.1
 * Hardware used (e.g. Vive/Oculus) - Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities) - SteamVR

### Steps to reproduce

Slow down the dash lerp time to 2 or 3 and then put a debug.log statement in a subscribed event to Teleporting and Teleported

### Expected behavior

Calls teleporting when starting a dash and Teleported when the dash is complete

### Current behavior

Calls teleporting and then immediate called teleported as though it was a blink or standard teleport.

**Comment by thestonefox** [comment]
PR to fix the issue:

https://github.com/thestonefox/VRTK/pull/1136

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/pull/1136
