### ISSUE TITLE
Adaptive quality generates warnings that avoids to use it

### ISSUE THREAD

**Issue by FairT** [thestonefox/VRTK#1138]
Hi,
I just updated my whole VR project to :
Unity 5.6.0f3
VRTK today build
SteamVR 1.2.1

When I use the adaptive quality I got thousands of warnings :
RenderTexture: Resolving surfaces of different sizes.

That makes the project very slow so unusable.

If I disable the adaptive quality it works fine.

**Comment by thestonefox** [comment]
What do you mean by VRTK today build? The latest version of github master? If so what commit hash?

**Comment by FairT** [comment]
Hi,

Sorry if I was not clear.

I meant that I just downloaded the Github master when I writed this report.

I don't know where to find the commit hash, if you still need it tell me
how and I ll give you this information.

But to be clear I downloaded the github master yesterday.

Have a good day,

Cédric

**Comment by thestonefox** [comment]
Are you using single pass rendering?

**Comment by FairT** [comment]
If it is the right thing we talk about :

[image: Inline images 1]

**Comment by thestonefox** [comment]
Doesn't look like your image uploaded

**Comment by FairT** [comment]
Oh sorry,

It was written :
Stereo Rendering Method : Multi Pass

**Comment by thestonefox** [comment]
If you're using multi pass rendering then that's probably the issue.

I think the adaptive rendering and unity 5.6 don't work with multi pass, apparently it's a bug in unity 5.6 (i hear).

try single pass rendereing

**Comment by FairT** [comment]
Unfortunatelly the single pass does not solve the problem.

**Comment by FairT** [comment]
I just tested the github project with only the last SteamVR version added and the example 39 AdaptiveQuality has the problem.

**Comment by thestonefox** [comment]
maybe when @bddckr is back from vacation he can chip in with some thoughts?

**Comment by FairT** [comment]
Of course, no hurry at all.

You 're doing a great job guys, focus on something more important and come
back to it when you got time.

**Comment by bddckr** [comment]
Unity logging
> RenderTexture: Resolving surfaces of different sizes.
all the time on 5.6.0f3 is a Unity bug we can't work around. 😩

Until Unity fixes it in a new (patch) release I suggest disabling/not using Adaptive Quality since the logging is bogging down the framerate.

**Comment by KevinComerford** [comment]
I haven't used VRTK, but I fixed this issue in the lab render. It seems that [renderViewportScale doesn't work correctly anymore](https://docs.unity3d.com/ScriptReference/VR.VRSettings-renderViewportScale.html) and pops out a message.  You have to switch the functions to renderScale.

**Comment by bddckr** [comment]
@KevinComerford That won't work as we need `renderViewportScale` _in addition to_ `renderScale`. `renderViewportScale` is broken in the latest 5.6 patch releases, but works fine in 5.6.0f3, only a subset of users are getting the error spam above.

Let's hope these things are fixed in 2017.1.

**Comment by KevinComerford** [comment]
Oh really? So has it been fixed in the last unity update? That's good news. Someone was pointing out to me that this was an issue. I'll get back to them if it's no longer the case.

**Comment by bddckr** [comment]
It's working fine for me and several others in 5.6.0f3, is broken in 5.6.1p4. Dunno why the error spam is hitting the issue author here.

I have no idea if it works in 5.6.2p1 or 2017.1.

**Comment by SmartCarrion** [comment]
Anyone have Adaptive Quality working on Oculus?  It seems to be doing nothing, although I am not getting those console errors.  When I play on Vive/SteamVR it is fine.  Unity 2017.1.1f1.  VRTK 3.2.0 git version from Sept 14.

![image](https://user-images.githubusercontent.com/5105110/30679656-c1f94adc-9e4f-11e7-91b5-7ea4b8b5ca12.png)

**Comment by bddckr** [comment]
Adaptive Quality uses [`renderViewportScale`](https://docs.unity3d.com/ScriptReference/VR.VRSettings-renderViewportScale.html) which is broken on every new Unity version these days except for 2017.2.b10, but even in that version there's some perf problems going on that prevent AQ from being useful.

**Comment by djarcas** [comment]
Given as it's 3 months later and I'm seeing exactly the same issue - has there been any resolution to this issue? The solution presented is 'disable dynamic resolution' in every thread I've seen, which really misses the point.

**Comment by thestonefox** [comment]
@djarcas as you're still seeing the same issue then it's probably fair to assume there hasn't been any resolution

**Comment by bddckr** [comment]
@djarcas The issue posted here is a Unity bug that was resolved after 5.6.0f3. If the same issue is back again it's again on Unity to fix it.

The issue of `renderViewportScale` not working was also a Unity bug which seems to be fixed with one of the patch releases of 2017.1.

You can probably see we're not affiliated with Unity in any way.

@thestonefox I vote to close this issue.
