### ISSUE TITLE
(UI) Pressed the image, The OnPointerDown will be call many times

### ISSUE THREAD

**Issue by BensonZheng2016** [thestonefox/VRTK#1141]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK  (Github master bcaa719802ce7e16af2724e8c7b2c340e461c0b3)
 * Version of Unity3D (Unity 5.5.0f3)
 * Hardware used (Vive)
 * SDK used (SteamVR)

### Steps to reproduce
Use 034_Controls_InteractingWithUnityUI scene to reappear the problem.
1.Modify the "VRTK_UIPointer" script of RightController as follow picture 
![image](https://cloud.githubusercontent.com/assets/18454958/25433992/253a971a-2abd-11e7-9295-d7b0b9568a30.png)
2.
i)Create a Image game object on ExampleObjects/Canvas/Button.
ii) Remove the "Button" component of ExampleObjects/Canvas/Button.
iii) attach PointerEventTest  script to  ExampleObjects/Canvas/Button game object and run.
public class PointerEventTest : MonoBehaviour, IPointerDownHandler, IPointerUpHandler
{
    public void OnPointerDown(PointerEventData eventData)
    {
        Debug.LogWarning("----- OnPointerDown enter");
    }

    public void OnPointerUp(PointerEventData eventData)
    {
        Debug.LogWarning("----- OnPointerUp enter");
    }
}
iv) Pressed the ExampleObjects/Canvas/Button game object, hold on .
It will print "----- OnPointerDown enter" more than one times.
  
I think it is a bug.

**Comment by thestonefox** [comment]
I can recreate it, but what's the purpose of the set up?

You have an image that you want to listen to the pointer up/down events on?

**Comment by thestonefox** [comment]
Ok you can fix the issue you're getting by adding an `EventTrigger` component to your `Button` script.

I'm guessing without that EventTrigger the UI Element cannot determine it's event state.

I'm going to assume this isn't a VRTK bug now but a Unity restriction (unless someone can clarify better)

**Comment by bddckr** [comment]
This may be an issue because we don't handle the selection state correctly in our own VR input module. We can't do it properly, though, because that would break VR-and-desktop-UI-usage AFAIK. (Unity's EventSystem is made for _one_ active input module at a time. 😟)

**Comment by thestonefox** [comment]
Is it fair to say you need to add an EventTrigger to a UI element for it to work (as it seems to fix the issue)

**Comment by bddckr** [comment]
The [Unity docs](https://docs.unity3d.com/ScriptReference/EventSystems.EventTrigger.html) tell us:

> NOTE: Attaching this component to a GameObject will make that object intercept ALL events, and no events will propagate to parent objects.

😞

**Comment by thestonefox** [comment]
But in the original issue, the button is being edited so it is no longer a button and just an image.

Without the EventTrigger being added to the image, then it will bubble every event (which is what's causing the issue).

The Image example in the UI Example scene adds the EventTrigger to make sure the image can capture events.
