### ISSUE TITLE
How to Disable/Enable Teleport at runtime

### ISSUE THREAD

**Issue by Jithendrakumar** [thestonefox/VRTK#1144]
Can anyone please explain me how to Disable/Enable Teleport at runtime, i am using Unity3d 5.5 with HTC Vive.

I have tried to access the Enable Teleport from VRTK_DestinationMarker but that didnt work.

Any suggestions will be helpful.

**Comment by thestonefox** [comment]
Disabling either the teleport script (using the `enabled = false` flag on the script will prevent teleporting from happening

But also, setting the `Enable Teleport = false` on the Destination Markers that are creating the teleport event will also disable teleporting.

So if you have 2 pointers one on each controller, that means there are 2 destination markers, so both destination markers would need their enable teleport setting to false.

**Comment by Jithendrakumar** [comment]
But i don see any Destination Markers script attached to the controller, here i am seeing VRTK_Pointer script attached which is derived from VRTK_Destination Markers since it is deriving i can see Enable Teleport toggle button in inspector where i can toggle but doing it from script in VRTK_Pointer doesn't disable it.

**Comment by thestonefox** [comment]
The VRTK Pointer is of type Destination Marker (as you've mentioned).

I've just tried toggling it on and off in code and it's working fine for me.

Are you using the latest version of vrtk from github master? If not then update.

**Comment by Jithendrakumar** [comment]
Hey @thestonefox  sorry i was off from work for couple of days, as i said above i tried your suggestion for disabling and enabling but that didnt worked, can you give any example or your tried code would also be helpful.

**Comment by thestonefox** [comment]
what have you tried already?

simply setting `enable teleport = false` on the destination marker will prevent teleporting.

**Comment by Jithendrakumar** [comment]
Thanks, i have figured it out, i have done that in VRTK_Pointer Class itself, since i can't access that outside of that class, i had to write code to disable it in Update function of same class.

**Comment by Fruity84** [comment]
I am also interested in this.  How to abort a teleport at runtime? Button X is used to show the pointer. If i press Button X again, the pointer disappears and i am teleported to the selected playArea.
So I am forced to teleport if i have pressed Button X.
What I want to achive is to abort the teleport with TriggerPressed. The pointer should disappear but i dont want to be teleported. For this, I created a OnTriggerPressed in VRTK_Pointer.cs, but I have no idea what to do to achive this. I have tried to call Toggle(false) in the Pointer Class  but this is not working.

**Comment by thestonefox** [comment]
@Fruity84 you want to teleport on trigger press? what button are you using to activate the pointer beam?

you can have a different activation button to the set button, so you can activate/deactivate pointer on touchpad touch, but a set button on the trigger.

**Comment by Fruity84** [comment]
hey stonefox... this is solution i was looking for. Thank you
