### ISSUE TITLE
Youtube Video Ideas

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1146]
Please leave comments on anything you'd like to see covered in a Youtube video as I'm going to be doing 1 a week in May as we've reached that patreon goal.

Don't add the same topic twice, just thumbs up on the message with the suggestion and we'll consider that a voting system from people!

Any valid suggestions will be added to a GitHub Poll:

Vote on your preferred tutorial (powered by [GitHub Polls](http://gh-polls.netlify.com))

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Inventory%20System)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Inventory%20System/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Using%20the%20Unity%20UI)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Using%20the%20Unity%20UI/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Moving%20in%20zero%20gravity)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Moving%20in%20zero%20gravity/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Avatar%20hands)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Avatar%20hands/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Controllables%20%5Bdoors%20buttons%20levers%20chests%20dials%5D)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Controllables%20%5Bdoors%20buttons%20levers%20chests%20dials%5D/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Multiplayer%20with%20UNET)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Multiplayer%20with%20UNET/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Multiplayer%20with%20Photon%20PUN)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BY3RAZ1FCDNZMTZRS599Y03Q/Multiplayer%20with%20Photon%20PUN/vote)

Completed tutorials will be listed below:

- [ ] Inventory System
- [ ] Using the Unity UI
- [ ] Moving in zero gravity
- [ ] Avatar hands
- [ ] Controllables (doors, buttons, levers, chests, dials)
- [ ] Multiplayer with UNET
- [ ] Multiplayer with Photon PUN
- [x] Snap Drop Zones
- [x] Unity Survival Shooter Tutorial
- [x] SDK Script registration
- [x] Creating a headset menu
- [x] Object control locomotion (touchpad walking)
- [x] Teleporting changing direction (robo recall style)
- [x] Teleporting and body awareness
- [x] Teleporting - destination points to different locations
- [x] Styling destination points
- [x] Styling pointer appearance
- [x] Teleporting and destination restrictions
- [x] Grab attach mechanics

**Comment by Vytek** [comment]
I think a complete Teleport tutorial is very important. In Patreon comments:

I am very interesting in complete Teleport Tutorial. Starting to easy pointer teleport to bezier height teleport? How to modify code, objects, etc to create a similar https://github.com/Flafla2/Vive-Teleporter ? How disable and enable zone teleport? We can create singolar point teleporting similar to Iteracatable Object System of SteamVR?
2m
The Stonefox
Have you tried the teleport destination points in the latest version of VRTK? Look at Example `044_CameraRig_RestrictedTeleportZones` and if you don't have that example then if you upgrade your version of VRTK you should then have it.

Also for an example of modifying the bezier pointer to look nicer, check out example scene `036_Controller_CustomCompoundPointer`

Hope that helps you :)

With a complete tutorial I think it is better ;-)
Thank you very much!

**Comment by nattapong3d** [comment]
Hello! A simple walk-though of how set up the SnapDropZone would be great. It took me awhile to figure out that you need tags, the policy list, and that the target object could be hidden. I've got it working well enough now, but I still don't fully understand how to set up the transparent material. :P Thanks!

**Comment by borrowedLadder** [comment]
I'd love to see a tutorial on the teleportation stuff! One thing I'd love to see is different methods of exclusion. Right now if an object is made to not be teleportable you have the bezier curve turn red so the teleport there wont work - but I'd love if it was physically stopped from moving through those things (kind of like when the default layer is on). So the teleport always lets you teleport, and always puts you in the closest correct place when blocked :)

Keep up the great work!

**Comment by wirelessdreamer** [comment]
Before Action Alias Buttons went away I had my control scheme set up so the application button teleported, and the touchpad button brough up the pointer to interact with the ui/scroll, while the trigger clicked the pointer, and selected stuff on the ui.

With the new structure I'm currently having trouble getting this control scheme in place. Its been a great control sceme to use. I'm hoping i'm just missing something simple and its still possible to set it up this way.

Showing how to build this could help cover a lot of the new controller action binding stuff.

**Comment by thestonefox** [comment]
I've got 7 videos planned for teleporting tutorials. Lemme know if I'm missing anything:

1: setting up vrtk and showing basic teleport with simple pointer

2: show height adjust teleport, dash teleport, terrain/mesh teleporting. show ability to block certain teleport locations with policy list and nav mesh.

3: Set up Bezier pointer, show various options (and line renderer) and then style like steamvr pointer

4: Set up play area cursor, style accordingly, show collision and additional options

5: Set up direction indicator, style accordingly and show how to rotate play area cursor too.

6: Set up destination points and areas, style like steamvr. Show how they can be used to teleport upstairs/downstairs.

7: Show ability to use custom destination markers (like model village) and force teleport locations via script. Show teleporting/teleported events to do things.

**Comment by nadimalam** [comment]
Please can you do an updated tutorial for integrating VRTK3 with NewtonVR. 

The previous one is out of date and completely changed so doesn't work anymore. 

Also a tutorial on how we can put our own hand models instead of the generic vive remotes would be really useful.

**Comment by smart09091** [comment]
could you do a tutorial on the simulator? like how to implement features for it that can directly translate to the vive when a vive is plugged in? I was thinking something along the lines of a tutorial series that would cover the following
-teleportation with the simulator rig
-body physics with the simulator
-controller events with the simulator
-changing the controller models with the simulator

something like an indepth tutorial on this would really help teams with just 1 vive set available

**Comment by nadimalam** [comment]
I think another really useful tutorial would be on you showing us how to create a locked door that can only be opened with a key, I'm sure this would use a combination of your scripts to achieve.

**Comment by thestonefox** [comment]
I think the tutorial series is now completed. Suggestions for the next series to be covered?

**Comment by nadimalam** [comment]
Creating an inventory system?

**Comment by defenestrator6** [comment]
Would love a tutorial on making realistic interactable objects from scratch like a gun with this toolkit specifically

**Comment by thefreeline** [comment]
I'd love a tutorial on how to create player movement in zero-gravity.

**Comment by fatcatrolling** [comment]
Hi,
Thank you so much for all the tutorials.
Could you please also do a tutorial on setting up the GearVR Controller is possible? (so instead of the Left & Right Controller of the Oculus Rift, does VRTK also works for developing mobile device app?)
Thank you!

**Comment by ardazeytin** [comment]
UNET(unity network) tutorial.

**Comment by Christian996** [comment]
Hello thestonefox,

thank you for doing so much tutorials.
I have to work a lot with the simulator but I can't figure out how to simulate the touchpad touching ..

It would be really nice if you could do a tutorial how to use the touchpad in simulator correctly. I know how to press it or to touch it. But i cant change the touched position to check if my Buttons will work or not ..

Hopefully you can help me out here, thanks in advance :)

**Comment by thestonefox** [comment]
@Christian996 there is no way currently in the simulator of simulating where abouts on the touch pad you're touching.

**Comment by nadimalam** [comment]
@thestonefox when is your vr hands releasing? if it hasn't already? I would really be interested in seeing different types of hand tutorials with VRTK and how to grab objects correctly with correct finger orientations etc... Maybe even having the hand open up more when you get closed to an object you can interact with etc..

**Comment by bddckr** [comment]
@nadimalam Hands are in already: #1349.

**Comment by nadimalam** [comment]
@bddckr Ah thats awesome, i didn't even know about it LOL. It would be great to get a few tutorials based around the hands 👍  Also if its possible to change the hand model with another one on asset store such as the popular: VR Hands and FP Arms Pack from NatureManufacture here: https://www.assetstore.unity3d.com/en/#!/content/77815

**Comment by thestonefox** [comment]
you're not going to be able to just switch the hand models out for any old hand model because the armature would need to match.

I'll do some hand based videos when the hands are finalised and released into the next stable release.

**Comment by nadimalam** [comment]
cool, thank you! 👍

**Comment by Christian996** [comment]
thestonefox,
is there a easier way to order the buttons at the vrtk radial menu into a new place? Want to have three Buttons. Two at left and right and a third in the middle. 
I calculate the position from touch and take a bool to check if i am in the middle area. I changed the InteractButton function and calculate the buttonAngle new with / 2 if resetButton is unselected ( we touch not the middle) or we do. can't test it right now but do  you think this works?
If not, do you have a better solution for this? :)

**Comment by thestonefox** [comment]
@Christian996 it would be better if you opened a separate issue for your questions so you don't muddy the topic of this open issue.

**Comment by Christian996** [comment]
Oh yeah thats right, sorry for this :)

**Comment by Vytek** [comment]
Controllables (doors, buttons, levers, chests, dials) +1

**Comment by thestonefox** [comment]
@Vytek I've added a Github poll, vote with that and we can keep the comments purely for suggestions then :)
