### ISSUE TITLE
bug?(ClimbingFalling Example) - Cannot Consistently Stand On Top of Surface After Climb

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#1149]
* Source of VRTK (Github)
 * Version of VRTK (Github master commit hash)
 * Version of Unity3D (5.5.0f3)
 * Hardware used (Vive)
 * SDK used (SteamVR)

### Steps to reproduce

Climb up something and try to _stand_ on top of the surface you're climbing up towards.

### Expected behavior

Having the HMD clearly over the surface I wish to stand on, I expect to be Height Adjust teleported to now be standing on said surface.

### Current behavior

Having tried different positions of both the HMD and Controllers, sometimes I indeed Height Adjust teleport onto the surface, other times (consistently) the physics doesn't like what's happening and I'm forcefully flung away as the interpenetration of the Player rigidBody and the surface rigidBody resolve.

**Comment by BinaryLegend** [comment]
Agreed, see this behavior daily.

**Comment by BinaryLegend** [comment]
I managed to hack around this problem (for now) in my own project by calling TogglePreventSnapToFloor(false) and SnapToNearestFloor() in the Ungrab() method of PlayerClimb.

**Comment by xEvoGx** [comment]
That's all you added and it appears to work?

**Comment by xEvoGx** [comment]
@BinaryLegend Hmmm I can't seem to get this to work (Unity isn't recognizing those two methods)...

...could you elaborate in the event this is a reasonable fix I can use in the interim?

**Comment by BinaryLegend** [comment]
Well, I've extended both BodyPhysics, PlayerClimb, and AdjustHeightTeleport for my own needs. I see I did in fact miss one thing. I turn toggle enableBodyCollisions to false when in a climbing state, and set it back to true when not. I have a lot of other code that does other things in those scripts, but those are the only ones that I tampered with to get it working.

**Comment by xEvoGx** [comment]
Err, so your previous comment you mentioned what sounded like a simple fix; can you elaborate on it? 

I'm asking if you could contribute something more specific so myself (and others) could have a quick fix while we wait for a proper one. 😄 

Thanks Daniel!

**Comment by thestonefox** [comment]
Ok so my thoughts are:

 * On Ungrab:
   * Try height adjust teleport first to snap to nearest floor
   * Then check for position rewind and set the rewind delay to 0 so rewind is immediate
   * Finally re-enable body physics colliders and let Unity resolve the collision

**Comment by xEvoGx** [comment]
So I'll attempt to "_fix_" this myself for the interim, but when I tried what Daniel suggested, I couldn't call those methods he mentioned...any thought on that?

**Comment by xEvoGx** [comment]
I see what I did wrong...

...I called the method alone not realizing it was a part of bodyphysics (e.g.  **bodyPhysics.TogglePreventSnapToFloor(false);**

Finally I'm sorta maybe paying closer attention! 😆

**Comment by mikekan13** [comment]
This still doesn't seem to work.

**Comment by thestonefox** [comment]
@mikekan13 that is why this issue is still open?

**Comment by thestonefox** [comment]
PR to attempt to fix this: https://github.com/thestonefox/VRTK/pull/1253

**Comment by thestonefox** [comment]
The PR addresses the snap to nearest floor to ensure when your headset is not colliding and over a valid floor on climbing you should snap to that floor.

It also addresses the push back to reset you to a valid position if you climb inside an object and release whilst inside.

**Comment by xEvoGx** [comment]
Awesome Stone
