### ISSUE TITLE
New User:  Can't pick up objects with controllers in any of the example scenes.

### ISSUE THREAD

**Issue by scandell** [thestonefox/VRTK#1157]
> **NOTE:** Any issue that does not follow the below template will be immediately closed and not re-opened until the template structure is adhered to.

### Environment

 * Source of VRTK (Github)
 * Version of VRTK (latest)
 * Version of Unity3D (5.6)
 * Hardware used (Vive)
 * SDK used (SteamVR)

### Steps to reproduce

I simply load sample scenes 005 or 023.
I add the update_poses SteamVR script to the eye camera. (necessary to see controllers through headset)
I attempt to click and hold, and pick up an object...
nothing happens.

Oddly enough, in the door-open example scene...i can open the door with the controller...

### Expected behavior

I would expect to pick up an object.

### Current behavior

i can't pick up the object.

This is my first time attempting to use VRTK,   Probably user error...but i'm pretty smart...and read alot of the provided documentation. :)

**Comment by thestonefox** [comment]
If you're using the latest version of Github master, you shouldn't need to add the poses script yourself as VRTK does it for you.

Also, depends what button you're pressing to try pick things up. The grab button is the default button.

I can also confirm the example scenes work.

**Comment by bddckr** [comment]
Can confirm the example scenes allow grabbing objects on Unity 5.6.0f3 and latest SteamVR plugin (1.2.1 I think).

**Comment by scandell** [comment]
ok. I might be an idiot.  I thought the trigger would be utilized for picking up things...not the side touch pads.

**Comment by thestonefox** [comment]
you can change the default to trigger if you want.

**Comment by scandell** [comment]
excellent. done.  I should have caught that.  But i expected trigger due to valve's lab shooter.
