### ISSUE TITLE
Controller Tooltips leaking when no button transforms are found

### ISSUE THREAD

**Issue by Tubyhes** [thestonefox/VRTK#1158]
### Environment

 * Unity Asset Store
 * 3.1.0
 * 5.5.0f3
 * Vive
 * SteamVR

### Steps to Reproduce

Use the standard SteamVR CameraRig prefab, set the Controller Models to the Model Alias fields in the VRTK prefab. On the CameraRig Controller Model objects, uncheck "Create Components", so the actual in game model will be one piece. In the Controller Tooltips prefab, dont populate all button transform fields. 
Now, in ControllerTooltips.InitialiseTips(), transforms for some buttons will remain null, causing the corresponding Initialised boolean to stay false. Because of this ControllerTooltips.TipsInitialised() will return false, causing InitialiseTips() to be called every frame. 
Unity profiler reported 4.6kB memory allocated every frame by InitialiseTips().

### Expected Behaviour

Probably to ignore buttons for which no transform can be found, or buttons for which the tooltip is "" anyway. At least not to cause a redraw every frame. 

### Current Behavior

See above.

**Comment by thestonefox** [comment]
Here is a PR which should resolve this issue and deal with the initialisation in a better way

https://github.com/thestonefox/VRTK/pull/1173
