### ISSUE TITLE
Discussion: Structure of controller related functions

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1161]
First of all this is just my personal thoughts about some of the recent additions and changes, feel free to just ignore it if you think its stupid : )

I think its a bit messy now how you access some of the controller related APIs. Some things are on the controller scripts (use/grab etc), some are on the device finder (velocities) and some in some obscure shared methods class (haptics). I think there should be a common way of getting all APIs related to a controller, to make it easier for the user to figure it out.

Something like:
-Get the controller reference using DeviceFinder or some other means.
-Get the relevant script
-Call the relevant function

And this should be valid for everything that are related to a specific controller, like grab, use, haptics, velocity and whatever other API calls. At least i suggest that haptics stuff gets moved to the haptics script, and also that the velocity and angular velocity gets moved from the DeviceFinder and onto some of the controller scripts.

**Comment by thestonefox** [comment]
I agree that just having DeviceFinder and SharedMethods as a dumping ground is stupid, it's too generic and unstructured.

However, I'm also keen not to have to add scripts to game objects if they don't need state.

So for instance, the Haptics stuff doesn't need a state as you can just tell it the index and the rumble settings and it will go about its business.

So what we could do maybe is have a script that has a static method on it that does the haptics if you want to call it via code, but then maybe you can also attach that script to one of the controller script aliases then you can just call methods on it that will use the script alias it's attached to?

**Comment by virror** [comment]
So you mean you add them to the haptics script but as static methods? I think that would be the best idea probably. No idea where the velocity stuff would fit in though?

**Comment by thestonefox** [comment]
Well haptics could be:

new Haptics script that has static methods so you can just call them statically if you want, then maybe it also can be added to a game object (and you can either provide a custom game object for the script alias to use, or you attach it to the script alias), then you could call instance methods on that specific game object.

so you'd be able to do `VRTK_DeviceFinder.GetLeftController().GetComponent<VRTK_Haptics>().Rumble(x,x)`

although that's a bit silly when the controller reference stuff is merged as using the static method would be easier.

Velocity again should be moved out of shared methods, even if it was another script like object velocities or something, better to have small and to the point scripts than these god dumping grounds imho.

**Comment by thestonefox** [comment]
Ok so just to make a couple of quick rules:

 * Device Finder is only used for finding devices (not for things like velocities)
 * Shared Methods is only used for methods that provided extended functionality (such as shallow vector equality)

Anything that is a specific VRTK type function (like haptics or velocity of controller/headset) should have it's own static utility class so it's very specific.

**Comment by virror** [comment]
Sounds good to me! But i find it a bit confusing to have 2 haptic scripts, one for attaching and one for static methods?

**Comment by thestonefox** [comment]
well it could be the same script and you could decide whether to attach it or not.

But really i think it wont be necessary to attach it to anything, just have the static way of calling it i think.

We already have `VRTK_Haptics` which needs to get added at runtime because it needs to be instanced to do the coroutines.

I'm wondering if we have a separate script in the Utilities directory maybe that's just a facade through to that Haptics script.

**Comment by virror** [comment]
As long as its logical to the users. Just think it might be more apparent with a single haptics script? No idea really, i will just leave that one to you to decide : )

**Comment by thestonefox** [comment]
https://github.com/thestonefox/VRTK/pull/1182

**Comment by thestonefox** [comment]
This doesn't cover the device finder velocities, as at the moment the DeviceFinder does say it's for getting devices and key device information.
