### ISSUE TITLE
Bug with scaling up the camera rig while using straight pointers with object interaction on them.

### ISSUE THREAD

**Issue by KevinRobertsBacon** [thestonefox/VRTK#1162]
Got VRTK from github.
3.1.0
Unity 5.0.6f3
HTC Vive
Steam VR SDK

Attach VRTK_Pointer and VRTK_StraightPointerRenderer to controller object, check interact with objects.  Keep scale factor set to default.

Scale up camera rig through script (or just in the editor).  At the same time, scale up the scale factor of VRTK_StraightPointerRenderer by the same amount.  Note that the collider for the interacting object parented under the controller in the camera rig hierarchy is larger than the cursor at the end of the pointer by a significant margin.  

### Expected behavior

The collider used to interact with object should stay the same size as the cursor at the end of the pointer.

### Current behavior

Trying to scale up the camera rig and pointer should keep the interact collider at the same size as the cursor.

**Comment by thestonefox** [comment]
PR to resolve the issue: 
https://github.com/thestonefox/VRTK/pull/1265
