### ISSUE TITLE
GetControllerVelocity is broken for Simulator

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1163]
### Environment

VRTK Github af7ccb638fef06236c07233f367327473728795a
Unity 5.5

### Steps to reproduce
Try to get GetControllerVelocity when using simulator

### Expected behavior
Get valid values

### Current behavior
Always getting zero

**Comment by thestonefox** [comment]
Related to https://github.com/thestonefox/VRTK/issues/840

**Comment by virror** [comment]
My brain is broken, closing this
