### ISSUE TITLE
Inconsistent Usage of LoadPreviousState + SaveCurrentState

### ISSUE THREAD

**Issue by DenverCoulson** [thestonefox/VRTK#1164]
### Environment

 * VRTK Unity Asset Store I believe
 * v3.0.1
 * Unity 5.5.3f1
 * Oculus Hardware
 * SDKs used: Oculus

### Steps to reproduce

Write a script that disables a VRTK_InteractableObject that has "isKinematic" set true while a laser is touching it. Have it re-enable after 1 second.

### Expected behavior

I would expect re-enabling to maintain "isKinematic" as true.

### Current behavior

The VRTK_InteractableObject will have "isKinematic" set false because it will call LoadPreviousState() but SaveCurrentState() is never called anywhere else to give the appropriate isKinematic state.

### My Solution

Because it's possible for LoadPreviousState to be called in OnEnable() and SaveCurrentState() is never called in OnDisable(), I have simply added it in VRTK_InteractableObject as follows:

         protected virtual void OnDisable() {
            UnregisterTeleporters();

            if (autoHighlighter)
            {
                Destroy(objectHighlighter);
                objectHighlighter = null;
            }

            forceDisabled = true;
            ForceStopInteracting();
            SaveCurrentState();
        }

This seems to take care of  the issue entirely.

**Comment by thestonefox** [comment]
I'd recommend updating to github master, 3.0.1 is quite old

**Comment by DenverCoulson** [comment]
Understood, we plan to shortly but wanted to make sure our system is mostly bug free before dealing with upgrade incompatibilities. Just thought I'd share this in case it hasn't been seen.
