### ISSUE TITLE
Lots of stuff not working with Simulator in scene #25

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1165]
### Environment
Latest from github: af7ccb6
Unity 5.5

### Steps to reproduce
Try to interact with the sliders, door or drawer. 

### Expected behavior
Something should happen : )

### Current behavior
Nothing happens : (

**Comment by thestonefox** [comment]
This is due to the same problem behind https://github.com/thestonefox/VRTK/issues/1108
