### ISSUE TITLE
Interactable Object not working with Oculus SDK

### ISSUE THREAD

**Issue by potatoWootu** [thestonefox/VRTK#1167]
VRTK any interactable object is not working with oculus SDK. Even a simple pickup object is not working. I already set up the SDK Oculus in the VRTK System SDK / Controller SDK and its still not working. But when i switch to steamVR it works perfectly

**Comment by thestonefox** [comment]
you need to provide steps to reproduce, plus the version of unity, and the version of the SDK you're using..

Otherwise we can't recreate the issue.

**Comment by potatoWootu** [comment]
Oculus SDK 1.10.0 
Unity Version 5.6.0f3
VRTK version latest from Github

1.Open any interactable object grab scene 005/ 006 / 008 / 013 / 014 / 021. Install OVR 1.10.0 Utilities and OVR Avatar. 

2.Drag the OVR camera rig and OVR avatar prefab into the scene and delete the steamVR camera Rig

3.Click on VRTK SDK manager and set up System SDK / Boundaries SDK / Headset SDK / Controller SDK

4.Test Out in VR cant grab and interact with any object .

But for other function such as teleporting is working.

**Comment by thestonefox** [comment]
I'm not sure if Oculus 1.10 works with Unity 5.6

I'd recommend moving up to like Oculus 1.12 or above.

**Comment by samurai926** [comment]
Hi,
I'm having the same problem, using Oculus CV1 with touch controllers they cannot grab, bump, interact with anything in the example scenes.  Using Oculus 1.16 and Unity 2017.1.0f3.  Any thoughts?

Thanks,
Jeffrey

**Comment by thestonefox** [comment]
@samurai926 don't use Oculus Utilities 1.16 it's a beta and not supported.

**Comment by samurai926** [comment]
@thestonefox Hey thanks fox for the reply.  I rolled back Oculus Utilities to 1.15 and OvrAvatar to 1.15 and grab/interaction works!  Thanks for the help.

Jeffrey
