### ISSUE TITLE
Steam VR Issue with Button Alias Configuration

### ISSUE THREAD

**Issue by wirelessdreamer** [thestonefox/VRTK#1168]
Using Version 3.1.0 from the Asset store, The same type of configuration worked as expected in version 3.0.1
Unity 5.5.1f1
Vive hardware
SteamVR Version 1.2.0

### Steps to reproduce

Start with Scene: 036_Controller_CustomCompoundPointer

Under VRTK->RightController->VRTK_ControllerEvents
change Pointer Toggle Press from TouchPad_Press to Button_One_Press
change Pointer Set Button from TouchPad_Press to Button_One_Press

Under VRTK->RightController->VRTK_Pointer
Change Activation Button to Button_One_Press
Change Selection Button to Button_One_Press

(having to change both of these seems redundant, I've tried changing both individually, with no success, and only list it here to cover everything.)

### Expected behavior

Using the Application Button should now teleport

### Current behavior

Changing Only  VRTK->RightController->VRTK_ControllerEvents
Doesn't affect what button the action is bound to.

Changing  VRTK->RightController->VRTK_Pointer
makes it so the Bezier teleport no longer functions at all.

![image](https://cloud.githubusercontent.com/assets/140221/25822704/6bf14a16-3407-11e7-9a2b-e53c2eed4e17.png)

**Comment by thestonefox** [comment]
The controller button aliases have now been deprecated. If you use Github master version then this will no longer be an issue.

**Comment by wirelessdreamer** [comment]
Issue resolved. As a side note I should of been using button two above, not button one, that's just here for anyone else that reads this issue later. 
![image](https://cloud.githubusercontent.com/assets/140221/25823288/972ddd46-3409-11e7-896f-45be141625ec.png)

**Comment by wirelessdreamer** [comment]
Thanks for the quick response btw
