### ISSUE TITLE
SDK_OculusVRHeadset line 65 uses OVRPlugin.GetEyeVelocity which is no longer there

### ISSUE THREAD

**Issue by olykken** [thestonefox/VRTK#1169]
To recreate simply download the newest version of the Oculus SDK for Unity and import it into a blank project, then download the current version of VRTK. An error will immediately pop up saying "Assets/VRTK/SDK/OculusVR/SDK_OculusVRHeadset.cs(65,56): error CS0117: `OVRPlugin' does not contain a definition for `GetEyeVelocity'". I have been unable to find which version of the OVRPlugin that line of code was removed (or moved) but it cannot simply be added back in. That being said the GetEyeVelocity method is no longer there so that line of code will have to be changed (if that behavior is still needed).

**Comment by brucevang** [comment]
I had the same issue. Downloading the Github version fixed the Asset Store version. Thanks!
