### ISSUE TITLE
`VRTK_Pointer` requires the `VRTK_ControllerEvents` component warning shown when ControllerEvents is already added

### ISSUE THREAD

**Issue by wirelessdreamer** [thestonefox/VRTK#1170]
### Environment
VRTK Git 2065a7f9e3c202b480dac80c1416d2b2d39a584d
Unity 5.5.1f1
Vive
SteamVR 1.2.1

### Steps to reproduce

Start with Scene: 034_Controls_InteractingWithUnityUI
Open scene Additive: 036_Controller_CustomCompoundPointer

from scene 36 copy component: VRTK->RightController->VRTK_Pointer
paste it in scene 34 to:  VRTK->RightController
Change Button_Activation and Selection_Button on the new script to: Button_Two_Press

from scene 36 copy component: VRTK->RightController->VRTK_BezierPointerRenderer
paste it in scene 34 to:  VRTK->RightController

Link the pointer renderer from the new pointer to the VRTK_BezierPointerRenderer

Remove scene 36

At this point the first controller works as expected

### Where things go wrong ###
Delete VRTK->LeftController
Duplicate VRTK->RightController
Rename it to LeftController

Drag the reference for left controller to reference on the VRTK object

Now none of the cursors work, and this error shows up repeatedly, even though Controller Events are on both parent objects.

![image](https://cloud.githubusercontent.com/assets/140221/25866864/ef0326ea-34c5-11e7-98b1-4343e7a93c58.png)

### Expected behavior

After Duplicating the right controller settings for the left controller, and setting the references both controllers should behave the same way.
### Current behavior

After Duplicating controller settings, all UI Pointers are broken, and complain about references not existing that do.

**Comment by thestonefox** [comment]
This seems like a bit of a weird set up.

Why are you opening a scene to copy the pointer into a scene that already contains a pointer?

**Comment by wirelessdreamer** [comment]
One pointer is for the compound bezeier pointer for teleporting, the other is the pointer for interacting with the ui.

I copied the other pointer from another scene so I wouldn't need to describe the settings I had on the other pointer, so you'd end up with the exact same setup I had. You could just as easily attach the same pointer script, instead of copying it from the other scene.

**Comment by thestonefox** [comment]
Can you provide simple steps to reproduce where you're not copying one script from another scene, nor duplicating game objects.

I'm not entirely sure what the issue is. It reads like it's a configuration issue which is likely caused by trying to copy/paste things.

Can you recreate the issue with just setting up scripts from new?
