### ISSUE TITLE
TrackObject does not give same rotation as ChildOfController and FixedJoint

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1171]
### Environment
Unity 5.5
VRTK 621e644965ae9b2bb79bf0e6861e2262fdc4d5e2

### Steps to reproduce
Grab an object with TrackObject, then change that to  ChildOfController and/or FixedJoint

### Expected behavior
Grabbed object should have same orientation regardless of grabbing mechanism.

### Current behavior
Different rotations for different grabbing mechanism.

From Scene #8
https://dl.dropboxusercontent.com/s/ubn7or8wvyn2ybe/shot_170509_162333.jpg
vs
https://dl.dropboxusercontent.com/s/spbnqgt44ydji0w/shot_170509_162431.jpg

**Comment by thestonefox** [comment]
I think this is just a product of how the track object works.

By default the joint and child of controller mechanics just use the origin of the grabbed object (i.e. the centre point 0,0,0)

However, the track object also adjusts the rotation of the object, and if no snap handle is given to adjust to or precision snap is not set, then it will just rotate the object to it's origin which is 0,0,0.

This is why the track objects orientate themselves on first grab, which gives it that rotation.

I can see it could be considered a bug, but I'm not sure of any real solution as it needs to orientate itself when grabbed.

The solution would be to use a snap handle I guess?

**Comment by virror** [comment]
Using snap handle does not solve the issue for me, i still get different results. Also i do thing the user expects all grab mechanics to give the same results regardless of using a snap handle or not? Otherwise its just very strange behavior from a users perspective imo?

**Comment by thestonefox** [comment]
I don't disagree, but as I said I'm not sure of a workable solution due to the nature of how the track object mechanic works.

**Comment by virror** [comment]
Its not a major issue, just something i noticed and reported : )

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/1377
