### ISSUE TITLE
OVRAvatar causes Unity to crash when using Oculus SDK

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1188]
### Environment

 * Source of VRTK: Github
 * Version of VRTK:  d4445f2505fe169e0454cbe2a11d56511efb7c9b
 * Version of Unity3D: 5.5.3f1
 * Hardware used: Oculus
 * SDK used: Oculus Utilities 1.12, OVRAvatar 1.12

### Steps to reproduce

 * Load Example Scene 005
 * Run scene

### Expected behavior

Scene should load

### Current behavior

Unity crashes

**Comment by thestonefox** [comment]
You need to specify an App ID for Oculus Avatar (you do this via the Oculus Avatar Unity Menu)

This doesn't fix the issue though.

**Comment by thestonefox** [comment]
I can confirm Oculus Utilities 1.13 and Oculus Avatar 1.13 don't crash Unity

**Comment by quintesse** [comment]
And I can confirm 1.14 works too.

**Comment by bddckr** [comment]
No crashing here with Utilities and Avatar 1.13.

**Comment by thestonefox** [comment]
Lets just say 1.12 is no longer supported!
