### ISSUE TITLE
UIPointerElementEnter event is firing multiple time

### ISSUE THREAD

**Issue by KospY** [thestonefox/VRTK#1191]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: Last version
 * Version of Unity3D:  5.6.0f3
 * Hardware used: HTC Vive
 * SDK used: SteamVR

### Steps to reproduce

Add a listener of the event
Put a debug line in the target method
Point any UI (ideally with multiple text/rawimage overlapping)

### Expected behavior

Event is only fired once, if some items is overlapping, fire one event for each item and stop.

### Current behavior

Event is fired every frame. UIPointerElementExit is working well however (only fired once)

Thanks for your help :)

**Comment by thestonefox** [comment]
You'll need to provide better steps to reproduce.

The example Scene (34) already has a script that implements the `UIPointerElementEnter` event and that's not being emitted every frame.

So you must be doing something extra to what the example scene is doing.

**Comment by KospY** [comment]
After some tests it seem that the problem happen when UI component are overlapping.
My UI have some background raw images, pointing a button fire an event for the button and the background infinitly.
To reproduce, simply add a Raw image component overlapping a button to one of the UI of the scene 34, pointing the button will fire multiple event in loop.

**Comment by thestonefox** [comment]
Is this the same as this issue?

https://github.com/thestonefox/VRTK/issues/1141

If you add an image without an EventTrigger then the events in Unity just keep getting called as they don't get caught by the element.

**Comment by KospY** [comment]
Well I don't think it's the same as I use the VRTK event and not the classic IPointerDownHandler & IPointerUpHandler.
Anyway I found a workaround: I disabled raycast target on all my background image ;)

![image](https://cloud.githubusercontent.com/assets/2311302/26028918/db1e8e00-3829-11e7-9880-27894897bebf.png)

**Comment by thestonefox** [comment]
The Unity Events are just the c# events re-emitted.

Try adding an EventTrigger to your image

**Comment by KospY** [comment]
Adding an event trigger to the background image seem to stop my button to work.
Anyway I'm ok with the workaround, I do not need to raycast the background image as it's not a button, so not problem for me with this solution :) 
Thanks for your help.
