### ISSUE TITLE
Update CONTRIBUTING.md to describe new github branch arrangement

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1198]
After the 3.2.0 release, the GitHub branches will be utilised better moving forward.

Only bug fixes can be merged into GitHub `master` branch (where patch releases can be created to push to the Unity Asset Store if required).

Any new features will go into a new branch that is named accordingly for the next release.

e.g. a new branch will be created called `3.3.0-alpha` and all new features will need to be pull requested into that branch.

When the next version branch is out of alpha it will be renamed (or recreated) as `3.3.0-beta` for final testing and bug fixes, when finally it will be released and merged back into `master` and a new `3.3.0` release tag created.

The GitHub `master` branch will always be rebased back into the new release branch so any existing bug fixes are also up to date.

**Comment by KavanBahrami** [comment]
This sounds like a solid plan
