### ISSUE TITLE
Provide ability to get VRTK Auto Generated objects and track to them

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1208]
VRTK has a number of scripts that auto generate required game objects.

It is useful if there are getter methods for these objects and the ability to track to those objects (without the need for custom scripts)

### VRTK_HeadsetCollision
 * headsetColliderContainer

### VRTK_BodyPhysics
 * bodyColliderContainer

### VRTK_PlayAreaCursor
 * playAreaCursor -> `GetPlayAreaContainer()` - Ability to follow

### VRTK_BasePointerRenderer
 * objectInteractor - Ability to follow

### VRTK_StraightPointerRenderer
 * actualContainer
 * actualCursor - Ability to follow

### VRTK_BezierPointerRenderer
 * actualContainer
 * actualCursor - Ability to follow

**Comment by virror** [comment]
Yes, thank you : )

**Comment by thestonefox** [comment]
Start of a PR: 

https://github.com/thestonefox/VRTK/pull/1212

**Comment by thestonefox** [comment]
https://github.com/thestonefox/VRTK/pull/1212
