### ISSUE TITLE
FramesPerSecondPrefab not working with NVRPlayer

### ISSUE THREAD

**Issue by adamsowinski** [thestonefox/VRTK#1211]
I dragged and dropped FramesPerSecondCanvas prefab into the scene and hooked up Head gameObject from NVRPlayer (NewtonVR) but it doesn't show up. Funny thing is when I removed the reference to the camera it shows up on the monitor (Game view) but not in the headset.

**Comment by thestonefox** [comment]
NewtonVR uses it's own CameraRig. VRTK doesn't officially support NewtonVR.

**Comment by adamsowinski** [comment]
Ok, fair enough.
