### ISSUE TITLE
(enhancement) add ButtonStateHolder

### ISSUE THREAD

**Issue by Backer-Sultan** [thestonefox/VRTK#1213]
**Section: Controls**
**Script: VRTK_Button.cs**

Add a feature to hold the state of VRTK_Button while it is pushed and the controller-trigger (or other button on the controller) is pressed, so VRTK_Button maintains it's "pushed" state even if the controller moves away from VRTK_Button. The VRTK_Button's state becomes "unpushed" when the controller-trigger is released and the controller is not pushing VRTK_Button.

This is useful in case of a player should keep pressing a button and looking away. On small-size buttons it's hard to do.

**Comment by thestonefox** [comment]
this doesn't work when you're pushing buttons with just the controller rigidbody (without any button press). it kind of goes against the default concept of the button control.

You could attain the same solution with additional custom script (which I think is my preferred option).

**Comment by Backer-Sultan** [comment]
@thestonefox I agree! a custom script is the neatest solution. I thought of not visually implementing this (by manipulating buttons rigidbody), but only by removing, and adding listeners to events, or more easily by adding a `bool heldByController` (within VRTK_Button) and triggering `OnReleased` only if `heldByController` is set to false.
