### ISSUE TITLE
Unity Beta Issues :: FPS

### ISSUE THREAD

**Issue by KavanBahrami** [thestonefox/VRTK#1215]
Is this the place for Beta issues as well?

### Environment
 * Source of VRTK (Github. pulled 5.18.17)
 * Version of VRTK (3.1.0)
 * Version of Unity3D (Unity 2017.1.0b5 (64-bit))
 * Hardware used (Vive)
 * SDK used (SteamVR)

### Steps to reproduce
Create a fresh scene, create SDK setup and set properly, create VRTK and set properly. Add FramePerSecondCanvas to Hierarchy, drag SDKSetup>CameraRig>CameraHead>Camera(Eye) to FPSC script [RenderCamera] .. Run

### Expected behavior
If done on current version the FPS overlay is displayed.

### Current behavior
There is no FPS overlay

**Comment by thestonefox** [comment]
Beta's are never supported because things within the beta will most likely change.

Best thing to do is wait until 2017 is released and then find bugs.

**Comment by KavanBahrami** [comment]
Understandable .. that said, should we be making a list of potential issues as they come up?

**Comment by thestonefox** [comment]
well you can, but there's nothing to say that Unity wont just fix them in their beta process.

This is why it's best to just wait for the release and see what's broken then.

**Comment by KavanBahrami** [comment]
Sounds good.

Again, thanks for building / opening the TK to the dev community
