### ISSUE TITLE
VRTK scripts disabled before running will get enabled anyways when running.

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1216]
When using scripts like VRTK_BasicTeleport or VRTK_BodyPhysics and you want to disable it for testing something, it will get enabled anyways by the SDK manager. The manager should respect the initial enable state for those scripts. Atm the only way of running without a certain script enabled is to remove it, which will make it loose all the settings.
This issue is also confirmed by @bddckr

**Comment by thestonefox** [comment]
@bddckr can't we just update the `List<Behavior>` to be a `Dictionary<Behaviour, bool>` and the value is the `enabled` state of the behaviour script i.e. `behaviour.enabled` then when you do the toggle you just set it back to the original state? Or you skip toggling it if the state is false?

**Comment by virror** [comment]
That is whats kind of what i suggested as well, seems easy enough?

**Comment by thestonefox** [comment]
there may be a reason why it isn't easy. I looked at the code in the SDK_Manager, on the face of it it seemed easy enough, but then i got lost (bored) of looking at the detail. I figured @bddckr would be best placed to know :)

**Comment by bddckr** [comment]
Either changing it to a Dict, or just adding a second List is fine. I've got no time to do this, so go ahead.

**Comment by thestonefox** [comment]
@bddckr what do you think of this for the fix?

https://github.com/thestonefox/VRTK/pull/1252
