### ISSUE TITLE
VRTK_Pointer does not toggle on/off properly in runtime

### ISSUE THREAD

**Issue by dnorth** [thestonefox/VRTK#1218]
### Environment

 * Source of VRTK *Unity Asset Store*
 * Version of VRTK *Unity Asset Store*
 * Version of Unity3D *Unity 5.5.0f3*
 * Hardware used *Vive*
 * SDK used *SteamVR*

### Steps to reproduce

Open Example scene `009_Controller_BezierPointer`

----------------------------------------------------------------------------------
(I don't think these steps are necessary, but just trying to be sure it's a script-controlled toggle)
In `VRTK -> RightController` or `VRTK -> LeftController`:
* Change `Use Toggle Button` on `VRTK_Controller Events` to `Undefined`
* Change `Activation Button` and `Selection Button` on `VRTK_Pointer` to `Undefined`
* Uncheck `Enable Teleport`
* Uncheck `Hold Button To Activate`
----------------------------------------------------------------------------------

Add some kind of test script to `VRTK -> RightController` or `VRTK -> LeftController`:

```
    private VRTK_ControllerEvents events;
    private VRTK_Pointer pointer;

	// Use this for initialization
	void Start () {
        pointer = GetComponent<VRTK_Pointer>();
        events = GetComponent<VRTK_ControllerEvents>();

        events.GripPressed += Events_GripPressed;
        events.GripReleased += Events_GripReleased;

	}

    private void Events_GripReleased(object sender, ControllerInteractionEventArgs e)
    {
        Debug.Log("Toggling off...");
        pointer.Toggle(false);
    }

    private void Events_GripPressed(object sender, ControllerInteractionEventArgs e)
    {
        Debug.Log("Toggling on...");
        pointer.Toggle(true);
    }
```

Run game and press and release the grip 

### Expected behavior

Pointer should be shown on Grip Pressed, and no longer shown on Grip Released.

### Current behavior

Pointer is shown on `Grip Pressed`, and still shown on `Grip Released`. When clicking the grip a second time, it is still shown on `Grip Pressed` and no longer shown on `Grip Released`.

### Extra Notes

This isn't the exact behavior happening in my personal project, but it's strange enough to report or at least ask about and hope that whatever comes of it also fixes the problem in my personal project. In my personal project, I can toggle the pointer on but it doesn't toggle back off. 

My use case for this is to cast a spell which enables the pointer for three seconds. After the three seconds are up, I want the spell to be cast at the location of the pointer and for the pointer to be disabled. Here's what it looks like in my project:

```
    public override void Cast()
    {
        StartCoroutine("InstantiateMeteor");
    }

    IEnumerator InstantiateMeteor()
    {
        pointer.Toggle(true);
        //Instantiate hand effects

        yield return new WaitForSeconds(3f);
        pointer.Toggle(false);
        //Instantiate Meteor at pointer destination
    }
```

The pointer turns on, but not back off after the 3 second wait. (However, is I replace `VRTK_Pointer` with `VRTK_BezierPointer` and use `pointer.ToggleBeam(false)` then it works like I need it to).

In this vein, I am also curious to know if I can get the destination that the pointer is pointing at (So I can cast the spell at that location after 3 seconds). I didn't see an easily accessible way to get it. 

Please let me know if i'm using the pointer incorrectly and should be using something else instead. This just seemed to fit with the problem I wanted to solve.

Thanks!

**Comment by thestonefox** [comment]
You have `Uncheck Hold Button To Activate` which would make the activation button work as a toggle.

So one press/release of the button turns on, then another press/release of the button turns off.

**Comment by whoops1122** [comment]
Hi, I m trying to figure out how to toggle the pointer on and off via c# script, any examples i can find?

**Comment by thestonefox** [comment]
Look at the docs at http://docs.vrtk.io

If you read through the docs for the pointer you'll see the Toggle method

**Comment by whoops1122** [comment]
i totally tried the toggle function, and it works. However, my goal is to
use it with VRTK_Radial menu, I m guessing that radial menu somehow changed
few controller events and made it so that the pointer doesnt display.


thanks!

**Comment by joebain** [comment]
I just stumbled across this and would like to comment. It seems the "Hold Button to Activate" option means that calling `Toggle()` does not necessarily toggle the pointer, and you may need to call that method twice, or more realistically make sure that option is checked on the component. This is not at all obvious from the name of the option and not mentioned in the docs.
