### ISSUE TITLE
Proposal/Request: Better support for secondary grab/Two handed objects

### ISSUE THREAD

**Issue by nixtwiz** [thestonefox/VRTK#1224]
## **Example:**
When setting up a two handed weapon there are at least two grab locations - the grip and somewhere on the front. With the current options you create a box collider on the interactable object, set the primary option to ChildOfControllerOnGrabAttach and secondary to ControlDirectionGrabAttach. This creates some problems however as some weapons should have specific grab spots. In addition, if the primary hand lets go, the weapon just falls even though the secondary hand should still be holding it at the front. This would be useful for weapons for quickly cycling the bolt with the correct hand instead of what most VR weapon solutions seem to do (cycle bolt with secondary hand which is not how you're supposed to do it) as well as many other possible situations such as holding an object with both hands like a wheelbarrow, motorcycle handlebars, steering wheels, etc. all three of which if you let go with the primary hand would force the secondary hand to ungrab (it took a couple months for Onward to finally add it, but it's the only instance I've seen of it so far which is disappointing). 

## **Main Problems**
So the first problem is it would be great to be able to set multiple grab locations on an object using multiple objects with colliders. I ended up doing it by just adding additional collider components but I explain the issue with that below. 

The second problem is the object being able to switch primary and secondary grabs to allow the secondary hand to still hold the object with the same orientation (it shouldn't just snap to the rotation of the controller, but should have the option to) when the primary releases.

## **My Attempts**
I "solved" the first problem by adding another collider component to the object, but this created problems with my VRTK_SnapDropZone script (it allows grabbing the item from anywhere in the drop zone without actually touching the item, _another feature that would be great to have as a built in option_, I use it for weapon holsters behind the player's head and on their back). To solve that I had to make the secondary collider component a different type and make my snap drop zone script override SnapObject to check what type of collider it was before doing anything otherwise it threw errors.

The second problem I have spent the last couple of hours trying to solve using multiple different methods and just can't figure out how to do it. I'm still learning the inner workings of VRTK's grabbing systems but it doesn't seem like it's possible to transition the grab to the secondary controller while maintaining the object's current position relative to the secondary controller. 

## **Suggestions**
- _Option to transfer grab to secondary controller if primary releases first_
This would be useful for most two handed objects as dropping the object when the primary releases even though the secondary should still be grabbing is a bit annoying. Add an option to reset the transform to the secondary controller attach point or let it remain as it is relative to the secondary controller.

- _Set multiple gameobjects with colliders on them as the grab locations of the interactableObject with the ability to set if that grab point is a use point (ie the controller grabbing the grip can "use" the gun, but a controller grabbing the front can't "use" the gun)._
 In a way I completed the first part of it by just using a different collider type, but that's not really optimal. Doing it as separate objects would be much better.

- _Set which collider is a primary grab point and the others secondary._
Secondary grab points would be used to determine when to break the secondary grab based on how much it moves the point relative to the primary grab point. IE, moving the front too far or pulling it too far relative to the trigger hand would break the grab because in real life it can't just pivot and stretch.

- _Set individual controller/hand model snap zones for each grab point not just left/right controller_
A controller grabbing the front of the gun should have the model snap to a location on the front and same for on the grip, but not be based on left/right to allow for items to be used by left and right handed players. I was able to do this one myself, but a built in solution would be nice.

There was a similar post about this about two months ago, but I wanted to go into much more detail on my experience, why it'd be useful, and how it might be done, so I decided to make it a separate post.

**Comment by thestonefox** [comment]
It's possible to do the hand swapping, if you ask @smonz in the slack channel he can probably help you out as he's done it already.

**Comment by nixtwiz** [comment]
Alright thanks, they did it similarly to the way I was trying to do it I'll just have to try again.

**Comment by thestonefox** [comment]
I think @smonz was looking at a way of making it more generic to potentially be included in VRTK

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522

maybe?
