### ISSUE TITLE
Proposal/Request: Add God Mode to Examples

### ISSUE THREAD

**Issue by noorbeast** [thestonefox/VRTK#1229]
It is already possible to create an Out of Ammo style God Mode with VRTK, similar to this example by Fuseman: https://www.youtube.com/watch?v=5OIGhi0QyMo

But I think it would be useful to have a prefab and additional example of the God Mode mechanic included with VRTK.

**Comment by thestonefox** [comment]
This is part of this issue:
https://github.com/thestonefox/VRTK/issues/763
