### ISSUE TITLE
TriggerClicked doesnt get called in Simulator

### ISSUE THREAD

**Issue by DavoMyan** [thestonefox/VRTK#1232]
* Source of VRTK GitHub
 * Version of VRTK  The most updated one with the OLDER SDK
 * Version of Unity3D  5.6.0f3
 * Hardware used (Simulator Prefab)
 * SDK used  Simulator

### Steps to reproduce
1. Setup the simulator
2. Press trigger

### Expected behavior

Trigger should be clicked.

### Current behavior

Trigger doesnt get clicked..

So I tried out the simulator prefab, all the buttons worked except the Trigger but I did notice my event that gets called as I release the trigger works. So I tried using the controller event listener example to debug log each level of trigger press and found out that indeed the TriggerClicked doesnt get called, only the hairline, touch and press. Not clicked

**Comment by thestonefox** [comment]
Not sure I follow the issue.

You press the trigger but it doesn't get clicked?

Press and Click are two different events. What are you actually trying to achieve?

**Comment by WNPIII** [comment]
Ran into a similar issue. Either I'm missing something, or it looks like default key presses do not emit "clicked" and "unclicked" events in the simulator, which can be problematic for some trigger and grip functionality. Adding the controller event listener to the scene shows that it's emitting a "pressed" event with a pressure of zero, but that's as far as it goes.

**Comment by seep** [comment]
Ran into this as well after I switched some of my grab interactions to use the click event. I think the simulator just needs another button press mode modifier; there's no way that I see for the simulator to emit a trigger click.

**Comment by kristianpd** [comment]
`TriggerPressed` is emitted but not `Clicked`. I wonder if we should emit both Pressed and Clicked since there's no pressing state on a mouse button?
