### ISSUE TITLE
Radial menu onClick not working

### ISSUE THREAD

**Issue by noorbeast** [thestonefox/VRTK#1233]
* Source of VRTK  Github
 * Version of VRTK commit cf205d2
 * Version of Unity3D 5.6.0 p3
 * Hardware used Vive
 * SDK used SteamVR plugin for Unity - v1.2.1

### Steps to reproduce

Use the flashlight RadialMenu example here: https://github.com/tonygod/unity-vrtk-flashlight

### Expected behavior

Changing the Flashlight example to the latest VRTK or attaching the script and light the to the latest VRTK Radial Menu Example the light should toggle (works with the bundled flashlight VRTK version).

### Current behavior

Light does not toggle with RadialMenu, no error issued.

**Comment by thestonefox** [comment]
Can you recreate this in the example scene?

**Comment by noorbeast** [comment]
You can download the scene from the link already provided: https://github.com/tonygod/unity-vrtk-flashlight

With the included old version of SteamVR and VRTK the included Flashlight scene radial menu properly populates a radial menu button when you hit Regenerate Buttons, to which you can attach the flashlight game object and set it to toggle, which works when you run it.

But if you use the latest SteamVR and VRTK with the Radial Menu demo scene (030) then hit the Regenerate Buttons it will only create child buttons that appear to be disabled. If you hook up the light it will not toggle.

**Comment by thestonefox** [comment]
You need to provide steps to reproduce in an example scene. Otherwise people can end up debugging custom code which generally people don't have time for.

**Comment by noorbeast** [comment]
This can be closed, it is Smart Core that breaks the Radial Menu, resulting in the onclick functions not to render, which is a pity as it is handy for productivity: https://www.assetstore.unity3d.com/en/#!/content/46286
