### ISSUE TITLE
VR does not work at all on unity 2017

### ISSUE THREAD

**Issue by georgejecook** [thestonefox/VRTK#1236]
> **NOTE:** Any issue that does not follow the below template will be immediately closed and not re-opened until the template structure is adhered to.

### Precheck

Done

### Environment

 * Source of VRTK (Unity Asset Store or Github) 
git hub
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.1.0
 * Version of Unity3D (e.g. Unity 5.4.4f1)
Unity2017.1.0b1
 * Hardware used (e.g. Vive/Oculus)
Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
OpenVR

### Steps to reproduce
Open any example scene  or use any steamVr prefabs

Attempt to recreate the issue in a VRTK example scene and provide steps to reproduce in a clear text step by step list. Include code samples, errors and stacktraces if appropriate.

### Expected behavior
Should have openVr initialization and headset tracking, controllers etc

Briefly describe what you expect should happen

### Current behavior
black screen - also will stop tracking working for any other steamVr scenes (which do not use VRTK) in the same project.

Briefly describe what is actually happening
not sure of all the details; but I already found a fix - submitting shortly.

**Comment by bddckr** [comment]
3.1.0 is old, use the latest master. Though we don't support 2017 anyway right now, could still be an issue even when using the latest master.

The tracking issue sounds like you've just been bitten by the SDK Manager auto-managing the used VR Settings of the Player Settings: You'll have to move OpenVR to be the first entry to make the SteamVR example scenes run.

**Comment by georgejecook** [comment]
Thanks,

the issue is steamVR. They have some c# directives for `UNITY_5_6` which need replacing with `UNITY_5_6_OR_NEWER`

submitted pr to valve https://github.com/ValveSoftware/steamvr_unity_plugin/pull/36

**Comment by bddckr** [comment]
Ah I see you've been bitten by the same thing we were when adjusting VRTK to work with SteamVR plugin 1.2.1: https://github.com/ValveSoftware/steamvr_unity_plugin/pull/14

Our fix included in VRTK should work even on 2017 I think, it's doing the same thing your PR does pretty much: https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs#L27-L33

**Comment by georgejecook** [comment]
Their issue also screws up the rendering too.
On 5/29/2017 11:14:30 AM, Christopher-Marcel Böddecker <notifications@github.com> wrote:
Ah I see you've been bitten by the same thing we were when adjusting VRTK to work with SteamVR plugin 1.2.1: ValveSoftware/steamvr_unity_plugin#14 [https://github.com/ValveSoftware/steamvr_unity_plugin/pull/14]
Our fix included in VRTK should work even on 2017 I think, it's doing the same thing your PR does pretty much: https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs#L27-L33 [https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs#L27-L33]

**Comment by bddckr** [comment]
Just saying: If it's fixed by your PR but not by our fix in VRTK we probably need to update VRTK in case they don't fix it by the time 2017 is released.

**Comment by georgejecook** [comment]
That's likely the case:
  * I had latest master from VRTK/github and had the problem. 
  * Appied my fix to steamVR and did not have the problem.
On 5/29/2017 11:35:38 AM, Christopher-Marcel Böddecker <notifications@github.com> wrote:
Just saying: If it's fixed by your PR but not by our fix in VRTK we probably need to update VRTK in case they don't fix it by the time 2017 is released.
