### ISSUE TITLE
Error thrown when switching radialMenu buttons while in use.

### ISSUE THREAD

**Issue by thodl15** [thestonefox/VRTK#1243]
If an instance of the Radial Menu prefab is active (i.e. touching the trackpad), switching the buttons and calling RegenerateButtons() causes the Radial Menu to become inoperable until it is released.

I've identified the issue to be occurring on Line 302 in the VRTK_RadialMenu.cs file, and given that an outOfRange exception is being thrown, my personal guess is that the array of menuButtons, if updated to have fewer than previously stated, is causing the error.

I've temporarily patched this in my own work, but it is most definitely just a temporary fix.

**Comment by thodl15** [comment]
Just a follow-up thought, would it make more sense to have a standardized way of replacing the menu buttons, just to make sure that any necessary events happen before the buttons are replaced?

**Comment by thestonefox** [comment]
@thodl15 can you use the issue template when raising a bug including steps to reproduce the issue otherwise it's very difficult to look into the bug.

I'm closing this ticket as it doesn't adhere to the issue template. It will be reopened when the template is adhered to.
