### ISSUE TITLE
Switching scenes with VRTK_SDKManager.instance.UnloadSDKSetup() crashing

### ISSUE THREAD

**Issue by manxjason** [thestonefox/VRTK#1244]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: cf205d2
 * Version of Unity3D: 5.6.1 (and an earlier version, I forget the version exactly)
 * Hardware used: Oculus Rift
 * SDK used: OpenVR/SteamVR

### Steps to reproduce

- Load any sample scene
- Hit backspace

### Expected behavior

Another scene should load

### Current behavior

Same scene may flicker on one or one attempts, then either Unity will crash for the SDK Setups will fail to load any SDKs.

Both editor and build will display inconsistent results. Sometimes the scene will load, other times not - this is repeating the same exact steps over and over.

To reproduce you may need to attempt several times.

**Comment by thestonefox** [comment]
Are you saying this only fails when you go back a scene and don't go forward?

i.e. Backspace crashes but Space never crashes?

**Comment by manxjason** [comment]
Both directions. Also crashes in my own scenes where I use that function and try to change scenes.

**Comment by manxjason** [comment]
Reinstalled Unity to 5.6.1f, reinstalled SteamVR, and the switching between scenes (in my own project) seems stable.

Neither space or backspace loads another scene - it now reloads the current.

**Comment by thestonefox** [comment]
As you're getting different results, I'd say this is a localised issue only you're having as you're not able to consistently recreate the issue.

**Comment by manxjason** [comment]
I'm happy if you want to close this for now - if I experience further difficulty can always reopen.

**Comment by thestonefox** [comment]
Yeah, may be worth closing this and trying to solve this one in the slack channel as it seems localised to your setup (http://invite.vrtk.io)

**Comment by thestonefox** [comment]
I'm actually able to recreate this if I skip the scenes very fast I can cause unity to crash.

If i pause between each skip then it's fine, but rapidly skipping crashes.

**Comment by thestonefox** [comment]
Actually I can recreate it every time.

Unity 5.5 with latest github master.

Open Up `006_Controller_UsingADoor` and cycle to the next scene.

It will crash every time.

**Comment by thestonefox** [comment]
Seems to be something to do with the body physics script

**Comment by thestonefox** [comment]
fixed with https://github.com/thestonefox/VRTK/commit/b94d453234f0d9bee6ac79cbb027714ae37ddec4
