### ISSUE TITLE
How to teleport On Objects

### ISSUE THREAD

**Issue by Jithendrakumar** [thestonefox/VRTK#1251]
Hi,

I am using VRTK 3.1.0, and i have HTC Vive using for my project. I am able to teleport anywhere in the scene using the basic teleport, but whenever i try to teleport on top of some objects, the Pointer will be able to interact with the Objects and i can visualy see that it is at the top of the object but when i click on Trackpad, i'll be in the Pointer's chosen location but height will be 0 means i'll be stick to the ground not on top of the object.

This is kinda weird or i may be missing something to turn on.

I am using all the default setting and the VRTK Prefab that comes with the Library.

Any suggestions?

**Comment by thestonefox** [comment]
You need to use the Height Adjust Teleport and not the Basic Teleport

**Comment by Jithendrakumar** [comment]
Thanks @thestonefox , i found out that the Playarea should be attached "VRTK_HeightAdjustTeleport" script and that worked well, i compared Basic and Height adjust examples and found the difference.
