### ISSUE TITLE
HeadsetFollower doesn't become a child of CenterEyeAnchor on Oculus - with fix

### ISSUE THREAD

**Issue by lambdor** [thestonefox/VRTK#1255]
* Source of VRTK: github 
 * Version of VRTK: master 96334ddcadaa3050dffbc50c8434971010d2a3ff
 * Version of Unity3D: 5.6.1p1
 * Hardware used: Oculus
 * SDK used: Oculus Utilities

### Steps to reproduce

start the 031_CameraRig_HeadsetGazePointer example and find that the HeadsetFollower object is not a child of OculusVR/OVRCameraRig/TrackingSpacE/CenterEyeAnchor

### Resolve

In VRTK_SDKObjectAlias OnEnable:
1. the VRTK_SDKManager instance is set to a local variable instead of the member => remove local variable
2. ChildToSDKObject() is called immediately even though sdkManager.loadedSetup is not yet assigned. This procedure will be called again anyway once the setup is assigned => remove line

**Comment by thestonefox** [comment]
This is already fixed (i believe) with https://github.com/thestonefox/VRTK/commit/256e60136ae489b363d71d8665655ae493284a1e
