### ISSUE TITLE
Controller grab not working

### ISSUE THREAD

**Issue by pcreation2** [thestonefox/VRTK#1258]
**Environment**
•	Source of VRTK (Unity Asset Store)
•	Version of VRTK (Unity Asset Store 3.1.0)
•	Version of Unity3D (5.5.1f1)
•	Hardware used (Vive)
•	SDK used (SteamVR 1.2.1)

**Steps to reproduce**
1.	Download and install Unity 5.5.1f1.
2.	Import VRTK Virtual Reality Toolkit 3.1.0 from asset store.
3.	Import SteamVR Plugin 1.2.1 from asset store.
4.	Open Examples folder and load ‘005_Controller_BasicObjectGrabbing’
5.	Play

**Expected behavior**
I should be able to pick the objects up by using the trigger button.
According to https://www.youtube.com/watch?v=FjwN8AJx0rY 

**Current behavior**
The objects highlight when I put the controller inside them but when pulling the trigger button you cannot pick them up.
I am not seeing any errors in the Console.
I did notice the ‘Controller’ has only one script assigned to it [SteamVR_TrackedObject] yet the ‘Controller’ from the video link above has many more scripts assigned to it like ‘SteamVR_ConrollerEvents’, ‘SteamVR_InteractGrab’, ‘SteamVR_InteractTouch’ and more but I also noticed the video is more than a year old so I assume the scripts have been optimised/changed.

This lack of controller/object interaction is happening on all the Example scenes.
Any advice much appreciated.

**Comment by thestonefox** [comment]
Try pressing grip
