### ISSUE TITLE
InteractableObject not usable when using Pointer in headset

### ISSUE THREAD

**Issue by lambdor** [thestonefox/VRTK#1261]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 20a5267ceffe6cc961ac08b50db4e0c345f30221
 * Version of Unity3D: 5.6.1p1
 * Hardware used: Oculus
 * SDK used: Oculus Utilities 1.15.0

### Steps to reproduce

Start in 031_CameraRig_HeadsetGazePointer.unity

In [VRTK]/Headset
remove VRTK_BezierPointerRenderer and VRTK_PlayAreaCursor
add a VRTK_StraightPointerRenderer with Cursor Visibility: Always On
In VRTK_Pointer component:
* Enable Teleport: false
* PointerRenderer: reference to StraightPointerRenderer
* Hold Button to Activate [ ]
* Activate On Enable [x]
* Select After Hover Duration: 1
* Remove Controller reference

Add a VRTK_InteractableObject component to any existing object (use one of the blue ones)
* Is Usable [x]
* Hold Button To Use [ ]
* Pointer Activates Use Action [x]

If you start the scene and hover over the object for one second a NullPointerException is thrown:
VRTK_Pointer.cs Line: 596
```givenInteractableObject.IsValidInteractableController(controller.gameObject, givenInteractableObject.allowedUseControllers))```

### Expected behavior

I'm just looking for a way to gaze at an object to "use" it. DestinationPoint basically does what I need, but if I disable teleport the whole object is disabled. Should I inherit from DestinationMarker and implement my own DestinationMarkerObject?

**Comment by thestonefox** [comment]
Relies on this:

https://github.com/thestonefox/VRTK/pull/1254

**Comment by thestonefox** [comment]
The fix after the above PR is merged is in `VRTK_Pointer` line `596`

currently is:

`return (givenInteractableObject != null && givenInteractableObject.pointerActivatesUseAction && givenInteractableObject.IsValidInteractableController(controller.gameObject, givenInteractableObject.allowedUseControllers));`

it needs to check if controllers are required like:

`return (givenInteractableObject != null && givenInteractableObject.pointerActivatesUseAction && (!ControllerRequired() || givenInteractableObject.IsValidInteractableController(controller.gameObject, givenInteractableObject.allowedUseControllers)));`

**Comment by lambdor** [comment]
Then it fails in VRTK_Pointer Line 633
```pointerInteractableObject.StartUsing(controller.gameObject);```

**Comment by thestonefox** [comment]
That's what the PR fixes already ;)

**Comment by lambdor** [comment]
kk

**Comment by lambdor** [comment]
It is still a little weird to use though. I have to add an VRTK_InteractUse component which "is attached to a Controller object and requires the VRTK_ControllerEvents and VRTK_InteractTouch" all of which make no sense in the headset. Also I didn't find a way to react to start or stop hover events. What is the intended way do make a progress bar in a gaze pointer?

**Comment by thestonefox** [comment]
what do you mean the Interact Use requires the controller events and touch? Are you reading code comments? they may just be out of date
