### ISSUE TITLE
VRTK play area cursor not aligned with pointer

### ISSUE THREAD

**Issue by reddo123** [thestonefox/VRTK#1264]
* Source of VRTK - Unity Asset Store
 * Version of VRTK - 3.1.0
 * Version of Unity3D - 5.6.1f1
 * Hardware used - Vive
 * SDK used - SteamVR

Steps to reproduce

Add VRTK_PlayAreaCursor script to Left or Right controller which has Straight or Bezier renderer and pointer scripts attached
Drag LeftController or RightController gameobject onto Playarea cursor setting of renderer scripts
Play project and trigger pointer to teleport. 

### Expected behavior

Pointer should be in the middle of play area cursor.

### Current behavior

Pointer is currently not centered correctly with the play area cursor

**Comment by thestonefox** [comment]
The cursor is showing your representation of where you're standing in your play area.

If you want that turned off then untick the `Headset Position Compensation` option 

![image](https://user-images.githubusercontent.com/1029673/26967959-2c929b4a-4cf8-11e7-9701-03a2bc7407a8.png)

**Comment by reddo123** [comment]
That did the trick. Thank you for the direction
