### ISSUE TITLE
Documentation generator doesn't understand langword

### ISSUE THREAD

**Issue by bddckr** [thestonefox/VRTK#1267]
The documentation generator isn't handling the `langword` xml tag like in `<see langword="null"/>`.

This is observed for `VRTK_SDKManager.loadedSetup` for example. [Here](https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs#L178)'s the original code docs and [here](https://github.com/thestonefox/VRTK/blob/master/DOCUMENTATION.md#class-variables-17)'s the generated documentation (scroll down a bit).

**Comment by thestonefox** [comment]
Merging with https://github.com/thestonefox/VRTK/issues/1296
