### ISSUE TITLE
Ability to provide varying snap handle transform info based on controller type

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1268]
Currently when applying a snap handle to a Interactable Object, it will only be at the correct orientation based on one controller.

However, the Vive wand in SteamVR is a different orientation to the Oculus Touch on home (and also different to Oculus Touch on SteamVR).

There needs to be a way that you can specify a snap handle but with different transform position/rotations based on the current controller being used.

**Comment by thestonefox** [comment]
Similar to: https://github.com/thestonefox/VRTK/issues/876

and has links to: https://github.com/thestonefox/VRTK/issues/472

**Comment by bddckr** [comment]
As I mentioned on Slack:

We probably need a generic solution for per-SDK/headset settings. Someone wanted different activation buttons, and I'm sure there are other valid settings, too.

**Comment by thestonefox** [comment]
What do you mean different activation buttons?

You mean like on a pointer for instance at the moment you can say touchpad press activates? but you may want to say:

vive = touchpad press
oculus touch = grip press
?

**Comment by bddckr** [comment]
The use case in Slack was teleportation:
- Vive uses touchpad _press_
- Rift should use touchpad _touch_

**Comment by bddckr** [comment]
If it's only snap handles and button mapping I guess we're fine with this issue and #842.

**Comment by thestonefox** [comment]
@bddckr yeah I think that other issue is how we solve that (who does it first, VRTK or xR Foundation Toolkit?!)
