### ISSUE TITLE
Grip release on non-grip joint break.

### ISSUE THREAD

**Issue by tjhowse** [thestonefox/VRTK#1269]
### Environment
Github VRTK 94914f07c9a5098ff6a477df03f3e3c8ef8c917c
Vive, SteamVR

### Steps to reproduce

Create two grabbable VRTK_InteractableObjects, A and B.
Give them both rigidbodies.
Add a fixed joint to A, attached to B, with a break force of 100.
Grab A.

### Expected behavior

Object A should be grabbed, the fixed joint should snap, B should fall, and A should remain grabbed.

### Current behavior

When the fixed joint snaps, A is ungrabbed.

**Comment by thestonefox** [comment]
I can recreate the issue.

I'm struggling to understand why the PR fix of `if (controllerAttachJoint == null)` works

The OnJointBreak will get called for any joint that is on the object when it breaks right?

But when you pick the object up, you'll have `controllerAttachJoint` set to the created joint.

So then why in the OnJointBreak for the second joint is the `controllerAttachJoint` null?

**Comment by tjhowse** [comment]
It's a crude fix. The object catches an OnJointBreak event when either the
grab joint or the manually-added joint snaps.

All my fix does is check to see whether the grab joint exists when the
OnJointBreak is received. If the grab joint still exists it is still intact
and the object should not be ungrabbed. It must have been a a different
joint destruction that sent OnJointBreak.

**Comment by thestonefox** [comment]
So basically when the OnJointBreak happens

because there are 2 joints on the object, it does that check for both joints and one joint is tied to the `controllerAttachJoint` and the other one isnt?

Your fix works, but will it cause any other issues?

**Comment by tjhowse** [comment]
I couldn't think of any cases in which a grab should continue to exist when the joint that performed the function of the grab no longer existed.

**Comment by thestonefox** [comment]
The PR causes more issues so it will need to be reverted.

I think the best solution to this problem is just not have 2 joints on the interactable object, if you have another object that is to be attached with a joint then point the joint on the other object.
