### ISSUE TITLE
Opacity on vive controllers, exported project.

### ISSUE THREAD

**Issue by galleplop** [thestonefox/VRTK#1283]
### Environment

 * **Source of VRTK:** Unity Asset Store
 * **Version of VRTK:** Unity Asset Store
 * **Version of Unity3D:** Unity 5.5.1f1
 * **Hardware used:** Vive
 * **SDK used:** OpenVR

### Context

Hi!

I've been using VRTK for 2 months, and now when I built my project from Unity, controllers opacity doesn't work well. On play mode works well with Unity.

I wrote a script similar to "VRTK_ControllerAppearance_Example.cs" wich is used in "035_Controller_OpacityAndHighlighting.unity" example. I'm using "SetControllerOpacity(float alpha)" and "HighlightControllerElement(GameObject element, Color? highlight, float fadeDuration = 0f)" functions from "VRTK_ControllerActions".

I checked all parameters in "VRTK_SDKManager.cs", specially model alias.

In exported project, I see a few opacity when I pressed a button (even if alpha number is decreased), it's as if not all controller's parts and buttons had the same opacity.

I have had a similar problem when I built "035_Controller_OpacityAndHighlighting.unity" example.

### Steps to reproduce

Build and run "035_Controller_OpacityAndHighlighting.unity" example.

### Expected behavior

I expected Unity's play mode behavior.

### Current behavior

Confused opacity behavior. For example you can't see well trigger highlighted button when you pressed it.

### Possible solutions.

May be I need to set different "Play setting" options. Do you have some advice?

-- Guillermo Suárez.

**Comment by thestonefox** [comment]
I dont understand what the issue is from the current behaviour being "confused opacity" Do you have some screenshots of the issue?

Also are you saying it isn't an issue in the editor but only in a build?

**Comment by galleplop** [comment]
Yes, it is an issue only in a build.

For example in "035_Controller_OpacityAndHighlighting.unity" scene.

Built project's screenshot:
![capture01](https://user-images.githubusercontent.com/5725306/27202440-06acc504-51f8-11e7-81b6-eb96b3d9b0a9.PNG)

Unity play mode's screenshot:
![capture02](https://user-images.githubusercontent.com/5725306/27202441-06ae9b40-51f8-11e7-8c53-baac36eb5c88.PNG)

**Comment by thestonefox** [comment]
Yeah I can confirm this too. It's like when you're in build mode steamvr is streaming a different set of materials or something, or perhaps some optimizations are done that make the materials no longer have the ability to be transparent.

I'll keep looking into it, but if anyone can shed any light that would be great.

**Comment by bddckr** [comment]
This is an issue because the `SteamVR_RenderModel` uses the Standard shader by default. Unity only compiles the shader variants that are actually used in the scenes you include in a build.

This issue boils down to no transparent Standard shader variant being compiled and included in the standalone build. To work around this:

1. Create a new material, set it to use the Standard shader.
2. Set the material's `Rendering Mode` to `Transparent`.
3. Use the material on any object that is included in a scene that will be included in the standalone build. (Game object can be set inactive.)

**Comment by thestonefox** [comment]
So is this an issue with the SteamVR plug in for unity? If so should we raise an issue on their github?

**Comment by bddckr** [comment]
This is more just a normal Unity issue, I don't think you can call this a SteamVR issue.

Users "just" have to make sure the transparent variant of the shader used (Standard if not changed on SteamVR_RenderModel) is included in builds.

**Comment by thestonefox** [comment]
So i guess we just mark this as PSA and close the ticket. as we can't provide a built in solution, just point people to this as the solution? seem fair?

**Comment by thestonefox** [comment]
I'm going to tag this as PSA and close the ticket as mentioned
