### ISSUE TITLE
Rotation during Teleport

### ISSUE THREAD

**Issue by claytmcneil** [thestonefox/VRTK#1291]
protected virtual void DoTeleport(object sender, DestinationMarkerEventArgs e)
        {
            if (enableTeleport && ValidLocation(e.target, e.destinationPosition) && e.enableTeleport)
            {
                StartTeleport(sender, e);
                Vector3 newPosition = GetNewPosition(e.destinationPosition, e.target, e.forceDestinationPosition);
                CalculateBlinkDelay(blinkTransitionSpeed, newPosition);
                Blink(blinkTransitionSpeed);
                Vector3 updatedPosition = SetNewPosition(newPosition, e.target, e.forceDestinationPosition);
                Quaternion updatedRotation = SetNewRotation(e.destinationRotation);
                ProcessOrientation(sender, e, updatedPosition, updatedRotation);
                EndTeleport(sender, e);
            }
        }

In the above, translation (SetNewRotation) occurs before rotation (SetNewRotation). When e.destinationRotation changes the play-space rotation and Headset Compensation is enabled, the result can be that the headset does not actually end up at e.destinationPostion (the severity of the error depends on the distance the headset is from the center of the the play-space).

I've worked around the problem as follows, although I'm not crazy about the solution...

        protected virtual void DoTeleport(object sender, DestinationMarkerEventArgs e)
        {
            if (enableTeleport && ValidLocation(e.target, e.destinationPosition) && e.enableTeleport)
            {
               Vector3 newPosition;
                StartTeleport(sender, e);
               /* calculate new position to get blink delay */
                newPosition = GetNewPosition(e.destinationPosition, e.target, e.forceDestinationPosition);
                CalculateBlinkDelay(blinkTransitionSpeed, newPosition);
                Blink(blinkTransitionSpeed);
               /* perform rotatation first to account for possible HMD translation */
                Quaternion updatedRotation = SetNewRotation(e.destinationRotation);
               /* calculate new-new position */
               newPosition = GetNewPosition(e.destinationPosition, e.target, e.forceDestinationPosition);
                Vector3 updatedPosition = SetNewPosition(newPosition, e.target, e.forceDestinationPosition);
                ProcessOrientation(sender, e, updatedPosition, updatedRotation);
                EndTeleport(sender, e);
            }
        }

**Comment by claytmcneil** [comment]
My attempt to help the visually inclined:

![image](https://user-images.githubusercontent.com/26917963/27207112-221a6af0-520a-11e7-8bc6-87d8dd981feb.png)

**Comment by thestonefox** [comment]
So you're saying that currently when you teleport with rotation. You're not actually standing in the correct part of the play area?

In the image above, the rotation on the second operation doesn't seem to have any rotation applied to it? Is this as to be expected or just an error with the image?

**Comment by claytmcneil** [comment]
Its not that you're not in the correct part of the play area, its that the play area isn't moved correctly to account for the extra HMD translation that occurs due to rotation.

To clarify the image above, teleporting with rotation involves two operations, teleport (i.e. change play area position) and rotate. Depending on which you do first, you get different results.

Look at the first row- the first operation is a rotation 90 degrees clock wise. You'll notice that the rotation also introduced a translation of the HMD. Even though the play area maintained its position (because it was rotated about center) the HMD has a new position. When the actual teleportation occurs, HMD compensation will take care of the extra translation that occurred and put the HMD in the intended final position.

Now look at the second row- when rotation occurs after the teleportation, the extra translation still occurs with rotation. However, since teleportation already occurred, it doesn't get compensated for and the HMD ends up in the wrong position.

Of course, this isn't a problem if there is a) not rotation applied, b) the HMD is in the center of the play area.

**Comment by thestonefox** [comment]
sorry i was reading the image wrong :) i was reading as columns rather than rows :)

**Comment by claytmcneil** [comment]
Yep, I thought that might be the confusion. Hopefully the expanded explanation helps aid the drawing.

**Comment by bgr** [comment]
@thestonefox I believe this is related to the issue I encountered with Destination Marker with Rotation With Headset Offset on `release/3.3.0-alpha`

**Comment by thestonefox** [comment]
PR to fix the issue: https://github.com/thestonefox/VRTK/pull/1367

Just need to call rotation before doing anything with teleport.

This is probably going to need a further fix in the release branch as the dash teleport lerps to the destination rotation but doesn't do it in current master.
