### ISSUE TITLE
Auto generate documentation with an official xmldoc generator

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1296]
At the moment the documentation is auto generated with a custom generator that generates the `DOCUMENTATION.md` file but also splits out the documentation into the separate pages that are required for `readme.io`.

There are a number of things that the custom generator doesn't support, so it would be better to use an official generator but also need it to generate the two required outputs.

**Comment by bddckr** [comment]
The .NET Foundation supports [DocFX](https://github.com/dotnet/docfx).

**Comment by thestonefox** [comment]
https://www.codeproject.com/Articles/1030797/Automatic-Markdown-formatting-for-VS-xml-documenta

**Comment by thestonefox** [comment]
Also found http://www.stack.nl/~dimitri/doxygen/

I think the output it generates (and potentially any of these off the shelf generators) is a bit confusing and very verbose

**Comment by thestonefox** [comment]
Come back to this another time
