### ISSUE TITLE
NullReferenceException when using the simulator

### ISSUE THREAD

**Issue by trumpetx** [thestonefox/VRTK#1299]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: eb55971012b6b4d550105b04f02c4f4340bcba60
 * Version of Unity3D : 5.6.1p3
 * Hardware used: Vive
 * SDK used: SteamVR / Simulator

### Steps to reproduce

Use the simulator from the SDK switcher

### Expected behavior

Can look up & down

### Current behavior

Looking is limited to left & right accompanied by a NRE:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.SDK_InputSimulator.UpdateRotation () (at Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs:365)
VRTK.SDK_InputSimulator.Update () (at Assets/VRTK/SDK/Simulator/SDK_InputSimulator.cs:250)
```

**Comment by thestonefox** [comment]
I can't recreate this.

I'd recommend re-downloading and double checking your installation.

**Comment by trumpetx** [comment]
I was getting this error, then updated to the latest last night and I still get the error (Different line).

@bddckr noticed the issue with @virror 's PR - something to do with the prefab not having a neck.

**Comment by bddckr** [comment]
Yeah @virror only updated the SDKSetups prefab that is used in the example scenes, so anyone using the Simulator prefab directly will need to wait for @virror's fix 😄

**Comment by thestonefox** [comment]
ah right ok, so the simulator in the example scene works because it's part of the SDK Setup prefab, but the simulator camera rig prefab is broken?

**Comment by bddckr** [comment]
@thestonefox Exactly.

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1302
