### ISSUE TITLE
SnapRotateObjectControl for persistent SDKs

### ISSUE THREAD

**Issue by outerbrain** [thestonefox/VRTK#1300]
### Environment

 * Source: Github
 * Version of VRTK: latest
 * Version of Unity3D: 5.6.1
 * Hardware used: Vive/Oculus
 * SDK used: SteamVR
### Steps to reproduce

With a Persist On Load SDK, add a Snap Rotate Object Control. Load to another scene, and the snap rotate functionality will not work for a short amount of time.

### Expected behavior

Snap Rotate will work on scene load

### Current behavior

Inside SnapRotateObjectControl, due to the protected virtual float Rotate() function, "snapDelayTimer = Time.timeSinceLevelLoad + snapDelay;" does not reset on scene load. By adding an OnEnable function that resets snapDelayTimer to 0, the issue has been fixed.

**Comment by thestonefox** [comment]
I wonder if `timeSinceLevelLoad` is the best choice if it's causing this issue.

**Comment by bddckr** [comment]
Why isn't this using `Time.time`?

**Comment by thestonefox** [comment]
I'm not sure why it isn't I swiped the code from the TouchpadMovement script :D

**Comment by thestonefox** [comment]
PR to address the issue https://github.com/thestonefox/VRTK/pull/1303

**Comment by thestonefox** [comment]
@outerbrain are you able to check if the PR fixes your issue?

**Comment by outerbrain** [comment]
@thestonefox confirmed, all working as expected 👍
