### ISSUE TITLE
DestinationPoint doesn't disappear

### ISSUE THREAD

**Issue by Backer-Sultan** [thestonefox/VRTK#1307]
Destination points doens't disapper anymore when teleporting to them after pointer activation button is changed from 'Touchpad press' to 'Touchpad touch'.

 * Source of VRTK: GitHub
 * Version of VRTK: eb55971012b6b4d550105b04f02c4f4340bcba60
 * Version of Unity3D: 5.6.1f1
 * Hardware used: Oculus
 * SDK used: SteamVR

### Steps to reproduce

1. Open Example scene 44.
2. On 'VRTK_Pointer' script that is attached to 'RightController' game object, change 'Activation button' to 'Touchpad Touch'.
3. Teleport to any destination point.

### Expected behavior

The destination point disappears.

### Current behavior

The destination point doesn't disappear and appear again instantly.

#### Things I noticed that might be related to/cause the issue:
- `Disabled` event is triggered twice when teleporting.

**Comment by thestonefox** [comment]
Try this PR https://github.com/thestonefox/VRTK/pull/1308

**Comment by Backer-Sultan** [comment]
@thestonefox now it hides the destination point when teleporting to it, but it doesn't show it again after leaving. (it doesn't set the active state of the default cursor object to true after teleporting away).

**Comment by thestonefox** [comment]
@Backer-Sultan that's not the output i'm getting.

When i teleport to a destination point and then teleport somewhere else, the destination point is becoming active again.

I'll upload a gif to show it

**Comment by thestonefox** [comment]
![teleport](https://user-images.githubusercontent.com/1029673/27342466-2e86e878-55d8-11e7-8641-222363c2cdc6.gif)

**Comment by Backer-Sultan** [comment]
I'll double check.

**Comment by Backer-Sultan** [comment]
@thestonefox well, that's true if you're teleporting only from one destination point to another.
But when you teleport to a non destination point object (the floor), the last teleported-to destination point keeps intactive. I'll see if I cant upload a video.

**Comment by thestonefox** [comment]
ah ok so when you just teleport to a normal destination

**Comment by thestonefox** [comment]
@Backer-Sultan I've pushed a further fix to the existing PR

**Comment by Backer-Sultan** [comment]
@thestonefox Fixed! Thank you!
I think the PR is ready to merge.
