### ISSUE TITLE
Simulator "neck" is rotated 90 degrees

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1311]
Using latest from github:

-Remove the Sim rig from the sdk setups and replace it with the prefab.
-Play the scene and all movements are wrong, you move left instead of forward and so on.

Looking at the "Neck" GO, its rotated y = 90. Setting this to 0 fixes the issue.

**Comment by virror** [comment]
@thestonefox @bddckr 
I think we should get this in the 3.2 release? Its a super quick fix and potentially pretty breaking for the user.

**Comment by thestonefox** [comment]
https://github.com/thestonefox/VRTK/pull/1310/commits/0246fb4047c62d96a14efdf5353f25745db6fb1f
