### ISSUE TITLE
Unity 2017 compatibility

### ISSUE THREAD

**Issue by cameronoltmann** [thestonefox/VRTK#1318]
Controllers are missing in Unity 2017.  Making the following change resolves this:

**Commit:** 0acab31a39414f6818da389ff3971627b863df35
**File:** Assets/VRTK/SDK/SteamVR/SDK_SteamVRBoundaries.cs

Change line 27 from:
`#if UNITY_5_6`
to:
`#if UNITY_5_6 || UNITY_5_6_OR_NEWER`

**Comment by thestonefox** [comment]
This was changed in a previous PR https://github.com/thestonefox/VRTK/commit/43638c8b0d7f0132cb8708cd6049be9ccd3fa877

Because apparently an older version of Unity 2017 didn't require the Update Poses.

I think this is a case of Unity Betas not being stable enough to make decisions on.

**Comment by cameronoltmann** [comment]
Interesting.  As of b10, it's necessary again.  Wasn't in b9.  Love it.

**Comment by thestonefox** [comment]
This is why it's best to stay well away from Unity betas :D

Let's close this ticket and deal with it when unity 2017 is released

**Comment by nylki** [comment]
> Let's close this ticket and deal with it when unity 2017 is released
Apparently thats today :)

**Comment by thestonefox** [comment]
@nylki afaik VRTK 3.2.1 is compatible with Unity 2017.1 - Quite a few people are using it already

**Comment by nylki** [comment]
@thestonefox Ok. good to know, thx for the heads up!
