### ISSUE TITLE
ControllerTooltips NullReferenceException

### ISSUE THREAD

**Issue by LeoTindall** [thestonefox/VRTK#1321]
### Environment

 * Source of VRTK: *Github*
 * Version of VRTK: *master 0acab31*
 * Version of Unity3D: *5.6.1f1*
 * Hardware used: *Vive*
 * SDK used: *SteamVR from Asset Store*

### Steps to reproduce

I created a scene in which the right controller's script alias has a `VRTK_ControllerTooltips` on it. I then created a script to enable and disable them with `ToggleTips`. I then ran the scene.

![controller tooltips problem](https://user-images.githubusercontent.com/3290365/27517815-5592bf84-5987-11e7-9085-986762aa93be.PNG)

### Expected behavior

Tooltips should appear. According to the docs: 

> If the transforms for the buttons are not provided, then the script will attempt to find the attach transforms on the default controller model.

### Current behavior

I got no tooltips appearing and the following error:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_ControllerTooltips.InitButtonsArray () (at Assets/ImportSDK/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs:264)
VRTK.VRTK_ControllerTooltips.Awake () (at Assets/ImportSDK/VRTK/Prefabs/Resources/Scripts/VRTK_ControllerTooltips.cs:200)
```

**Comment by thestonefox** [comment]
You need to provide more information

What is your custom script doing? When are you calling Toggle Tips?

Can you provide steps of how to recreate this issue in the example scenes.

**Comment by LeoTindall** [comment]
The script calls ToggleTips in Update, but the same thing happened when I called it in Setup. I'm currently working on recreating on an example scene.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using VRTK;

public class MenuLevelController : MonoBehaviour {

    [Tooltip("The level controller will turn these tooltips on and off as appropriate.")]
    public VRTK_ControllerTooltips ControllerTooltips;

    [Tooltip("The transform to use in order to track the player's position.")]
    public Transform PlayerLocation;

    [Tooltip("The transform of the object the player should go to and use.")]
    public Transform TargetLocation;

    [Tooltip("How close to the TargetLocation the PlayerLocation should be before prompting the player to interact.")]
    public float TargetDistance = 1.5f;

	void Start () {
		if (ControllerTooltips == null)
        {
            Debug.LogError("MenuLevelController::ControllerToolTips may not be null.");
            return;
        }

        if (PlayerLocation == null)
        {
            Debug.LogError("MenuLevelController::PlayerLocation may not be null.");
            return;
        }

        if (TargetLocation == null)
        {
            Debug.LogError("MenuLevelController::TargetLocation may not be null.");
            return;
        }
	}
	
	void Update () {
        float distance = Vector3.Distance(PlayerLocation.position, TargetLocation.position);
        if (distance > TargetDistance)
        {
            try
            {
                // Turn off all the tooltips.
                ControllerTooltips.ToggleTips(false);
                // Turn on the controller's tooltip for teleportation.
                ControllerTooltips.ToggleTips(true, VRTK_ControllerTooltips.TooltipButtons.TouchpadTooltip);
            }
            catch (System.NullReferenceException e)
            {
                Debug.Log("Tried to set tooltips, but controllers were not yet available." + e);
            }
        } else {
            try
            {
                // Turn off all the tooltips
                ControllerTooltips.ToggleTips(false);

                // Turn on the interaction hint
                ControllerTooltips.ToggleTips(true, VRTK_ControllerTooltips.TooltipButtons.TriggerTooltip);

            } catch (System.NullReferenceException e)
            {
                Debug.Log("Tried to set tooltips, but controllers were not yet available." + e);
            }
        }
	}
}

```

**Comment by LeoTindall** [comment]
Successfully recreated by loading `004_CameraRig_BasicTeleport.unity` and adding `VRTK_ControllerTooltips` to `[VRTK_Scripts]/RightController`.

**Comment by thestonefox** [comment]
I cannot recreate this issue.

My steps were:

 * Open VRTK github master (3.2.0) in Unity 5.6.1f1
 * Open example scene `004_CameraRig_BasicTeleport`
 * Add the prefab `ControllerTooltips` to `[VRTK_Scripts]/RightController`
 * Run the scene and it works.


I'm guessing your issue is you're just adding a prefab script without the prefab.

**Comment by LeoTindall** [comment]
Yes, I think you're right! Perhaps it would be useful to add a sentence about this to the VRTK_ControllerTooltips documentation?

In any case, I apologize for wasting your time.
