### ISSUE TITLE
VRTK.SDK_OculusHeadset.GetHeadset NullReferenceException

### ISSUE THREAD

**Issue by D3m0n92** [thestonefox/VRTK#1324]
With the latest update just starting my scene I immediately get this repeating error:

NullReferenceException: Object reference not set to an instance of an object
VRTK.SDK_OculusHeadset.GetHeadset () (at Assets/VRTK/SDK/Oculus/SDK_OculusHeadset.cs:55)
VRTK.SDK_OculusHeadset.GetHeadsetCamera () (at Assets/VRTK/SDK/Oculus/SDK_OculusHeadset.cs:69)
VRTK.VRTK_SDK_Bridge.GetHeadsetCamera () (at Assets/VRTK/SDK/VRTK_SDK_Bridge.cs:503)
VRTK.VRTK_TransformFollow.OnCamPreRender (UnityEngine.Camera cam) (at Assets/VRTK/Scripts/Utilities/ObjectFollow/VRTK_TransformFollow.cs:119)
UnityEngine.Camera.FireOnPreRender (UnityEngine.Camera cam) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/CameraBindings.gen.cs:719)

When I change the scene the error stops.

**Comment by thestonefox** [comment]
you need to provide steps to reproduce the error in an example scene

**Comment by bddckr** [comment]
Sounds like you didn't set up the needed SDK Setups. Check the example scenes.

**Comment by D3m0n92** [comment]
Nope.. I solved copying a sdkmanager from a sample scene and copying my scripts. Anyway, really did not change anything (in fact some update did everything worked properly).

**Comment by D3m0n92** [comment]
Go to example 005, tick onPersistentOnLoad and press Play. Error VRTK.SDK_OculusHeadset.GetHeadset () 
 spamming started.

**Comment by bddckr** [comment]
Sounds like #1316? The PR for that one should reduce the potential for errors in case you were on a previous version and it was working fine.
We recommend to switch to additive scenes or put the SDK stuff into every scene, though, as you can read in that issue.

**Comment by thestonefox** [comment]
@D3m0n92 we're phasing out `persist on load` as it doesn't work as we expect it to.
