### ISSUE TITLE
Body collider hight for Simulator calculated wrongly

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1325]
After the addition of the Neck for the Simulator the body collider height now gets calculated incorrectly.
This can be seen very easy by just playing using the Simulator and bodyPhysics.

The fix is to change one line in VRTK_BodyPhysics.cs in the UpdateCollider method:
Old:
float newpresenceColliderYSize = (headset ? headset.transform.localPosition.y - (headsetYOffset + CalculateStepUpYOffset()) : 0f);
New:
float newpresenceColliderYSize = (headset ? (headset.position.y - playArea.position.y) - (headsetYOffset + CalculateStepUpYOffset()) : 0f);

This will calculate the height based on the difference of the headset and play area positions instead of just using the localPosition. This should also be a safer method overall since it does not rely on the assumption that the headset Object is always a direct child of the playArea.

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1334
