### ISSUE TITLE
Support for Ximmerse Flip SDK ( unity Cardboard )

### ISSUE THREAD

**Issue by tazzkiller** [thestonefox/VRTK#1328]
immerse has release a SDK for the Flip Controller ( https://github.com/Ximmerse/SDK_Flip ) but is not compatible with VRTK. You think possible to add comaptibilty with VRTK and Cardboard for unity ?

**Comment by thestonefox** [comment]
I don't have a Flip controller, but if someone wants to add support then feel free

**Comment by tazzkiller** [comment]
thank's for your reply thestonefox,
the SDK is detected but return error : 

``VRTK.SDK_BaseController.ControllerType' does not contain a definition for `LeftController'`

``VRTK.SDK_BaseController.ControllerType' does not contain a definition for `RightController'`

`Ximmerse.InputSystem.ControllerInput' does not contain a member `GetButton' and the best extension method overload `Ximmerse.InputSystem.XimmerseExtension.GetButton(this Ximmerse.InputSystem.ControllerInput, Ximmerse.InputSystem.XimmerseButton)' has some invalid arguments

`Ximmerse.InputSystem.ControllerInput' does not contain a definition for `GetTouchPos' and no extension method `GetTouchPos' of type `Ximmerse.InputSystem.ControllerInput' could be found.`

`The name `DaydreamButton' does not exist in the current context`

**Comment by thestonefox** [comment]
It was the Ximmerse team that built the Ximmerse support into VRTK, if you contact Ximmerse and let them know about this issue they may be able to update their support for VRTK
