### ISSUE TITLE
Prefab ControllerTooltips missing script reference - VRTK_ControllerTooltips

### ISSUE THREAD

**Issue by rgjones33** [thestonefox/VRTK#1329]
Version 3.2.0 
![image](https://user-images.githubusercontent.com/26989653/27689473-4b0f3682-5cac-11e7-99e0-86f4c79a94b0.png)

**Comment by thestonefox** [comment]
Can't recreate this.

I'm guessing you've not deleted the old version of VRTK before updating or something.

It's working fine for me, if anyone else can check it too to confirm.

**Comment by rgjones33** [comment]
Hmm I was pretty sure I deleted the folder in my app and dragged in a fresh copy after doing a git pull to my main clone of VRTK. Will double check when i get home.

**Comment by rgjones33** [comment]
Just doubled checked it on a fresh download and you're correct the script reference is fine. I will be more careful to reproduce the issue on a fresh copy before opening another issue in the future.

**Comment by thestonefox** [comment]
no worries :) thanks for double checking
