### ISSUE TITLE
VRTK_SDK Manager/SDKSetupSwitcher - Simulator loaded first - Causes issues with SteamVR and grabbed objects

### ISSUE THREAD

**Issue by MustardCat** [thestonefox/VRTK#1330]
### Environment

 * Github
 * 3.2.0 and 7490bea
* SteamVR version 1.2.1 and 1.2.2
 * Unity 5.6.1f1
 * Simulator and Vive
 * Simulator and then switched to SteamVR using SDKSetupSwitcher

### Steps to reproduce

1) Load up example scene 008 (or any scene that has a grabbable object and the SDKSetupSwitcher)
2) In the SDK Manager, move the Simulator rig to the top position so it loads first
3) After starting the scene, switch to SteamVR
4) Try to grab a grabbable object.  Sometimes this glitch happens only with one controller (and it could be left or right), other times it happens with both

### Expected behavior

The grabbed object will attach to the controller and behave like it would when SteamVR is loaded first

### Current behavior

The grabbed object teleports to a random position and does not follow any controller movements when "grabbed"

Here are a couple of videos explaining the issue: 

1) Scene 008 - SteamVR 1.2.1 - https://streamable.com/q02l0
2) Empty scene with just a grabbable cube, plane and the SDK setups - SteamVR 1.2.2 - https://streamable.com/8pj3a

The videos were made in separate projects

**Comment by thestonefox** [comment]
Confirmed

**Comment by thestonefox** [comment]
The `InteractGrab` controller attach point is not being reset correctly

**Comment by thestonefox** [comment]
The issue is when you switch to SteamVR, SteamVR takes a few seconds to set the controllers up and the InteractGrab script has already tried to set up the attachpoint by the time the controllers are enabled.

**Comment by thestonefox** [comment]
It's actually more fundamental than this i think.

It looks as if when you switch from something to SteamVR and steamVR wasnt the first to be enabled, then the VRTK_TrackedController doesn't get the correct index

**Comment by thestonefox** [comment]
PR to fix https://github.com/thestonefox/VRTK/pull/1332
