### ISSUE TITLE
Attempt Grab Issue

### ISSUE THREAD

**Issue by telso2** [thestonefox/VRTK#1337]
### Environment

 * Source of VRTK: Unity Asset Store
 * Version of VRTK: 3.1.0
 * Version of Unity3D: 5.6.1f1
 * Hardware used: VIVE
 * SDK used: Steam VR

### Steps to reproduce

The problem I'm encountering is I want an object to instantiate into the players hand, whilst he presses the respective Grab button. 

This is basically what my code is doing.

    GameObject SpawnedGameObject = (GameObject)Instantiate(GameObjectToSpawn, LeftControllerScript.transform.position, LeftControllerScript.transform.rotation);
    LeftControllerScript.GetComponent<VRTK.VRTK_InteractGrab>().AttemptGrab();

### Expected behavior

Players presses down the trigger (button that Grab is mapped to), the Object instantiates, then the player can move their hands around and the object will be in a state of 'grab' and do the usual things that a grabbed object does.

### Current behavior

The Object instantiates and falls straight to the floor, the player then has to pick the object back up again. 

I'm trying to use the AttemptGrab() in the VRTK.VRTK_InteractableGrab and even instantiating it directly ontop of the corresponding controller position.

thanks,
telso

**Comment by bddckr** [comment]
You'll have to force the InteractTouch, too. I suggest to just use the `VRTK_ObjectAutoGrab` script. 😄

**Comment by telso2** [comment]
Yeah i was thinking that. Il do some tests with it.

**Comment by MustardCat** [comment]
I'm not sure how your VRTK_InteractableObject script is set up in the inspector, but I ran into a similar issue before.  I don't believe it's a bug (but someone with more knowledge of the VRTK code could verify).

In the inspector for your instantiated prefab, make sure you have the "Grab Attach Mechanic" field correctly set; don't leave it as none. 

Ex - My instantiated object needed to be climbable so I dragged the VRTK_Climbable Grab Attach script into that field

I also used ForceTouch() and AttemptGrab() but that's because my climbable object may not have been instantiated where the controller was

**Comment by telso2** [comment]
@MustardCat 
Ah okay, thats interesting. Did your method end up working for you in the end?

I'm using the autograb method that Bddckr recommended and its kinda working, still have to try a few more things with it.

**Comment by MustardCat** [comment]
Yep, everything works good now. Took a while to figure out that I needed to drag-and-drop the script as the protip states the following (so I didn't actually figure it out until much later than I should have):

> This determines how the grabbed item will be attached to the controller when it is grabbed. If one isn't provided then the first Grab Attach script on the GameObject will be used, if one is not found and the object is grabbable then a Fixed Joint Grab Attach script will be created at runtime.

Using the same code in my script, without dragging-and-dropping the grab script into that field, the controller wouldn't grab onto the instantiated item.

**Comment by thestonefox** [comment]
If this is resolved, can we close the ticket?
