### ISSUE TITLE
Possible bug? -> VRTK seems to prevent SteamVR camera rig prefab from working...

### ISSUE THREAD

**Issue by MarkDasMagic** [thestonefox/VRTK#1353]
### Environment

 * Asset Store
 * 3.2.1 [6 July 2017 release]
 * 5.6.1f1
 * Vive
 * SteamVR 1.2.2 [29 June 2017 release]

### Steps to reproduce

1. Start a new project and import SteamVR then VRTK.
2. Run any VRTK example scene.
3. Open a new, clean scene and drop in the SteamVR camera prefab.
4. Hit play.

### Expected behavior

A working, stock-standard SteamVR [CameraRig]

### Current behavior

The scene doesn't load - the headset turns on, but I'm stuck in my bland, grey SteamVR "loading room". Note that I'm not referring to the new(ish) Steam Home beta, that is not running at all.

**Comment by bddckr** [comment]
The `VRTK_SDKManager` that sits in (every) example scene(s) has a checkbox to auto-manage the needed VR settings. You can disable that checkbox and manage the list yourself. You have to make sure it works with the used VRTK SDK Setups if you use VRTK, though, so it's recommended to leave it checked.

If you don't load the VRTK scenes with an SDK Manager in them that has that checkbox checked the settings won't be changed, too.

You can find them at `Edit > Project Settings > Player`.

**Comment by MarkDasMagic** [comment]
Thanks, didn't even think to check player settings.

**Comment by thestonefox** [comment]
Is this good to close now?

**Comment by MarkDasMagic** [comment]
Yeah, just had to move openvr to the top of the list as suggested. I should have explicitly stated that everything is sorted - still new to all this github stuff...
