### ISSUE TITLE
SDK_InputSimulator Exception when "Persist On Load" with runtime prefab Instantiate

### ISSUE THREAD

**Issue by RanaInside** [thestonefox/VRTK#1355]
### Environment

* VRTK GitHub master version
* Unity 5.6.1f1
* Vide
* OpenVR

### Steps to reproduce
Setup as Persist on load on SDK_Manager with all the sdks underneath; use as a prefab and instantiate.

### Expected behavior
when using as prefab, not throw an error :)

### Current behavior
Currently, SDK_InputSimulator is using FindInScene to get the cameraRig; which in turn get's all the resources and returns the first matched in activeScene.

Issue: With "Persist on load" and loading prefab runtime, sdk_Manager is moved to a different scene named "DontDestroyOnLoad"; so VRTK_SharedMethods.FindEvenInactiveGameObject method returns null, and fails with sdkSimulator.

My current patch: following three methods check for component in activeScene;

FindEvenInactiveGameObject<T>
FindEvenInactiveComponents<T>
FindEvenInactiveComponent<T>

I've refactored scene check into a different method

```
      private static bool IsInScene(Scene activeScene, GameObject gameObject)
        {
            return (gameObject.scene == activeScene) || (gameObject.scene.name.Equals("DontDestroyOnLoad", StringComparison.OrdinalIgnoreCase));
        }

```
I'm not doing a pull request as I'm not sure if my style would fit existing codebase :D 

Thanks again for vrtk.

**Comment by thestonefox** [comment]
Persist on Load is deprecated. You should move away from using it:

https://github.com/thestonefox/VRTK/commit/63adb7ed32367bfaa3a68b34b22cec0e8eb1e8da

**Comment by RanaInside** [comment]
Hi thestonefox, so what are the replacement for it? Especially when we start on a fast initial loader while loading the mainscene on background?

**Comment by thestonefox** [comment]
As it says in the link I posted:

```
It's recommended to use additive scene loading instead. To reduce
the likelihood of these issues breaking the project for users
already using the setting this fix also makes sure to only populate
the SDK Setup object references when this setting is *not* checked.
```

**Comment by RanaInside** [comment]
Hi, sorry I was on mobile and didn't see the link; understood. And thanks again.
