### ISSUE TITLE
GetObjectCenter in VRTK_BaseObjectControlAction returns wrong center

### ISSUE THREAD

**Issue by Avatar70** [thestonefox/VRTK#1357]
### Environment

VRTK Version 3.2.0 from Unity Asset Store
Unity Version 5.6.1p1
Vive and Oculus Rift

### Steps to reproduce

Load Example 017_CameraRig_TouchpadWalking, remove Bodyphysics from Playarea, get a Nullpointer in GetObjectCenter.

In function GetObjectCenter in RotateAroundPlayer it tries to get a CapsuleCollider from the first children, but the VR-Controllers are also Childrens of this. The Vive Controllers uses a Capsule Collider for the body object, so it returns this instead of the one in [VRTK][AUTOGEN][BodyColliderContainer] which I think was the idea.
 
It works on Oculus Rift because because here, only a sphere Collider is used. But if no Bodyphysics is added to the playarea it crashes because then no Capsule Collider will be found.

### Expected behavior

The function should not use the CameraRig and search for a collider there, it should rather search for [VRTK][AUTOGEN][BodyColliderContainer] and get the capsuleCollider from here. If not found it may just return a zero vector.

### Current behavior

GetObjectCenter only works with Oculus Rift and Bodyphysics added as a component to Playarea, but should also work without this and on Vive the Rotation Center should not be the VR Controller.

**Comment by thestonefox** [comment]
PR with fix: https://github.com/thestonefox/VRTK/pull/1358
