### ISSUE TITLE
ScaleObjectInteractor method shrinks controller gameObject

### ISSUE THREAD

**Issue by thodl15** [thestonefox/VRTK#1362]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.1.0
 * Version of Unity3D: Unity 2017.1.0f3
 * Hardware used: Oculus
 * SDK used: SteamVR

### Steps to reproduce

Attempt to recreate the issue in a VRTK example scene and provide steps to reproduce in a clear text step by step list. Include code samples, errors and stacktraces if appropriate.

 * Open Example Scene 030_Controls_RadialTouchpadMenu
 * Add VRTK_Pointer & VRTK_Straight Pointer Renderer Scripts to the RightController GameObject.
 * Set VRTK_Pointer's Pointer Renderer to the attached VRTK_Straight Pointer Renderer.
 * Press Play
 * Open RadialMenu to ensure correct size
 * Activate RightController pointer
 * Open RadialMenu again

### Expected behavior

The RadialMenu should be the same size before and after activating the RightController pointer.

### Current behavior

After activating the RightController pointer, the RadialMenu has visibly shrunk in size.

### Personal Analysis
I spent some time researching what might be happening in the program, and I found that the ScaleObjectInteractor method in the VRTK_BasePointerRenderer class was causing the scale change. It looks like it is calling the method SetGlobalScale that is adjusting the size of the controller GameObject. Is that working as intended?

**Comment by thestonefox** [comment]
I followed the steps you outlined in VRTK version 3.2.1 and I cannot recreate the issue.

Are you missing any steps or has the problem been fixed in a newer version?

**Comment by thodl15** [comment]
Oh, yes there is a step missing I realized:

Before hitting Play, the Straight Line Pointer Renderer needs to have the "Interact With Objects" option selected.

Its this option selection that causes the problem, unfortunate that it seems to be the step I accidentally omitted in my earlier post!

**Comment by thestonefox** [comment]
PR to fix the issue: https://github.com/thestonefox/VRTK/pull/1366
