### ISSUE TITLE
Suggestion about method naming

### ISSUE THREAD

**Issue by Roland09** [thestonefox/VRTK#137]
I suggest a more meaningful method naming like e. g. there is:

```
public bool IsControllerVisible()
public void ToggleControllerModel(bool on, GameObject grabbedChildObject)
```

A more meaningful method and parameter could be

```
public bool IsControllerVisible()
public void SetControllerVisible(bool visible, GameObject grabbedChildObject)
```

The toggling can be done explcitly as well without having to know what "bool on" is.

```
public bool ToggleControllerVisibility() {
    SetControllerVisible(  ! IsControllerVisible(), ...);
}
```

**Comment by thestonefox** [comment]
Seems legit, do you want to do a PR or happy to have it queued up for me to look at?

**Comment by Roland09** [comment]
Please queue it, I can do it in a PR later if you wish. I'm not that familiar with Unity yet.
