### ISSUE TITLE
CameraRig falls through floor when VRTK_BodyPhysics is enabled and Headset loses tracking

### ISSUE THREAD

**Issue by ZnelArts** [thestonefox/VRTK#1374]
### Description
When ```VRTK_BodyPhysics``` is enabled and the ```CameraRig``` is on a level upper than the floor, if the headset loses tracking for a split second, sometimes the ```CameraRig``` will fall through the floor.

Even when the tracking resumes, the ```CameraRig``` already fell through the floor.

This is even reproducible in the ```037_CameraRig_ClimbingFalling``` Example Scene

### Environment

 * Source of VRTK
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
62aa1e0893e0fe64120b173455d222ed2d5d3db1
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.1
 * Hardware used (e.g. Vive/Oculus)
Vive and Oculus
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR

### Steps to reproduce
1. Open the ```037_CameraRig_ClimbingFalling037_CameraRig_ClimbingFalling``` Example Scene
1. Climb to some level above the floor
1. Cover the headset with your hands to simulate a temporal lost of tracking
1. Once tracking was lost observe what happened, repeat previous step if nothing happened.

### Expected behavior
The ```CameraRig``` should resume tracking where the player was standing.

### Current behavior
When the headset loses tracking, the ```CameraRig``` starts falling through the floor.

**Comment by thestonefox** [comment]
I can't recreate this, I've tried 5 times and i never get the issue that's being reported. Maybe someone else can try it?

**Comment by haywirephoenix** [comment]
For me, I can't seem to prevent the CameraRig from falling through the floor when using VRTK_BodyPhysics with latest build and 3.2.1

Unity v2017.1.0f3, Oculus Utilities v1.16.0, OVRPlugin v1.16.0, SDK v1.16.0.

**Comment by thestonefox** [comment]
Unless someone can provide consistent steps to reproduce, i'll end up closing this ticket.

**Comment by steve-salmond** [comment]
For anyone who may be interested, I encountered a similar behaviour when adding VRTK to my existing project.  It turned out that this was due to my having earlier disabled physics interactions between 'Default' and 'Ignore Raycast' layers (in the collision matrix on Unity's physics setting page - Edit > Project Settings > Physics). Hope that might help in this case!
