### ISSUE TITLE
Tracers that work in the bezier renderer don't work in the straight renderer

### ISSUE THREAD

**Issue by insominx** [thestonefox/VRTK#1378]
### Environment

 * Source of VRTK - Github
 * Version of VRTK - 10ad77636fee591e8d7aff3e524dfd91e8812353
 * Version of Unity3D - 2017.1.0f3
 * Hardware used - Oculus CV
 * SDK used - Oculus Integration (1.15 July 13 2017)

### Steps to reproduce

Open the VRTK example 003_Controller_SimplePointer
On the VRTK_StraightPointerRenderer component and set the CustomTracer property to the LightSegmentTexAnim prefab as shown in the VRTK example videos.

Hit play and notice the lack of tracer visuals when teleporting.

### Expected behavior

Visuals should be similar to those experienced with the bezier renderer.

### Current behavior

The "segment" gameobject is offset from the hand controller instead of being attached to it.  It also doesn't appear to be billboarding correctly.

![image](https://user-images.githubusercontent.com/180210/28343482-662b4ab6-6bd2-11e7-8d8c-bbc1091f15ef.png)

**Comment by thestonefox** [comment]
The Straight Pointer Renderer and the Bezier Pointer Renderer are different concepts and it's not expected that custom objects for them should be interchangable between them,

The bezier pointer uses multiple objects to represent the beam, whereas the straight pointer uses one object.

You would have to build two separate custom tracer objects for each one. Tracer is just the concept name for the beam it's not an actual implementation of a concrete concept.

There are very little common denominators between the straight pointer and bezier pointer.

**Comment by insominx** [comment]
Thank you for the quick response @thestonefox

**Comment by insominx** [comment]
Ok, I think I understand the issue now.  For anyone else that might experience this, the line render will scale a single object so in order for that to work correct correctly, that single object's origin must be in its center.  The bezier version uses an origin that is in the back of the object which makes sense when you're going to place multiple of them.

**Comment by piede828** [comment]
> Ok, I think I understand the issue now. For anyone else that might experience this, the line render will scale a single object so in order for that to work correct correctly, that single object's origin must be in its center. The bezier version uses an origin that is in the back of the object which makes sense when you're going to place multiple of them.

This has helped me so much and it should be in the documentation. Otherwise there is no way to implement a custom tracer for the Straight Renderer
