### ISSUE TITLE
Default Objects Lock up when unsnapped from code

### ISSUE THREAD

**Issue by Eforen** [thestonefox/VRTK#1379]
Default Objects Lock up when unsnapped from code.

### Environment

 * Source of VRTK (Unity Asset Store)
 * Version of VRTK (3.1.0)
 * Version of Unity3D (Unity 5.6.1f1)
 * Hardware used (Oculus)
 * SDK used (SteamVR)

### Steps to reproduce

1. Set an object (foobar) as the default object to be snapped into a `VRTK_Snap Drop Zone` that is in joint mode
2. On an object (foobar) that is currently snapped in call `foobar.GetStoredSnapDropZone().ForceUnsnap();`
3. Then Move said object anywhere it will nolonger move at all it will be locked in space. This is because the object will have the is Kinematic flag set. Though if the object is removed from the snap by hand it does not retain this flag.

### Expected behavior

The object falls out of the snap with the kinematic flag removed

### Current behavior

The default object retains the kinematic flag

**Comment by thestonefox** [comment]
Try this with the latest github master
