### ISSUE TITLE
UI Raycast strange prioritization.

### ISSUE THREAD

**Issue by Larsupulami** [thestonefox/VRTK#1382]
UI Raycast strange prioritization.
I have 2 canvases in front of each other. 10cm distance between. One turned around y 180°. Both functional but one has priority over the other. Always. If I try to click it from the Front it works fine, but from the back, the front button reacts.
Even with a solid cube (mesh filter/mesh renderer/collider) in between.

Source: 
          Unity Asset Store and Github
Versions: 
          Unity Asset Store 3.2.1 (Jul 06, 2017)
          Github Latest commit 64b576 (20.07.2017)
          Unity 5.6 and 2017.1
Hardware:
          Vive
SDK:
          Unity: OpenVR
          VRTK_SDK Manager: SteamVR

Reproduce:
          1. Create 2 world space Canvases (similar to them in scene 34) (VRTK_UI Canvas component present)
          2. Both filled with a button
          3. place both with a little distance (like 5cm) in between
          4. turn the behind one around y 180°
          5. try to press them from both sides straight on so that the ray "would" hit both

Expected behavior:
One Canvas should block the other one from reacting and should react.

Current behavior:
One Canvas always has priority over the other. The position doesn't matter. Blocking Objects doesn't matter.
Ps: tried every combination of Blocking Objects and Blocking Mask. Both canvases with child elements are on the UI Layer.

**Comment by thestonefox** [comment]
Is this issue the same as one of these?

https://github.com/thestonefox/VRTK/issues/1197

https://github.com/thestonefox/VRTK/issues/982

**Comment by Larsupulami** [comment]
Its similar to #982. Could be the same problem. But im not sure. 

-------- Ursprüngliche Nachricht --------Von: StoneFox <notifications@github.com> Datum: 20.07.17  21:06  (GMT+01:00) An: thestonefox/VRTK <VRTK@noreply.github.com> Cc: Larsupulami <lars.guettinger@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [thestonefox/VRTK] UI Raycast strange prioritization. (#1382) 
Is this issue the same as one of these?
#1197
#982

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thestonefox/VRTK","title":"thestonefox/VRTK","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thestonefox/VRTK"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thestonefox in #1382: Is this issue the same as one of these?\r\n\r\nhttps://github.com/thestonefox/VRTK/issues/1197\r\n\r\nhttps://github.com/thestonefox/VRTK/issues/982"}],"action":{"name":"View Issue","url":"https://github.com/thestonefox/VRTK/issues/1382#issuecomment-316800280"}}}

**Comment by thestonefox** [comment]
I cannot recreate this issue.

What I did was

 * Open Example scene 34
 * Copy the `ExampleWorldObjects/Canvas` game object
 * Change the copy's rotation to `y=90` so it's rotated to face the other way
 * Change the copy's position to `x=-4.5` so it's further away from the original
 * Start the scene and try and click the `Generate Canvas` button on both canvases

I can successfully select the correct `Generate Canvas` button on both canvases.

**Comment by Larsupulami** [comment]
I'll try to recreate the problem tomorrow and record it. Wasnt working for me. Even posted it in your Slack Channel. Nobody could help me. For context: I wanted to create a UI like that from Tiltbrush. And the problem appeared as soon as I got two Canvases above each other. My workaround was to test for my possible Pointers and deactivate the UI-Canvases

**Comment by thestonefox** [comment]
If you can recreate it in the example scene with steps to reproduce then I can try look at it too.

Don't create a custom scene and upload it because the bug may not be within VRTK and people tend not to have time to debug 3rd party code.

**Comment by Larsupulami** [comment]
I could recreate it. No custom code. I'll try to recreate it in that example scene. A video will be ready soon. (16kbit soon.... shit :D)

**Comment by Larsupulami** [comment]
Ok, I found a solution. Tested it before. Pretty sure. Works now. I'm fine with that. Maybe while I was testing something went wrong. Graphic Raycaster has to be set to "All". Still a little bit of strange behavior. Activates sometimes from behind sometimes not. But the rest reacts like planned. I really should activate Shadowplay at work. Would save time. Thanks anyway.  Your VRTK is awesome btw. Especially that new Simulator. 
Ps: Will test it tomorrow at work. Have to do some research to prevent false calls. I want to know what went wrong.

**Comment by ownstoppable** [comment]
I think I'm having this problem as well. Basically what is happening is that one world canvas always has priority over another one, and I can't find the reason.

Source:
Unity v2018.2.11f1
Oculus Utilities v1.30.0 
OVRPlugin v1.30.0, SDK v1.32.0
VRTK (latest commit)

Reproduce:
Create scene
Create two VRTK_UICanvas
Add graphic raycaster to both canvas with Blocking objects set to All
Add a button with an action to both Canvas
Move one behind and slightly above the other one
Angle your controller so it would click on both of them if there was no raycast blocking

Expected behavior:

The Canvas that is closer to the camera should block the Canvas that is behind it

Current behavior:

One of the Canvas always has priority over the other one, even if it is behind

PS: Make sure to swap the canvas on a second try, because you might have the "priority" Canvas in front and it might look like it works properly.

**Comment by wdulot** [comment]
I had the same problem and solved it this way:
- I turned on Blocking Objects = All on the canvas Graphics Raycaster
- I added a custom tracer and a custom cursor to my Straight Pointer Renderers. These custom tracer and cursor have no collider and rigidbody. (there seem to be a raycasting problem with the tracer and cursor created by default)
