### ISSUE TITLE
No controller models...broken script links in examples

### ISSUE THREAD

**Issue by SmartCarrion** [thestonefox/VRTK#1386]
### Environment

 * Source of VRTK : Github
 * Version of VRTK : f5e91a4
 * Version of Unity3D : 2017.1
 * Hardware used: Oculus
 * SDK used : Oculus Utilities 1.16

### Steps to reproduce

Open VRTK in Unity, add oculus utilities, open scene 035_Controller_OpacityAndHighlighting (or any of them).  Hit Play and look at controllers.

### Expected behavior
You should see the controllers and button highlighting

### Current behavior

Controllers are absent.  In the project hierarchy under 'LocalAvatar'  there seem to be many scripts not loaded, but I can't tell what they are!  Note, there are no compile errors.
![image](https://user-images.githubusercontent.com/5105110/28497200-33954248-6f36-11e7-969f-45d9b9c0fdf1.png)

**Comment by bddckr** [comment]
You're missing the Oculus Avatar package. Import that one, too. The Oculus Utilities package doesn't provide controller models AFAIK.

**Comment by SmartCarrion** [comment]
OK, that sounds like it should work.  This should probably be updated in the documentation, that more is need than just the Oculus Utilities.  Otherwise, I'd mark it closed:

> 
> Oculus
> Instructions for using Oculus Utilities
> 
> Download the Oculus Utilities from the Oculus developer website.

**Comment by bddckr** [comment]
Well the docs are kinda right, aren't they?
You only need Avatar if you want the models that are provided by the vendor. Most people don't want to use these models anyway. If you just slap a box on the game object you have a representation of them, too.
