### ISSUE TITLE
GearVR - Changning Handedness in Game Leaves Ghost Controller

### ISSUE THREAD

**Issue by InnerScript** [thestonefox/VRTK#1388]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
GitHub

 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0-alpha

 * Version of Unity3D (e.g. Unity 5.4.4f1)
5.6.1f1

 * Hardware used (e.g. Vive/Oculus)
GearVR

 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
Oculus

### Steps to reproduce
1. Setup a GearVR scene with the GearVR prefab in right and left hands
2. Play game to validate controller appears
3. In game, long press the Back button until the Oculus menu appears
4. Change the handedness from Right/Left or Left/Right
5. Click "Back" to return to game
6. Note the controller model in the other hand is still present, floating in it's default position

### Expected behavior

The previous controller GameObject should be hidden.

**Comment by thestonefox** [comment]
I'm not sure if this is more of an issue with the Oculus OVRCameraRig. It doesn't seem to hide the GameObject for the tracked controller anchor if it's disabled. I would assume that it should do this, if you're using a Oculus Rift with Touch and the touch is not active then it should probably hide the controller anchor GameObject.

I'm not sure whether this is a VRTK issue or an Oculus Utilities issue as you'd get the same behaviour even if you weren't using VRTK.

**Comment by thestonefox** [comment]
I can confirm that the OVRCameraRig doesn't disable the game object when the tracking anchor is not available. Therefore this issue isn't technically a bug within VRTK as it would have the same outcome if you were just using the OVRCameraRig.

Another potential alternative would be to use Oculus Avatar package and make the GearVR Controller model a child of the relevant hands. As Oculus Avatar seems to correctly hide when a controller isn't available.
