### ISSUE TITLE
Changing Scenes VRTK

### ISSUE THREAD

**Issue by ohthatsjhall** [thestonefox/VRTK#1391]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.1.0
 * Version of Unity3D: 5.6.1 
 * Hardware used: Vive
 * SDK used: SteamVr

### Current behavior

I’m trying to load a new scene in Unity (5.6.1) with VRTK but having troubles. I’ve tried SceneManager.loadscene (both single and additive modes) which put my VRTK camera in the next scene in the floor and not usable by VRTK. SteamVR_LoadScene options crash unity. I’ve tried every combination of checking "persist on load" in the VRTK SDKmanager and the UnloadSDKManager method before load scene but nothing seems to be working. Any tips would be appreciated.

**Comment by thestonefox** [comment]
You need to provide steps to reproduce in an example scene

**Comment by bddckr** [comment]
Make sure to update VRTK to 3.2.1, since it has this: https://github.com/thestonefox/VRTK/pull/1301

**Comment by ohthatsjhall** [comment]
@bddckr thank you, this was exactly what I needed. Feel free to close this issue.
