### ISSUE TITLE
VRTK_BodyPhysics.SweepCollision() CapsuleCast calculations fail when PlayArea is rotated.

### ISSUE THREAD

**Issue by Michaelwolf95** [thestonefox/VRTK#1395]
In VRTK_BodyPhysics.SweepCollision(), the calculation to find the starting points for the CapsuleCast does not take into account rotations of the PlayArea, and thus behave unexpectedly when the PlayArea is rotated. 
I've resolved this on my Fork by changing:
>`
Vector3 point1 = (bodyCollider.transform.position + (bodyCollider.center)) + (Vector3.up * ((bodyCollider.height * 0.5f) - bodyCollider.radius));
Vector3 point2 = (bodyCollider.transform.position + (bodyCollider.center)) - (Vector3.up * ((bodyCollider.height * 0.5f) - bodyCollider.radius));
`
to:
>`
Vector3 point1 = bodyCollider.transform.parent.TransformPoint(bodyCollider.transform.localPosition + (bodyCollider.center)) + (Vector3.up * ((bodyCollider.height * 0.5f) - bodyCollider.radius));
Vector3 point2 = bodyCollider.transform.parent.TransformPoint(bodyCollider.transform.localPosition + (bodyCollider.center)) - (Vector3.up * ((bodyCollider.height * 0.5f) - bodyCollider.radius));
`
### Environment
 * Source of VRTK: GitHub
 * Version of VRTK: 3.3.0-alpha
 * Version of Unity3D: Unity 5.62p4
 * Hardware used: Vive
 * SDK used: SteamVR

### Steps to reproduce
1. Open Example Scene "042_CameraRig_MoveInPlace"
2. Rotate "[VRTK_SDKManager]" (or your SDK Setup)  90 degrees.
3. Walk around the inside of the "room". You should notice that you'll stop suddenly when NOT near a wall.

### Expected behavior
Player should stop moving only when walking into a wall.

### Current behavior
When the PlayArea is rotated, the player stops when _not_ walking into a wall, since the CapsuleCast start from the wrong position.

**Comment by thestonefox** [comment]
It would be good if you could raise a pull request with the proposed fix.

**Comment by ShaneHamlin** [comment]
I recently ran into this myself. Thanks so much for fixing this Michaelwolf95 .

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1408

**Comment by Michaelwolf95** [comment]
@thestonefox 
Sorry for not raising the PR, I've been absolutely swamped with multiple projects, and I just hadn't had a chance. Thanks for doing it for me!
