### ISSUE TITLE
Request for VRTK to support handedness (left/right swapping)

### ISSUE THREAD

**Issue by rgjones33** [thestonefox/VRTK#1398]
For our application we would like to deal with a concept Primary controller and a Secondary controller. Where the handedness can be easily swapped and there would be no issues where controller actions would break due to swapping for left vs right handed people.

Propose that VRTK should abstract this so that every developer could assign functions and reference  Primary/Secondary/Both vs Left/Right/Both - then it would be easy to swap functions between hands.

I realize there is the concept of a left and right controller alias but I am not sure if that goes far enough?

**Comment by thestonefox** [comment]
What's the point of a primary/secondary controller? there is simply a controller in the left hand and a controller in the right hand.

a primary controller is game specific, not all games would require a primary controller and would just duplicate the controls on the left and right controller.

If a game wanted a primary controller then it would be possible with VRTK to set it up so certain controls acted on one controller and would easily be swapped to the other controller.

**Comment by rgjones33** [comment]
How do do you easily swap them?

**Comment by bddckr** [comment]
[Archive link.](https://vrtoolkit.slackarchive.io/general/page-57/ts-1501432720822507)

**Comment by thestonefox** [comment]
That's a lot of conversation. Could you describe in a concise form what you're actually trying to achieve.

It generally helps to describe a specific problem rather than offer a generic solution to what you think may solve your specific problem. That way other people can also provide other solutions to the given problem rather than try and understand how the solution fits into problems.

**Comment by JWNJWN** [comment]
I believe in the end it was decided that replacing the left and right controller alias's and systems with a primary and secondary controller made no real difference to the existing functionality, as anyone who wanted the same controls on both primary and secondary controllers would just set it up the same way and not change anything, but for anyone wanting primary and secondary controllers right now it's rather inconvenient to setup with pointer switching and stuff, replacing the current system with primary and secondary really just extends vrtk's functionality. If people still want left and right, they can just access them as primary and secondary, which correlates to right and left and not have to use the built in swapping.

**Comment by thestonefox** [comment]
@jwnjwn my view is you don't have a primary and secondary controller. You have a left and right hand controller.

The concept of a primary and secondary controller are specific to the needs of a game mechanic (e.g. left controller does X right controller does Y and you want that interchangable).

My thoughts are VRTK is doing it correctly by specifying Left and Right hand controller.

However, I do think it should be easier to swap functionality that is assigned to the left controller and that is assigned to the right controller.

This is a similar concept to what @dustinlacewell has been suggesting: https://github.com/thestonefox/VRTK/issues/875

**Comment by rgjones33** [comment]
Left or right, primary or secondary, a or b - whatever

Please don't let my terminology or concept of primary/secondary confuse the the end goal which is as jwn and yourself inferred correctly  "support for people who want handedness would be there, and easily toggleable." and "it should be easier to swap functionality that is assigned to the left controller and that is assigned to the right controller."

If VRTK can provide a mechanism for wholesale swapping of functionality between controller a and controller b vs me trying to figure out how to handle that I would be very happy.

In my app (not game)  I want function a,b,c on the controller of the users dominant hand and i want  function d,e and f on the non dominant hand . Once I determine which hand is what for a particular user, I want to adjust my app to accommodate.

I think we are all on the same page now.

**Comment by thestonefox** [comment]
Terminology is important

There is a difference between Left/Right hand and Primary/Secondary.

Renaming the left/right script alias stuff to primary/secondary wouldn't actually help with the problem and would cause more confusion anyway.

I suggest we close this issue as it is just an extension of the existing open issue of

https://github.com/thestonefox/VRTK/issues/875

**Comment by rgjones33** [comment]
I am fine with that. Hopefully you can factor in an easy way of function swapping between controllers into future versions of VRTK
