### ISSUE TITLE
Come up with categories for VRTK Awards 2017

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1399]
I want to do a VRTK awards where we recognise and award people within the VRTK community of things they've worked on, built and achieved.

Let's come up with some award categories.

Then I'll try and see if we can get some sponsorship for the prizes for each category.

Let's aim to have the awards in October/November time maybe? And perhaps make it annual?

** Current Categories** __(subject to change)__

 * Best VRTK creation (best thing created with vrtk to date)
 * Best VRTK Game on Steam (best game on steam created with vrtk)
 * Best VRTK Game on Oculus Home (best game on oculus home created with vrtk)
 * Best VRTK Academic usage
 * Best VRTK feature contribution (best user who created the best new feature contributed)
 * Best VRTK issue reporter (user who reported the best, most useful bug reports)
 * Number one VRTK bug fixer (user who helped fix the biggest, most bugs in vrtk)
 * Most helpful VRTK community member (user who helps out most in the community)
 * Best VRTK newcomer (user who is new to development making best progress)

**Comment by thestonefox** [comment]
Some category ideas

 * Best VRTK Game
 * Best VRTK contribution
 * Most helpful VRTK community member
 * Best VRTK experience
 * Best VRTK newcomer

**Comment by bddckr** [comment]
- Best VRTK maintainer :heart: 

I'd split "Best VRTK contribution":
- Best bugfix
- Best new feature contribution
- Best feature enhancement
- Best documentation contribution
- Best issue reporter

**Comment by talothman** [comment]
Would be interesting to see if people in academia are using VRTK. Maybe have a "Best Academic VRTK Contribution". I'm using it to start off research. :)

**Comment by thestonefox** [comment]
This probably isn't going to happen, no sponsors came forward. Let's leave it for a bit
