### ISSUE TITLE
IndependentRadialMenuController.cs shares objects InteractableObject component

### ISSUE THREAD

**Issue by rgjones33** [thestonefox/VRTK#1400]
* Source of VRTK (Unity Asset Store or Github) - github
 * Version of VRTK (Unity Asset Store/3.2.1 (Github master commit hash) bc305ec  
 * Version of Unity3D (e.g. Unity 5.4.4f1) 5.6.2.f1
 * Hardware used (e.g. Vive/Oculus) Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities) SteamVR 1.2.2

### Steps to reproduce

Working on it ...

### Expected behavior

Before or after the Radial menu is enabled, it should not get clicks/unclicks or other events unless the interacting controller is over the actual menu

### Current behavior

Radial menu is getting clicks/unclicks and other events when the interacting controller is not over the actual menu

### Briefly describe what is actually happening

Because the IndependantRadialMenuController.cs shares the sending objects  InteractableObject component the onClicked/OnUnclicked events for example get triggered even when the menu is not being interacted with.

**Comment by rgjones33** [comment]
So upon trying to replicate this behavior in the example #30 scene, I noticed that since I added support for Allowed controller type in IndependentRadialMenuController, so it would only show menus on Left, Right or Both controllers. When I select to limit support to only one controller, events are still being triggered on the radial menu when the "use" button is pressed on the other controller. So i expect this isn't really a problem with the code as shipped, it seems to be my adaptation to it for an enhancement.

**Comment by thestonefox** [comment]
i'm not sure what this issue is about now.

is it a bug report or a feature request?

**Comment by rgjones33** [comment]
At first I thought it might have possibly been a bug report but now I think it's more of a feature request. Hard to tell initially when your just trying to figure out how things work and making adjustments to suit your use case.
I added support for Allowed controller type in IndependentRadialMenuController and will possibly submit a pull request so you can see if you think it's of any value generally.

**Comment by rgjones33** [comment]
I would like to change this to request an update to the IndependentRadialMenu system where 

1. Controller Touch/Untouch activates/deactivates the menu (same as now)
2. The menu system reacts to it's own InteractableObject so object and menu events are kept separate
3. The menu system does not react to the scaling of the gameObject it's attached too

**Comment by thestonefox** [comment]
I'm not sure what the request for the new feature is.

perhaps you could close this issue, start a new issue with the request and provide more detail (maybe with proposed graphical designs if possible).
