### ISSUE TITLE
SnapDropZone fails to function if highlight container is outside collider

### ISSUE THREAD

**Issue by Slayd7** [thestonefox/VRTK#1401]
VRTK version: 3.2.1 (from Asset Store)
Unity version: 2017.1.0f3
HMD: Vive
SDK: SteamVR

### Steps to reproduce

Set up a SnapDropZone with the HighlightContainer outside the SnapDropZone's collider, and attempt to place the desired object in the SnapDropZone

### Expected behavior

Object snaps into place at the desired location

### Current behavior

Object stops snapping as soon as it leaves the collider. See: https://gfycat.com/lastingleadinginganue

**Comment by thestonefox** [comment]
If the object leaves the collider then it will no longer be considered snapped.

**Comment by Slayd7** [comment]
Understood, but it does not fire ObjectSnappedToDropZone in this case. It should, so I can pick up where the drop zone leaves off, since in this particular case it will never be considered snapped.

**Comment by thestonefox** [comment]
Because when the object leaves the collider it's no longer in the drop zone so it releases it from the drop zone. Basically when the snapped object calls OnTriggerExit it should auto drop
