### ISSUE TITLE
Create 3d controls that don't rely on Unity Physics and Joints

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1409]
The current set of 3d controls rely on Unity Joints and engine physics to work.

This gives a lot for free but creates a number of problems.

I propose to create a complimentary suite of 3d controls (which may eventually replace the existing ones) that don't use physics or joints at all and simply fake the control mechanism based on the movement/rotation/position-distance of the grabbing controller.

The following controls are proposed:

## Button

The button would simply be a collider and have an unpressed height and a pressed height. Upon the controller colliding with the button it would move it to it's pressed state, you wouldn't be able to just half press a button. It's either pressed or not.

## Chest

The chest would have a closed rotation and a open max rotation. When the controller grabs the chest, it would determine how much the open rotation is based on how far the controller is away from the original grab point.

## Door

The door would have a min rotation/max rotation and a closed rotation (maybe) and again the rotation would be calculated based on the controller position from the original grab position. Upon ungrabbing the door, the speed swing of the door would be determined by the velocity of the controller.

## Drawer

The drawer would have a closed position and a open position. Upon grabbing the drawer it would determine how far along that linear path it is based on how far the controller is away from the initial grab point. Upon ungrabbing the drawer, the speed slide of the drawer would be determined by the velocity of the controller.

## Lever

The lever would have a min rotation and a max rotation. Upon grabbing the lever it would determine the current rotation based on how far the controller was from the original grab point. Upon ungrabbing the lever, the speed swing of the lever would be determined by the velocity of the controller.

## Spring Lever

This would probably just be included in the lever code.

## Wheel

The wheel would need to rotate around its central axis but not simply based on how far the controller was from the original grab point. Need to think about this one in more detail.

**Comment by sbmhome** [comment]
This seems like an excellent idea and would controls much more stable.

**Comment by thestonefox** [comment]
Start of PR https://github.com/thestonefox/VRTK/pull/1550

**Comment by thestonefox** [comment]
Done
