### ISSUE TITLE
Support for 6DOF head tracking in Google VR

### ISSUE THREAD

**Issue by andybak** [thestonefox/VRTK#1410]
See https://developers.google.com/vr/android/release-notes#gvr_sdk_and_ndk_for_android_v1800_august_2017

**Comment by thestonefox** [comment]
Until I get a daydream, I'm not in a position to do anything with Google VR

**Comment by andybak** [comment]
No currently available hardware supports 6DOF either. Is it worth leaving this issue open as a marker for the future? I'll try and grab the standalone headset when it becomes available and I can assist with this feature.

**Comment by thestonefox** [comment]
Worth keeping open for reference
