### ISSUE TITLE
Radiu Menu will be hidden on oculus rift

### ISSUE THREAD

**Issue by BensonZheng2016** [thestonefox/VRTK#1415]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (version 3.2.1)
 * Version of Unity3D (2017.1.0f3)
 * Hardware used (Oculus)
 * SDK used (Oculus Utilities version 1.16.0)

### Steps to reproduce
1.open example scene :030_Controls_RadialTouchpadMenu
2.modify the setting of ovravatar as follow:
![ovravtarsetting](https://user-images.githubusercontent.com/18454958/29204411-7016453c-7ea9-11e7-8c6f-56b5601460cf.png)
3.disable hand_left and hand_right game object.
![33](https://user-images.githubusercontent.com/18454958/29204453-baa6eef8-7ea9-11e7-88b7-5a99a4dba63f.png)

### Current behavior
The touch menu in front of touch controller,so we can see the whole touch pad menu.
a part of touch controller will be hidden.

**Comment by thestonefox** [comment]
Have you tried simply rotating the radial menu transform?

**Comment by BensonZheng2016** [comment]
yes, I had done it , But the result is same.

**Comment by BensonZheng2016** [comment]
![image](https://user-images.githubusercontent.com/18454958/29206251-abeca394-7eb3-11e7-8428-7b59047da09a.png)

**Comment by thestonefox** [comment]
That's a problem with the Oculus Avatar shader on the controller, it's rendering in front of everything else.

Look at this issue on Hover-Kit-UI for the proposed fix:

https://github.com/aestheticinteractive/Hover-UI-Kit/issues/52#issuecomment-267657591

**Comment by BensonZheng2016** [comment]
Thank you, It is very useful.
