### ISSUE TITLE
Documentation suggestion: "Is added to" and "Also requires" for each script

### ISSUE THREAD

**Issue by andybak** [thestonefox/VRTK#1416]
Whilst this information is often in the description for a component - it's not always there and is sometimes a bit buried.

I suggest a standard format for the docs where each component has an entry maybe at the start of "Overview" that describes:

1. What gameobject/prefab this component is intended to be added to
2. What other components/prefabs either here or elsewhere in the scene are needed for minimal functionality.

The probably I'm trying to solve here is the "starting from scratch" problem. I still find myself grabbing prefabs from the example scenes that do what I need - as it's quicker than figuring out what combination of components I need to add to a vanilla scene.

**Comment by bddckr** [comment]
Good idea. A shared doc format can go a long way in making it more beginner-friendly and eases the pain that is documenting it all.

**Comment by andybak** [comment]
I've been thinking about this some more. Personally - I've been going back to basics. My original project involving VRTK was rushed and I mainly muddled through by grabbing a whole hierarchy from the examples and tweaking it as needed.

I've started to try and teach a couple of others to use VRTK and it's forced me to ensure I fully understand what's going on.

With that in mind I've started going through the examples to see the simplest route to recreate their functionality. As mentioned elsewhere "getting started" stops a little short and the main docs are a mix of things you really need to know to get anywhere and a bunch of more advanced things that will just confused someone starting out. 

My method so far has been a mixture of:

a) Taking apart the example to see which components are used
b) Recreating the same thing in a new scene to see what the minimum required configuration is
c) Reading the docs when I get stuck.

As you can see - reading the docs comes last in this list! So - how could the docs be more useful? 

This ticket is one addition that would help. It would make it much easier to understand how to use each component.

The other thing that would be a huge improvement to the current state of the docs is the addition of something along the lines of RECIPES.md

I envisage this as a fairly short, succinct step by step instructions for common functionality. The more basic ones would come first (with the general gist of 'getting started' being the very first recipe).

Later recipes would refer to earlier ones. e.g.:

Recipe 12: Picking up an object with a controller
------------------------------------------------

1. See recipe 1: basic camera setup
2. See recipe 2: basic tracked controller setup
3. Create an object and follow recipe 3: basic interactable object
4. blah blah blah.
5. blah.
6. profit... ;-)

(I realise this comment has got very little to do with the title of this issue now. Apologies - I'll start a new issue if anyone thinks this is worth pursuing)

**Comment by thestonefox** [comment]
Gonna close this and roll the discussion into this new issue: 

https://github.com/thestonefox/VRTK/issues/1422
