### ISSUE TITLE
SnapDropZone - highlightAlwaysActive has issue turning off

### ISSUE THREAD

**Issue by rgjones33** [thestonefox/VRTK#1421]
### Environment

 * Source of VRTK (Unity Asset Store or Github) github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash) 3.2.1 (i think)
 * Version of Unity3D (e.g. Unity 5.4.4f1) 5.6.2f3
 * Hardware used (e.g. Vive/Oculus) Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities) SteamVR(OpenVR)

### Steps to reproduce

Start the example  041_Controller_ObjectSnappingToDropZones. Toggle highlightAlwaysActive on any SnapDropZone component and it will turn on. Uncheck it and it will not turn off.

### Expected behavior

Toggle highlightAlwaysActive on any SnapDropZone component and it will turn on. Uncheck it and it should turn off.

### Current behavior

Toggle highlightAlwaysActive on any SnapDropZone component and it will turn on. Uncheck it and it will not turn off.

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1426
