### ISSUE TITLE
Controller Tooltips do not work with Pointer (when enabling "interact with objects") 

### ISSUE THREAD

**Issue by yalongyang** [thestonefox/VRTK#1424]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Unity Asset Store
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.2.1
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.1
 * Hardware used (e.g. Vive/Oculus)
Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR

### Steps to reproduce

1. Open example scene, 029_Controller_Tooltips
2. Add VRTK_Pointer and VRTK_StraightPointerRenderer to a controller script alias
3. In VRTK_Pointer, check the "Active on Enable" and "Interact With Objects"
4. Run the example

### Expected behavior

Controller tooltips will shown, and the pointer will work properly.

### Current behavior

Pointer works properly, controller tooltips are not shown.

**Comment by thestonefox** [comment]
Just tried it in github master, works for me.

I recommend trying it on github master
