### ISSUE TITLE
VRTK_Pointer's Interact with objects turns Radial Menu Invisible.

### ISSUE THREAD

**Issue by Leo11504** [thestonefox/VRTK#1437]
### Environment

 * Source of VRTK: Unity Asset Store
 * Version of VRTK: Unity Asset Store 3.2.0
 * Version of Unity3D Unity 2017.1.0f3
 * Hardware used: Vive & Oculus
 * SDK used: (e.g. OpenVR/SteamVR/Oculus Utilities)

### Steps to reproduce

Using Example scene 030_Controls_RadialTouchpadMenu's radial menu system and applying it to 019_Controller_InteractingWithPointer's controller scrips Toggle on the VRTK_Pointer script's Interact with Objects script. The menu will initially be visible but as soon as you trigger the pointer it no longer shows.

### Expected behavior

When Interacting with object (for highlight or pointer grabbing) radial menu on same controller should be visible.

### Current behavior

When VRTK_Pointer is set to Interact with Objects a Radial Menu tied to the same controller no longer becomes visible. It still functions but does not show.

**Comment by thestonefox** [comment]
I can't recreate. Maybe would be better if you provided a step by step guide of how to recreate the issue in the example scene.

**Comment by Leo11504** [comment]
Alright, I went in on a fresh installation of everything and am still getting the issue.

Open example scene 030_ControlsRadialTouchpadMenu. 

Under [VRTK_Scripts] Copy the Left Controller's Child RadialMenu GameObject with it's child RadialMenuUI and Panel components.

Open example scene 019_Controller_InteractingWithPointer

Paste the RadialMenu GameObject Under the Left and Right Controllers (setting it up as it was on the 030 scene.

On the Left Controller GameObject in the VRTK_Pointer (Script) go down to PointerInteractionSettings and enable Interact with Object (leave the Right Controller alone).

Press Play to start up VR and activate the radial menu by touching the touchpad/joystick, notice the menu on both controllers. Press and activate the Pointer Objects on both Controllers (set to touchpad click which will teleport by default) Go back and activate the radial menu on each controller. The Left Controller's radial menu should not be visible while the Right Controller's radial menu should be.

The radial menu is still technically there, applying a function to a button will still work on activate but it's not visible.

**Comment by thestonefox** [comment]
Have you tried adding in the radial menu from the prefab and not copying objects from one example scene into the other?

**Comment by Leo11504** [comment]
Yes, same issue. Also it occurs if I make each component of the prefab individually.

**Comment by thestonefox** [comment]
I can't follow your steps to reproduce.

I'm starting the scene.

I don't see the radial menu on either controller.

 * I touch the left touchpad, the radial menu appears
 * I touch the right touchpad, the radial menu appears
 * I press the left touchpad, the radial menu stays visible, the pointer is visible
 * I press the right touchpad, the radial menu stays visible, the pointer is visible
 * I release the left touchpad from press (but still touching) the pointer is not visible but the radial menu is visible
 * I release the right touchpad from press (but still touching) the pointer is not visible but the radial menu is visible
 * I stop touching the left touchpad, the radial menu disappears
 * I stop touching the right touchpad, the radial menu disappears
 * I touch the left touchpad, the radial menu appears
 * I touch the right touchpad, the radial menu appears

(repeat over and over, still same result)

That all seems correct to me.

**Comment by thestonefox** [comment]
I'd also recommend trying on github master, your version of the unity asset store is old.

**Comment by Leo11504** [comment]
I'll try the github master and report back.

**Comment by Leo11504** [comment]
Tried with the Unity store on a fresh installation and still had the same issue. Just grabbed the Master branch and it works as expected. Not sure what changed but thanks again.

**Comment by BJNguyen** [comment]
Hi,
Love what your doing with VRTK ! What a great job and helpful for beginners (I am !).
I've got the same issue unfortunately...
1/ Creating a brand new project, importing SteamVR and VRTK.
2/ Creating a GameObjects for SDKManager, SDK Setup and Controllers.
3/ Adding on R Controller (for example) :
- Pointer
- Bezier Pointer Renderer
- Pointer
- StraightRenderer
- Controller Events
4/ Using prefabs to add Radial Menu.
5/ Hovering to show the Radial Menu and pressing trigger to have the "laser beam" make the Radial dissapearing :(

    Source of VRTK: Unity Asset Store
    Version of Unity3D Unity 2017.3.0p1
    Hardware used: Vive
    SDK used: (SteamVR)

Regards

**Comment by bddckr** [comment]
@BJNguyen Only VRTK 3.3.0 supports Unity 2017 and later. Use 3.3.0.

Additionally issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. GitHub issues are only useful for proper bug reports with steps to reproduce in an example scene like the Issue Template requires.

**Comment by BJNguyen** [comment]
Oki doki, I'm very new to all of this, all my apologies.
Thank you for the informations
