### ISSUE TITLE
Haptics aren't working with Oculus SDK

### ISSUE THREAD

**Issue by russellweed** [thestonefox/VRTK#1447]
> **NOTE:** Any issue that does not follow the below template will be immediately closed and not re-opened until the template structure is adhered to.

### Environment

 * Unity Asset Store & GitHub
 * 3.2.1 / f4cd485
 * Unity Version 5.6.1f1 (64-bit)
 * Oculus Rift + Touch Controllers
 * Oculus SDK 1.15.0

### Steps to reproduce

1. Create a new project
2. Import SteamVR SDK
3. Import Oculus SDK
4. Import VRTK (either from Github-master #f4cd485 OR Asset Store 3.2.1)
5. Load example scene 016

Haptics will not work for the Touch controller as expected. Upon switching to the SteamVR SDK, haptics work as intended.

### Expected behavior

Expect the controllers to vibrate when hitting the boxes in example scene 016.

### Current behavior

No vibration in the controller motors when using Oculus SDK.

**Comment by thestonefox** [comment]
What version of the oculus SDK are you using? Also try increasing the vibration intensity.

**Comment by russellweed** [comment]
Oculus Utilities for Unity 5 1.15.0 (latest stable version at the time of this writing)

Reproduction scenario here was with the example scene that comes w/ VRTK w/o any changes. In my own code I've also tried ramping up the intensity/duration and it still has no effect.

**Comment by thestonefox** [comment]
The issue isn't with the Oculus SDK for VRTK, it's to do with the example scene code.

in `Sword.cs` on line 42

`VRTK_ControllerHaptics.TriggerHapticPulse(controllerReference, hapticStrength, 0.5f, 0.01f);`

just change the `hapticStrength` parameter to `1f` and it will work.

The issue is how the example code normalises the velocity based on the vive values.

**Comment by russellweed** [comment]
Please close this ticket.

It turns out my Oculus SDK was completely corrupted and I had to completely nuke it from Unity. Re-imported the version from the web and not the asset store, and now everything works as it should.

My apologies.
