### ISSUE TITLE
Hinge Rotation limited to 360 degrees

### ISSUE THREAD

**Issue by TomaszFoster** [thestonefox/VRTK#1452]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
 * Version of VRTK: 3.2.1   (d227047f815dcd87d840eb993ce8b80c89ba10b8)
 * Unity 2017.1p2
 * Hardware used: HTC Vive
 * SDK used: SteamVR

### Steps to reproduce

1. Open VRTK example scene `025_Controls_Overview`
2. Select any wheel and ensure `lock rotation` is enabled
3. Specify `0` to `359` as the range

### Expected behavior

The limitation is it's only lockable to 0 - 360 degrees at the moment, but it would be nice to have an enhancement to allow higher numbers, as well as specify a start point.

### Current behavior

Hinge rotations, when lock is enabled, are limited to 360 degrees. When set to 360 degrees, it starts in the middle and allows rotation to the left and to the right 180 degrees respectively. This amounts to 360 degrees of range of motion but it would be nice to have it start at 0, not halfway.

**Comment by thestonefox** [comment]
Artificial rotator has no hinge limitations.

Physics rotator still does, but you can create most of what you need with the artificial one
