### ISSUE TITLE
Unable to invoke SecondaryGrab action when AllowedController is limited to one or the other controller

### ISSUE THREAD

**Issue by rgjones33** [thestonefox/VRTK#1453]
* Source of VRTK (Unity Asset Store or Github) Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash) 3.2.1
 * Version of Unity3D (e.g. Unity 5.4.4f1) 5.6.2f1
 * Hardware used (e.g. Vive/Oculus) Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities) OpenVR

### Steps to reproduce

In example 43 set the AllowedGrabControllers to  Left Only or Right Only in the VRTK_InteractableObject component for the SphereScale gameobject.

Press play and attempt to scale the sphere.

### Expected behavior

The sphere should scale. There are cases where you want to limit the primary grabbing controller to left or right but still want to invoke secondary grab actions. 

### Current behavior
In this particular example the sphere loses the grab but with other objects (isKinematic) the secondary Grab mechanic is just ignored

**Comment by thestonefox** [comment]
The Allowed Grab should either be the initial grab (i.e. primary grab)

Or should contain additional settings like:

 * Both (both controllers can do a primary grab and a secondary grab)
 * Right primary only (only right contorller grab grab, left can still perform secondary action)
 * Left primary only (only left can grab, right can still perform secondary action)
 * Right Only (right can only grab, left cannot perform secondary action)
 * Left Only  (left can only grab, left cannot perform secondary action)

I think option one is more appropriate at the moment for a fix. The `Allowed Grab Controller` shouldn't affect the secondary grab. If there is a need to prevent a secondary grabbing controller then option 2 can be implemented in the future.

**Comment by rgjones33** [comment]
I agree. My work around was to remove the check for IsValidInteractableController in InitSecondaryGrab.

**Comment by bddckr** [comment]
Maybe _two_ settings, one for the allowed primary grab, one for the secondary action? I guess that would result in some configurations that aren't possible right now?

**Comment by thestonefox** [comment]
@bddckr Yeah two drop downs or one drop down with more settings.

But either way I think we defer that till someone says they actually want it.

What's the point of being able to grab with the left controller but never be able to secondary grab with the right controller?

**Comment by thestonefox** [comment]
PR With fix https://github.com/thestonefox/VRTK/pull/1455
