### ISSUE TITLE
disabled VRTK_UI Canvas script gives error at scene change

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1459]
### Environment
3.3.0 alpha

### Steps to reproduce
Create a new ui canvas with a disabled VRTK_UI Canvas script on it and then change scene during runtime. An error will occur. 

### Expected behavior
Nothing should really happen, scene should just change without errors.

### Current behavior
Scene changes fine but an error pops up in the console:
NullReferenceException: (null)
UnityEngine.MonoBehaviour.StopCoroutine (UnityEngine.Coroutine routine) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/MonoBehaviourBindings.gen.cs:99)
VRTK.VRTK_UICanvas.RemoveCanvas () (at Assets/VRTK/Scripts/UI/VRTK_UICanvas.cs:199)

The solution is simple, just add an if check before the StopCoroutine on row 199 like:
if(draggablePanelCreation != null)
  StopCoroutine(draggablePanelCreation);

**Comment by thestonefox** [comment]
PR containing fix https://github.com/thestonefox/VRTK/pull/1461
