### ISSUE TITLE
New VRTK Structure Proposal

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1460]
For v 4.0.0 I recommend the following structure for the repo:

```
-RepoRoot/
---Documentation/
-----Getting Started/
-------sub content....
-----Tutorials/
-------sub content....
-----Source API/
-------sub content....
-----FAQ.md
---Demo Scenes/
-----sub content....
---Prefabs/
-----AvatarHands/
-------sub content....
-----CameraRigs/
-------sub content....
-----Resources/
-------sub content....
-----ConsoleViewerCanvas.prefab
-----etc.prefab
---Resources/
-----Materials/
-------sub content....
-----Textures/
-------sub content....
---Source/
-----Editor/
-------sub content....
-----Scripts/
-------sub content....
-----SDK/
-------sub content....
```

This would also mean that there is no unity project within the repo.

**Comment by thestonefox** [comment]
Reference: 
https://github.com/thestonefox/VRTK/issues/1422
https://github.com/thestonefox/VRTK/issues/763

**Comment by bddckr** [comment]
For the source API docs make sure to not include HTML files - I think Unity tries to import those for some reason and fails. At least that's what's happening with [Entitas](https://github.com/sschmid/Entitas-CSharp).

**Comment by thestonefox** [comment]
I don't think we should go with `Doxygen` as the doc generator anyway. I don't like html, I don't like the mess of files they create, I think their generated docs are very complete but too confusing.
