### ISSUE TITLE
HapticPulse strength has a different intensity curve on Oculus SDK vs OpenVR

### ISSUE THREAD

**Issue by Peaj** [thestonefox/VRTK#1464]
### Environment

 * Source: Github
 * Version of VRTK: 3.2.1
 * Version of Unity3D: 2017.1.0.f3
 * Hardware used: Oculus
 * SDK used: OpenVR & Oculus SDK

### Steps to reproduce
Use VRTK_SDK_Bridge.HapticPulse with a low strength like 0.2 with OpenVR. Switch to Oculus SDK and compare the physical strength of the haptic Feedback.

### Expected behavior
For the same strength value the haptic feedack intensity should feel the same on both sdks.

### Current behavior
The Oculus SDK feels a lot less intense for lower strength values. However for the max value of 1 it has the same intensity.

### Possible fix
I did a workaround by using Mathf.Sqrt to intensify the low values and decrease the higher values.
For my quick Tests it worked out pretty well and makes the Oculus SDK strength feel a lot more like the OpenVR one.
It may not be exact however. One would have to either measure the physical intensity or take a look at the OpenVR code how they map their values to the rift touch controlers the get the proper curve.

**Comment by thestonefox** [comment]
They use different haptic methods and different motor setups.

It's probably not too realistic to expect the same value to yield the same result.

You even notice this on Oculus Touch between Oculus SDK and SteamVR with Oculus.

**Comment by Peaj** [comment]
"You even notice this on Oculus Touch between Oculus SDK and SteamVR with Oculus."

Thats exactly the problem I have. Maybe I did not describe it well enough.
My Problem is not different intensities on different controlers but different intensities on the same (touch) controler with different SDKs.

I started to design the haptic feedback on SteamVR, but after switching to Oculus SDK its so weak you cant even feel it in some situations.

While developing a "multistore" game it is essential to get the same feeling on each SDK. So I could check for the active SDK and implement different haptics for each SDK but I think thats exactly what the abstraction layer (VRTK) is good for.

Thanks for this awesome framework btw! For 99% of the code the SDK switch did just work and thats great. The haptic feedback was the only real problem I encountered

**Comment by thestonefox** [comment]
The haptics on SteamVR for Oculus are a hack by valve in OpenVR. I recommend you raise a bug with the OpenVR github project as it's really their problem to fix.

If we put any fixes in VRTK and then they do fix OpenVR then that just breaks VRTK again (because it would then be too strong).

**Comment by Peaj** [comment]
Ok I see. I'll take a look how they handle it. Thanks for your replies
