### ISSUE TITLE
Ensure enums are named correctly

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#1466]
There are a number of cases where enums have plural names.

Plural names in enums should only be the case when multiple enums can be selected

so

```
enum MyNums {
First = 1,
Second = 2,
Third = 3
}
```

is correct

and

```
enum MyNum {
First,
Second,
Third
}
```

is also correct.

**Comment by thestonefox** [comment]
This is going to cause some pretty nasty breaking changes so defer it to `4.0.0` at least

**Comment by bddckr** [comment]
Note: If we have any bitfield-y enums those should use plural as the enum name, have a `None = 0` (or more fitting name) case and need the `[Flags]` attribute annotation :)
