### ISSUE TITLE
Platform (Store) dependent compilation

### ISSUE THREAD

**Issue by Peaj** [thestonefox/VRTK#1474]
As the Oculus store does refuse to accept the openvr.dll and Steam seems to depend on openvr to have proper achievement display etc.:

Is it already possible or planned to **set the VR SDK at compiletime**?

Atm it would be possible to manually adjust the sdk list before building. However this is only a workaround. It would be great to set the SDK e.g. via precompiler defines so it could work with autobuild and create a Steam build with openVR api only and an Oculus build with Oculus VR api only.

This would be really usefull for publishing to multiple storefronts.

**Comment by bddckr** [comment]
You can just remove the OpenVR dlls for Oculus Home builds: The same built will run just fine and never switch to the SteamVR SDK Setup. If you follow the example scenes' SDK Setup order on the SDK Manager it will then load and use the Oculus SDK Setup only.

For other API usage we don't have anything in place and there are no plans to do so AFAIK.

The whole SDK Manager and SDK Setups are usable at runtime so I suggest writing a little script that sets the SDK Manager's `setups` based on your own defines and then does `.enabled = true` on the SDK Manager. This should handle your use case fine 😄

**Comment by bddckr** [comment]
Oh another (better) thought: For autobuilding I suggest defining the VR SDK defines we already have in place yourself, manually. That way is probably the saner one and is easier to work with. If a define symbol isn't present the SDK Setup won't be used.

You can find them in the `SDK*_Defines` files.

**Comment by Peaj** [comment]
Thanks thats great. Just what I was looking for. I'll try it out asap

**Comment by bddckr** [comment]
Make sure to disable `VRTK_SDKManager.autoManageScriptDefines` if it becomes a problem in the autobuild pipeline.
