### ISSUE TITLE
Small Pointer Activation Issue? Proposed small fix.

### ISSUE THREAD

**Issue by devinkelly** [thestonefox/VRTK#1477]
In VRTK_Pointer.cs, line 386 in the function CanActivateOnToggleButton(). Should that perhaps also take into account state being set to false, so as to trigger deactivation regardless? So it reads like the following:

```
   // Basically just add a "|| !state" to the line like below
   if (result || !state))
   {
      willDeactivate = true;
   }

**Comment by thestonefox** [comment]
Could you provide steps to reproduce the issue where your fix would apply?

**Comment by devinkelly** [comment]
Yeah sorry, should have followed the template. Was secretly hoping you'd just be like "Oh yeah, sure." =]

Anyway, I encountered an issue when implementing a VRTK UI pointer that only allowed for one hand to have an active pointer at a time.  I was using the pointer class's Toggle function to essentially do the switching whenever the user pulled the trigger on the relevant handle. So for example, if the right trigger was pressed, I would call rightHandPointer.Toggle(true) and leftHandPointer.Toggle(false) and hopefully see the right pointer go on, and the left pointer go off.

In the example above I was encountering an issue where the left pointer would not go off, and both left and right pointers were active. I traced it down to CanActivateOnToggleButton() where it seems when I pass in state = false, that is, I want to turn OFF the pointer, it will skip over the block at line 386, which sets the willDeactivate flag, which then gets processed at the bottom of the Toggle function. So without willDeactivate getting called, the pointer remains active.

**Comment by thestonefox** [comment]
so steps to reproduce in an example scene then?

**Comment by devinkelly** [comment]
## Steps to reproduce:
1. Open 019_COntroller_InteractingWithPointer example scene.
2. Select the [VRTK_Scripts]->LeftController.
3. On VRTK_Pointer script, set Activation Button to Undefined. 
4. On VRTK_Pointer script, uncheck Hold Button To Activate. 
5. Repeat steps 2-4 with [VRTK_Scripts]->RightController.
6. Create an empty gameobject at root level, and attach the script below.
7. Play the scene, and press trigger on left controller, notice right pointer still active.
8. Alternative between left hand and right hand triggers, notice pointer activation inconsistent.

Test Script:
```
using UnityEngine;
using VRTK;

public class PointerToggleTest : MonoBehaviour
{
   public Util.Handedness laserHand;
   VRTK_ControllerEvents leftHand;
   VRTK_ControllerEvents rightHand;

   public void Start()
   {
      //InitVRTK();
      Invoke("InitVRTK", 0.2f); // needs to wait a frame
   }

   public void InitVRTK()
   {
      // Grab left hand and right hand devices
      leftHand = VRTK_DeviceFinder.GetControllerLeftHand().GetComponent<VRTK_ControllerEvents>();
      rightHand = VRTK_DeviceFinder.GetControllerRightHand().GetComponent<VRTK_ControllerEvents>();
      // Initialize Trigger callback
      InitVRTKHandlers(leftHand);
      InitVRTKHandlers(rightHand);
      // Initialize pointer hand
      SetVRUILasersEnabled(true);
   }

   public void InitVRTKHandlers(VRTK_ControllerEvents conEvents)
   {
      // Clear previous
      conEvents.TriggerPressed -= OnTriggerPress;
      conEvents.TriggerPressed += new ControllerInteractionEventHandler(OnTriggerPress);
   }

   public void SetVRUILasersEnabled(bool laserOn)
   {
      Debug.Log("SetVRUILasersEnabled> laserOn=" + laserOn + " laserHand=" + laserHand);
      leftHand.GetComponent<VRTK_Pointer>().Toggle(laserOn && laserHand == Util.Handedness.LEFT);
      rightHand.GetComponent<VRTK_Pointer>().Toggle(laserOn && laserHand == Util.Handedness.RIGHT);
   }

   // Switch pointer hand on trigger press
   private void OnTriggerPress(object sender, ControllerInteractionEventArgs e)
   {      
      if (laserHand == Util.Handedness.LEFT && e.controllerReference.hand == SDK_BaseController.ControllerHand.Right)
      {
         // If pointer is on left hand, and right trigger is pressed
         laserHand = Util.Handedness.RIGHT;
         SetVRUILasersEnabled(true);
      }
      else if (laserHand == Util.Handedness.RIGHT && e.controllerReference.hand == SDK_BaseController.ControllerHand.Left)
      {
         // If pointer is on right hand, and left trigger is pressed
         laserHand = Util.Handedness.LEFT;
         SetVRUILasersEnabled(true);
      }
   }
}
```

**Comment by thestonefox** [comment]
the proposed fix causes additional issues so cannot be used.

**Comment by thestonefox** [comment]
I think your issue is you're manually toggling the pointer with `Toggle` you just need to have the `Hold Button To Activate` option ticked and then your manual toggle will just work.

**Comment by devinkelly** [comment]
The desired behavior was to have a single press of the trigger cause activation of a pointer without having to hold any buttons. That is, without any buttons pressed, one (and only one) pointer is active (either left or right) at any given time. I'm not sure the above suggestion achieves that, does it? Perhaps I'm misunderstanding?

**Comment by thestonefox** [comment]
yes, because you're manually toggling then the button being held won't be needed.

the `Toggle` forces the pointer on regardless of button press. So just leave that `Hold Button To Activate` checked and it should do what you want with the script you provided.

**Comment by devinkelly** [comment]
Understood. And you are correct. Just tested to confirm.

Thank you for your diligence with this, very appreciated! And thank you for VRTK, it's really well done.

Feel free to close this issue at your discretion.
