### ISSUE TITLE
Unchecked NullReferenceException in VRTK_InteractTouch.ControllerColliders()

### ISSUE THREAD

**Issue by ThaRedstoner** [thestonefox/VRTK#1478]
# Problem
Permalink to code in question:
https://github.com/thestonefox/VRTK/blob/d4e29330c06370cbc02c43a95a097070302046b0/Assets/VRTK/Scripts/Interactions/VRTK_InteractTouch.cs#L247

If `controllerCollisionDetector` is null, this piece of code will always cause a NullReferenceException.
The cause is the condition and the second statement in the conditional operator:

`controllerCollisionDetector != null && controllerCollisionDetector.GetComponents<Collider>().Length > 0`

If that statement is falsified because `controllerCollisionDetector` is null, the second statement is returned:

`controllerCollisionDetector.GetComponentsInChildren<Collider>()`

Which assumes `controllerCollisionDetector` is not null, resulting in a NullReferenceException.

# Resolution
Either a (public) way needs to be provided to verify if `controllerCollisionDetector` is null before attempting to call the method, or an empty Collider[] / null needs to be returned from the method if it is null.

Preferably the former, otherwise there is no way to know if the value has been assigned.

**Comment by thestonefox** [comment]
Steps to reproduce the problem in an example scene please.

**Comment by ThaRedstoner** [comment]
## Steps to reproduce
1. Open example 034 (Interacting with Unity UI)
2. Select [VRTK_Scripts]/RightController
3. Add a new script with this content:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using VRTK;

public class ControllerColliders : MonoBehaviour
{
    private void Awake()
    {
         VRTK_InteractTouch touch = GetComponent<VRTK_InteractTouch>();
         touch.ControllerColliders();
    }
}

```
4. Run the scene and see the NullReferenceException in the console.

**Comment by thestonefox** [comment]
Although it's probably still worth preventing the null exception, as it's still not the desired result.

**Comment by ThaRedstoner** [comment]
Yes, my thought exactly, otherwise the already present null-check would not be necessary either since it would always result in an error in the case it is false.

**Comment by thestonefox** [comment]
PR with fix  https://github.com/thestonefox/VRTK/pull/1480
