### ISSUE TITLE
Can't use two UI pointers

### ISSUE THREAD

**Issue by SmartCarrion** [thestonefox/VRTK#1489]
### Environment

 * Github v. 949cb737
 * Unity 2017.1.1
 * Oculus (probably vive too)
 * Oculus SDK

### Steps to reproduce

In scene 34 (UI scene), copy right hand to left hand so both have UI pointers.
Play scene and try to interact using both hands.  

### Expected behavior

Any connected hand should be able to interact with UI.

### Current behavior

Only one will work, other throws event handler errors

**Comment by thestonefox** [comment]
I've had 4 independent tests all say this works for them.

I'm assuming there is something wrong with your setup

**Comment by SmartCarrion** [comment]
I'm still hunting it down, this is the error i get: 

NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_VRInputModule.Scroll (VRTK.VRTK_UIPointer pointer, System.Collections.Generic.List`1 results) (at Assets/VRTK/Scripts/Internal/VRTK_VRInputModule.cs:315)
VRTK.VRTK_VRInputModule.Process () (at Assets/VRTK/Scripts/Internal/VRTK_VRInputModule.cs:40)
VRTK.VRTK_EventSystem.Update () (at Assets/VRTK/Scripts/Internal/VRTK_EventSystem.cs:50)

I have done a fresh update of VRTK to the master branch on git.  currently building a fresh project to test outside of my normal project.  the only thing that should really be different is the physics layers which i can't see producing this error above, but i'm going to test anyway!

**Comment by bddckr** [comment]
Can you check what actually is `null` on that line? I assume `.controller` is: That one is `null` because no `VRTK_ControllerEvents` is on the game object the `VRTK_UIPointer` is on.

**Comment by SmartCarrion** [comment]
That error goes away and it works if I remove the UI pointer from the Head object.  Now to figure out why it wasn't working in my project which doesn't have that issue...
