### ISSUE TITLE
VRTK_AvatarHandController ignores "Index Button" setting

### ISSUE THREAD

**Issue by RoryHarvey** [thestonefox/VRTK#1495]
### Environment

 * Source of VRTK: GitHub
 * Version of VRTK:  3.3.0-alpha
 * Version of Unity3D: 2017.1.0p4
 * Hardware used: Oculus
 * SDK used: Oculus

### Steps to reproduce

1) Open 032_Controller_CustomControllerModel
2) Set VRTK_BasicHand "Index Button" functionality to "Undefined" under Digital Finder Settings
3) Run

### Expected behavior

Index behaviour should not happen on controller input

### Current behavior

Index behaviour always happens and defaults to trigger press on controller.

![image](https://user-images.githubusercontent.com/1025639/30325735-beb8c32c-97bd-11e7-92c9-9edfd66f1dfb.png)

**Comment by thestonefox** [comment]
What does that get set to at runtime though?

Can you take a screenshot of your controller script at runtime

**Comment by RoryHarvey** [comment]
Here you go

![image](https://user-images.githubusercontent.com/1025639/30332252-c82b3296-97d1-11e7-9ab8-4a513b5bc858.png)

**Comment by thestonefox** [comment]
Do you not see from your screenshot what's going on?

When you start the game, the controller is being recognised Oculus Touch which sets the index to use the axis setting so it doesn't matter what the digital setting is at.
