### ISSUE TITLE
Play Area Cursor should rotate with Direction Pointer Indicator

### ISSUE THREAD

**Issue by ZippyStardust** [thestonefox/VRTK#1499]
### Environment
 * VRTK 3.2 from the asset store
 * Unity 2017.1
 * Vive / Steam VR

### Steps to reproduce
Add a Play Area Cursor and a Pointer Direction Indicator to a Pointer Renderer. Try rotating the pointer. The play area remains in the same orientation. 

### Expected behavior
The Play Area Cursor should rotate with the Pointer Direction Indicator. It should rotate around the pointer cursor. 

### Current behavior
The Play Area Cursor does not rotate with the Pointer Direction Indicator .  This gives an incorrect representation of where the play area will be after the teleport.  As a result The valid/invalid collision checks are often wrong as well - allowing the user to teleport to a place where the play area has a wall in it. 

I am also seeing drifting of the Pointer Cursor within the play area cursor, with each teleport. Although this may be a separate issue

Thanks!

**Comment by thestonefox** [comment]
PR with proposed fix: https://github.com/thestonefox/VRTK/pull/1500
