### ISSUE TITLE
Request: extending simulator input

### ISSUE THREAD

**Issue by RanaInside** [thestonefox/VRTK#1504]
A way to allow us enter custom input (ie. xbox controller) to simulate vr controller events, especially trigger axis, touchpad axis touch and so on.

After digging though the code, it seems like
1) I have to uncomment "SDK_Description" from "SDK_SimController"
2) Create a new class which inherits from "SDK_SimController" - let's call it "SDK_Sim360Controller"
3) Add "SDK_Description" to this class.
4) Finally override the methods I want for control detection.

One clean way to achieve it would be to extend attribute "SDK_Description" with something like Priority; then during initializing, if more that one implementation is found, use the one with highest priority.

With that setup, I don't have to edit any existing vrtk files.

Thanks
Rana

**Comment by bddckr** [comment]
I assume you just copied the existing SDK_Description. That won't work of course, you'll need to create _your own_ description.
Just define your own SDK_Description, don't touch the existing ones. Have a look at the SDK*System classes, all the other descriptions just refer to that one in their constructor. The system description has all the details. You can just use the other constructor of SDK_Description.

**Comment by thestonefox** [comment]
Wouldn't it be better to just write an Xbox controller SDK?

**Comment by RanaInside** [comment]
@thestonefox 
Actually xbox was an example - developer may have a ps3 controller or even a flight stick :) as this is for development+test only, I was thinking of using getInput method. My initial idea was perhaps I can send a message to vrtk to raise that event, but with current codebase, that would be too messy.

@bddckr 
That sounds like wrong way of going about it; SDK_Description is an attribute - so it just tells the main manager what to initialize. So I am unsure what you mean in your suggestion.

Use case: I can test my application on windows and linux with VIVE, but not on my mac. To test it, I just want to go through some of the actions and ensure all the shaders and assets are working as intended. The issue is, my application relies completely on trigger axis and touchpad axis - so in simulator, I can't do anything.

I guess those are the only two things missing in simulator.

**Comment by thestonefox** [comment]
As I said just use the unity controller sdk and map the controller axis accordingly

**Comment by RanaInside** [comment]
Hi @thestonefox I'm not sure that I'm understanding you; are you suggesting change the git file to map it? I was actually looking for a way that would not update any existing vrtk files.

**Comment by RanaInside** [comment]
I'm an idoit :) I can just create a class extending SDK_BaseController, and set that as controller in detailed selection for simulator sdk setup. I think that should work.

**Comment by bddckr** [comment]
Yes, but as my initial comment suggested you'll have to give it your own SDK_Description. Of course you can't reuse the existing description, how would you select one vs. the other otherwise?

---

I still agree on @thestonefox's recommendation: It's way easier to just set your SDK Setup's controller SDK to use the Unity controller SDK and then route whatever input you have to be available for Unity's input system which will then be picked up by the Unity controller SDK automatically.
