### ISSUE TITLE
VRTK_Drawer - Autodetect and linear limits not working properly

### ISSUE THREAD

**Issue by kristianpd** [thestonefox/VRTK#1511]
### Environment

 * Not related to any environment, tested on `3.3.0-alpha` but I believe it's unrelated to alpha branch.

### Expected behavior
 
The drawer should allow for auto detecting the correct axis of the drawer as well as allowing you to specify it. 

### Current behavior

Adding a `VRTK_Drawer` to a new example scene does not exhibit expected behaviour.  It is also broken in scene `025_ControlsOverview`. Autodetect appears to detect the correct dimension, but I believe the problem is that it sets both the Axis and the the `Limited` motion axis to the same direction.

The `ConfigurableJoint` can have its `Axis` set. This results in a new local `X/Y` axis that the joint then uses for its various configurable values. I believe the problem here is that the code both sets the joint to be the detected direction (OK) but then also uses that same world space direction as the limited motion axis (not OK). 

In this first picture, you'll see that the autodetect does pick the correct dimension, and point it down `Vector3.forward`, or the world space Z axis. 

![pasted image at 2017_09_19 11_26 am](https://user-images.githubusercontent.com/378038/30601069-02944bcc-9d2f-11e7-93bd-9ca54ec66b30.png)

This *should* now mean that `X` in the joint values is `Z` in the world values, but the code locks the `X` motion of the joint and unlocks the `Z` motion. 

This results in the drawer moving along the world space `X` axis shown in this picture.
![pasted image at 2017_09_19 11_12 am](https://user-images.githubusercontent.com/378038/30601070-0294924e-9d2f-11e7-87aa-c2a5d8e954a1.png)

I believe the problem lies here: 

https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/Controls/3D/VRTK_Drawer.cs#L148

I think the correct behaviour here would be to set the X axis of the `ConfigurableJoint` to be `Vector3.forward` but then unlock `X` dimension motion as opposed to `Z`.

I'm not sure if this has ever really worked properly, but I can try to come back around to another look at this once I'm done with my PR.

**Comment by kristianpd** [comment]
VRTK_Drawer seems pretty broken atm, i'll try to get back around to this in a bit.

**Comment by thestonefox** [comment]
Fixed
