### ISSUE TITLE
Proposal: ReturnHome drop type

### ISSUE THREAD

**Issue by iraytrace** [thestonefox/VRTK#1514]
### Overview
For our CAD application we want users to be able to pick up parts, hand them around, carry them places and when they are dropped have them snap back into their original place.  This seems to be different from drop zones which would require the user to return an object to drop it (finding where that screw came from can be awkward).  In addition, setting up drop zones for a multitude of objects is tedious.

### Code in Progress

I have added the following to VRTK_InteractableObject.cs:

* added ReturnHome to  ValidDropType
* private variables snapPosition, snapRotation, grabInProgress
* in Grabbed():   A check is done to see if the object was previously grabbed, and a save of current position/rotation if not.  Set/clear grabInProgress on entry/exit of method to guard against restoring during ungrab which occurs during grab.
* in Ungrabbed(), if a grab is not in progress (which is the case when transferring object between hands) then restore position/rotation.

As a result, objects with this DropType selected can be grabbed, carried and they teleport "home" when dropped.

**Comment by bddckr** [comment]
Can't this all be done as a pure extension to the current VRTK code?

The Drop Zones emit events to notify AFAIK and by listening to those, then checking the grabbed object for an existence of a new `ReturnableToHome` component gives enough information at the start.
The actual "home values" would be then saved on that new component to be retrievable later in the ungrab.

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522
