### ISSUE TITLE
Proposal: Add primary/secondary hand as payload to grab events

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1516]
I think it would be nice to get info about what type of grab/ungrab was performed with the events, like primary or secondary. It would make a much more clean solution than having to check for GetGrabbingObject and GetSecondaryGrabbingObject.

**Comment by thestonefox** [comment]
you have to write a line of code either way, where is the saving?

**Comment by virror** [comment]
I just think it makes for a lot neater and more logical code.

**Comment by thestonefox** [comment]
but it ends up being

`if (e,isSecondHandGrabbing)` to `if (e.object.GetSecondaryGrabbingObject())`

But to do the first a chunk of extra code has to be added for the removal of `.object.`

**Comment by virror** [comment]
Was just an idea, no one has to like it : p

**Comment by thestonefox** [comment]
I'm not saying i'm right, i'm just giving my opinion ;)

Other's may tell me i'm stupid and then it becomes a candidate.

remember it's not up to me, its up to all of us! :D
