### ISSUE TITLE
SnapDropZone highlighter falls to floor if object with joints are used as highlighter object

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1517]
### Environment
VRTK 3.3.0 alpha
Unity 5.6.3

### Steps to reproduce
 * Create an interactible object that has some kind of joint setup
 * Assign that as the highlighter object for a snap drop zone.
 * Since it has joints, it will fail at removing the RigidBody because the Joint depends on it.
 * This will result in a Highlighter object with a RigidBody on it that will fall to the floor when playing the game.

One solution would be to first make sure to get rid of all the joints before getting rid of the Components.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/pull/1518
