### ISSUE TITLE
VRTK_TouchpadControl does not re-enable

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#1521]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
alpha 3.3 and current master branch
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.1 but was also present in 5.6
 * Hardware used (e.g. Vive/Oculus)
Vive & Oculus
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVr & OculusVR
### Steps to reproduce
 Open fresh project with current master or alpha 3.3
- Open Scene 017_CameraRig_TouchpadWalking
- Double check "Disable Other Controls On Active" is selected
-Select Either controller so you can see the script enabled
-Hold down OR just be touching the touchpad on one controller
-Start the scene while still holding down/touching track pad on one controller. 
- after scene starts release/ stop touching touchpad. Other track pad will disable and not re-enable.

### Expected behavior

On release/stop touching of either touchpad the alternate touchpadcontrol script should re-enable.

### Current behavior

when touchpad is pressed when starting a scene and then released it does not re-enable the alternate touchpad.

*** This also happens on Oculus touch when pressing the joystick beyond the deadzone.

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1537

it's in the release branch, but you can probably port the changes easily enough if you need to
