### ISSUE TITLE
Add axis arrows to simulator hands

### ISSUE THREAD

**Issue by dantman** [thestonefox/VRTK#1532]
When controlling the simulator hands there is very little indication of how you're going to move them when you move the mouse. The control hints kindly tell you the current mode and what controls to use to switch back to the HMD, switch hands, switch axis, and switch to rotation. But unless you look at the current axis value and try to comprehend it you basically just end up moving your mouse till you see something happen and go from there.

It would probably be much easier to comprehend if the active hand had straight/curved arrows pointing along the axis that moving your mouse will move the hand. Then without reading text you immediately know which hand is active, whether you are moving or rotating it, and which axis you will move it along. And whenever you press a button to switch hands, switch axis, or switch to rotation you immediately get visual feedback about that.

I might do this myself if I feel like sparing the time... though I think I'm running out of time this weekend.

It's a side discussion but I'm also contemplating whether the mock spheres should use the standard shader instead of Unlit so you get and cast shadows that make it easier to tell where they are.

**Comment by virror** [comment]
I like the idea with guides, as long as there is an option for turning it on/off : )

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/1602
