### ISSUE TITLE
VRTK_UIPointer events do not fire UIPointerElementExit if switching to another UI Element.

### ISSUE THREAD

**Issue by kristianpd** [thestonefox/VRTK#1542]
### Environment

 * 3.2.0 (Asset store version)

### Steps to reproduce

This can be observed in the sample scene by looking at the events on keyboard hover (with headset at least).

### Expected behavior

Should have one `Exit` event for every `Enter` event.

### Current behavior
 The `UIPointerElementEnter` is not fired on `VRTK_UIPointer` when you switch to another UI element.

**Comment by kristianpd** [comment]
I can take a look at the fix for this

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/1599
