### ISSUE TITLE
Suggested feature: Rotating on teleport

### ISSUE THREAD

**Issue by GregFrench** [thestonefox/VRTK#1544]
It would be really cool to have the option of being able to rotate on teleport. Similar to what UE4 has in their VR template and the mechanism that exists in Robo Recall. It would work best for people like myself with 180 degree setups. I could help code it if need be. It's just something I've wanted to see in VRTK for a while now.

**Comment by thestonefox** [comment]
https://www.youtube.com/watch?v=qD-dD43E8pg
