### ISSUE TITLE
How to change position of attached objects in grab

### ISSUE THREAD

**Issue by Jithendrakumar** [thestonefox/VRTK#1558]
Hi,

As i was working on Interaction with Objects, the examples were very helpful but i didnt find option to change the position of the attached object on controller. Presently when i use Trigger Press for Grab object is attached to centre of the Controller, how to change it to the edge of the Controller.

Any suggestion??

Regards,
Jithendrakumar K.

**Comment by thestonefox** [comment]
You need to use a snap handle, there are example scenes showing this.

this is also a question for the slack channel as it's not a bug or feature request.

http://invite.vrtk.io
