### ISSUE TITLE
VRTK_Pointer - Custom Origin casting direction issue

### ISSUE THREAD

**Issue by 13Flo** [thestonefox/VRTK#1560]
### Environment

 * VRTK 3.2.1 (Github)
 * Unity 5.6.3
 * HTC Vive
 * SteamVR

### Steps to reproduce

- Assign a custom origin to VRTK_Pointer
- In Play mode, dynamically assign another custom origin

### Expected behavior

The teleport bezier pointer should start from the newly assigned custom origin and cast to the related transform.forward direction.

### Current behavior

The teleport bezier pointer does start from the newly assigned custom origin **BUT it casts to the previous custom origin transform.forward direction**. Manually changing the rotation of the previous custom origin does change the cast direction, while the start point is actually right, which does prove the above issue.

**Comment by thestonefox** [comment]
If you're dynamically assigning a custom origin at runtime then realistically you'd need to assign it via code, in that instance just disable the pointer script, (script.enabled = false) then swap the custom origin, then re-enable the script (script.enabled = true) this will ensure the setup is run again.

The alternative is to have a bunch of variables being checked in an update loop and if they change then it runs the setup, which I personally find overkill.

The ideal solution would be that you can use proper setters and getters on the variables so when the variable changes the setter knows to run additional logic, but these types of variable are not accessible via the Unity inspector

**Comment by 13Flo** [comment]
Ok, I see. Thank you for the quick reply. 

(I love VRTK, thank you so much for everything you do)
