### ISSUE TITLE
Removing while iterating over array in VRTK_BasePointerRenderer.MakeRenderersVisible

### ISSUE THREAD

**Issue by bgr** [thestonefox/VRTK#1561]
I believe this is a buggy, some renderers in the array will be skipped over: https://github.com/thestonefox/VRTK/blob/7f19760c259185459b02e4b943070027fe482b19/Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs#L411-L414

**Comment by thestonefox** [comment]
Raise a proper bug report or a pull request otherwise this issue will be closed
