### ISSUE TITLE
TrackObjectGrabAttach dropping objects early

### ISSUE THREAD

**Issue by Teascade** [thestonefox/VRTK#1563]
### Environment

 * Source of VRTK (master-branch, through `git clone`)
 * Version of VRTK (revision `e16de5a`)
 * Version of Unity3D (e.g. Unity 2017.2.0f3)
 * Hardware used (HTC Vive)
 * SDK used (SteamVR, also tested with NewtonVR's SteamVR camera rig)

### Steps to reproduce

1. Open example project `021_Controller_GrabbingObjectsWithJoints`
2. Select `ExampleWorldObjects > TrackGrab_Cube` (the green cube of the three)
3. Scroll the inspector to find Track Object Grab Attach options and set `Velocity Limit` to anything other than Infinity (I used 1, but this happens with any value). This affects `Angular Velocity Limit` aswell but not as demonstratibly.
4. Enter VR and attempt to move the green `TrackGrab_Cube`.

### Expected behavior

The cube's movement speed should be limited and if you set the `Velocity Limit` to something like 1 or less, it should be visibly slowly following the controller. Otherwise the cube should follow the controller as previously to the changes to the example, except it's velocity should be limited.

### Current behavior

The cube is difficult to pick up as it will stop following the controller if the controller moves even slightly too fast for the cube, but it won't even detach from the controller properly.

Example gif:
![preview](https://user-images.githubusercontent.com/3822998/31673241-659062b2-b367-11e7-8e27-5163af536c97.gif)

**Comment by Teascade** [comment]
PR with fix: #1562

**Comment by thestonefox** [comment]
So what if you have velocity limit set to `infinity` and in your PR you're using `infinity` as the max delta difference?

**Comment by Teascade** [comment]
I've used it a bit and it doesn't seem affected. However I'd like to ask what does `Infinity` actually do to the variable? Does it just set it to `Float.MaxValue` automatically, it needs to set it as a float value or it would cause a type exception. Whatever Unity sets for it though ends up in the `maxDeltaDifference` aswell.

The PR does nothing else than make the script consistent with itself. The only variable changed is a local variable in a function so it shouldn't interfere with anything outside the script, and whatever ends up as `velocityLimit` ends up as `maxDeltaDifference` aswell.

**Comment by thestonefox** [comment]
`infinity` is just a Unity keyword that gets replaced to `Float.maxValue`

**Comment by thestonefox** [comment]
New PR https://github.com/thestonefox/VRTK/pull/1600
