### ISSUE TITLE
ControlDirectionGrabAction should rotate around second hands AttachPoint

### ISSUE THREAD

**Issue by virror** [thestonefox/VRTK#1564]
At the moment when using VRTK_ControlDirectionGrabAction, the IO rotates around the second hands origin point, i think it would make more sense to instead rotate around the AttachPoint.

**Comment by thestonefox** [comment]
is this a feature request or a bug report?

**Comment by virror** [comment]
A little bit of both? : D
But i see it more as a bug then a feature tbh.

**Comment by virror** [comment]
It was from a guy on slack, so i just thought i put it up here after looking at the source and thinking the behavior was not optimal atm.

**Comment by thestonefox** [comment]
if it's a bug then you know the drill ;)
