### ISSUE TITLE
VRTK_ObjectControl FixedUpdate movement results in choppy movement of objects following sdk objects

### ISSUE THREAD

**Issue by PrimeDerektive** [thestonefox/VRTK#1568]
### Steps to reproduce

Attach or child a pointer renderer to either controller alias and use touchpad playarea movement (adding a pointer and pointer renderer to either hand in example 017 is a simple way to test) and you'll notice when you move, the renderer is choppy/doubles every frame.

Moving the functions in FixedUpdate() to LateUpdate() in VRTK_ObjectControl solves the issue.

**Comment by thestonefox** [comment]
I would say these steps to reproduce need to be clearer, plus it's important to know versions of things.

That's why the issue template is needed to be followed because it ensures people are able to recreate the issue successfully and find a suitable fix.

**Comment by PrimeDerektive** [comment]
Sorry about that.
Unity v5.6.2f1, Oculus Utilities v1.13.0, OVRPlugin v1.14.0, SDK v1.19.0, VRTK 3.2.1

Steps:
>Open example scene 017.
>Add a pointer and pointer renderer to LeftController.
>Play and strafe/move, witness stuttering pointer.

**Comment by thestonefox** [comment]
Have you tried increasing the physics timestep to 1/90 ? I'm guessing the issue you're facing is the rift is running at 90fps but your physics isn't.

**Comment by virror** [comment]
Why are you still insisting on using fixed update instead of lateUpdate anyways? LateUpdate is pretty much made for cases like this and you don't get the timestep limitation which I think should be avoided as much as possible.

**Comment by thestonefox** [comment]
If you're moving the camera rig collider around then Late Update is too late to check for physics collisions.

**Comment by virror** [comment]
Hmm, ok. But just out of curiosity, why is it to late?

**Comment by thestonefox** [comment]
Because physics are constantly calculated within the fixed update. the fixed update loop is the physics routine. If you move something in the Late Update, then a bunch of physics frames will have passed and you could miss colliding with something. or something could miss colliding with you.

**Comment by virror** [comment]
How can a "bunch of physics frames" have passed if the physics loop is running at the same speed or slower? I can see there is a small risk of missing one frame, but not more then that.

**Comment by thestonefox** [comment]
The FixedUpdate (or physics loop) is at a different timestep to the normal Update/LateUpdate route.

FixedUpdate always runs at a consistent difference between frames and is run just before any physics update calls are run.

Update/LateUpdate are not on a fixed time step and the time between the update frames differs. Doing any physics based calculations in Update/LateUpdate will only create issues and missed collisions.

**Comment by zealousappex** [comment]
I'd like to reopen this as I am getting the same issue.

1. Running the more recent VRTK.
2. Open: "[006 - Locomotion] MovementTypes"
3. Set the "locomotionType" to walk in the direct your controller is facing, using the touchpad to walk.
4. Walk around any object looking at it, while walking around it you can see it stutter.

I changed the "physics timestep" but that didn't help.
Does anyone know how to correct this?
I was reading this and this seems to be the issue: http://www.kinematicsoup.com/news/2016/8/9/rrypp5tkubynjwxhxjzd42s3o034o8
