### ISSUE TITLE
Pointer + Interact With Objects = flickering highlight color

### ISSUE THREAD

**Issue by kumilanka** [thestonefox/VRTK#1571]
### Environment

VRTK 3.3.0 alpha (from GitHub, 23.10.2017)
Unity 2017.1
Oculus Rift with Touch
SteamVR SDK

### Steps to reproduce

1. Open or duplicate example scene 003_Controller_SimplePointer
2. On RightController alias, add VRTK_InteractTouch component
3. On RightController alias, set VRTK_Pointer setting Interact With Objects to true
4. On RightController alias, set VRTK_StraightPointerRenderer setting Cursor Scale Multiplier to 5 (optional, but helps identify the issue)
5. In scene, select red Cube. Use Window -> VRTK -> Setup Interactable Object. Set Touch Highlight Color to blue, leave everything else as default, Setup selected object(s)
6. Run scene, activate pointer and point at cube. Move pointer around on top of the cube while activated.
 
### Expected behavior

Highlight color of the object will stay constantly on while moving pointer on top of the cube.

### Current behavior

Highlight color of the cube flickers on and off, 
https://gyazo.com/86d142322123cd687db4f56133eea666

### Additional info

Release 3.2.1 on Asset Store does not have this bug.

https://gyazo.com/e466a6ae7ceccc2a1aed021530cd930b (here, change to straightpointerrenderer in code)
https://gyazo.com/6890447ef55f96bee89e18a3de85e435 (here, the other change, setting pointer renderer parent)
https://gyazo.com/60ac3e735d8405b3493fce344f51aae6 (here, 3.2.1 release scene hierarchy, pointer renderer not parented under controller follow object)
https://gyazo.com/6c6d9fc14f29a1af16020b2d2eb3fce5 (here, 3.3.0 alpha scene hierarchy, pointer renderer is parented under controller follow object)

My conclusion is that this specific change has re-introduced the flickering when moving interact pointer on objects. In release 3.2.1, you can cause this bug while the game is running by simply placing pointer renderer object nested underneath the controller follow script, no code change necessary. In 3.3.0 alpha, removing nested object will fix the issue with flickering, but break the pointer renderer (since it is no longer positioned or rotated correctly).

**Comment by bddckr** [comment]
@thestonefox This makes a lot of sense. I never included FixedUpdate in the TransformFollow script because it made no sense to update transforms in FixedUpdate.

The whole differentiation between Rigidbody and Transform into two Follow scripts is probably something that needs to be more flexible: Like you'd want the ability to set a transform based on the physics position of a rigidbody or something.

Your fix looks good to me, so if @kumilanka can confirm that that fixes it 🚢 it!
