### ISSUE TITLE
Highlight disappear in Vive for Unity 2017.2

### ISSUE THREAD

**Issue by ruonanzh** [thestonefox/VRTK#1574]
### Environment

Source of VRTK  : Unity Asset Store
Version of VRTK ：Unity Asset Store 3.2.1
Version of Unity3D ：Unity 2017.2.0f3
Hardware used: HTC Vive
SDK used: SteamVR

### Steps to reproduce

1. Set VRTK in Unity 2017.2.0f
2. Open 005_Controller_BasicObjectGrabbing Scene
3. Use your controller touch green ball

### Expected behavior
It should be a pink outline around green ball

### Current behavior
but there is none outline
it looks like this in simulator:

![image](https://user-images.githubusercontent.com/14535595/32049674-7848783e-ba80-11e7-886d-b7e6b803db2c.png)

I dont know it is one problem or two. The outline gameobject is active, but it is invisible in VR and looks bad in simulator. I think it is a  shader problem.

**Comment by thestonefox** [comment]
Please follow the issue template

**Comment by ruonanzh** [comment]
sorry about that already edit issue

**Comment by ruonanzh** [comment]
after further investigation it disappear because we are using Deferred rendering path. Seems like there is no easy way to fix it

**Comment by thestonefox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test1](https://trello.com/c/ruEH4hp8/1-test1)
