### ISSUE TITLE
FindEvenInactiveComponent(s) only searches in active scene

### ISSUE THREAD

**Issue by Peaj** [thestonefox/VRTK#1580]
### Environment

 * Source of VRTK: Asset Store
 * Version of VRTK: 3.2.1
 * Version of Unity3D: 2017.1.0p5
 * Hardware used: None
 * SDK used: Simulator SDK

### Steps to reproduce

Use VRTK_SharedMethods.FindEvenInactiveComponent, FindEvenInactiveComponents or FindEvenInactiveGameObject to find a GameObject or Component which is not in the active scene (with mutliple scenes loaded)

### Expected behavior

The GameObject or Component should be found.

### Current behavior

The methods dont find anything because they check for "gameObject.scene == activeScene".

All 3 methods can only find objects in the currently active scene which leads to errors e.g. if the SimulatorRig is not located in the active scene because it will not find itself.

### Possible solution

I would recommend using [this solution](http://answers.unity3d.com/answers/1272001/view.html) to find (even inactive) Components in all loaded Scenes.

**Comment by bddckr** [comment]
Cross-scene references are a huge pain in Unity.

Example 1:
1. Get a reference to the Simulator camera rig in another scene.
2. Unload that other scene.
3. Litter your whole code base to handle a destroyed camera rig.

**Comment by Peaj** [comment]
But the current implementation does not prevent cross references.
If it is located in the active scene you would still find and reference it from any other scene.
And the active scene can be unloaded like any other scene.

As "SDK_InputSimulator.FindInScene" does only search in the active scene,
it just has the (unnecessary?) limitation that the SDKManager cannot be located anywhere else. This makes it really hard to use in a multiscene setup.

Because I never need to unload the VRManager (and even to prevent broken references) I like to put it in a global scene wich is loaded once and only unloaded once the game quits. This would in most cases not be the active scene, because the active scene is also responsible for lighting etc.

In this case all the other simulator components cannot find the InputSimulator.
Maybe they should even use GetComponentInParent istead or at least a method that searches in the scene the searching object is located in?

All in all I wouldn't expect any of these methods to only search in the active scene. Because none of the Unity methods like FindObjectsOfType does either.

**Comment by thestonefox** [comment]
Any news on this?

**Comment by Peaj** [comment]
It seems to work correctly in our project. I will try to create a pull request next week. Btw. is there a specific Unity Version I should use to test it?

**Comment by Peaj** [comment]
I created a pull request (#1637) and changed the commit message after GitCop complained about the length of the lines. However it still complains even though the subject and body should be less then 72 characters per line now

**Comment by thestonefox** [comment]
Try closing the pull request, and raising a new one with the cleaned up git message

**Comment by Peaj** [comment]
Seems like it worked :) #1645

**Comment by kristianpd** [comment]
This can be closed now
