### ISSUE TITLE
Unable to Change Pointer Renderer on Runtime

### ISSUE THREAD

**Issue by Jayvd** [thestonefox/VRTK#1587]
### Environment

 * Source of VRTK (Unity Asset Store)
 * Version of VRTK (3.2.1)
 * Version of Unity3D (e.g. Unity 2017.1.1f1)
 * Hardware used (e.g. Vive)
 * SDK used (e.g. SteamVR)

### Steps to reproduce

    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    using VRTK;

    public class MenuToggle : MonoBehaviour {

    public VRTK_Pointer pointer;
    public VRTK_StraightPointerRenderer straightPointerRenderer;
    public VRTK_BezierPointerRenderer bezierPointerRenderer;
    public VRTK_ControllerEvents controllerEvents;
    public GameObject menu;

    bool menuState = false;

    void OnEnable()
    {
        controllerEvents.ButtonTwoReleased += ControllerEvents_ButtonTwoReleased;
    }

    void OnDisable()
    {
        controllerEvents.ButtonTwoReleased -= ControllerEvents_ButtonTwoReleased;
    }

    private void ControllerEvents_ButtonTwoReleased(object sender, ControllerInteractionEventArgs e)
    {
        menuState = !menuState;

        if (menuState)
        {
            pointer.enableTeleport = false;
            pointer.pointerRenderer = straightPointerRenderer;
            pointer.activationButton = VRTK_ControllerEvents.ButtonAlias.Undefined;
            pointer.holdButtonToActivate = false;
            pointer.activateOnEnable = true;
        }
        else if (!menuState)
        {
            pointer.enableTeleport = true;
            pointer.pointerRenderer = bezierPointerRenderer;
            pointer.activationButton = VRTK_ControllerEvents.ButtonAlias.TouchpadPress;
            pointer.holdButtonToActivate = true;
            pointer.activateOnEnable = false;
        }

        menu.SetActive(menuState);
    }
    
}

  > Do not upload custom projects with custom code to demonstrate the issue.

### Expected behavior

The pointer renderer should change when set to different pointer renderer in code

### Current behavior

No changes on the pointer renderer when set.

**Comment by thestonefox** [comment]
have you tried when you change the pointer renderer calling disable and then enable on the pointer so it can re-do it's set up

**Comment by Jayvd** [comment]
@thestonefox 

I just added these lines, but the problem gets more interesting. The straightPointerRenderer stays visible when the menu is turned off, but it is left at the last position it was.

        pointer.enabled = false;
        pointer.enabled = true;

**Comment by thestonefox** [comment]
You're also forgetting to disable/enable the pointer renderer like this:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using VRTK;

public class MenuToggle : MonoBehaviour
{

    public VRTK_Pointer pointer;
    public VRTK_StraightPointerRenderer straightPointerRenderer;
    public VRTK_BezierPointerRenderer bezierPointerRenderer;
    public VRTK_ControllerEvents controllerEvents;
    public GameObject menu;

    bool menuState = false;

    void OnEnable()
    {
        controllerEvents.ButtonTwoReleased += ControllerEvents_ButtonTwoReleased;
    }

    void OnDisable()
    {
        controllerEvents.ButtonTwoReleased -= ControllerEvents_ButtonTwoReleased;
    }

    private void ControllerEvents_ButtonTwoReleased(object sender, ControllerInteractionEventArgs e)
    {
        menuState = !menuState;
        pointer.enabled = false;
        pointer.pointerRenderer.enabled = false;
        if (menuState)
        {
            pointer.enableTeleport = false;
            pointer.pointerRenderer = straightPointerRenderer;
            pointer.activationButton = VRTK_ControllerEvents.ButtonAlias.Undefined;
            pointer.holdButtonToActivate = false;
            pointer.activateOnEnable = true;
        }
        else if (!menuState)
        {
            pointer.enableTeleport = true;
            pointer.pointerRenderer = bezierPointerRenderer;
            pointer.activationButton = VRTK_ControllerEvents.ButtonAlias.TouchpadPress;
            pointer.holdButtonToActivate = true;
            pointer.activateOnEnable = false;
        }
        pointer.pointerRenderer.enabled = true;
        pointer.enabled = true;

        menu.SetActive(menuState);
    }
}
```

**Comment by thestonefox** [comment]
it disables the pointer at the start, disables the current renderer at the start

does all the switching

then enables the new pointer renderer and re-enables the pointer.

that should work

**Comment by Jayvd** [comment]
@thestonefox

Oh I see. I didn't expect that. I just "fixed" it by Toggle(false) on the ButtonPressed event. Your approach is much cleaner.

Thank you

**Comment by codemonkeynorth** [comment]
@thestonefox I'm using this method but it's causing a flash of a white cube at the origin with the pointer ray pointing out of it when I release my A/X button. It looks like it's visible for a brief moment before it attaches to the hand controllers?

(I've got the A/X button activating a teleport which is disabling the pointers on press and enabling on release... it's actually changing `VisibilityStates.AlwaysOf` / `VisibilityStates.AlwaysOn` but i'm disabling/enabling as per your example above before and after I switch that state.

(Note, I think i don't actually need to disable/enable to change that state, but i do need to disable/enable when i set my pointer max length elsewhere in my app)

ie disable pointers&renderers , set pointer max length, enable pointers&renderers.. If i do that,  i see the flash of the pointer renderer appearing at the origin for a few milliseconds... looking at the inspector i can see a delay on the collider object being removed/added
