### ISSUE TITLE
Namespace newly introduced MinMaxRangeAttribute (and possibly other classes)

### ISSUE THREAD

**Issue by bgr** [thestonefox/VRTK#1590]
Hi,
I've just pulled the latest `release/3.3.0-alpha` and `MinMaxRangeAttribute` clashed with the same class that's present in another asset (I will ask the author to namespace it as well). I saw that there are a few other classes that are in the global namespace that could be namespaced as well (e.g. `Limits2D`).

I've also had another clash, with a 3rd party `SerializedPropertyExtensions` which we also had a copy of in our project. Based on the nature of it I don't think changing the namespace would be the solution for this one, so this is just an FYI (I've just removed our copy of the file).

**Comment by thestonefox** [comment]
Agreed, these should be namespaced.

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1593
