### ISSUE TITLE
Error when trying to grab object with mesh collider

### ISSUE THREAD

**Issue by PraxxP** [thestonefox/VRTK#1604]
I'm using VRTK with Unity 2017.1.1f1, SteamVR and my HTC Vive.

I want to grab objects with a mesh collider, therefore I added the "VRTK_InteractGrab" script to the controllers and the "VRTK_InteractableObject" script, "VRTK_FixedJointGrabAttach" script, a kinematic rigid body (gravity off) and a non-convex mesh collider to the game object.

When I try to grab an object, I get the error "Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported in Unity 5."

The collider has to be non-convex, so what can I do about it? Are the controllers kinematic?

**Comment by thestonefox** [comment]
You haven't followed the issue template. This will be closed if the template isn't followed.
