### ISSUE TITLE
[feat] 2-Handed Autograb

### ISSUE THREAD

**Issue by grendelbiter** [thestonefox/VRTK#1608]
It would be nice if there was an easy way to pick up an Object and have it be Autograbbed by the Secondary Controller and optionally dropped if either Controller ungrabs. Sometimes you don't want an Object to be useable one-handed for example a Minigun or a 2-Handed melee weapon. It would also be useful for Autograbbing 2-Handed Objects at the start of a scene.

**Comment by thestonefox** [comment]
PR with solution https://github.com/thestonefox/VRTK/pull/1614

**Comment by grendelbiter** [comment]
That was quick! Awesome!
