### ISSUE TITLE
VRTK_UIPointer bug: Raycast only registering with the farthest canvas behind other canvases

### ISSUE THREAD

**Issue by octopusjuice** [thestonefox/VRTK#1609]
### Environment

 * Source of VRTK: Unity Asset Store
 * Version of VRTK: 3.2.1
 * Version of Unity3D: 2017.1.1f1
 * Hardware used: Vive
 * SDK used: SteamVR

### Steps to reproduce

 * Open example scene 034
 * Add a world space canvas to the scene and add a VRTK_UICanvas component to it
 * Set the canvas width and height to 500, scale the Canvas to 0.001 on the x and y axes, and position it in the scene
 * Add an image to the canvas, name it "red", color it red, and stretch it to fill the canvas
 * Duplicate the canvas, rename its image "green" and color it green
 * Position the green canvas behind the red canvas

### Expected behavior

Pointing a VRTK_UIPointer at the red image should log PointerEnter events for the red image even if the green canvas is behind it and in the path of the ray.

### Current behavior

Pointing a VRTK_UIPointer at the red image with the green canvas behind it (and also in the path of the ray) only logs PointerEnter events for the green image.

See screenshot below:

![vrtk_uipointer issue](https://user-images.githubusercontent.com/27227702/32758712-bfb64b10-c8b3-11e7-9377-31b017bb002f.png)

**Comment by thestonefox** [comment]
Can you update the issue title to something that explains the issue so when people are searching the issues they can have an understanding of the problem without needing to read the issue text.

**Comment by thestonefox** [comment]
Have you tried turning on `Blocking Objects` = `All` on the canvas Graphics Raycaster that is appearing behind the other one otherwise it won't consider anything to be blocking it.

**Comment by octopusjuice** [comment]
Wow, that was the issue! I wasn't familiar with how the Graphic Raycaster worked. Thank you so much!
