### ISSUE TITLE
DestinationMarkerEnter and DestinationMarkerExit are not emitted when VRTK_Pointer set to 'Activate on Enable'

### ISSUE THREAD

**Issue by AzzyDude24601** [thestonefox/VRTK#1610]
### Environment

 * Source of VRTK (Unity Asset Store or Github)   **Github**
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)   **3.2.1**
 * Version of Unity3D (e.g. Unity 5.4.4f1)   **Unity 2017.1.0f3**
 * Hardware used (e.g. Vive/Oculus)   **Vive**
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)   **SteamVR**

### Steps to reproduce

Just open up example scene 3 and stick a script on the Left and Right controllers  with the below code. Then make sure to tick the 'activate on enable'  in VRTK_Pointer on each. 

    void Start () {
        GetComponent<VRTK_Pointer>().DestinationMarkerEnter += exit;
        GetComponent<VRTK_Pointer>().DestinationMarkerExit += enter;
    }

    private void enter(object sender, DestinationMarkerEventArgs e)
    {
        Debug.Log("Pointer entered " + e.target.name + " on Controller index [" + e.controllerReference + "]");
    }
    private void exit(object sender, DestinationMarkerEventArgs e)
    {
        Debug.Log("Pointer exited " + e.target.name + " on Controller index [" + e.controllerReference + "]");
    }

### Expected behavior

The messages should be logged to the debugger when you point your pointer at an object. 

### Current behavior

Nothing happens, unless you deactivate and reactivate your pointer mid-play, then the messages will start appearing in the debugger when you aim at objects.

**Comment by thestonefox** [comment]
Easy fix, i'll raise a PR in a bit

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1611
