### ISSUE TITLE
Snap Drop Zone highlight not disappearing after object has been moved away from trigger area

### ISSUE THREAD

**Issue by V3DS-Benji** [thestonefox/VRTK#1623]
### Environment

 * Source of VRTK (Unity Asset Store or Github) - GitHub
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)  - Latest 3.3.0 branch downloaded from GitHub on 17/11/2017 13:34
 * Version of Unity3D (e.g. Unity 5.4.4f1) - Unity 2017.1.2f1
 * Hardware used (e.g. Vive/Oculus) - Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities) - SteamVR version 1.2.2

### Steps to reproduce

• Create new Unity project
• Import VRTK and Steam VR
• Accept to all SteamVR project setting changes.
• Open example scene 041_Controller_ObjectSnappingToDropZones
• Click Play
• Pick up the Torso with one controller
• Pick up one of the Arm pieces with the other controller
• Move Arm to either Arm Snap Drop Zone and release
• Arm snaps successfully
• Now unsnap the arm and move it away from the torso
• The snap drop zone red highlight stays visible until you ungrab the torso object
• Now pick up the torso again with one controller and a leg piece in the other controller
• Snap the leg to the torso
• Leg successfully snaps
• Now unsnap the leg and move it away from the torso
• The Leg snap drop zone highlight disappears as expected when out of range

### Expected behavior

When snapping an object that is apart of the interactable object like the torso example, the highlight should disappear once all valid objects have left the trigger area. The correct behaviour happens with the torso legs. 

### Current behavior

When snapping an object that is apart of the interactable object like the torso example, the highlight doesn't disappear once all valid objects have left the trigger area. I only know that this happens with the torso arms in the example scene.

**Comment by thestonefox** [comment]
I know what the problem is, if the collider on the snap drop zone is overlapping the thing you're grabbing, then it will cause the issue. The legs don't overlap the torso but the arm colliders do.

I'll look into a fix.

**Comment by thestonefox** [comment]
https://github.com/thestonefox/VRTK/pull/1624

**Comment by takpare** [comment]
takpar
