### ISSUE TITLE
Ray which is used to Raycast distance to intersection with surface out of sync causing input glitches.

### ISSUE THREAD

**Issue by rygo6** [thestonefox/VRTK#1625]
https://github.com/thestonefox/VRTK/blob/c29a6e3c59cc968b1df464150dd2d735b1adf483/Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs#L113-L116

The highlighted if statement and the logic inside of it is responsible for creating a bad race condition that causes severe input glitching in some situations.

This causes input issues specifically when you have a large flat plane which the pointer is to intersect with. If you point the pointer far away on the plane, then rapidly rotate your hand towards the center of the plane, the ray it uses to raycast lags one cycle behind, so it returns a much larger distance than it really should. This results in it placing the objectInteractor trigger far through the plane in some situations, causing the OnTriggerExit/Enter to fire, causing the input to glitch.

Commenting out that line of code fixes this.

The logic of the objectInteractor seems to determine the correct distance to place the Trigger so that it always correctly intersects with the collider and does not falsely call OnTriggerEnter/Exit when you move quickly over it.

However the logic which is placing actualCursor.Transform.Position is not correctly determining this distance. Thus setting objectInteractor to the actualCursor position can falsely fire OnTriggerEnter/Exit.

So far my solution has been to delete this suspect if statement and the line inside of the if statement. I assume a more proper solution is that the logic behind actualCursor needs refactoring. Although it seems strange to me that what is essentially the visual representation of the cursor can get out of sync with the collider which does the actual interacting, and needs to be periodically forced back into sync. This entire if statement seems suspect to me in signifying the need for more significant refactor and rearchitecture of how the whole pointer system works.

**Comment by rygo6** [comment]
The solution I described in my post above actually turned out to produce another isssue. When the pointer is not hovering over anything it then gets placed at the origin, interacting with whatever is there. 

Passing 'false' as an argument on this line:
https://github.com/thestonefox/VRTK/blob/c29a6e3c59cc968b1df464150dd2d735b1adf483/Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_StraightPointerRenderer.cs#L191

Then disabling smoothing on the pointer entirely fixes the issue for me.

Any advice on a proper solution would be appreciated.

**Comment by thestonefox** [comment]
If you're raising a bug then you need to provide steps to reproduce the issue in an example scene, if bugs are raised that don't follow the Issue Template then they will be closed.
