### ISSUE TITLE
variable go in ControlReactor.cs should also accept a TextMeshPro game object (not only TextMesh)

### ISSUE THREAD

**Issue by DebrisHauler** [thestonefox/VRTK#1633]
### Environment

 * Source of VRTK
Github
* Version of VRTK
unknown
 * Version of Unity3D (e.g. Unity 5.4.4f1)
Unity 2017.1.0p5
 * Hardware used (e.g. Vive/Oculus)
Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR

### Steps to reproduce

Install TextMeshPro from the asset store.
Open example scene 25  with sliders.
Find a slider in the scene.
Replace Display object under SliderGroup with a newly created TextMeshPro object.
Newly created TextMeshPro object cannot be assigned to Control Reactor Script of Slider game object.

### Expected behavior

Control Reactor component should accept either a TextMeshPro object or a TextMesh object.

### Current behavior

It only accepts TextMesh.

**Comment by thestonefox** [comment]
It's an example script, you shouldn't be using example scripts in your own code, just using them for inspiration. If you want to support text mesh pro in your own script then just do so.
