### ISSUE TITLE
Change Tracer Length at runtime

### ISSUE THREAD

**Issue by Jithendrakumar** [thestonefox/VRTK#1636]
Hi,

Can anybody suggest how to override Tracer length at runtime, any example??

Regards,
Jithendrakumar.

**Comment by thestonefox** [comment]
This in't a feature or a bug request. All questions should be asked on the slack channel at http://invite.vrtk.io or on stackoverflow.com with the `vrtk` tag applied to the question.

**Comment by Jithendrakumar** [comment]
Registered, Thanks.
