### ISSUE TITLE
Stuck in loading screen in the vive headset

### ISSUE THREAD

**Issue by ngware** [thestonefox/VRTK#1650]
### Environment

 * Source of VRTK GitHub
 * Version of VRTK b515d98
 * Version of Unity3D 2017.2.0F3
 * Hardware used Vive
 * SDK SteamVR

### Steps to reproduce

1. Download VRTK from Github
2. Open a example scene
3. Hit play

### Expected behavior

A working scene in the headset

### Current behavior

In the game tab, the scene is running well but in the vive I'm stuck on the loading screen (cf pic) : 

![vrtkissue](https://user-images.githubusercontent.com/3046392/33726636-d50f7944-db75-11e7-9672-92ce3ba503d8.png)

I tried to put OpenVR first in the list in XR Settings, save and reopen Unity but nothing works...

**Comment by thestonefox** [comment]
This isn't a problem with VRTK. it's a problem with steamvr.

I'd suggest you reboot your steamvr and try again.

For further support ask in the slack channel at http://invite.vrtk.io
