### ISSUE TITLE
VRTK_PhysicsSlider drawers moving automatically on game start, if objects are placed inside

### ISSUE THREAD

**Issue by borrowedLadder** [thestonefox/VRTK#1651]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
1648 Github Commit Hash (3.3.0 Alpha)
 * Version of Unity3D (e.g. Unity 5.4.4f1)
Unity 2017.1.1f1
 * Hardware used (e.g. Vive/Oculus)
Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
OpenVR

### Steps to reproduce

Create a sliding drawer using the VRTK_Physics Slider, place Interactable Objects inside.

### Expected behavior

On game start, the drawers should not slide open due to the Objects inside reacting in physics. Objects should be parented to the drawer, so when the drawer is opened, the objects do not slide around.
On picking up the objects, they should be unparented from the drawer and not be affected by the drawer being opened/closed. Should work with all grab attach types.

### Current behavior

Placing objects in drawers causes the drawers to slide open/move on game start. If objects are placed inside the drawers after the game has started, they react in strange ways moving around (and sometimes falling through the drawers) when you open/close the drawer.

**Comment by JWNJWN** [comment]
Can you try this on the latest master branch?
I tried to reproduce and I am getting the expected behaviour.
