### ISSUE TITLE
All VRTK Scripts are Showing Compile errors. 

### ISSUE THREAD

**Issue by kcom2016** [thestonefox/VRTK#1659]
### Environment

 * Source of VRTK (Unity Asset Store or Github) **Asset Store**
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash) **3.2.1**
 * Version of Unity3D (e.g. Unity 5.4.4f1) **5.5.1f1**
 * Hardware used (e.g. Vive/Oculus) **Vive**
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities) **Steam VR**

### Steps to reproduce

1. Import VRTK to asset folder, apply scripts from examples for cameras and hands etc. 
2. 
![image](https://user-images.githubusercontent.com/17214494/33949258-16396e04-dff7-11e7-90ac-346c18e2fe5f.png)
3. Error in scene view saying compilation errors. 

### Expected behavior

Error in scene view saying compilation errors & VRTK will not run.

### Current behavior

Error in scene view saying compilation errors & VRTK will not run.

**Comment by thestonefox** [comment]
This isn't a bug with vrtk, it's something with your configuration. Ask on the slack channel for help with problems like this.

**Comment by kcom2016** [comment]
I’m asking on your end becuse it happens when I redownlodes just VRTK. It was working fine yesterday, and when I downloaded VRTK again, it popped up with the error. Nothing else changed. I am going to create a new project to see if it is a config issue. (I have been using VRTK for close to a year now with no issue, but this just came up.) 

Thanks.

**Comment by thestonefox** [comment]
If it's worked before then its not a problem with VRTK, nothing has changed with VRTK. This is an issue for the slack channel because it's not a bug.
