### ISSUE TITLE
Cloned InteractableObjects (Instantate(this)) do not react to interactions

### ISSUE THREAD

**Issue by ValooFX** [thestonefox/VRTK#1660]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
AssetStore version
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.2.1
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.2.0f3
 * Hardware used (e.g. Vive/Oculus)
Oculus Rift + touch
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
Oculus assetstore sdk package

### Steps to reproduce

A GameObject is set up via the interactable wizard. A custom script instantiates 'this' on Use (subscribed to InteractableObjectUnused event from the VRTK_InteractableObject component) to create a new Instance/clone of the GameObject.

### Expected behavior

The clone should have the same interactions as the original.

### Current behavior

The clone does not react to grab or use interactions anymore. Instances created from prefabs function as expected.

**Comment by thestonefox** [comment]
You're going to need to provide better steps to reproduce. It's too unclear what your custom script is doing to expect anyone to reproduce this issue.

**Comment by ValooFX** [comment]
These are the relevant parts 
`
//Event subscription
            interactable = GetComponent<VRTK_InteractableObject>();
            if (!interactable) return;
            interactable.InteractableObjectGrabbed += OnBeginGrab;
            interactable.InteractableObjectUngrabbed += OnEndGrab;
            interactable.InteractableObjectUsed += OnBeginUse;
            interactable.InteractableObjectUnused += OnEndUse;
`
The grabbing handlers do nothing but log and toggle an isGrabbing bool.
The using handler that does something is this:
`
public void OnEndUse(object sender, InteractableObjectEventArgs args)
        {
            isUsing = false;
            if (isGrabbed)
            {
                if (PlacementType == ActorPlacementTypes.PlaceMultiple)
                {
                    RaycastHit hit;
                    if (Physics.Raycast(transform.position, Vector3.down, out hit, 0.3f))
                    {
                        if (hit.transform == MapGrid.Instance.transform)
                        {
                            var instance = Instantiate(this);
                            var pos = MapGrid.Instance.SnapToMapGrid(hit.point);
                            instance.transform.position = pos;
                            instance.SnapRotation();
                            MapGrid.Instance.OnObjectPlaced(instance.gameObject);
                        }
                    }
                }
            }
            else
            {
                Debug.Log("End Use: " + name);
            }
        }
`
The rest is handled through the components that were set up via the wizard

**Comment by thestonefox** [comment]
you're only cloning the interactable object, you dont seem to be cloning the grab mechanics to go with it.

**Comment by ValooFX** [comment]
I do get a fully cloned GameObject hierarchy. The serialized variables on all scripts also look the same. It's just not reacting anymore. I also Debug logged in Awake and that is being called too.

**Comment by ValooFX** [comment]
I just discovered and must have previously overlooked that IsGrabbable seems to reset on the clone.
