### ISSUE TITLE
Cannot set VR devices because the platform passed isn't supported by Unity

### ISSUE THREAD

**Issue by D3Munky** [thestonefox/VRTK#1662]
### Environment

 * Source of VRTK (Unity Asset Store)
 * Version of VRTK (3.2.0) 
 * Version of Unity3D (Unity 2017.0.2f3)
 * Hardware used (Oculus Headset, Touch Controllers)
 * SDK used (Oculus Utilities v 1.20)

### Expected behavior

To run the application with XR settings and virtual reality supported after updating VRTK and Unity

### Current behaviour

I have been tasked with updating a unity project from version 5.6.2f1. I am updating to version 2017.0.2 (after trying 2017.0.1)

Upon opening, i updated the API as suggested and once completed was presented with errors (ranging from this is deprecated to this is obsolete, etc) I could still run and see the XR settings showing VR  is supported and oculus too.

I updated from VRTK to 3.0.1 to 3.2.0 which reduced the errors and all errors could be fixed with changes in the inspector and this was when VR stopped working.

When I add VR Support and Oculus in XR Settings and press play...i get warnings but the concerning error is **"Cannot set VR devices because the platform passed isn't supported by Unity."** Warning as follows.

Cannot set VR devices because the platform passed isn't supported by Unity.
UnityEditorInternal.VR.VREditor:SetVREnabledDevicesOnTargetGroup(BuildTargetGroup, String[])
VRTK.VRTK_SDKManager:ManageVRSettings(Boolean) (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:351)
VRTK.VRTK_SDKManager:AutoManageScriptingDefineSymbolsAndManageVRSettings() (at Assets/VRTK/Scripts/Utilities/SDK/VRTK_SDKManager.cs:854)
UnityEditor.EditorApplication:Internal_CallHierarchyWindowHasChanged()

And when i stop running i get the error

Please add Oculus to the list of supported devices to use the Utilities.
UnityEngine.Debug:LogError(Object)
OVRMoonlightLoader:EnforceVRSupport() (at Assets/OVR/Editor/OVRMoonlightLoader.cs:139)
OVRMoonlightLoader:OnUpdate() (at Assets/OVR/Editor/OVRMoonlightLoader.cs:75)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

I managed to find the step that broke this was updating from 3.0.1 to 3.2.0 of VRTK which i can understand is pretty vague. Sorry. I did have name space issues as VRTK updated from assets store. It created Assets\VRTK where before the update it was Assets\SDK. To fix the namespace issue i deleted the SDK folder before importing again.

**Comment by thestonefox** [comment]
what version of unity is 2017.0?

do you mean 2017.2?

**Comment by D3Munky** [comment]
Apologies. Version 2017.2.0f3...i initially downloaded 2017.1.1f1, but updated to 2017.2.0f3.

**Comment by thestonefox** [comment]
you'll need to be using version .3.3.0 then

3.2.1 isn't supported on 2017.2

**Comment by D3Munky** [comment]
I cant see 3.3.0 under https://github.com/thestonefox/VRTK/releases. Sorry to be a pain but can you point me to its location?

**Comment by thestonefox** [comment]
It hasn't been released yet

**Comment by D3Munky** [comment]
ill rollback to an earlier version in the mean time. Does 3.2.1 work with Unity 5.6.4?

**Comment by thestonefox** [comment]
Yeah it does

**Comment by LangTao92** [comment]
But I develop the project in  Unity  2018.1.0 ,the VRTK is Version 3.2.1 ,I don' know how to solve

**Comment by bddckr** [comment]
All you need to do is download and use from GitHub.

If you need any assistance with that join our [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. GitHub issues are only useful for proper bug reports with steps to reproduce in an example scene like the Issue Template requires.
