### ISSUE TITLE
Unity UI OnClick() handlers get called multiple times if many in list

### ISSUE THREAD

**Issue by markus-at-fake** [thestonefox/VRTK#1665]
### Environment

 * Source of VRTK: Github
 * Version of VRTK:release/3.3.0-alpha, 12cd070
 * Version of Unity3D :  Unity 2017.1.2f1
 * Hardware used: Vive
 * SDK used: SteamVR

### Steps to reproduce

1. Open the example scene "034_Controls_InteractingWithUnityUI"
2. Add a GameObject into the scene
3. Add a simple script to the GameObject:

using UnityEngine;
public class Test : MonoBehaviour
{
    public void SetString(string s)
    { Debug.Log("SetString : " + s); }
}

4. Attach two event handlers to object "ExampleWorldObjects/Canvas/Button" OnClick, both pointing to the newly created GameObject (SetString, with parameters "one" and "two" for example).

5. Run the program and click the said button in scene

### Expected behavior

Clicking the button once, I only should have debug output "one" and "two" from the created GameObject.

### Current behavior

For one button click, I get debug output sequence of: "one", "two", "one", "two

**Comment by thestonefox** [comment]
I can't recreate it, i only get `one` then `two` output, I do not get it in multiples.

I suggest getting someone else to confirm otherwise I think this should be closed.

**Comment by jukka-at-fake** [comment]
I can reproduce this bug. Here's a video: https://www.youtube.com/watch?v=ZNAoT3JTA9k where I repro the issue with clean VRTK.

**Environment**
* Source of VRTK: Github
* Version of VRTK:release/3.3.0-alpha
* Version of Unity3D : Unity 2017.1.2f1
* Hardware used: Oculus
* SDK used: SteamVR

**Comment by thestonefox** [comment]
Can we have it reproduced by an independent account?

**Comment by jukka-at-fake** [comment]
This issue doesn't appear in the latest Unity release (2017.3.0f3).

**Comment by thestonefox** [comment]
Isn't 2f1 a release candidate and not the final release? Try updating your unity to 2017.1.f3 which I believe is the official release.

Unity betas and release candidates are always buggy

**Comment by markus-at-fake** [comment]
We reported the issue to happen on 2017.1.2f1 which is the official release. You can check this from the archive page:

https://unity3d.com/get-unity/download/archive

where the 2017.1.2 - mainline is the said one. There is no such version as "2017.1.f3" (or 2017.1.2f3 if that is what you meant). There is a patch release for *.1.2 (Patch 2017.1.2p4).

Anyway, we will soon move to the latest release so the problem fixes itself with that :).

**Comment by markus-at-fake** [comment]
Hello, it indeed seems that this was a Unity bug:

https://issuetracker.unity3d.com/issues/onclick-event-of-the-button-is-called-as-many-times-as-there-are-different-events-registered-to-it

So we can close this one. Sorry the trouble with this, @thestonefox  :).

**Comment by thestonefox** [comment]
Thanks for the investigation in to it, hopefully it will help others in the future :)

always worth raising an issue :)
