### ISSUE TITLE
Pointer is shaking and lags when the player is moving

### ISSUE THREAD

**Issue by interillusion** [thestonefox/VRTK#1675]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (3.3.0-alpha)
 * Version of Unity3D (Unity 2017.3)
 * Hardware used (Oculus)
 * SDK used (Oculus Utilities)

### Steps to reproduce

- Attach the player (SDKManager root) to a moving object (e.g. car, platform, etc).
      (this can be by making it a child of the other moving object, or by adding a VRTK_TransformFollow component)
- While moving, press to show the pointer
- See that the line rendered is shaking because its position is only updated every so often (fixedUpdate) instead of every frame

### Expected behavior

Pointer should be smooth and attached to the hand always

### Current behavior

Pointer origin is not always in the right position, which causes the pointer to show a ghost effect when moving.

**Comment by thestonefox** [comment]
Fixed update happens way more every frame than late update. The problem you're probably facing is the fixed update is in the physics time step but oculus is running at 90fps but the physics time step is only running at 60fps. Try setting your physics time step to 1/90 so it's also at 90fps

**Comment by interillusion** [comment]
Pointer rendering should be independent of Physics update. 

Increasing the physics update to match the rendering is not always feasible, as you maybe skipping frames, and different systems have different update frequencies (90Hz, 120Hz, etc).

In this case, what's happening is that the fixed update is not updating as often as the late update (which is great for performance) causing this out-of-sync.

Can you please, describe a situation where updating the pointer every frame could cause issues?

**Comment by thestonefox** [comment]
The fixed update is required for when the pointer is interacting with things, especially when using the pointer to grab.

**Comment by thestonefox** [comment]
You'll never skip frames if you match the physics timestep to the refresh rate, it's actually going to give you a better experience.

For example, the SteamVR plugin automatically sets the physics timestep to match the refresh rate.

If you want to have it so Oculus is always matching the refresh rate then just write a small script that sets the timestep based on the refresh rate.

`Time.fixedDeltaTime = Time.timeScale / UnityEngine.XR.XRDevice.refreshRate;`
