### ISSUE TITLE
VRTK_Pointer - interactWithObjects feature dumped?

### ISSUE THREAD

**Issue by f3flight** [thestonefox/VRTK#1677]
* Source of VRTK - Unity Asset Store
 * Version of VRTK - 3.2.1
 * Version of Unity3D - 2017.3.0f3
 * Hardware used - Oculus
 * SDK used - SteamVR

Looks like the new VRTK_Pointer which replaces VRTK_BasePointer does not have any code which uses interactWithObjects flag. Is that expected, or am I missing something? I grepped for this field throughout the code and it only appears in VRTK_BasePointer and VRTK_BasePointerRenderer.

My aim is to be able to "touch" an object with pointer, seems not possible with the current code (without writing my own).

Ideally I'm looking for a way to trigger touched object's event which would receive the destination marker raycastHit, i.e. the touched object would know where it got touched. This may be a case where a new kind of "Interact" script has to be introduced, like "VRTK_InteractPointerTouch", and add a new event listener delegate in VRTK_InteractableObject code.

**Comment by thestonefox** [comment]
The pointer creates an object interactor that follows the pointer cursor around.

If you have Interact_Touch and Interact_Grab on the controller then it will allow you to grab the objects as well.

I'm assuming you're missing the Touch and Grab script.

**Comment by f3flight** [comment]
@thestonefox thank you for directing me in the right way, work fine.  Still puzzled how this works since this field is nowhere to be seen in the code, but nevermind. ANd I still have to figure out how to pass raycastHit though this event, not sure it's possible. I've asked about this in Slack channel. Let me close this bug.
