### ISSUE TITLE
Unwanted positionchange through VRTK_RotateObjectControlAction

### ISSUE THREAD

**Issue by RunenGamer** [thestonefox/VRTK#1693]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: release/3.3.0-alpha (e43089a4dbefba55af2716d22de31458e0b615ca)
 * Version of Unity3D (e.g. Unity 2017.3.0f3)
 * Hardware used (e.g. Vive)
 * SDK used (e.g. SteamVR)

### Steps to reproduce

1.     Pull latest from feature branch 3.3.0-alpha
2.     Open Example scene 017_CameraRig_TouchpadWalking
3.     Enable SteamVR SDK (download, enable, populate)
4.     Select [VRTK_Scripts]>PlayArea>LeftController>TouchpadControlOptions
5.     Disable GameObject "XAxis = Slide  -  YAxis = Slide"
6.     Enable "XAxis = SnapRotate  -  YAxis = Slide" (or another rotate one)
7.     Start scene, use touchpad to rotate and observe global position of [VRTK_SDKManager]>SDKSetups>SteamVR>[CameraRig]>Camera (eye)

### Expected behavior

No matter where the real player stand inside of the PlayArea, a rotation should only rotate the player without changing player's global position. 

### Current behavior

Depending on where the real player stand inside of the PlayArea, the rotation not only rotates the player (Camera (eye)) but also changes player's global position (because [VRTK_SDKManager]>SDKSetups>SteamVR>[CameraRig] gets rotated). 

I would like to fix that by reposition [VRTK_SDKManager]>SDKSetups>SteamVR>[CameraRig] accordingly. 
Therefore I suggest to push to the master branch. 
If you do not consider this behaviour as a bug, I suggest to implement a feature (public flag on these scripts to enable repositioning) and target the release/3.3.0-alpha branch.

**Comment by LuckyJosun** [comment]
I've noticed this in the current release. I believe the headset is being rotated using the playspace's centre point as a pivot.

So, if the headset is in one corner of the playspace, and snap rotate is triggered, the headset's position can be dramatically changed instantly -- in my case, this causes players to move completely through virtual walls rotating near them.

I'm using an Oculus CV1 w/ Touch Controllers, the current SteamVR Unity Plugin (1.2.3 aka 54), the current release of VRTK (3.2.0), and Unity 2017.3.0f3 Personal. Windows 10.

**Comment by bddckr** [comment]
@LuckyJosun Use [VRTK 3.3.0](https://github.com/thestonefox/VRTK/tree/release/3.3.0-alpha).

**Comment by LuckyJosun** [comment]
@bddckr thanks for your reply, I didn't realise. I was using the version from the asset store (listed as 3.2.1). The asset page says it is compatible with "5.5.3 or higher", but I presume that text is unchangeable. I've grabbed the current state of 3.3.0-alpha now, and will work with that going forwards, updating as necessary.

I've also checked if this issue exists in 3.3.0-alpha on my machine, it does. I've experimented with it a little more, and it looks as though the rotation pivot isn't the centre of the playspace - it's the starting position of the headset.

To reproduce, follow @RunenGamer 's steps above, but replace step 7 with:
`Physically place your headset in one corner of your playspace, start scene, physically carry your headset to the opposite corner of your playspace, then the use the right touchpad/stick to rotate the player observing the global position of [VRTK_SDKManager]>SDKSetups>SteamVR>[CameraRig]>Camera (eye)`

On my machine, this drastically changes the position of the player with each rotation.

**Comment by RunenGamer** [comment]
> Edit: It looks like the scene view isn't showing the camera move, but it is very noticeable inside the headset. 
If you look at the headset's transform you can see the position change.

@thestonefox Do you want to confirm the bug or does these two observations confince you, so that I can make a PR with the fix?

**Comment by thestonefox** [comment]
feel free to make a pr

**Comment by RunenGamer** [comment]
@thestonefox Thank you. I will work on it. I will make a PR by sunday or earlier.

**Comment by JWNJWN** [comment]
This is fixed in current master.
@thestonefox
