### ISSUE TITLE
Network useability with PUN or Unity-Network

### ISSUE THREAD

**Issue by seehcpu** [thestonefox/VRTK#1700]
Problem / missing feature:
 *  The current SDK-Manager spawnes the player dynamically according to the VR-Settings-GUI
 * This interferes with any network code which tries to set up a game room, or instantiate players

Proposed solution:
*  Find a way to spawn the (complete) vrtk-sdk through the network-system. Meaning: for the instantiation of the room and the player within one needs to be able to:
    * spawn vrtk-sdk-manager on runtime AND
    * influence the spawned player prefab (from vrtk) in such a way, that it includes all necessary network stuff.

**Comment by thestonefox** [comment]
Many people are using PUN and UNET with VRTK. I suggest you ask in the slack channel for help as it's possible.

**Comment by bddckr** [comment]
>according to the VR-Settings-GUI
Nope, it's done according to the SDK Manager's list of SDK Setups, in order.

No need to do anything special. You can disable and enable the SDK Manager at runtime, you can also use its public API to load a specific SDK Setup or fire off the loading mechanism via the `autoLoad` setting. Tons of possibilities, just need to use the API.

Again I want to emphasize using [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) for these kind of questions.
