### ISSUE TITLE
Prefabs and vrtk functions missing after building

### ISSUE THREAD

**Issue by AyameMiwa** [thestonefox/VRTK#1702]
### Environment

- Source of VRTK - Unity Asset Store

- Version of VRTK - 3.2.1

- Version of Unity3D - 5.6.4f pro

- Steam VR Plugin - 1.2.2

- Hardware used - HTC Vive

First, sorry for my bad English ;-). I’m working on a simple application for my bachelor thesis. It works fine in editor mode – but after building, I am missing some gameobjects and vrtk functions.
-	I used 3D buttons as prefab from vrtk – they are missing after building.
-	I used 2D UI elements and they are nor working after building.
-	All gameobjects are visible after building (default is invisible).
-	Teleporting works after building.

How my application works: When I use a 3D button, a specific gameobject (cube, sphere, torus) will be show (it is invisible before I activate it with the 3D button). Each gameobject has its own button.
I get no errors while I am building my application. I try to fix it for days and I am really desperate. My tags for the gameobjects are “ExcludeTeleport” – not “EditorOnly” ;-).

**Comment by bddckr** [comment]
Unity 5.6 is old, so is VRTK 3.2.1.

I suggest using [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) for this kind of help as GitHub is better for issue description rather than troubleshooting.

**Comment by AyameMiwa** [comment]
Thank you for your reply - I updated my unity version and opened VRTK-master as a new project. I installed the new version of steamVR plugin. Now I am building your example scene "25 controls overview" and get the same problem. I don't know what's wrong with my settings. 

![image](https://user-images.githubusercontent.com/35525958/35048843-8897a4bc-fb9e-11e7-9165-769666ebd07d.png)
