### ISSUE TITLE
feat: StraightPointerRenderer AlwaysOn Condition Update

### ISSUE THREAD

**Issue by prashant-naidu** [thestonefox/VRTK#1707]
At the moment, when the renderer is set to always on, the ray is still visible when the controller model is hidden due to controller inactivity.

Make the renderer hide when the controller model hides as well

**Comment by thestonefox** [comment]
I'm not sure if this is still the case in 3.3.0 as I believe the pointer renderer is not attached to the controller GameObject anymore
