### ISSUE TITLE
bug - interact button override does not return to default

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#1713]
> **NOTE:** Any issue that does not follow the below template will be immediately closed and not re-opened until the template structure is adhered to.

### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0 Alpha
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.3 (also tested in 2017.2
 * Hardware used (e.g. Vive/Oculus)
Vive & Oculus
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR

### Steps to reproduce

create project with several vrtk_Interactable objects in a row, close together, with use over-ride button set to something (say touchpad press). Set interact use script to Trigger clicked. Start project and pass hand from one object to the other (so that at some point you're touching both objects), withdraw hand.

### Expected behavior
after you stop touching all objects the interact use button on the interact use script would return to trigger clicked (using the example above)

### Current behavior
interact use button stays with touchpad press (using the above example)

-I assume this is because when you untouch one object but begin touching another it stores the current use button, which is still being overridden by the previous object and never gets a chance to return to normal. I think the use button should be stored in the on start method and always set to that after onstoptouching is called. Or maybe the interact script is having a hard time determining when to call on stop touching if your touching 2 things at once?

**Comment by JWNJWN** [comment]
Can you try this on the latest master branch?
I tried to reproduce and I am getting the expected behaviour.
