### ISSUE TITLE
Pointers don't work (render or interact) in the latest build.

### ISSUE THREAD

**Issue by Danthekilla** [thestonefox/VRTK#1720]
* Source of VRTK (Unity Asset Store or Github)
GitHub, latest version as of yesterday.

 * Version of Unity3D (e.g. Unity 5.4.4f1)
Unity 2018.1.0b4 (64-bit)

 * Hardware used (e.g. Vive/Oculus)
Oculus Rift CV1

 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
Oculus Utilities were installed

### Steps to reproduce

Load the 003_Controller_SimplePointer scene or build a pointer sample yourself

### Expected behaviour

I expect for the pointers to interact with the scene and render a line from the controller

### Current behavior

Nothing is happening, when moving the thumbstick or any controls nothing renders or happens

I also followed a tutorial from youtube bit by bit and where they got a line rendering on their pointer I got nothing.

**Comment by bddckr** [comment]
Unity 2018 is a beta, we don't support betas.

Unity 2017 is only supported by VRTK 3.3.0, [WIP branch is here](https://github.com/thestonefox/VRTK/tree/release/3.3.0-alpha).

I suggest to join [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) if you need more help. GitHub issues aren't good for troubleshooting.

**Comment by Danthekilla** [comment]
I'll join the slack and see if I can get some help there.

I just tried it all again with Unity 2017.3 and the same issue still happens. Using the Unity asset store version of VRTK.

**Comment by bddckr** [comment]
Let me repeat myself here :)

> Unity 2017 is only supported by VRTK 3.3.0, WIP branch is here.

**Comment by flashmandv** [comment]
Same problem here. Unity 2018.1.1f1 (non beta) is not working with VRTK and oculus (Oculus plugin 1.14).
The pointer is sitting static somewhere. The hands (avatar) and controller move OK..but no pointer is attached

**Comment by ahmadsay** [comment]
> Та же проблема здесь. Unity 2018.1.1f1 (не бета) не работает с VRTK и oculus (плагин Oculus 1.14). 
> Указатель сидит где-то неподвижно. Руки (аватар) и контроллер двигаются нормально ... но никакой указатель не прикреплен 

Hi, did you find any solution? I still have the same problem.. but why?

**Comment by flashmandv** [comment]
Hi @ahmadsay 
I made it work, yes. Here is a test scene with just the SDKManager setup for Vive and Oculus.
[ViveAndOculusDemo.zip](https://github.com/thestonefox/VRTK/files/2538580/ViveAndOculusDemo.zip)
Unity version is 2018.1.1f1 and I forgot which Oculus version I managed to get it work...but here is my Assets/Oculus folder zipped (it could be the latest but I'm not sure)
[Oculus.zip](https://github.com/thestonefox/VRTK/files/2538602/Oculus.zip)
Good luck

**Comment by ahmadsay** [comment]
> Hi @ahmadsay
> I made it work, yes. Here is a test scene with just the SDKManager setup for Vive and Oculus.
> [ViveAndOculusDemo.zip](https://github.com/thestonefox/VRTK/files/2538580/ViveAndOculusDemo.zip)
> Unity version is 2018.1.1f1 and I forgot which Oculus version I managed to get it work...but here is my Assets/Oculus folder zipped (it could be the latest but I'm not sure)
> [Oculus.zip](https://github.com/thestonefox/VRTK/files/2538602/Oculus.zip)
> Good luck

Thanks! I will test. For me, this problem very often appear. Or my lasers don't see in the scene, or it somewhere and froze.
