### ISSUE TITLE
Body Physics "bounces" on fall/ landing a jump (Possible Fix included)

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#1721]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github 
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
latest 3.3.0 alpha (downloaded today) - also in previous version of alpha
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.3
 * Hardware used (e.g. Vive/Oculus)
Vive & Oculus
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVR/Oculus
### Steps to reproduce

Open touchpad walking scene 017
Add a cube, place on any layer except ignore raycast. Add hip tracking to the cube, lower it to -0.8 offset (so it touches the ground first)

Add a test script with below code - 
	void Update () {
        if (Input.GetKeyDown(KeyCode.Z))
        {
            bp.ApplyBodyVelocity(new Vector3(0, jump, 0), true, true);
        }
	}

Or fall off an object

Change Body physics step height to .3 (or anything really, but I wanted a slightly larger step height to match a normal stairs height

### Expected behavior
You'd fall to the floor

### Current behavior

You fall to the floor, but then bounce up the step height forever and ever.
If you raise the Step drop threshold it will stop.
If you set the HipTracked object to ignore raycast it will also stop. This leads me to believe it was due to some raycasting done when steps are calculated that only has a layermask for the Ignore Raycast layer.

**Fix?**
I'm not as awesome as TheStoneFox or BDDCKR but i was able to fix this but I'm not certain its the *right* way to fix it.

In the bodyphysics script line 965 it does a boxcast to determine if you should step up. but it does not do any type of layermask (save for the default Ignore raycast). I added ~customRaycast.layersToIgnore to use the body physics custom raycast option as a layermask. I can now add my object to any layer, set the custom raycast script to ignore that layer, and i no longer bounce!

before - 
                if (Physics.BoxCast(castStart, castExtents, Vector3.down, out floorCheckHit, Quaternion.identity, castDistance) && (floorCheckHit.point.y - playArea.position.y) > stepDropThreshold)

after - 
                if (Physics.BoxCast(castStart, castExtents, Vector3.down, out floorCheckHit, Quaternion.identity, castDistance, ~customRaycast.layersToIgnore) && (floorCheckHit.point.y - playArea.position.y) > stepDropThreshold)

**Comment by thestonefox** [comment]
I think the issue here is the `Physics.BoxCast` in't going through the custom raycaster.

That should the fix.

**Comment by thestonefox** [comment]
PR with fix
https://github.com/thestonefox/VRTK/pull/1765
