### ISSUE TITLE
Hoe to Enable Submesh Outline on Controller Enter

### ISSUE THREAD

**Issue by Jithendrakumar** [thestonefox/VRTK#1726]
Hi,

I have attached Interactable Object and outlinecopyhighlighter script to parent Gameobject and this parent have submeshes, whenever i touch only parent is highlighting with outline.
There was an option called "Enable submesh" in outlinecopyhighlighter script, that didn't do anything even after enabling it.

Any help would be helpful.

Regards,
Jithendra.

**Comment by mike-caputo** [comment]
Hey Jithendra, I think your issue is best suited for the help channel of the VRTK Slack: https://vrtoolkit.slack.com

Thanks.
