### ISSUE TITLE
PhysicsRotator Collider Mis-detected/Initialized Unless BoxCollider

### ISSUE THREAD

**Issue by Kyrluckechuck** [thestonefox/VRTK#1727]
### Environment
 * Source of VRTK (Unity Asset Store or Github)
   * Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
   * 3.3.0-alpha
 * Version of Unity3D (e.g. Unity 5.4.4f1)
   * 2017.3.0f3
 * Hardware used (e.g. Vive/Oculus)
   * Vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
   * OpenVR/SteamVR

### Steps to reproduce

General Idea, attempting to add a VRTK_PhysicsRotator to an object. The object didn't originally need a collider pre-created for OnTouch events to be triggered.

When adding the PhysicsRotator, it manually creates a BoxCollider on the object, which just won't do as it isn't the same dimensions, etc. I attempted to add a capsule collider, only, but it seems it won't trigger the OnTouch events with it at all when it's added. However, when it's a box collider being pre-created, it works :confused:

 * It seems that when any Collider exists, it doesn't create a default Box Collider ✔️ 
   * When a Box Collider exists/is created
     *  OnTouch events trigger ✔️ 
   * When a non Box Collider exists (such as Capsule Collider) 
     * OnTouch events don't trigger ❌ 
   * When both a Box Collider and other (Capsule Collider) exist 
     * OnTouch events are triggered by both colliders ✔️ 
     * If the Box Collider is removed dynamically (via Destroy()) in the gameObject's OnEnable(), the other Colliders still trigger fine ✔️ 

### Expected behavior

Should trigger OnTouch for the gameObject by the pre-created collider if it exists.

### Current behavior

Only triggers OnTouch for the gameObject by the pre-created collider if a box collider also exists when it is initialized (it can be removed dynamically after without problem).

**Comment by thestonefox** [comment]
There are no steps to reproduce the issue. The steps instead seem to be a bunch of inferences.
