### ISSUE TITLE
artificial rotator object generation

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#1728]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0 alpha (downloaded yesterday 2/13/18)
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.3
 * Hardware used (e.g. Vive/Oculus)
vive & oculus
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
steamvr and oculus
### Steps to reproduce

open example scene 25 and hit play. In the Editor disable any of the artificial rotators on the wheel objects and then reenable. It will create and nest itself in yet another VRTK Interactable Object.

### Expected behavior

Gracefully turn off and back on again.

### Current behavior

Duplicates the first time setup process

**Comment by thestonefox** [comment]
This is fixed in this branch https://github.com/thestonefox/VRTK/tree/feat/new-example-scenes
