### ISSUE TITLE
Artificial slider changes custom attach points rotation

### ISSUE THREAD

**Issue by CraigASanford** [thestonefox/VRTK#1729]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0
 * Version of Unity3D (e.g. Unity 5.4.4f1)
2017.3
 * Hardware used (e.g. Vive/Oculus)
vive
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
steamvr

### Steps to reproduce
Open Example 25 - add a gameobject to one of the controller aliases, add a rigidbody, set as that controllers custom attach point.

Grab the artificial slider and notice the rotation of your custom attach point changes. When you ungrab it does not get set back either.

### Expected behavior

no changes to custom attach point.

### Current behavior

custom attach point is rotated and is not returned to its previous rotation.

**Comment by CraigASanford** [comment]
I just tried this with the new examples branch and the issue persists in this branch.

**Comment by polerin** [comment]
Possibly related the base CreateTrackPoint() returning a reference to the controller attach point if precision grab is off?

**Comment by polerin** [comment]
Possibly related the base CreateTrackPoint() returning a reference to the controller attach point if precision grab is off?   I might try to give this a shot.

**Comment by JWNJWN** [comment]
Can you try this on the latest master branch?
I tried to reproduce and I am getting the expected behaviour.

**Comment by Tarteaututo** [comment]
Hi guys, i just ran into this issue and i may have fixed it by changing :
```
returnTrackpoint.rotation = Quaternion.identity;
returnTrackpoint.localScale = Vector3.one;
```
by 
```
returnTrackpoint.localRotation = Quaternion.identity;
returnTrackpoint.localScale = Vector3.one;
```
For me, it has fixed the controller rotation issue, but it may have thrown others errors.
