### ISSUE TITLE
Physical Interaction of Children of Physics Parents

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#174]
Is my Subject even a real sentence!! Haha...

...but yea just like the rather fantastic **Hot Dogs, Horseshoes and Hand Grenades**, being able to manipulate physicalized children of physicalized parents, such as holding a gun, and sliding the slide back, lowering a folding stock and so on.

Thank you!

-Steven

**Comment by thestonefox** [comment]
I'll check into this and see what's possible already, then find the holes to fill in :)

**Comment by xEvoGx** [comment]
Sweet!

**Comment by thestonefox** [comment]
This is possible, @mimminito has been doing this with a fire extinguisher. I'm hoping he's going to donate an example scene to demo it for others :)

I'll leave this issue open until we have a demo of it working.

**Comment by xEvoGx** [comment]
Yay! Any way we can start throwing rocks his way to get his attention? :smile:

**Comment by thestonefox** [comment]
He's in the slack channel daily if you wanna pester him :p
