### ISSUE TITLE
Does VRTK support HTC Vive Focus?

### ISSUE THREAD

**Issue by LiuYangTientsin** [thestonefox/VRTK#1748]
Hello! I have used VRTK for HTC Vive PC. But I have bought HTC Vive Focus.
Does VRTK support HTC Vive Focus?

**Comment by bddckr** [comment]
So far there's no VRTK SDK for the Vive Focus as far as we know.

Supporting a new device or vendor SDK is done by basically copying the included SteamVR SDK in VRTK and then modifying it to use the vendor SDK. VRTK is made to allow additions of SDKs without us having to ship with it.

We don't have this particular device in the hands of the core contributors of the repo so your best chance is to find someone in the community who has access to one or do the work yourself.

If you want to ask the community for help join us on [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io)!

**Comment by moscartong** [comment]
There is a SDK for VIVE FOCUS [here](https://developer.vive.com/cn/wave-en/) named VIVE Wave. You need to register as a developer and download the sdk [here](https://hub.vive.com/en-US/profile/material-download). Documents see [here](https://hub.vive.com/en-US/profile/documents). Also note that you need to target Android platform to develope apps for VIVE FOCUS.

**Comment by bddckr** [comment]
Yes but we're talking about VRTK here and VRTK needs its own Focus/Wave SDK to interop with the vendor SDK.

**Comment by thestonefox** [comment]
And we don't have a HTC Vive Focus to test on.

**Comment by wojiuxuihuan** [comment]
HTC Vive Focus use Wave SDK, which is a "Cross-platform Support, Accelerating Deployment,
High-performance Optimization" solution,
