### ISSUE TITLE
Auto manage Day Dream wrong XR setting

### ISSUE THREAD

**Issue by stankuhn** [thestonefox/VRTK#1754]
with latest Unity 2017.3.1f1 if there is GoogleVR sdk and Auto manage is checked Or button manage now is pressed Daydream is added to XR settings in buid settings but with wrong name https://www.dropbox.com/s/eoc8chx60i38vfd/Screenshot%202018-03-26%2013.00.05.png?dl=0
It shoul dbe added with lowercase "daydream" to be correctly recognised by Unity
Bug appears on release/3.3.0-alpha (#1753)

**Comment by thestonefox** [comment]
Known issue:

https://github.com/thestonefox/VRTK/pull/1639

**Comment by stankuhn** [comment]
Yeah, were talking about this on Slack yesterday. Found another issue that I wanted to report but before I wanted to update to latest 3.3 code. But than this bug re-appeared for me so aparently fix was not commited yet. What is best place to report bugs actually.

**Comment by thestonefox** [comment]
Bug reports should be made on github issues following the issue template.

This issue doesn't come under the issue template so should technically be deleted, but I'm happy to leave this up in case anyone else doesn't see the PR.

3.3.0 is still in alpha so all things have not been fixed yet.
