### ISSUE TITLE
Auto manage - None in XR list

### ISSUE THREAD

**Issue by stankuhn** [thestonefox/VRTK#1755]
Auto manage VR settings (or manage now) produces None in XR list in this SDK configuration
https://www.dropbox.com/s/jlwxd26bo3zfb01/Screenshot%202018-03-26%2013.08.03.png?dl=0
result
https://www.dropbox.com/s/x0gzoeg4rc2i3fl/Screenshot%202018-03-26%2013.08.20.png?dl=0

The None causes broken app. When device is inserted to GearVR, Unity logo shows up in non setereo mode and then app remains in black showing nothing.
Removing None manually and turning Auto manage VR settigns off makes app functioning correctly.
Bug is on release/3.3.0-alpha (#1753)
Unity 2017.3.1f1

**Comment by thestonefox** [comment]
Don't use AutoManage For GearVR. This isn't a bug, for questions like this please use the slack channel at http://invite.vrtk.io
