### ISSUE TITLE
VRTK_ArtificialRotator SetAngleTarget() bug

### ISSUE THREAD

**Issue by ShidoArima** [thestonefox/VRTK#1756]
### Environment

 * Source of VRTK (Unity Asset Store or Github)
Github
 * Version of VRTK (Unity Asset Store/Github release number) (Github master commit hash)
3.3.0 alfa
 * Version of Unity3D (e.g. Unity 5.4.4f1)
Unity 2017.1.1f1
 * Hardware used (e.g. Vive/Oculus)
Vive, Simulator
 * SDK used (e.g. OpenVR/SteamVR/Oculus Utilities)
SteamVr, SDK_InputSimulator
### Steps to reproduce

Create object to rotate. 
Add **VRTK_ArtificialRotator** with:
Z Axis
Limits 0 180
Resting Angle 0
Angle Target 180
Use Step As Value - true
Snap To Step - true
Add Custom script to use **VRTK_ArtificialRotator.SetAngleTarget(0)**

Start scene
Change Rotation with grab to max
SetAngleTarget to 0 from script

Also when i add **CancelUpdateRotation()** to **VRTK_RotateTransformGrabAttach** line 279 else statement it work fine for raw test.
```csharp
            if (transitionTime > 0f)
            {
                CancelUpdateRotation();
                updateRotationRoutine = StartCoroutine(RotateToAngle(newCurrentRotation, VRTK_SharedMethods.DividerToMultiplier(transitionTime)));
            }
            else
            {
                CancelUpdateRotation();
                UpdateRotation(newCurrentRotation, false, false);
                currentRotation = newCurrentRotation;
            }
```
### Expected behavior

Rotation changed from max (180 by z) to min (0 by z)

### Current behavior

Rotation change from max (180 by z) to min (0 by z) for few frames and then goes to (-170~ by z)

**Comment by thestonefox** [comment]
Are you saying adding the `CancelUpdateRotation()` fixes the issue?

If so raise a pull request with the fix.

**Comment by ShidoArima** [comment]
Yes, ok.

**Comment by JWNJWN** [comment]
Can you test this in the latest master branch?
I tried to reproduce and I was getting the expected behaviour.
