### ISSUE TITLE
SDK_OculusController.GetCurrentControllerType is returning wrong values (sometimes)

### ISSUE THREAD

**Issue by bddckr** [thestonefox/VRTK#1762]
Excuse me for not following the issue template right now 😛

The following usage of `OVRInput.GetConnectedControllers` is wrong because that API returns an enum *flag*, not a single value (can be see by checking the `Controller` type's definition which it returns). Therefore the `switch` here is wrong and we need to change to to a bitwise comparison (`Enum.HasFlag` isn't available in .NET 3.5, it was added in 4.0).
https://github.com/thestonefox/VRTK/blob/72c9f432c84abea285c5009f637951a07181ca6f/Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs#L89-L108

**Comment by thestonefox** [comment]
Do you want to raise a pr with the fix?

**Comment by bddckr** [comment]
Oh I'm also wondering what we wanna do in case we see multiple things connected? AFAIK our own `ControllerType` we return only allows for a single value.

I suppose we will just keep the above order of checks and therefore report in that order instead of giving all info about connected devices?

**Comment by thestonefox** [comment]
I'm not going to get chance to do it as it's Easter holiday time!

**Comment by bddckr** [comment]
Related to #1763.

**Comment by RajOOI** [comment]
Based on your conversation above, and related to #1763, I'm wondering if it's possible for you to consider the flexibility of having us be able to choose the priority of the controller. In our game, our ideal situation would be to have both Touch and Gamepad detected, but we really need to run a different code path for gamepad in VR. If you could expose a way for us to set priority over Touch or Gamepad, we could have our players choose this from a menu. Then if you detect both Touch and Gamepad it uses our preferred setting and returns. Sorry if that sounds confusing. I'm currently unsure as to how I would ask to see if the X, Y button on a gamepad is pressed, as controllerEvents only has buttonOne, buttonTwo... do they relate to the LeftController ref and the A, B buttons to the Right ref?... I don't see mappings for how gamepad works, this is probably not the correct place to ask these questions, but I feel it's prudent to address it at this juncture :) Feel free to ignore/delete the comment if I'm talking about irrelevant stuff.

**Comment by thestonefox** [comment]
@RajOOI if you want to raise a PR with that feature then that would be good.

**Comment by thestonefox** [comment]
@RajOOI I don't suppose you could do a PR with the fix for this?

I'm away for a week now and am not going to have time to do it, and I think @bddckr is also pretty busy as well.

**Comment by RajOOI** [comment]
I'm not gonna get bandwidth for this for a long while as I have other priorities and workload, if I get on it at some point and see nothing has been started I'll comment on here,

**Comment by bddckr** [comment]
I raised a PR to fix this: #1779.

I was not able to find a way to allow returning multiple controllers on the VRTK side of things (huge change), nor was I able to find a good way to allow changing the order of importance, especially not without having to restart the app.
