### ISSUE TITLE
Cannot use Oculus Touch AND Gamepad together

### ISSUE THREAD

**Issue by RajOOI** [thestonefox/VRTK#1763]
### Environment

 * Source of VRTK = Github
 * Version of VRTK = Github release/3.3.0-alpha (probably on master also)
 * Version of Unity3D = 2017.2.0p1
 * Hardware used = Oculus AND Vive
 * SDK used = SteamVR/Oculus Utilities

### Steps to reproduce

- Have 2 Oculus Touch controllers paired
- Plug in a gamepad (I have an XBoxOne controller connected via USB) into Windows
- Load and run scene [001 - Interactions] ControllerEvents
- Use the Left Touch Thumbstick

### Expected behavior

Output in the display window shows Thumbstick axis (-1.0 to 1.0) etc in the window

### Current behavior

Nothing is displayed in the output window.

Notes:

I have investigated and it would seem that the issue lies in SDK_OculusController::GetCurrentControllerType(). During OVRInput.Update() line 306: connectedControllerTypes |= controller.Update(); is called. Line 1605 of OVRInput: return ((Controller)currentState.ConnectedControllers & controllerType); has currentState.ConnectedControllers = 19.
This flag is thus: connectedControllerTypes = LTouch | RTouch | Gamepad

Line 91 of SDK_OculusController, in the switch statement here it does not cater for the flag as it seems to assume enum values. The returned value of 19 results in line 107: return ControllerType.Undefined; to be returned.
Calls to: protected virtual OVRInput.RawAxis2D GetTouchpadAxisMask(uint index) for example will fail the switch statement and fall to line 850: return OVRInput.Touch.PrimaryTouchpad; which results in any axis calls having 0.0, 0.0 always returned.

I hope this information can help in fixing this bug, though it seems like a bit of a refactor and I'm not sure what we want to happen in this situation - I would assume that we want the ultimate result to return (19) to interpret as GamePad.

**Comment by thestonefox** [comment]
Lets close this and work on this issue:

https://github.com/thestonefox/VRTK/issues/1762
