### ISSUE TITLE
VRTK_ChildOfControllerGrabAttach.StopGrab does not work (UnityEvents)

### ISSUE THREAD

**Issue by codemonkeynorth** [thestonefox/VRTK#1770]
tested currently with UnityEvents, - calling `StopGrab` does not drop the object

1) Open `[005_Interactions] Interactable Objects`

2) In the editor, go to the `GrabMechanicTypesStation` (to the right when you spawn)

3) disable  `Hold Button To Grab` on the red `CubeChildControllerGrab` (4th item)

4) add an  `VRTK_Interactable Object Unity Events` script to the `CubeSpringJointGrab` object to the left of it

5) on the `CubeSpringJointGrab` add an `InteractableObject Unity Event` for `On Grab` and tell it to call `CubeChildControllerGrab` -> `VRTK_ChildOfControllerGrabAttach.StopGrab`

6) run the app and go right to the Grab Mechanic Station

7) Grab the  `CubeChildControllerGrab` with the right controller

8) With the left controller, grab the yellow `CubeSpringJointGrab` object

### Expected behavior

Grabbing`CubeSpringJointGrab` should cause  `CubeChildControllerGrab` to drop from the controller (since `StopGrab` has been called on it)

You can test other events are working by replacing the function call with eg `CubeChildControllerGrab` -> `GameObject.SetActive` -> `false` (this will make the red cube disappear when picking up the yellow cube)

also for comparison this also works  `CubeTrackObjectGrab` -> `VRTK_TrackObjectGrabAttach` -> `StopGrab`

### Current behavior

`VRTK_ChildOfControllerGrabAttach` -> `StopGrab` is not dropping the object.

### Environment

* Source of VRTK (Github)
* Version of VRTK (Github Current Master Version)
* Version of Unity3D (2017.3.1f1)
* Hardware used (Oculus)
* SDK used (OculusVR)

**Comment by codemonkeynorth** [comment]
the grabbed object is still being parented after `StopGrab()` is called by this function in `SnapObjectToGrabToController`:

`obj.transform.SetParent(controllerAttachPoint.transform);`

**Comment by thestonefox** [comment]
You have to use `forceStopInteracting` otherwise you're still touching it.

I don't think this is a bug, just misuse

**Comment by codemonkeynorth** [comment]
Ok thanks.. I think `StopGrab` is a bit of a misnomer then as per docs

`The StopGrab method ends the grab of the current object and cleans up the state`.

from that i'd assume `forceStopInteracting` would be called automatically, in order to end the grab
