### ISSUE TITLE
NullReferenceException if SnapDropZone doesn't have a highlight object

### ISSUE THREAD

**Issue by codemonkeynorth** [thestonefox/VRTK#1771]
**Summary:** `NullReferenceException: Object reference not set to an instance of an object` if SnapDropZone does not have a `Highlight Object Prefab`

**(Note: placing an empty game object as the `Highlight Object Prefab` will suppress this error for now)**

### Steps to reproduce

1) Open `[005_Interactions] Interactable Objects`

2) Go to the SnapDropZone station and set the `Highlight Object Prefab` to `None` on the `SnapDropZone` in the `ScalingSnapPoint` object

3) either: Set `ScaleSaucerToSnap` as the `Default Snapped Interactable Object` and run the app
   or: run the app and drop the `ScaleSaucerToSnap` into the `SnapDropZone`  

4) refer to error in console

### Expected behavior

`SnapDropZone` should not produce an error if no `Highlight Object Prefab` is provided

### Current behavior

Error is generated:
`NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_SnapDropZone+<UpdateTransformDimensions>c__Iterator1.MoveNext () (at Assets/VRTK/Prefabs/SnapDropZone/VRTK_SnapDropZone.cs:789)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)`

### Environment

* Source of VRTK (Github)
* Version of VRTK (Github Current Master Version)
* Version of Unity3D (2017.3.1f1)
* Hardware used (Oculus)
* SDK used (OculusVR)

**Comment by thestonefox** [comment]
If you don't have a highlight object then the snap drop zone doesn't work.

I agree it shouldn't throw an error, but the only alternative is to catch the null exception and throw a nicer error

**Comment by codemonkeynorth** [comment]
@thestonefox  theoretically there's no actual need for a highlight object though?

again as mentioned, I just put an empty gameobject in to suppress the error.

**Comment by thestonefox** [comment]
If it's just suppressing the error is the issue, then a null check to prevent the error should be fine.
