### ISSUE TITLE
VRTK_TunnelOverlay needs more Range on initialEffectSize

### ISSUE THREAD

**Issue by RajOOI** [thestonefox/VRTK#1773]
### Environment

 * Source of VRTK - Github
 * Version of VRTK - alpha 3.3.0
 * Version of Unity3D 2017.2.0p1
 * Hardware used - Oculus
 * SDK used -Oculus Utilities)

### Steps to reproduce

The overlay seems to work fine within the sample scenes. When I apply the overlay to my project the tunnel initialEffectsize, even when at 0 is visible around the edges

![image](https://user-images.githubusercontent.com/38009086/39054379-ddef06ee-4487-11e8-82e3-69dec708425e.png)

If I change the Range slider to allow the shader to be less than 1, I am able to control the extents of the effect:

[Range(-1f, 1f)]
public float initialEffectSize = 0f;

### Expected behavior

I can control the size of the overlay based on my Camera's settings (or whatever the issue is).

### Current behavior

I cannot set the shader to start beow 0.

**Comment by RajOOI** [comment]
We finally got back to looking at this, and we found out what the cause was. Our far clip plane on our camera was set to 3000. Setting this down to 1500 removes the issue. You can reproduce if you load the scene "[006 - Locomotion] MovementTypes" and find the camera that has VRTK_TunnelEffect added to it when you enable the tunnel. Set the far clip plane to 3000 and you should see it.

**Comment by thestonefox** [comment]
Try this plug-in for tunnelling

https://github.com/sigtrapgames/VrTunnellingPro-Unity

**Comment by dallanporter** [comment]
Thanks for the fast reply! Funny--I just added this to my project the
moment your email arrived (found after some google searching). This looks
like a really great asset and should take care of my problem.

Cheers!
Dallan

**Comment by RajOOI** [comment]
A user Reznov on the forums recommended that plug in for us and so we also ended up using that.
