### ISSUE TITLE
feature: Generic trackers support

### ISSUE THREAD

**Issue by subzero911** [thestonefox/VRTK#1784]
- An ability to track positions of generic trackers
- The setup scene to bind trackers to hip / left foot / right foot by its device serial number (and to save it to JSON config)

This functionality provided by [Vive Input Utility](https://assetstore.unity.com/packages/tools/integration/vive-input-utility-64219) plugin, but it's difficult to make it work along with VRTK, because it has its own ViveCameraRig, connected to player, not to SDKManager.

**Comment by thestonefox** [comment]
You don't need to use the Vive Input Utility for tracker support, they're just another steamvr tracked object

https://youtu.be/p1u25WF0SWA?list=PLTiD-q2AfVNKwI9Wim5f-ge_Ucf7GjhVo&t=1691

**Comment by thestonefox** [comment]
HTC Vive input utility is providing bespoke solutions for a bespoke device. Vrtk tends not to support specific devices in a bespoke way. If you can come up with another way of supporting the tracker and potential future trackers in a generic way then I'd love to hear it
