### ISSUE TITLE
Touchpad 2 and Windows MR.

### ISSUE THREAD

**Issue by bigdaddio** [thestonefox/VRTK#1789]
VRTK 3.3.0
WMR
Unity 2018.1.0f2

### Steps to reproduce

Using Scenes [002 - Pointers] StraightPointer, [003 - Pointers] BezierPointer etc
change the VRTK_Pointer Activation button and Pointer Selection to Touchpad 2.

### Expected behavior

I expect the stick to work like the touch pad, move the stick and the pointer appears. Yes that happens just as if I were using the touchpad. Release the stick and the selection is made just like the touchpad,. 

### Current behavior

Release the stick and the pointer still remains. No selection is made. We never get a message from the control to call the  **DoActivationButtonReleased** in the VRTK_pointer component.

**Comment by bigdaddio** [comment]
The touchpad sends an untouched message. So does the stick. If you look at the controller events, there is an untouched when the stick is let go or centered. I'd expect that to be used just like the touchpad untouched.

**Comment by JWNJWN** [comment]
At least on latest master,
The stick does not send an untouched event, only axis changed and click events.
@thestonefox

**Comment by thestonefox** [comment]
@JWNJWN would you say this should be closed? You couldn't recreate and it's been sitting dormant for some time.

**Comment by JWNJWN** [comment]
@thestonefox Yea, I'd say it should be closed, the only things that should even emit a untouched event would be capacitive surfaces, which WMR doesn't have on it's touchpad.
