### ISSUE TITLE
Texture.Texture() is inaccessable

### ISSUE THREAD

**Issue by RickBlacker** [thestonefox/VRTK#1795]
### Environment
- Source : Unity Asset Store
- VRTK Version : 3.2.1
- Unity Version : 2018.1.0f2
- Hardware : Have not even been able to get that far yet

### Steps to reproduce
Created a brand new project
Downloaded VRTK from Unity Asset Store. 
Open project solution into Visual Studio. 

### Expected behavior
Expected a clean compile.  

### Current behavior
I get an error saying, 
**_"Texture.Texture()' is inaccessible due to its protection level"_**
This is happening in file:
**_"\Assets\VRTK\Scripts\Interactions\Highlighters\VRTK_MaterialColorSwapHighlighter.cs"_**
This is happening in Line **_"146"_**

**Comment by thestonefox** [comment]
VRTK 3.2.1 doesn't support Unity 2018.1 you will need to use VRTK 3.3.0 (which is currently the github master branch)

**Comment by RickBlacker** [comment]
Ok, ok!  Thanks so much.
