### ISSUE TITLE
[Feature Proposal] Pointer Activation on Button Release

### ISSUE THREAD

**Issue by agustinmorantes** [thestonefox/VRTK#1810]
I was trying to recreate the Oculus Home feature that lets you grab an object when pointing to it. What you do is lift your finger from the trigger and the pointer shows up. In the current VRTK_Pointer script there is no such option to activate the pointer on release of a button or anything similar. I could make a workaround myself but thought it would be a nice addition to VRTK.

### Environment

 * Source of VRTK: Github
 * Version of VRTK: Latest
 * Version of Unity3D: 2018.1.0f2
 * Hardware used: Oculus
 * SDK used: Oculus Utilities

### Steps to reproduce

When attaching a VRTK_Pointer script in a controller there is no option to activate the pointer when the activation button is NOT pressed.

### Expected behavior

There should be an option to activate on release.

### Current behavior

Pointer only activates on button press.

**Comment by thestonefox** [comment]
This will be resolved with how v4 handles action activation/deactivation
