### ISSUE TITLE
Attach the surface of the object to the tip of the pointer instead of the center of the object

### ISSUE THREAD

**Issue by a33366** [thestonefox/VRTK#1816]
### Environment

 * Source of VRTK ( Github)
 * Version of VRTK (Latest 3.20)
 * Version of Unity3D (2017.1.1)
 * Hardware used (Vive)
 * SDK used (OpenVR)

### Steps to reproduce
When attaching a VRTK_Pointer script in a controller 
Turn on interactWithObjects option
Turn on grabToPointerTip option
Add interactingObject script on interactive objects
### Expected behavior

The surface of the object is connected to the ray tip

### Current behavior

The center of the object is connected to the ray tip

**Comment by thestonefox** [comment]
V4 should allow for this feature request
