### ISSUE TITLE
[Feature Idea] Integrate Unity's SuperScience when installed

### ISSUE THREAD

**Issue by dantman** [thestonefox/VRTK#1817]
*issue template is not applicable*

[It seems](https://www.reddit.com/r/Vive/comments/8n1m0m/another_gem_from_unity_labs_smooth_tracking_of/) that Unity has published something that could be useful to integrate into some of the grab mechanics.

They've published a repository that includes (useful to us). Stabilizr, a system for smoothing the motion of steady, still, and orbiting motion of held objects. And PhysicsTracker, a motion tracker that is more reliable than checking raw delta data and improves speed/velocity/acceleration/etc calculations for things like moving and throwing grabbed objects.
https://github.com/Unity-Technologies/SuperScience

PhysicsTraker demo: https://www.youtube.com/watch?v=3L0Qs2F0Glo

The most immediately obvious use would be to integrate it into the throwing portion of the grab code.

**Comment by bddckr** [comment]
I have this on my radar to look into for [v4](https://github.com/ExtendRealityLtd/VRTK.Unity.Core).

**Comment by thestonefox** [comment]
I don't think we'll implement their stuff. Just make it so our stuff works with their stuff (which v4 is all about anyway)

We may offer alternatives to what they do if we feel there is a better way of doing things
