### ISSUE TITLE
Error when SDK_OCULUS_AVATAR is checked

### ISSUE THREAD

**Issue by RebelKeithy** [thestonefox/VRTK#1819]
I'm using:
Unity 2018.1.1f1
Oculus Avatar SDK 1.26
VRTK 3.3.0

In SDK_Manager script I check SDK_OCULUS_AVATAR and try to run it gives the error.

Assets/VRTK/Source/SDK/Oculus/SDK_OculusController.cs(692,32): error CS0122: `OvrAvatar.AssetsDoneLoading' is inaccessible due to its protection level

**Comment by bddckr** [comment]
Seems like Oculus have accidentally changed it to be private in that version.

I believe this is a bug on there end as a user now has no ability to get notified about the load being done.

**Comment by amrittb** [comment]
Upto which Oculus Avatar SDK does the master branch of VRTK support? I am having same issue.

**Comment by thestonefox** [comment]
whichever one doesn't set their version number as private, probably 1.25 I guess?

**Comment by LiangChen0323** [comment]
anyone find a solution for this? I'm having same issue.

**Comment by amrittb** [comment]
Yes. Use Oculus Avatar SDK v1.25. It should work fine. I don't have access to the machine right now to post the actual versions of Oculus Utilities, Oculus Avatar and Oculus Platform packages.

**Comment by amrittb** [comment]
Then try with 1.24

**Comment by LiangChen0323** [comment]
sadly v1.24 gave me bunch of errors of avatar scripts

**Comment by amrittb** [comment]
I used these versions importing in this order.

Oculus Utilities v1.25.2
Oculus Platform v1.24
Oculus Avatar v1.24

This solved the issue for me.

**Comment by LiangChen0323** [comment]
thank you so much it's finally working now

**Comment by VRArt1** [comment]
Having this issue.

**Comment by bddckr** [comment]
Multiple solutions here:

1. Tell Oculus to fix their change they did to make this `private` as it's needed by developers (not just by VRTK).
2. Fix it in that Oculus script yourself by just changing `private` to `public`.
3. Fix it by using an older Oculus package version that doesn't have that change to `private` yet.

**Comment by Seafore** [comment]
Thanks, bddckr! Replacing "private" with "public" did the trick. Greatly appreciate your advice. (on mine, it was line 100 of "OvrAvatar" script, just before "UnityEvent AssetsDoneLoading = new UnityEvent();")

**Comment by dpggit** [comment]
I dont have any Occulus script, i use htc vive and there is not OvrAvatar, but the script VRTKExample_FixSetup is trying to access that class

**Comment by bddckr** [comment]
Issues like these are better discussed in [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) because you can instantly get answers instead of waiting on here. It's also way easier for troubleshooting in general. **GitHub issues are only useful for proper bug reports** with steps to reproduce in an example scene like the Issue Template requires.

**Comment by Arctel** [comment]
Had this issue today and in OvrAvatar on line 179, took AssetsDoneLoading line out of the #ifAVATAR_INTERNAL.  It now looks like so:

	#if AVATAR_INTERNAL
    public AvatarControllerBlend BlendController;
	#endif
	public UnityEvent AssetsDoneLoading = new UnityEvent();

Had to add using UnityEngine.Events; at the top to make that work.

Now it works and haven't had any problems from that change.

**Comment by asmanjitha** [comment]
> Had this issue today and in OvrAvatar on line 179, took AssetsDoneLoading line out of the #ifAVATAR_INTERNAL. It now looks like so:
> 
> ```
> #if AVATAR_INTERNAL
> public AvatarControllerBlend BlendController;
> #endif
> public UnityEvent AssetsDoneLoading = new UnityEvent();
> ```
> 
> Had to add using UnityEngine.Events; at the top to make that work.
> 
> Now it works and haven't had any problems from that change.

Thanks @Arctel it worked for me

**Comment by cipiox** [comment]
@Arctel's solution got rid of most of the errors for me, but now I have this one: 
Assets\Oculus\Avatar\Scripts\OvrAvatar.cs(180,12): error CS0246: The type or namespace name 'UnityEvent' could not be found (are you missing a using directive or an assembly reference?)

There is a UnityEngine.Events at the top of my script already:
#if AVATAR_INTERNAL
using UnityEngine.Events;
#endif

When I get rid of the #if and #endif in my script and just have the UnityEngine.Events, I get a lot more errors. Any suggestions?
I am using Unity 2019.4.14f1, Oculus Integration 20.1.0, and VRTK 3.3.0.

**Comment by Arctel** [comment]
@cipiox I'm not sure I replicate it, but what are the new errors your seeing when you comment out the #if/#endif?

**Comment by cipiox** [comment]
When I comment out the #if/#endif, I get the following errors: 
Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(78,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R320'
Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(79,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R321'
Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(80,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R322'
Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(81,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R323'
Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(88,13): warning CS0162: Unreachable code detected

**Comment by Arctel** [comment]
> When I comment out the #if/#endif, I get the following errors:
> Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(78,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R320'
> Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(79,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R321'
> Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(80,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R322'
> Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(81,46): error CS0117: 'OVRPlugin.SystemHeadset' does not contain a definition for 'GearVR_R323'
> Assets\VRTK\Source\SDK\Oculus\SDK_OculusHeadset.cs(88,13): warning CS0162: Unreachable code detected

I see here an answer that may help: https://stackoverflow.com/questions/64197350/unity-vrtk-does-not-contain-a-defination-errors   Can you try uncommenting all GearVR related code/references in all the project?
