### ISSUE TITLE
Persist on load is now depreciated - and calling DontDestroyOnLoad causes errors.

### ISSUE THREAD

**Issue by guiglass** [thestonefox/VRTK#1820]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (Github release chore(Version): bump to version 3.2.0)
 * Version of Unity3D (Unity 2017.3.0f3)
 * Hardware used (Vive)
 * SDK used (SteamVR)

### Steps to reproduce

Select "persist on load" checkbox of [VRTK_SDKManager] manager component. Or call DontDestroyOnLoad on the manager object.

### Expected behavior

The gameobject [VRTK_SDKManager] should persist on load.

### Current behavior

I require the use of "persist on load" option in my project, or the ability to call DontDestroyOnLoad to presist the [VRTK_SDKManager] object and manager component. But with the latest updates it's now depreciated.

How should I persist the [VRTK_SDKManager] gameobject through scene changes?

[edit]
I have now set the parent of [VRTK_SDKManager] to an object that has already been set to DontDestroyOnLoad just prior to a scene change, and I believe that worked ok.

**Comment by bddckr** [comment]
`DontDestroyOnLoad` is evil. For more information read #1316.

Unity introduced additive scene loading as a replacement, use that instead.
