### ISSUE TITLE
Pointer UI

### ISSUE THREAD

**Issue by TecDesign** [thestonefox/VRTK#1827]
Hi, I do not know how to solve this issue, i like to hover over a gameobject with the pointer so that it highlite and than show a UI by pressing the trigger. Each gameobject (with interactbleobject script ) has its own UI. The first part has succeeded, but i dont know how to activate the UI. Do i have to write a script for this or can i use one of your VRTK buildingblocks?
I hope you can help me with this?

**Comment by thestonefox** [comment]
This is a question for the slack channel as it's not a bug report or a feature request

http://invite.vrtk.io
