### ISSUE TITLE
VR Camera Movement?

### ISSUE THREAD

**Issue by Sumedhsonkamble** [thestonefox/VRTK#1839]
I'm using Oculus Rift, and trying to move VR camera using Cinemachine dolly track and creating an empty game object adding the camera as a child and moving game object using a script, but the motion is not happening because of VRTK scripts?

**Comment by thestonefox** [comment]
this doesn't follow the issue template

**Comment by bddckr** [comment]
For general Unity help join [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io).

Hint: Unity sets the position of cameras that use `targetEye` set to anything else than `None`.
