### ISSUE TITLE
Cross Section/ Clipping Plane

### ISSUE THREAD

**Issue by Aenzi** [thestonefox/VRTK#1840]
Hey there,
I'm an absolutely beginner in VR, using unity and Windows Mixed Reality.
Your VRTK is amazing and it helped me a lot! Thanks for your great job!
Now i have to create a Clipping plane like maybe in this video 
https://www.youtube.com/watch?v=pvwVg9JiMKQ

what i want to do is having a plane (maybe create it by pressing a controller button, but just to grab the plane or move a slider to move the plane would be fine as well) with which i can clip objects and see "the inside". 
I tried it for about a month, but i didn't get it, it's not working (tried to use the "crossSectionShader" from AssetStore, but it's not working for me :( )
Do you guys have any idea how i can handle this? 
So glad to hear from you!

**Comment by thestonefox** [comment]
If you have queries on getting help then your best bet is to use the slack channel at http://invite.vrtk.io as github issues are only really used for capturing bug reports
