### ISSUE TITLE
VRTK ignores the isTrigger property on collision objects

### ISSUE THREAD

**Issue by github-gebruiker** [thestonefox/VRTK#1858]
VRTK either allow the player to collide with all objects (always fading to black) or with no objects (no fading). It is not possible to mix collision objects (isTrigger = false) with in the same scene with "zone" objects (isTrigger = true).

**Comment by github-gebruiker** [comment]
Documentation was not clear about the VRTK_CollisionTracker script.

**Comment by thestonefox** [comment]
This issue does not follow the outlined template.
