### ISSUE TITLE
Oculus Integrations not working correctly with VRTK

### ISSUE THREAD

**Issue by grizzlypath26** [thestonefox/VRTK#1866]
VRTK Source:Github
VRTK Version: 3.3.0 (I think or whatever most recent master is called)
Unity3D Version: 2018.1.0f2
Using Oculus
Oculus Utilities 1.27.0

Steps to reproduce
Switch the Oculus SDK in an pointer example scene to Oculus Utilities and play.

Expected behavior

Each hands pointer is dependent on its own hand's touch pad inputs.

Current behavior

Left hand inputs control both hands inputs. So, when you touch the joystick both hand's pointers activate, but on right hand inputs no output.

Other Notes

Local avatar works perfectly fine finger positions respond accurately to actual finger positions. Tracking is fine. Touch and near touch still work correctly, but in order to grab an object with right hand left hand grab needs to be used. All inputs work correctly through UnityXR.

**Comment by TMaloteaux** [comment]
Some Deisim players reported me the exact same issue.

VRTK 3.3.0
Unity 2018.2.1
Oculus Utilities 1.27 (but the first report was with the previous version)

**Comment by TMaloteaux** [comment]
The issue seems to happen when there is another controller plugged in to the computer.

**Comment by grizzlypath26** [comment]
That makes sense because it was working fine then it just wouldn't work anymore. I did buy a new Xbox controller for my PC around the time of this post.

**Comment by TMaloteaux** [comment]
@grizzlypath26 @quintesse Don't hesitate to try my pull request to confirm that it solve the issue on your site so we can merge it to the main branch.
Thank you in advance for your help.
