### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object Avatar

### ISSUE THREAD

**Issue by xfluidsss** [thestonefox/VRTK#1882]
NullReferenceException: Object reference not set to an instance of an object
OvrAvatarSkinnedMeshPBSV2RenderComponent.InitializeSingleComponentMaterial (IntPtr renderPart, Int32 lodIndex) (at Assets/Oculus/Avatar/Scripts/OvrAvatarSkinnedMeshRenderPBSV2Component.cs:91)
OvrAvatarSkinnedMeshPBSV2RenderComponent.UpdateSkinnedMeshRender (.OvrAvatarComponent component, .OvrAvatar avatar, IntPtr renderPart) (at Assets/Oculus/Avatar/Scripts/OvrAvatarSkinnedMeshRenderPBSV2Component.cs:77)
OvrAvatarComponent.UpdateAvatar (ovrAvatarComponent component, .OvrAvatar avatar) (at Assets/Oculus/Avatar/Scripts/OvrAvatarComponent.cs:56)
OvrAvatar.UpdateAvatarComponent (ovrAvatarComponent component) (at Assets/Oculus/Avatar/Scripts/OvrAvatar.cs:285)
OvrAvatar.UpdateSDKAvatarUnityState () (at Assets/Oculus/Avatar/Scripts/OvrAvatar.cs:418)
OvrAvatar.Update () (at Assets/Oculus/Avatar/Scripts/OvrAvatar.cs:624)

Yes I Draged and droped [VRTK_SDKManager]  from Prefabs  into scene
Avatar Shaders missing?

**Comment by xfluidsss** [comment]
OK dont even bother
[VRTK_SDKManager] has to be taken from prefabs
LocalAvatar also has to be replaced with its Prefab version
From some Reason references in Scenes are missing

**Comment by thestonefox** [comment]
This has been fixed in the latest github master branch
