### ISSUE TITLE
Oculus Integration Controllers,Controller Events DONT WORK AT ALL

### ISSUE THREAD

**Issue by xfluidsss** [thestonefox/VRTK#1884]
VRTK git master
 * Source of VRTK ( Github)
 * Version of VRTK  (Github master commit hash)
 * Version of Unity3D (Unity. 2018.2.5f1)
 * Hardware used ( Oculus+touch)
 * SDK used (Oculus Utilities  1.27.1)

### Steps to reproduce
Downlaload GitHub VRTK master. Open in Unity, lunch Locomotion -Movment Types Scene

 
### Expected behavior

Working samples of locomotion

### Current behavior
  Missing Refferences in [VRTK_SDKManager] and Oculus Local Avatar and Unity hangs at Play
  After Removing [VRTK_SDKManager] and Local Avatar   and Adding  them directly from PROJECT
 Controllers  appear at  right position, however they dont interact with anything, they can not grab  
 anything, or control anything

**Comment by thestonefox** [comment]
You've not specified which version of Oculus Utilities you're using.

There may be an incompatibility with the latest version of Oculus Utilities if Oculus have changed something on how it works internally.

**Comment by xfluidsss** [comment]
SDK used (Oculus Utilities  1.27.1)

**Comment by thestonefox** [comment]
I'd recommend trying an earlier version, I believe the example scenes were built in 1.24

**Comment by xfluidsss** [comment]
It Doesnt work with version 1.24 also

**Comment by xfluidsss** [comment]
solved:
1. in OVRAvatar Script
Change
private UnityEvent AssetsDoneLoading = new UnityEvent();
to
public UnityEvent AssetsDoneLoading = new UnityEvent()

2.Remove [VRTK_SDKManager] and add [VRTK_SDKManager] Prefab from PORJECT
3.Remove LocalAvatar from  Scene and add Prefab from PROJECT
4.And NOW Most important in [VRTK_SDKManager] in null Script Aliases add References to 2 GameObjects From [VRTK_Scripts],LeftControllerScriptAlias and RightControllerScriptAlias

**Comment by thestonefox** [comment]
I don't recommend following that for the solution.

**Comment by xfluidsss** [comment]
any better solution woud be really to appreciated

**Comment by thestonefox** [comment]
I told you the solution in the slack channel.

If the OVRCameraRig and/or OVRAvatar are showing missing references then delete those prefabs from the scene and re-add them back in to the same GameObject they were deleted from (the one with the VRTK_SDKSetup for Oculus) then on the VRTK_SDKSetup for Oculus click the `Populate Now` button so it can set up the references again.

That's all you need to do. If you delete the SDK Manager then you're going to have to go through and re-set up a whole lot of references.

**Comment by xfluidsss** [comment]
Sounds like a solution

**Comment by ZNixian** [comment]
Sorry to bump this, but for anyone else looking for a solution (since this can't be searched for on Slack, due to the searchable message limit):

Try defining `AVATAR_INTERNAL` in your script definitions thing, as this enables the missing field.
