### ISSUE TITLE
VRTK+STEAMVR No Longer Works

### ISSUE THREAD

**Issue by CrayzCrinkle** [thestonefox/VRTK#1892]
### Environment

 * Source of VRTK - Github
 * Version of VRTK - most recent github master version
 * Version of Unity3D - 2018.2.1f1
 * Hardware used - HTC Vive
 * SDK used - SteamVR

### Steps to reproduce

Install Unity, Steam VR, and VRTK in a brade new 3D project.
Attempt to follow tutorial video https://www.youtube.com/watch?v=2IWAwFDhX2M&t=542s
(001 The Basics)

### Expected behavior

On the first run in the tutorial video, following each and every step exactly, the controller should have a pointer which can teleport around.

### Current behavior

VR loads, but there is no pointer or teleport functionality, no errors or warnings are encountered. The code simply does not work as in the tutorial any more.

**Comment by thestonefox** [comment]
This isn't a bug with vrtk, this is probably user error. VRTK is working as expected.

**Comment by bongistka** [comment]
I don't think it's a user error and I think, you should answer this properly. It doesn't work for me either.

**Comment by bddckr** [comment]
We did on Slack. Your issue can be anything and you gave no information at all. Head to Slack to get help or open a new issue and follow the issue template, otherwise it will be closed.

**Comment by missmah** [comment]
This seemed like a proper bug report.

And now, while that person may be helped, all of us in the future on the internet have no idea what the solution was.

**Comment by missmah** [comment]
So, for someone who is considering whether or not to use VRTK, does VRTK work with the latest SteamVR update?

**Comment by thestonefox** [comment]
@missmah at the time his issue was not a bug, nor was his report a valid bug report.

However, since then there is a new issue with SteamVR 2.0 and it is not compatible with VRTK 3.3 (current github master)

You'll need to use the SteamVR 1.2.3 plugin which is available at https://github.com/ValveSoftware/steamvr_unity_plugin/releases/download/1.2.3/SteamVR.Plugin.unitypackage

**Comment by michaellernvr** [comment]
This has worked for me - Thank you.

**Comment by eniholjuh** [comment]
Is this still the way to go? Or is there a fix for VRTK / SteamVR?
