### ISSUE TITLE
SteamVR interactable object grabbing is broken on Rift when "Hold Button To Grab" is set to false

### ISSUE THREAD

**Issue by ciwolsey** [thestonefox/VRTK#1893]
### Environment

VRTK: Github
Commit Hash: 71a6369a850badddb8c96135963a82b2408a54da
Unity: 2018.2.6f1 (not present on 2017.4, gashek says it's not present on 2018.1 for him but he also has issues on 2018.2)
Hardware: Rift
SDK: SteamVR (1.2.3 Plugin)

#### Reproduction 1
1. Open the interactable objects example scene. 
2. Using a Rift controller, pick up the object labelled "Hold Button To Grab = false".
3. Repeatedly grab and ungrab the object.
#### Reproduction 2
1. Open the controller events scene
2. Fully press the grip trigger
3. Slowly depress the grip trigger
4. Notice that a grip untouched event is fired with a value of zero without actually untouching grip
#### Notes:
Issue present on both controllers so unlikely to be a controller fault.

### Expected Behavior

The object is "held" when grab is pressed the first time and released on the next press. Repetition of this should produce consistent results.

### Current Behavior

Frequently the object is either not attached to the hand when grabbed, or not released when ungrabbed. Sometimes the object is released for no reason while being held. Very unpredictable.

**Comment by XGashek** [comment]
Behavior confirmed, having the same issue as stated above in the Interactable Objects example scene using SteamVR and Unity 2018.2.6f1.

**Comment by ciwolsey** [comment]
Found this:
https://steamcommunity.com/app/250820/discussions/3/3338745825900929011/

**Comment by ciwolsey** [comment]
Switching between SteamVR branches I have the following results:
**Broken Branches**
stable branch
beta
openvr-inputemultaor-temporary

**Working Branches**
"v1527117754 - 6/21/2018 hotfix"

**Comment by bddckr** [comment]
Great detective work! The OpenVR repo as well as the SteamVR forums may be good targets to post a bugreport in.

**Comment by ciwolsey** [comment]
I've commented on the issue here:
https://steamcommunity.com/app/250820/discussions/3/3338745825900929011/

If anyone else has this issue I recommend you also post there.

**Comment by ciwolsey** [comment]
Since this is a SteamVR issue I'll just close this.
