### ISSUE TITLE
Can someone update the Unity Asset Store version?

### ISSUE THREAD

**Issue by nsmith1024** [thestonefox/VRTK#1899]
Hello,

Can someone update the Unity Asset store version with the latest VRTK?

Did you guys know that right now, VRTK in Unity Asset Store doesnt work, when the package is imported from asset store there are compile errors right off the bat, so its useless.

Second, I have a LARGE unity project right now. I tried using the VRTK from Gut Hub, but that one demands you to use their project, so i cant import it to my existing project.

So seems its totally useless, the one in unity asset store dont compile, and the one on GutHUB cant be imported into an existing project.

So then nothing works!

Can someone help, 

thanks

**Comment by thestonefox** [comment]
this isn't an issue for github, it also doesn't follow the issue template.
