### ISSUE TITLE
StartMenu button dont work for interactive objects

### ISSUE THREAD

**Issue by nsmith1024** [thestonefox/VRTK#1909]
### Environment

Versions
  Unity: 2018.1.0f2 (d4d99f31acba)
  VRTK: 3.3.0 (may not be correct if source is GitHub)
  SteamVR: 1.2.3
  OVRPlugin (Oculus Utilities)
    wrapperVersion: 1.28.0
    version: 1.28.0
    nativeSDKVersion: 0.0.0
VR Settings
  Standalone: None, Oculus, OpenVR
Scripting Define Symbols
  Standalone: CROSS_PLATFORM_INPUT;TMP_PRESENT;VRTK_DEFINE_OCULUS_UTILITIES_1_12_0_OR_NEWER;VRTK_DEFINE_SDK_OCULUS;VRTK_DEFINE_SDK_STEAMVR;VRTK_DEFINE_STEAMVR_PLUGIN_1_2_1_OR_NEWER;VRTK_DEFINE_STEAMVR_PLUGIN_1_2_2_OR_NEWER
  iOS: CROSS_PLATFORM_INPUT;MOBILE_INPUT
  iOS: CROSS_PLATFORM_INPUT;MOBILE_INPUT
  Android: CROSS_PLATFORM_INPUT;MOBILE_INPUT;VRTK_DEFINE_OCULUS_UTILITIES_1_12_0_OR_NEWER;VRTK_DEFINE_SDK_OCULUS
  Tizen: MOBILE_INPUT

### Steps to reproduce

Add VRTK_interactiveObject to a gameObject

Select the StartMenu as the override button

Run Unity, point pointer to above object, then press Menu button (not system menu), nothing happens, it should send StartUsing event to the object, but it doesnt.

If i pick a different over-ride button (touch press, trigger etc) it works, but not StartMenu.

### Expected behavior

Should call "StartUsing" or "StopUsing" when menu button is pressed on an interactive object

### Current behavior

Nothing happens

**Comment by bddckr** [comment]
You aren't specifying which hardware you're using but from the button description you're giving it sounds like it's a Vive controller you're talking about.

As we discussed on [![Slack](http://sysdia2.co.uk/badge.svg)](http://invite.vrtk.io) you're using the wrong button if you want to target the Vive controller's menu button: You need to use `ButtonTwo` instead, as seen [here](https://twitter.com/The_StoneFox/status/882922602708316161).

---

@thestonefox voting to close.
