### ISSUE TITLE
[fixed itselfe] Problem with Right Hand Oculus Touch Controller

### ISSUE THREAD

**Issue by MrMikeSimpson** [thestonefox/VRTK#1912]
Update!!!
the problem is gone, but I don't know why.
As nobody else seems to have had the same problem, it might have been a bug in my system and not in the VRTK.
End of update!!!

I setup a new project, and if I run example 002 - Pointer, the right hand Oculus Touch controller respond to the touch or button press of the left controller. That is not only the case with the example, also if I setup a scene from scratch.

### Precheck

 * I tried VRTK Slack channel, they suggested to post my issue here.

### Environment

 * Source of VRTK: Github master
 * Version of VRTK latest Github master release
 * Version of Unity3D: 2018.2.6f1 also tried with 2017.4, same problem
 * Hardware used: Oculus Rift with touch controller
 * SDK used: Latest Oculus Integration from the Asset Store 1.30.1

### Steps to reproduce

Open new project
Setup Oculus Integration
Import VRTK
Setup sample scene 002
Check settings for Oculus
Run

I made a small video where you can see the problem: [https://youtu.be/F8APaUj_Si8]

### Expected behavior

Each touch controller should work independently and not respond to a touch or button press of the other controller

### Current behavior
Watch the video (only 4 minute)

**Comment by bananalopa** [comment]
I have the same issue in Unity 2018.2.14 right now, so it's definitely not a bug in your system

**Comment by WeaselKing** [comment]
Same problem. No idea what's going on/what changed

**Comment by MrMikeSimpson** [comment]
Restart your computer and start Oculus software before you start Unity. That worked for me, but I don't know if this really solved the issue or if it was a coincidence.
