### ISSUE TITLE
It works for me also. Thank you

### ISSUE THREAD

**Issue by Yuyang01** [thestonefox/VRTK#1922]
adjusting the line in question to this: "renderer.material.SetTexture("_MainTex", new Texture2D(0,0));"
fixed the issue for me : )

I will keep an eye open for an update to  VRTK that works with 2018.2 +

_Originally posted by @treendy in https://github.com/thestonefox/VRTK/issues/1796#issuecomment-410544794_

**Comment by thestonefox** [comment]
This has been fixed already in v3.3.0
