### ISSUE TITLE
Impossible to use VRTK with Unity 2018.2.14f1

### ISSUE THREAD

**Issue by ahmadsay** [thestonefox/VRTK#1934]
Hi all. I long have to say it, and now hands reached. I don't know, it's my inefficiency or something else, but i have some problems:

Impossible to use VRTK Manager for controllers, i.e pointers not visible, always. One exception. If the instances were taken from VRTK example scripts and paste in my current scene it sometimes works.  it's so strange, MISTIC. 

If a scene has some UI object, pointers don't work so often, and if this UI object big, for example, a canvas, it's will never work.

Very often, if pointers work, there can't interact with UI buttons, slider, and e.t.c.

I use:

Htc Vive
Unity 2018.2.14.f1
VRTK Release 4.0 from GitHub
SDK: SteamVR v 1.2.3

Thank's for answers! And sorry for my English. I really look for a solution.

**Comment by thestonefox** [comment]
V4 isn't ready. Use GitHub master which is v 3.3
