### ISSUE TITLE
Is it Possible to make a dock with the current code?

### ISSUE THREAD

**Issue by sbmhome** [thestonefox/VRTK#196]
Sorry, about where this is posted, I don't know how else to get in contact with anyone expertly familiar with the toolkit ....which is just AWESOME!

I want to make a dock that can hold 1 item. This has driven me nuts for the past couple of days

If its empty, and a controller touches it with no Intractable object (then grabs) attached nothing happens.
If its empty, and a controller touches it with a intractable object attached (then grabs) it should be place in the dock.

if dock has item and controller touches (then grabs) it with no Intractable object attached, controller gets item, dock gets empty.

if dock has item and controller touches (then grabs) it with a Intractable object attached, controller gets item, dock gets item from controller.

Is this possible to build on the current code to create that kind of functionality? I've made hacks that have it almost working, but I want to make it the correct way.

**Comment by thestonefox** [comment]
Would this other issue be a solution to your problem?

https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/90

The concept of having snap points on another object?

**Comment by sbmhome** [comment]
Yes that would be.

If possible, It would be good to give the option to snap the grabbed object to another...and release on snap....or they get snapped together and the grabbed object is still attached to the controller.


Regards,
Steve

**Comment by koffertje** [comment]
im looking forward to this one.

**Comment by thestonefox** [comment]
@koffertje this is something I wanted to work on this week, it's scheduled for the 2.2.0 release anyway. I have a couple of ideas how this could work.

**Comment by xx1guardian1xx** [comment]
Any word of this? as 2.2 is out but I can't find it in the documentation. :/ @thestonefox

**Comment by thestonefox** [comment]
this also didn't make it into 2.2.0 release

**Comment by thestonefox** [comment]
Resolved with
https://github.com/thestonefox/VRTK/pull/670
