### ISSUE TITLE
Ask for help! [VRTK4]

### ISSUE THREAD

**Issue by smallcoderofme** [thestonefox/VRTK#2144]
I have a large scene, I need to be able to quickly set the user's coordinate position to some hot spots in the scene, what should I do?
Is there a way to reset the position of the HeadsetAlias?
MomentProcess seems to record transform position  information, is there a way to reset it?

[The teleporter method cannot be achieved because the distance is too far, I want to achieve it by setting the transform  position]

**Comment by thestonefox** [comment]
Please use the discord channel for general help: http://community.vrtk.io/
