### ISSUE TITLE
get stuck in solid object with the teleport

### ISSUE THREAD

**Issue by RGaleckio** [thestonefox/VRTK#2145]
i have a problem i created this ability of teleportating its like an istant dash for a 2 D game the ptoblem is tath i can stuck in wals or ground using the ability how can i prevent this thing
<img width="499" alt="problem" src="https://user-images.githubusercontent.com/114004868/191290232-bcce9ff1-f26a-4311-b545-2d1ab675f360.PNG">

**Comment by thestonefox** [comment]
use the discord channel to discuss issues http://community.vrtk.io/
