### ISSUE TITLE
[Suggestion] Adding item labels to example scenes.

### ISSUE THREAD

**Issue by baemoth** [thestonefox/VRTK#215]
Would it be worth it to go through the example scenes and add label prefabs to the objects? Like in 014, it could be useful to have them labeled by the snap type and such?

**Comment by thestonefox** [comment]
Yeah good idea.

Also worth probably making all of the buttons consistent, so grab is always grip (not a switch between trigger and grip as it is now)

**Comment by baemoth** [comment]
I'm very new to Git, but if there's a way for me to do this to help improve the tk I'm up for it.

**Comment by thestonefox** [comment]
@baemoth you can fork the repo, pull down your local branch, makes changes then create a PR.

If it's all a bit daunting then don't worry about it, I'll get round to it at some point :)

**Comment by thestonefox** [comment]
Merging into https://github.com/thestonefox/VRTK/issues/763
