### ISSUE TITLE
Hold one object with 2 controllers

### ISSUE THREAD

**Issue by koffertje** [thestonefox/VRTK#225]
as the title says,
one object, 2 controllers. (hold the object left and right).

**Comment by xEvoGx** [comment]
Actually yea, especially if you wanted to simulate holding a larger weapon such as a rifle. In fact, **RawData** does a neat thing that if you hold the sword with two hands, it aligns the hands as such that it looks like a correct two-handed sword hold.

**Comment by xx1guardian1xx** [comment]
Any Idea when this will release?

**Comment by thestonefox** [comment]
You can check the progress of issues on the issue tracking board

https://waffle.io/thestonefox/SteamVR_Unity_Toolkit

**Comment by WildStyle69** [comment]
This is a great idea - was also thinking that some objects can only be lifted with two controllers, i.e. heavy items.

**Comment by xx1guardian1xx** [comment]
Any word of this? as 2.2 is out but I can't find it in the documentation. :/ @thestonefox

**Comment by thestonefox** [comment]
it didn't make it into 2.2.0

**Comment by xx1guardian1xx** [comment]
Ah bugger same for the other one I guess, cheers anyway!

**Comment by thestonefox** [comment]
They're climbing up the list though :)

Someone has just made an inventory system for their game, they may be doing an PR of the work.

**Comment by xx1guardian1xx** [comment]
That's good to hear, I've tried messing around to get it to work but usually ends in tears.
I do like the idea of the snap system though so can't wait :) 

Thanks again for making such an amazing TK!

**Comment by xEvoGx** [comment]
Ah sorry Stone this is what I was talking about, and duh, I see now it's backlogged on Waffle.

Phew saved me from being that guy and posting a second issue on it 😜

**Comment by thestonefox** [comment]
This will be linked to #31 as a new "second controller grab action" will be added to an interactable object, determining what happens when a second attempts to grab an already grabbed object
