### ISSUE TITLE
Allow for providing haptic feedback strength in a range from 1 to 100

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#240]
at the moment the haptic feedback strength is from 0 to 3999 but it's confusing to use as anything under 200 doesn't even register.

It would be better to take a value of 1 to 100 and then convert that into the 0 to 3999 range

**Comment by carlosdp** [comment]
If you do this, maybe create another function with `Raw` at the end that accepts the original 0 - 3999 range for anyone that wants more fine-grained control for whatever reason.

**Comment by OmegaJak** [comment]
While this is a great idea and would be trivially easy to implement, my concern is how we'd manage the change. If people don't realize the change was made, and they're still calling the function with a strength of 1000, they may be confused why it's suddenly full strength. Should we just log a warning that the strength was over 100? Rename & deprecate? How is this usually done?

(If you have a good solution maybe it should be added to the guidelines for other changes?)

**Comment by thestonefox** [comment]
Yeah i agree with your point.

I'm still unsure whether this feature is totally worth it. It's on the back burner for the moment.

**Comment by thestonefox** [comment]
I think this is going to be more necessary now that the Oculus SDK is being supported.

Oculus SDK takes a float from 0 to 1 to determine strength. I currently just still allow the 0 to 3999 value and convert that to the 0 to 1 representation but it's now more confusing for different SDKs.

I think having the strength as a percentage from 0 to 100 is the right way forward and then this is interpreted between the min/max value of the relevant SDK.

**Comment by bddckr** [comment]
> I think having the strength as a percentage from 0 to 100 is the right way forward and then this is interpreted between the min/max value of the relevant SDK.

The general way to do percentage based stuff is with a float from 0 to 1, just like Oculus does. I vote for 0 to 1, instead of 0 to 100.

**Comment by thestonefox** [comment]
i would agree that 0,1 is the better way of doing it and represent it with a slider in the inspector

**Comment by thestonefox** [comment]
Done with https://github.com/thestonefox/VRTK/commit/c0fba69b64cb3c6d521a4240ab550b7afa16b1ab
