### ISSUE TITLE
Emit an event when a controller is looked at

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#241]
It would be really useful to know when the controllers were being looked at by the headset so other actions could be triggered (like showing tooltips only on glance)

**Comment by wheatgrinder** [comment]
One approach for this is to use a ray cast to detect when you hit the desired object and then do the desired thing.  Cast the ray from the "eye"  as that makes the most sense to me.

**Comment by thestonefox** [comment]
Quick PR to demo the concept:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/245

**Comment by carlosdp** [comment]
@thestonefox I finished this before I saw your PR, but figured I'd put it up anyways =P. Take a look as I made generalized Gaze Detection for any GameObject, which could be useful for gazes at things other than the controllers as well.

**Comment by thestonefox** [comment]
@carlosdp thanks for the PR

We were talking about this on the slack channel last night. Even my PR may be a bit redundant.

You can already use the Simple Pointer on the headset to cast a ray, it's just the controllers by default don't have a collider and are set to "Ignore Raycast" to prevent you from teleporting to your own controller and stuff like that.

But the discussion seemed to lean towards not trying to add another mechanism and see if the existing pointer mechanism could be updated to allow for this.
