### ISSUE TITLE
See representation of navmesh when teleporting

### ISSUE THREAD

**Issue by deedgeoakley** [thestonefox/VRTK#251]
Thanks so much for this toolkit, it has been a godsend. I was wondering about if there is a way to see a representation of the nav mesh when teleporting?

**Comment by thestonefox** [comment]
There is a way of representing the nav mesh in this repo:

https://github.com/Flafla2/Vive-Teleporter

They use a special `Vive Nav Mesh` class to render it accordingly

**Comment by thestonefox** [comment]
You could use Destination Points as the area to resolve this too
