### ISSUE TITLE
touchpad to rotate grabbed object

### ISSUE THREAD

**Issue by gregdowning** [thestonefox/VRTK#254]
I am building an experience where I would like users to be able to pick up objects for close inspection. The snapping methods still make turning the objects over a bit awkward. 

I would like to be able to use the touchpad to rotate an object on at least 2 axis. I took a look at "[015_Controller_TouchpadAxisControl - Examples Tour -](https://www.youtube.com/watch?v=ErSxZlZh6fc&index=17&list=PLRM1b2lKjTbdFJtYv_SNAb3NvYp-Gl7nZ)" with the remote control car and it looks very close to what I would like to do, I just want to be able to rotate the grabbed object rather than the remote car. Seems like all the pieces are there but I can't figure out how to put them together into a feature. Can anyone give me advice on modifying what exists or add this as a feature request?

**Comment by thestonefox** [comment]
if you write a script that sits on your controller that listens for the touchpad axis change (to get the x,y value of the touchpad touch position), and also includes a reference to the Interact Grab script on the controller, then when the touchpad axis changes, then call `GetGrabbedObject()` from the Interact Grab script.

This will return you the object you're holding (or null if you're not holding anything)

Then you can just update the rotation of that object based on whatever position of the touchpad you want. E.g. if the y axis is up (you're touching up) then rotate the object upwards.

You may want to look into the `Quaternion.AngleAxis` method to prevent gimbal lock with your rotations.

**Comment by dpmorrow** [comment]
Currently `VRTK_InteractableObject.GrabAttachType.Track_Object` causes any rotation to the grabbed object to be reset.  Looking for a way around this as it works better for me than other modes due to physics needs.

**Comment by thestonefox** [comment]
@dpmorrow  is your issue related to the main issue that you've posted in?

It seems like a separate issue. Also, I'd recommend looking at NewtonVR as they use a track object mechanic and I think they may have resolved the auto rotation on grab issue.

**Comment by dpmorrow** [comment]
@thestonefox I suppose it could be considered a different issue, but it seemed like I was trying to accomplish the same thing as this user.  An interface that allows touchpad button presses to rotate the grabbed object.  Furthermore I'm essentially using your prescription above and that is when I'm encountering the problem with the rotation being reset, probably every FixedUpdate.

I can make a separate issue if you want and I'll check NewtonVR since the grab mechanics and interactions physics-wise are pretty crucial in my game.  However, I'm certainly interested in any guidance on how to change rotation with a tracked object without it being reset by the next FixedUpdate.

Thanks again for the quick reply!

**Comment by dpmorrow** [comment]
I was actually able to get something that seems to work consistently by ungrabbing, rotating, and then moving the block to the attachment point and doing an AttemptGrab after a brief delay.

Just thought I'd share.  Warning though, you'll need to prevent rotation through other collidable objects!

**Comment by thestonefox** [comment]
I'm pretty sure NewtonVR solved this rotation issue. It's definitely worth checking out their repo to see if they have a solution.

**Comment by poopledoople** [comment]
This is something we're looking for as well in our own project. It'll be great if VRTK has this option.

**Comment by kristianpd** [comment]
This is a rather old issue. I'm trying to understand what this does beyond just rotating the controller to look at the object, to me a more intuitive behavior. 

I'm not saying this may not be useful for some games, but at first glance it appears to be a little specific for VRTK core.

I'm trying to clean up the issue list of issues that aren't likely to get worked on right now. Should we close this?

**Comment by reznovVR** [comment]
Maybe it was not as easy back then but I think the latest VRTK versions provide enough events and methods to implement this feature easily in the desired projects. I also suggest closing this unless someone has suggestions or examples of more generic use cases of why this should be implemented in the core features.

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522
