### ISSUE TITLE
Get logo for Toolkit

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#292]
I'd like a logo that people can use to show off that they've used the toolkit (if they want) on their games/apps/whatever.

**Comment by thestonefox** [comment]
@sdouglas 
![image](https://cloud.githubusercontent.com/assets/1029673/17040842/045c93b2-4f9a-11e6-9d0f-3510c25f1f9f.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17040847/0d25507e-4f9a-11e6-8755-24be257b20bf.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17040852/215988f8-4f9a-11e6-8f44-bdbcd7a32d30.png)

**Comment by thestonefox** [comment]
@Blueteak 

![image](https://cloud.githubusercontent.com/assets/1029673/17040897/5848cbe4-4f9a-11e6-96fd-5264345aec13.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17040910/6b58db98-4f9a-11e6-8a38-5cc68e613062.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17040917/7acb0222-4f9a-11e6-8a54-add3e82b2d19.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17040927/8871a46c-4f9a-11e6-9f84-675f68ab1574.png)

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/17040971/c091c5a2-4f9a-11e6-9812-5f08e3e6a43a.png)

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/17040974/c7375f98-4f9a-11e6-8b79-77c33bbdbf0b.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17040977/cafbe7de-4f9a-11e6-89fa-215b600a2234.png)

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/17040986/d4120c4a-4f9a-11e6-9878-43e058a8dd72.png)

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/17040990/daab28e8-4f9a-11e6-8985-92abd2d82e72.png)

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/17041001/e339cd98-4f9a-11e6-8936-34f528ffb8f1.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17041005/e716efc2-4f9a-11e6-8e49-269234e62527.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17041011/f8c267ec-4f9a-11e6-8f6e-d7677063d119.png)

![image](https://cloud.githubusercontent.com/assets/1029673/17041014/fc8bd8ae-4f9a-11e6-8090-cfe60f6414fc.png)

**Comment by xEvoGx** [comment]
You should number them so they're easier to talk about, but so far I like this one the most. Feels professional, and you can play around a little with the box/gear/controller positioning.

https://cloud.githubusercontent.com/assets/1029673/17040986/d4120c4a-4f9a-11e6-9878-43e058a8dd72.png

Then second would be this one, again simple and confident, without the need to say or show more. 

https://cloud.githubusercontent.com/assets/1029673/17040971/c091c5a2-4f9a-11e6-9812-5f08e3e6a43a.png

Perhaps you could try the font for VRTK in the second one and combine it with the first?

Cheers Stone

-Steven

**Comment by thepolypusher** [comment]
![image](https://cloud.githubusercontent.com/assets/6298677/17041162/0229ac2e-4f59-11e6-91c4-5513f0f2a1f5.png)
Im a fan of this one.

**Comment by thestonefox** [comment]
@xEvoGx I added numbers to them now :)

**Comment by thestonefox** [comment]
Maybe it's a good idea for people to vote under the one they like?

**Comment by mcguinnessdr** [comment]
![vrtk_logo](https://cloud.githubusercontent.com/assets/2281608/17041284/efb60a46-4f59-11e6-9ac3-30f6dd063bc9.png)
I agree with xEvoGx, did a quick mock up.

**Comment by xEvoGx** [comment]
Nice @mcguinnessdr and sweet thanks Stone!

**Comment by mattboy64** [comment]
I'd loose the "powered by." That gives me a CryEngine type vibe. I like @mcguinnessdr's addition, but I think it could use some hammers or screwdrivers or something. Maybe like this:
![vrtk](https://cloud.githubusercontent.com/assets/7003769/17043538/6a821654-4f6c-11e6-83de-c463d652c857.jpg)

**Comment by 10FingerArmy** [comment]
Wow these are some really cool ideas! Don't have a favorite yet but I'd try to not focus on the Vive controller in any of them but more on (abstract) glasses.

Maybe in a not too distant future we might very well support Oculus as well and the Touch inputs (revive shows how interoperable both devices are, so getting this abstraction into the toolkit is probably not so hard).

So if I had to pick a logo potentially the @mattboy64 one but put VR glasses inside the cog.

**Comment by hovissimo** [comment]
Backing up 10FingerArmy's point, the next generation SteamVR platform may use a controller of a different shape.

**Comment by shawnmcclelland** [comment]
Saw the reddit thread and thought I'd offer up a few designs.

![abstract inside](https://cloud.githubusercontent.com/assets/7469168/17273504/d44f0190-5684-11e6-94ec-53c126ba2e6a.png)
![abstract outside](https://cloud.githubusercontent.com/assets/7469168/17273508/d4525642-5684-11e6-8d57-c8aa72dce2cb.png)
![cube dark](https://cloud.githubusercontent.com/assets/7469168/17273506/d44fe9fc-5684-11e6-96d3-2359259efb85.png)
![cube light](https://cloud.githubusercontent.com/assets/7469168/17273505/d44f90d8-5684-11e6-8943-684bee35411c.png)
![roboto inside](https://cloud.githubusercontent.com/assets/7469168/17273507/d451be58-5684-11e6-8537-7c0084ab0488.png)
![roboto outside](https://cloud.githubusercontent.com/assets/7469168/17273509/d45b42c0-5684-11e6-8baa-12447fd494a4.png)

**Comment by shawnmcclelland** [comment]
![steam vr toolkit](https://cloud.githubusercontent.com/assets/7469168/17274018/f8c0891c-5699-11e6-901d-94746c6cde9c.png)

One more this time using the Steam logo since this is the Steam VR Toolkit.

**Comment by shawnmcclelland** [comment]
Another quick test with the Steam logo this time.

![steam vr toolkit](https://cloud.githubusercontent.com/assets/7469168/17274029/cb100708-569a-11e6-8bed-1091e68dca6b.png)

**Comment by shawnmcclelland** [comment]
More generic headset tests.

![headset outline text below](https://cloud.githubusercontent.com/assets/7469168/17277875/de620438-571b-11e6-89ba-555bb356571a.png)
![headset outline text mixed](https://cloud.githubusercontent.com/assets/7469168/17277871/de591058-571b-11e6-9287-bc24fd8bd0c9.png)
![vrtk headset below](https://cloud.githubusercontent.com/assets/7469168/17277872/de596b20-571b-11e6-97c1-791665e1111a.png)
![vrtk headset filled](https://cloud.githubusercontent.com/assets/7469168/17277873/de5afa12-571b-11e6-9270-305bc74dd503.png)
![vrtk headset inside](https://cloud.githubusercontent.com/assets/7469168/17277874/de5c0f1a-571b-11e6-97c3-9b90585c3bd4.png)
![vrtk headset outline](https://cloud.githubusercontent.com/assets/7469168/17277876/de78ea86-571b-11e6-9b8b-41cec150df3b.png)

**Comment by Blueteak** [comment]
Minimalist Style
![vrtklogo](https://cloud.githubusercontent.com/assets/10412514/17278619/d7136a68-5726-11e6-94a3-1f6394ac0263.png)

**Comment by thestonefox** [comment]
@shawnmcclelland I like the headset idea. I also like the logo that @Blueteak posted.

Is there some way of getting the two to work together?

Something like this perhaps?

![image](https://cloud.githubusercontent.com/assets/1029673/17299576/d2cbd14e-5806-11e6-80e2-58f1f60f58e1.png)

**Comment by shawnmcclelland** [comment]
@thestonefox - should be possible to play around with a few different iterations using those combos.

**Comment by xEvoGx** [comment]
Huge fan of Blueteak's version...

...not a fan of having the HMD background. You lose the elegance of the minimalism (though I'd still go with blue rather than lavender)

**Comment by thestonefox** [comment]
@xEvoGx The purpose of the addition to @Blueteak 's logo submission is to differentiate it from the source logo (the actual logo is from a 3rd party design site, i've asked the author if it's ok to use it but not heard back yet).

**Comment by HyppoNymous** [comment]
This one looks simple and good 
[https://cloud.githubusercontent.com/assets/1029673/17040971/c091c5a2-4f9a-11e6-9812-5f08e3e6a43a.png](url)

**Comment by lordvard** [comment]
![vrtk](https://cloud.githubusercontent.com/assets/11387435/17733801/a690a4f0-6478-11e6-967d-0d46191cbc78.png)

**Comment by mattboy64** [comment]
This is a modified version of @Blueteak's design from the slack channel:

![vrtk4_4](https://cloud.githubusercontent.com/assets/7003769/17789179/d9c27aec-6545-11e6-9b1a-2798f13db871.png)

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/17812031/3b10d924-661d-11e6-8a3a-aa0a4e433bb4.png)

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/17812040/4f0666e2-661d-11e6-84d1-a5dee45c5a96.png)

**Comment by imukai** [comment]
My little attempt.

![vrtk_logo](https://cloud.githubusercontent.com/assets/13815077/17881336/95b72d6c-68d2-11e6-8e88-f1fcdb64594c.jpg)

**Comment by imukai** [comment]
And another.  Mine with additional input by @Blueteak 

![vrtklogo3](https://cloud.githubusercontent.com/assets/13815077/17906052/98e50e52-6943-11e6-9653-e759c535159e.jpg)

**Comment by neilsutcliffe** [comment]
Hello

![vrtk logo 1](https://cloud.githubusercontent.com/assets/13319277/18028873/9df76e90-6c80-11e6-8c3d-d68d08c4c66d.png)
![vrtk logo 4](https://cloud.githubusercontent.com/assets/13319277/18028874/9fce0d00-6c80-11e6-9aee-2759ed374e1f.png)
![vrtk logo 2](https://cloud.githubusercontent.com/assets/13319277/18028876/a27f7d86-6c80-11e6-87e7-048752ea7b7e.png)
![vrtk logo 3](https://cloud.githubusercontent.com/assets/13319277/18028878/a6f44b9e-6c80-11e6-8346-9af35bb1c72c.png)
<img width="849" alt="vrtk best" src="https://cloud.githubusercontent.com/assets/13319277/18028898/f1077a62-6c80-11e6-9e85-ed88a5fa476e.PNG">

**Comment by neilsutcliffe** [comment]
![vrtk tool](https://cloud.githubusercontent.com/assets/13319277/18028953/6e495940-6c82-11e6-9c22-51c1d226bc6c.png)

**Comment by neilsutcliffe** [comment]
![vrtk logo alt](https://cloud.githubusercontent.com/assets/13319277/18028994/a6713af8-6c83-11e6-95ca-8820b4081446.png)

**Comment by imukai** [comment]
![vrlogo4](https://cloud.githubusercontent.com/assets/13815077/18032541/a37c5c2c-6cd5-11e6-82ce-b77681505629.jpg)

**Comment by getwilde** [comment]
![vrtk logo 4](https://cloud.githubusercontent.com/assets/13372931/18962851/ab2c7a7e-862f-11e6-8c27-ed9363f58f20.png)

**Comment by getwilde** [comment]
![capture](https://cloud.githubusercontent.com/assets/13372931/18966906/63d34b60-8640-11e6-82ab-c1a7dbdb7405.png)

Crop and color ideas by a-real-dinosaur

**Comment by getwilde** [comment]
![capture](https://cloud.githubusercontent.com/assets/13372931/18967116/4392f44e-8641-11e6-957a-21222d5e133e.PNG)

Didn't get around to color...

**Comment by getwilde** [comment]
![vrtk logo 4](https://cloud.githubusercontent.com/assets/13372931/18967193/926a1ab6-8641-11e6-8a08-27ecf8a512d4.png)

**Comment by thestonefox** [comment]
Robotty idea

![image](https://cloud.githubusercontent.com/assets/1029673/19016787/54c69d4c-881c-11e6-9545-a5f3df102c7d.png)

**Comment by getwilde** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/13372931/19166037/4c6d2620-8bc3-11e6-9ff6-6a710d35b883.png)

**Comment by thestonefox** [comment]
@getwilde awesome, can you also do the silhouette logos as well with the pig in vector format?

**Comment by getwilde** [comment]
![image](https://cloud.githubusercontent.com/assets/13372931/19377792/2c8f9f98-91a6-11e6-82dc-6391c5ddb303.png)

Here's the silhouette.  Don't use this for small icons at 64x64 or less!  I'll upload raster-based icons at several resolutions.

[VRTK Logo - Flying Pig - Silhouette.pdf](https://github.com/thestonefox/VRTK/files/528812/VRTK.Logo.-.Flying.Pig.-.Silhouette.pdf)

**Comment by getwilde** [comment]
![vrtk logo - silhouette - 16x16](https://cloud.githubusercontent.com/assets/13372931/19380119/e54c3a44-91b2-11e6-83af-b18b6cd442c3.png)


![vrtk logo - silhouette - 24x24](https://cloud.githubusercontent.com/assets/13372931/19380118/e544089c-91b2-11e6-85a4-ceac5244ab56.png)
![vrtk logo - silhouette - 32x32](https://cloud.githubusercontent.com/assets/13372931/19380113/e53d55ba-91b2-11e6-8d6d-f45adb92d916.png)
![vrtk logo - silhouette - 48x48](https://cloud.githubusercontent.com/assets/13372931/19380114/e53ee858-91b2-11e6-84bb-3d26281c1ac6.png)
![vrtk logo - silhouette - 64x64](https://cloud.githubusercontent.com/assets/13372931/19380116/e53feda2-91b2-11e6-8284-7be88832494b.png)

Here are small raster-based icons.

**Comment by gpvigano** [comment]
After posting a comment in #659 I noticed I am the only one who dislike this logo (thus I removed my comment).
Anyway I leave my comment here, it will be entrusted to the memory of posterity...   ;-)

> I really dislike this logo, any other logo proposed before would be really better. A pig is often related to rubbish, not suitable to a valuable software toolkit like VRTK.
