### ISSUE TITLE
Grab to scale object with both controllers (like pinch to zoom effect)

### ISSUE THREAD

**Issue by mimminito** [thestonefox/VRTK#31]
Implement the ability to grab an object with two hands to scale and rotate that object.

**Comment by thestonefox** [comment]
Nice idea, may have to make a separate grab script to implement this.

**Comment by gregdowning** [comment]
I would like to do this too. I saw that google daydream presented it in a feature they are calling "stretch to scale."

**Comment by thestonefox** [comment]
May have a go at implementing this soon

**Comment by gregdowning** [comment]
Great!

**Comment by rob100** [comment]
Even the grabbing of an object with two controllers would be great. This could be very useful to simulate a heavy object for that it is required to use both hands to grab it.

**Comment by MrJimbones** [comment]
I would like to second @rob100 's idea on this one. Chainsaws baby! ;D

**Comment by baemoth** [comment]
Focal point on the asset store does this, maybe have a look at how they implemented it? Link: https://www.assetstore.unity3d.com/en/#!/content/59625

**Comment by thestonefox** [comment]
@baemoth good link, has some good references in

**Comment by stitchlips** [comment]
I would love to see this. I have tried the focal point script and it works, kind of. It seems really touchy and only focuses on one game object. Would be a great feature!

**Comment by felix330** [comment]
I'd also love to see the ability to grab an object with both hands. Scaling aside, it should be possible to implement this for joint-based grabbing just to have things like rotation using 2 hands. (like when grabbing a wheel etc)

**Comment by thestonefox** [comment]
This will be linked to #225as a new "second controller grab action" will be added to an interactable object, determining what happens when a second attempts to grab an already grabbed object
