### ISSUE TITLE
Room Extender 'Extended Volume' Not Displaying

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#316]
I commented in the original issue to avoid creating a new one, but now I'm not certain it was received (since it was indeed closed) so I'm posting a new issue. Here's the original comment:

> 
> Not sure if it's worth reopening in case it's something I'm doing/not doing, but simply loading the scene 028 ...RoomExtender, I do not see the Room Extension Gizmo, SelectedOnly on nor off.
> 
> Again nothing special, just loading the scene, so one would expect to see it no?
> 
> Thanks!
> 
> -Steven

**Comment by thestonefox** [comment]
That's weird, I see it fine for me (as can be seen in this vid https://www.youtube.com/watch?v=qcBr6VWrRmo)

I was using Unity 5.3.5f, which version are you using?

**Comment by xEvoGx** [comment]
Yea no clue what could possibly be up, but I was on the latest 5.3.x version before now moving onto 5.4.x, same deal. 

Is it possible there's a setting in Unity I for some reason would have checked off/on?

**Comment by thestonefox** [comment]
can you try pulling down the latest version and going to the scene (maybe record a video of the steps) just to see if there is anything different?

**Comment by xEvoGx** [comment]
Okay no video (though you can imagine all I did was simply create a New Project, then imported the latest of both _SteamVR_ and _VRTK_, then launched the **028_CameraRig_RoomExtender**) but here is a lovely pic showing all the vitals!

![steamvrtk_noextendervolume](https://cloud.githubusercontent.com/assets/11222937/17349611/13662cfc-58e5-11e6-80aa-c8a5013cb6d3.JPG)
