### ISSUE TITLE
Store objects in an inventory

### ISSUE THREAD

**Issue by RoccoGD** [thestonefox/VRTK#32]
A little inventory function like in Budget Cuts would be very nice.

https://i.ytimg.com/vi/ybvMDaoStcM/maxresdefault.jpg

**Comment by RoccoGD** [comment]
Since there is no response so far, i don't know if this functionality is out of scope for the toolkit, but if not it will be a huge benefit for all kind of games in my opinion.

**Comment by drifio** [comment]
At the very least we could have an example scene with an example implementation, even if it is outside the scope of core functionality.

**Comment by thestonefox** [comment]
It's something I'd like to provide an example of.

**Comment by baemoth** [comment]
Could this be done with a sort of "belt" like in vanishing realms that could have "anchor" points where you could drop items? I'll try and see if I can do something like this.

**Comment by thestonefox** [comment]
Yeah there are definitely cross overs.

I believe someone in the slack channel said they are working on an inventory system.

**Comment by thestonefox** [comment]
The Snap Drop Zones PR will allow you to tether dropzones to your body or controller.

I would say it resolves this issue:

https://github.com/thestonefox/VRTK/pull/670
