### ISSUE TITLE
New 3D control: Lock

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/VRTK#388]
There should be a control that can simulate a lock with either key or number combination unlock.

**Comment by kristianpd** [comment]
I am proposing we close this issue. Each lock is so different that it's going to be a custom job anyway. It's also fairly easy to build with simple Touch events. I think this should be closed

**Comment by reznovVR** [comment]
Seems kinda project specific feature. I can see it being useful to many but I would rather see this as a wip/ready PR from someone who actually needs/used a lock in their game instead of a generic idea "issue". I also suggest closing this until then.

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522
