### ISSUE TITLE
Scaling [CameraRig] breaks SimplePointer and BezierPointer

### ISSUE THREAD

**Issue by phr00t** [thestonefox/VRTK#389]
In my app, if SteamVR is active, I scale up the CameraRig to better fit the scene in the player's room. Unfortunately, the simple pointer (and resulting basic teleportation) doesn't account for this scale. If I scale up the CameraRig 50%, the pointer will be ~50% longer than it needs to be -- causing teleports to overshoot the intended destination.

**Comment by thestonefox** [comment]
Ok i'll take a look a bit later and see if there's a workaround or a fix

**Comment by thestonefox** [comment]
Ok so I have a work around.

If you scale the camera rig up by a percentage, then scale the `WorldPointer_SimplePointer_Holder` down by the same percentage:

e.g. CameraRig is (2, 2, 2) so the [Controller (right)]WorldPointer_SimplePointer_Holder should be scaled to (0.5, 0.5, 0.5) to offset the effect.

**Comment by phr00t** [comment]
Are you going to implement something in the code to address this, or just instruct users like myself to implement the workaround? Wondering if I should do something on my branch, or wait for something official from you.

**Comment by thestonefox** [comment]
I'm not entirely sure of a fix within code.

I don't want to have it hard coded so the pointers are checking for changes in sizes of their parents (as the pointers may actually be connected to things that aren't controllers).

I'll keep thinking about it. If you do come up with a good generic solution, then let me know! :)

**Comment by thestonefox** [comment]
Another solution someone just suggested (which seems to work quite well).

Is not scale the camera rig, but put all of your world objects in a parent game object and scale that down (or up)

**Comment by phr00t** [comment]
This is how I solved it on my branch:

https://github.com/phr00t/SteamVR_Unity_Toolkit/commit/bf0ba5621377a5a5097f65e03d3aeb2d1984eefb

I just call that new function with the counteracting percent at the same time I scale my CameraRig. Works like a charm.

**Comment by thestonefox** [comment]
Yeah that works for the simple pointer, but for the bezier pointer it wouldn't work :(

i need to find a more generic solution

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/7e4cd637bc18949e8e7ced79c7aae8143c37bda9
