### ISSUE TITLE
Moving Platforms (Elevators, etc)

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#395]
Another core tool that might prove useful is allowing the player (playspace) to be moved along by an object, such as an elevator (**The Gallery: Call of the Starseed**), in-game vehicle where the player can embark/disembark at will (**Hover Junkers**) such as a boat or spaceship and so-on. Ideally there's an option toggle on/off _inheriting_ the motion of the vehicle (boat sway) as well. 

Thanks!

**Comment by HyppoNymous** [comment]
You can do it moving the [CameraRig] object with your own code script.

**Comment by xEvoGx** [comment]
Boy aren't you a party pooper! Three for three Hyppo :smile: 

Yes I'm aware **all** of what I've been suggesting to date can be done with _my own code_, including this whole toolkit. This here is merely another suggestion along with the multitudes that have already been suggested and implemented. Clearly people are going to want to have moving platforms of a sort in their games, so this seemed like a general/global enough of a suggestion to add to the kit.

Cheers man

**Comment by 10FingerArmy** [comment]
I will actually have an elevator in my current project so if I come across something generic I will do a PR for it :-)

**Comment by xEvoGx** [comment]
Sweet! Thank you 10Finger!

**Comment by smygarn** [comment]
Now this is getting interesting because it's a natural part of my game. It's important to inheritate the speed from the platform. 

Also try throw objects on a moving platform. This is also why a tracked object behaves more realistic than the other options in VRTK.

**Comment by xEvoGx** [comment]
Were you guys simple deriving the translation/rotation of the moving platform and applying it to the [CameraRig] or were you successful in using physics? 

I wondered if VRTK PlayerPresence would help in this? If not, would the player fall if stepping off the platform (as happens in the Climbing example when you step off any ledge)?

**Comment by HyppoNymous** [comment]
I think the simple way is like you said inherit  the translation/rotation and apply it to the base VR object.

**Comment by thestonefox** [comment]
I think the new Player Body Physics (Player Presence) PR should resolve this.

If you're naturally being pushed upwards by a floor and naturally falling to the nearest floor then this would work.

In fact the existing Player Presence script would probably resolve this.

However, this is only for elevator style platforms. Thinigs that move in forward/left+- directions wouldn't apply physics to you, they would slide around under you. One fix for this would be to child the camera rig to the platform (or just apply a `follow` script similar to the ferris wheel seats in Funfair)

The final thing is what do do when throwing something. The objects on throw need to have the play area velocity added to them as well, I believe someone did a PR for this, it's just waiting on the new Player Body Physics stuff to be implemented first.

https://github.com/thestonefox/VRTK/issues/603

**Comment by amandaelinn** [comment]
Hi @thestonefox, is this something that is currently being worked on?

I am trying to get a drive-able car working. I also want the player to be able to interact with items that are inside the car. I ran into some issues though.

There is more info about this issue including a video on the Unity Forums thread that I posted:
[VRTK-Interacting with Object while Moving](https://forum.unity3d.com/threads/vrtk-interacting-with-object-while-moving-issue.443874/)

Maybe if you or someone could point me in the right direction or even just let me know if it's being worked on (or not possible to do yet), that would be great. Thank you!

**Comment by thestonefox** [comment]
@amandalinn what's happening to the collider when you're moving? If you look in the scene view is it becoming detached from the object? Or at least displaced.

Also check what's happening on the colliders on the controller. Are they displacing?

**Comment by amandaelinn** [comment]
@thestonefox  Thank you for such a quick response!

I am not sure if I am able to see what is happening in the scene view since the car and game camera are moving (unless I am able to move the scene view with the car somehow?)

May I send the project folder over to you via email/message and you can quickly take a glance at it?

**Comment by thestonefox** [comment]
@amandaelinn if you want to zip up your project and put it on Dropbox or something then share the link then I'll try take a look (hopefully tomorrow)

**Comment by amandaelinn** [comment]
@thestonefox  Yeah, I can definitely do that.

What email should I send the link to? Sorry I couldn't find your email or where to message you (I'm new to github haha)

Also, no rush. I really appreciate you taking the time to look at it and also working on VRTK :)

**Comment by thestonefox** [comment]
You can use thestonefox at gmail dot com

**Comment by thestonefox** [comment]
Parenting the camera rig to an object or using body physics with height adjust teleporter resolves this.
