### ISSUE TITLE
handle to lever script

### ISSUE THREAD

**Issue by koffertje** [thestonefox/VRTK#411]
same as the door script where you can add handles. but this time for the lever script?

**Comment by 10FingerArmy** [comment]
I was thinking about that a bit as well. Could you elaborate on the expected behaviour? Should only the handle be grabbable?

**Comment by koffertje** [comment]
Hey.
I thin in the case when you add a handle. Only the handle ka grababble. When no handle is set specificly it behaves at it does now

**Comment by kristianpd** [comment]
This seems all doable to me right now? I think this issue should be closed.

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522
