### ISSUE TITLE
Non-Euclidean level tools?

### ISSUE THREAD

**Issue by kjm16** [thestonefox/VRTK#419]
This is more of a feature request, but I'm not sure where else to post so it'll get seen.

Will there be a way to easily design non-euclidean levels included in the toolkit? I feel like this would greatly expand the creative possibilities for roomscale.

**Comment by thestonefox** [comment]
Not sure what you mean? How would you envisage the toolkit help make non-euclidean?

**Comment by kjm16** [comment]
I'm not sure exactly, but maybe a script that calls on other levels that can be attached to walls that automatically detects when you're looking/interacting through them?

Here's an example of something that can be done with it: https://www.reddit.com/r/Vive/comments/4qioiu/i_created_a_noneuclidean_office_in_vr/

This guy was working on a vr level editor including it, not sure what happened to that project: https://youtu.be/1Fe9e5smHi8?t=1m25s
