### ISSUE TITLE
[Bug] 037 ClimbingFalling - Can Climb Down Into Geometry...

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#453]
...and fall out of the level and into the void. Pretty self explanatory, but if you'd like to see, grab any _climbable'_ and drag yourself into the ground...voila bye bye cruel world.

Never mind that I feel this extends Issue #407 , and would like some collision safety whilst mantling about

Cheers

**Comment by xEvoGx** [comment]
For a possible solution, we could **Raycast** downward from what would be the _Player Height_(the HMD) during a climb to determine if the player was pushing himself into the surface he is currently standing on (mind you we're not just talking about the ground, but any solid surface the player may stand on). 

We also have to take into account if the player is crouching, so doing cheap and dirty math in my head, If we're climbing, and there's a surface below us (Raycast), Y can only be a positive number. If Y is less than the starting value (player height upon initiating climbing), then the player is trying to go into the ground...reset position. 

Now this does bring up the issue of descending, such as down a ladder. Either you educate the player to lean over the edge a bit and then initiate the climb, or we have a threshold before the reset occurs; a grace period if you will before we force the position back to safety. This was players can start a descent, with the raycast likely detecting a -Y value initially before then being over open air (this is good) and they can climb down.

Thoughts?

**Comment by xEvoGx** [comment]
**Small Update:** 

Taking a quick look at the **VRTK_Player_Climb** script, during the initialization of the required scripts, this one...

`controllerManager = FindObjectOfType<SteamVR_ControllerManager>();
            var headCamera = VRTK_DeviceFinder.HeadsetTransform();
            collisionFade = headCamera.GetComponent<VRTK_HeadsetCollisionFade>();
            if (collisionFade == null)
            {
                collisionFade = headCamera.gameObject.AddComponent<VRTK_HeadsetCollisionFade>();
            }`

...clearly looks for the HeadsetTransform, yet when the scene is played, this component is added to the _Camera (eye)_. If you look at **017 ...TouchpadWalking**, _VRTK_Headset Collision Fade_ is assigned (correctly?) to _Camera (head)_. 

I'll try to test all this later today (I'm only perusing the scripts, away from my headset), but this sounds like a good reason why both this issue and #407 are having problems.

Cheers

**Comment by HyppoNymous** [comment]
`...and fall out of the level and into the void. Pretty self explanatory, but if you'd like to see, grab any climbable' and drag yourself into the ground...voila bye bye cruel world.`

How do you drag yourself into the ground ? 
If you climb some wall and release the climb object you just fall and land on the floor.

**Comment by xEvoGx** [comment]
As I said try it yourself, perhaps I'm crazy? I just grabbed and pushed myself down (raised my arm up) and I fell out of the world. 

Clearly I didn't imagine it :laughing:

**Comment by HyppoNymous** [comment]
> As I said try it yourself, perhaps I'm crazy? I just grabbed and pushed myself down (raised my arm up) and I fell out of the world. 
 
I didn't tried to raise the arm up while climbin to fall , i will give it a try. Like you said a raycast should correct the issue.

**Comment by xEvoGx** [comment]
Yea climbing is problematic still, and I'm hoping it gets addressed further at some point.

**Comment by thestonefox** [comment]
I'm sure it will get looked into. The dev behind the climbing stuff is just busy at the moment and I don't have time to look into this yet either. But the joy of open source means anyone can look into it if they have a solution :)

**Comment by xEvoGx** [comment]
Yea I've been wracking my brain now for  two days on how best to do this. There might be a larger problem so I'll do my best to be succinct here:

_VRTK Player Presence_ in and of itself does a fantastic job, as evidenced by **017 ...TouchpadWalking**. You bump into anything and you stop...no interpenetration. Lovely. My favorite part is crouch down under the steps, wiggling a bit inside then trying to stand up. Brilliant relocating back to your last safe spot. This is the benchmark right here that needs to be working in **037 ...ClimbingFalling**.

Now for a bit of sleuthing as to what is going on. In short, _isKinematic_ (on the RigidBody that is added to the **[CameraRig]**) being **true** (checked) allows for the headset to pass through geometry; _this is the culprit._ 

The reason this gets turned on is by _Falling Physics Only_ being **true** on the **VRTK Player Presence** component. Fine turn it off right? WELL...when you add the **VRTK Player Climb** component, ideally _Use Gravity_ will need to be checked on lest we immediately snap back to the ground upon letting go of a climbable, <inhales!>...

...thus _Use Gravity_ turns on _Falling Physics Only_ which turns on _isKinematic_...boom satisfying collision with geometry is gone.

Now just for one final small detail that may only be editor side; if I proceed to manually turn off _isKinematic_ in the Inspector while the scene is playing, the **[CameraRig]** begins falling through the world into the void. Perhaps if this is done through code rather than the Inspector, then this isn't an issue. If turning it off one way or or the other causes the entire rig to fall into the void, then there's yet another problem. You see, as with scene **017**, isKinematic is false when the scene first starts, and the Rig does not fall through the floor. Something wonky may be going on with the physics that might need addressing as well. Just a heads up.

Phew! Thanks for reading, and if TL;DR...Climbing is borked. :stuck_out_tongue_winking_eye:

**Comment by xEvoGx** [comment]
Oh and same thing happens when you add **VRTK_HeightAdjustTeleport** and check **Use Gravity**, though in that script there's a _Gravity Fall Height_ variable that isn't in _Player Climb_ (if that in fact this information is of any use).

Cheers guys

**Comment by HyppoNymous** [comment]
Good analysis, i hope we'll get a solid climbing.

**Comment by xEvoGx** [comment]
Yea me too...fun mechanic.

Either we fix **Climbing** to be physics based and leave _isKinematic_ out of it altogether (best solution)...

...or...

...have **Player Presence** work with both a _kinematic_ OR a _physics_ based solution, if this is even reasonable.

**Comment by HyppoNymous** [comment]
I think we should have the choice depending on the game we want to make, we could pick different scripts, some using physics others not.
Some VR games will stay simple without needingc limbing or advanced physics, while others can need physics to prevent such issues or issues with other physic objects in the 3D scene.

**Comment by xEvoGx** [comment]
Right exactly. Thing is with my project I'm moving away from teleporting, so having complete fluid movement is important (the climbing doesn't make me sick, and slow movements in game are fine). 

Forgetting VR sickness in all this, yea I'd like something that involves climbing that remains spatially consistent (again no teleporting). I can 'live' with the head fade during climbing if actual physical collision can't be solved, but it would be great if this was a tad more robust as you say.

**Comment by HyppoNymous** [comment]
About motion sickness, you will be able to use some tunneling option soon that could stay discrete but decrease a lot the sickness.

**Comment by thestonefox** [comment]
There are a number of good camera effects in the unity standard assets package that can help reduce vr sickness. I think a few people in the vrtk chat are looking into stuff like this.

**Comment by HyppoNymous** [comment]
If some effects are fast enought, it would be nice to have them included as options when we don't use the teleport or use both systems combined ( and some example usage scene).

**Comment by thestonefox** [comment]
it's something people are looking at, but as with everything, time and resource is limited on community led projects.

If it's something people think is essential then the best way to get it is to attempt to implement it and raise a Pull Request for review.

**Comment by HyppoNymous** [comment]
I could try and post some code if someone can get it integrated in the SDK ? 
But his will rise plugin dependency introducing Uniy Image Effects.

**Comment by mattboy64** [comment]
There's a bug fix PR by Chryis that will address the climbing fluid movment issue. He's got armswinger and jetpacking working well together with the climbing system.

**Comment by mattboy64** [comment]
I'll try and take a look this week.

**Comment by mattboy64** [comment]
#595 has been merged which should have fixed these issues. Please retest with the latest and close if no issues are caught.

**Comment by xEvoGx** [comment]
Just saw this now sorry! Thanks mattboy I'll take a peek asap
