### ISSUE TITLE
[feat] Add Timer to Headset Collision/Fade/Reset Safe Position

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#463]
This is just smart to have, as people will inevitably, unintentionally invoke collision. Sending them back to the last safe position without being able to 'correct' themselves is a tad draconian. 

IIRC The Gallery does this; you get the fade to 'dark grey' with a bit of a _noir-ification_ of the world, including muffling the sound (black and white filter, with blur and well I'm not sure how they muffle the sound. Anyway if you don't 'return' to the safe position within _n_ time, you're returned there automatically. 

Simple enough?

**Comment by thestonefox** [comment]
The headset collision fade script is currently being re-written to separate it out into:

 * headset collision script, which purely deals with checking if the headset has collided with something (and throws events for each state)

* headset fade script, which purely deals with fading the headset (and throws events for each state)

 * headset collision fade script, which just utilises the two above scripts to provide a default usage

But with this separation it will make it possible to provide more varied experiences of headset collision issues.

**Comment by xEvoGx** [comment]
Okie sounds goot!

**Comment by HyppoNymous** [comment]
You could create a scene example to include in the package ? The more we get , the better it is.

**Comment by thestonefox** [comment]
Yeah, my plan is to have a separate script that you can apply

So `HeadsetCollisionFade` still exists and will just do a headset fade

But I'm planning on making a `HeadsetCollisionResetPosition` (or something) that you can use in conjunction with the collision fade script (rather than have 1 script with a tonne of options)

**Comment by sblancodiez** [comment]
I commented this with @thestonefox already. Some weeks ago I had a simple implementation that did the following:

When the player starts the collision, create a collider just a little behind the player and store the last known good position. When the player stops colliding with everything except the collider behind, the camera fades back. Ifthe player keeps moving in another direction, if they separate more than some distance, move them back to the position (it will still be faded but they will be very close to going back).

This way, once the player enters fade they won't be able to go through walls , they can only go back. If you feel this is interesting maybe this weekend I can clean it up with the new changes and PR it.

**Comment by thestonefox** [comment]
Done in https://github.com/thestonefox/VRTK/pull/729
