### ISSUE TITLE
Provide start-up wizard 

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/VRTK#468]
Similarly to adventure creator or  probuilder  there should be a wizard opening up after import and through the menu to setup the scene initially and attach the basic scripts. Also we could provide presets that contain different sets of preferences depending on the experience people might want to create. This would simply the first start experience potentially a lot.

**Comment by HyppoNymous** [comment]
The combination of possible gameplay is almost infinite , and common cases are already on the example scenes you just need to use.

**Comment by maz35** [comment]
I have been thinking that a custom inspector with a paper-doll would make assembling the desired scripts for the player model nicer.  It is easy to forget that I need certain options for interaction, etc, and would be nice to have a context rich go-to.

**Comment by xEvoGx** [comment]
I like the idea, and what maz is describing (if I may), is a system that allows you to say "Grabbing Objects?"  or "Teleporting?" and so on, and then assigning the appropriate scripts.

Yea we can all easily just look at other examples to remind us what we need, so this all comes down to user experience and further polish of the tool.

**Comment by thebigdev433** [comment]
I think this can be closed. The amount of possibilities is endless and the example scenes already have everything needed

**Comment by thestonefox** [comment]
Yeah lets close it for now, always can reopen in the future
