### ISSUE TITLE
Provide analytics integration 

### ISSUE THREAD

**Issue by 10FingerArmy** [thestonefox/VRTK#469]
Unity analytics is a great storage for numbers and events of all sorts. This data can they be retrieved and visualized in various forms, eg heat maps. Vrtk could automatically send events and info like gaze direction, teleport paths, grabbed objects etc.

**Comment by HyppoNymous** [comment]
I don't want analytics by default as i know i won't use them.

**Comment by 10FingerArmy** [comment]
Good point. Should be opt in.

**Comment by reznovVR** [comment]
While this initially sounds useful it also feels something that is a very project specific thing. Usually you only track specific things that actually matter and not every possible thing you can think of. The analytics also require meaningful identifiers and values to provide useful info to the dashboard so you would have to have a way to specify them in the inspectors. 

At the moment the description is at a very vague idea level without practical use cases. How was the integration planned to happen and work from VRTK perspective? It would have to be a very generic solution with flexible customization options and rules. Supporting all this just feels like it would clutter the code base a bit and create a small dependency to the analytics system which is still evolving.

As users can already use the events provided by VRTK or the analytics scripts Unity provides I would leave this out of VRTK and close the issue unless someone had a vision how this would be cleanly implemented and how would it work from the VRTK/user perspective.

**Comment by thestonefox** [comment]
Let's close for now.
