### ISSUE TITLE
VRTK_Door Snapping option seem to be orientation dependant

### ISSUE THREAD

**Issue by lepoup** [thestonefox/VRTK#518]
-Open scene "025_Controls_Overview". Move "NormalDoor" where you want on the floor.
-Press play. It's OK.
-Stop.
-set rotation of "NormalDoor" to 0,-120,0.
-Press play. The door is opening without user interaction.
![door orientation 0 120 0](https://cloud.githubusercontent.com/assets/21106484/18253973/67c4dfea-7399-11e6-8fd1-3c5815c437f1.jpg)

-Stop. Set VRTK_Door Snapping to false.
-Play. The door is working normally again.

I don't find a simple way to fix this. Same issue with another door 3d model.

**Comment by 10FingerArmy** [comment]
fixed with the linked PR
