### ISSUE TITLE
Change VRTK_UIPointer click handlers to Down instead of Release

### ISSUE THREAD

**Issue by getwilde** [thestonefox/VRTK#525]
I've run into an interesting issue and a possible inconsistency. InteractableObject events fire on down/click, while GUI events fire on up/release. 

Background:  In my app, an Always_On pointer can be aimed at a gameObject.  Upon trigger press, that gameobject displays a popup GUI over it.  Then, the pointer can be used to interact with GUI buttons.  But what's happening is that on trigger _press_, the GameObject (correctly) shows the GUI, but then on trigger _release_, whichever GUI button happens to be under the popup menu is inadvertently fired.  Within a sub-second press/release of the trigger, two actions occur, when ideally only one should.

More generally, how should users interact with elements? In the desktop/mouse environment, mouseUp is typically when actions execute, and users are familiar with that convention.  But in VR... does it seem more appropriate to perform actions on trigger _click_, _grip_, etc? That would more closely mirror real life.  It would also make GUI interaction consistent with InteractableObject interaction.  (Consider this: If I had modeled buttons as meshes / InteractableObjects, they would have fired on press. But because I'm using GUI buttons, they fire on release. Devs know the difference... but users don't, and when they're standing in a VR environment with solid-looking objects at waist height, the distinction feels arbitrary.)

Anyway, just wondered if this issue is worth considering? 

As an aside, I'm making the transition over to VRTK from NewtonVR, where I never had this issue (but ran into several others, heh).  In NVRCanvasInput, I see ExecuteEvents.ExecuteHeirarchy (which I don't pretend to understand), with the following explanation:
```
// we want to do click on button down at same time, unlike regular mouse processing
// which does click when mouse goes up over same object it went down on
// reason to do this is head tracking might be jittery and this makes it easier to click buttons
```

As always, thanks for the great toolkit!

**Comment by getwilde** [comment]
BTW, I've tried several things to get around this issue, including: 
1. Set gameObjects to likewise perform their action on *release*. But frankly this felt terrible.  Also, its problematic:  I gave a demo to an older person last week who never released the trigger unless I told them to!
2.  Introduced a WaitForSeconds(0.25f) before activating the popup GUI canvas, in the hopes that a trigger release can occur before any buttons appear.  But this felt unresponsive... and retains the inconsistent behavior vs InteractableObjects, and is a problem for users who are slower to release.
3.  Changed my GUI buttons to use PointerDown events instead of OnClick. But anywhere I use toggle buttons (or swap out buttons), they fire in rapid succession.  To sidestep _that_ issue, I had to wire up a bunch of extra conditionals, and it started to feel like a giant workaround.

**Comment by thestonefox** [comment]
what's the tldr; for this?

UIPointer should work on "click down" rather than "click up"? (or the other way round?)

**Comment by getwilde** [comment]
Yes, UIPointer should work on click down.

**Comment by ridoutb** [comment]
My 2 cents - I don't think UIs should ever activate on down. It makes them feel aggressive and overzealous. Users should be able to change their mind and slide their finger (or pointer) off the button without it firing. We've got 35 years of mouse-clicks that don't work this way (unless they were coded badly, IMHO). It should work like the Comment button on this page works.

**Comment by getwilde** [comment]
That's what I would have thought as well. My day job is a UX human factors
engineer.  I've performed literally hundreds of usability tests, and am
keenly aware of desktop conventions.  But this isn't a desktop environment.
I've played with it both ways, and it feels much more solid to have the
action occur on press, not release. I'm not alone... the NewtonVR guys
apparently came to the same conclusion. (See snippet above, where they also
mention issues like accuracy, which is true.) When you're firing a laser,
it feels more appropriate to fire on _press_, not release.  Can you imagine
if a gun were fired when you _released_ the trigger?

**Comment by ridoutb** [comment]
@getwilde My apologies. I have to admit that I've changed my mind and I agree with you. I may not have given your post enough consideration. After going back to my own game, I think you are right. It even surfaced some memories where I thought "damn - that's annoying" when using the UI pointer on my own menus. Firing on press does make sense. Good analogy. I wonder if "pulling the trigger" vs pressing a button brings different expectations in our mind.

**Comment by getwilde** [comment]
Thanks for responding, ridoutb. No apology necessary. :) I _really_ had to think this through myself -- having been habituated to the desktop world for so long.  Kipman (Hololens lead) said this recently (paraphrasing): 

> "We'll look back at this first century of computing as a peculiar time... the only time in history when man was forced to live in a 2D space." 

Kinda' crazy, huh? I think we'll find that a lot of the old 2D desktop conventions don't translate well especially as finger tracking becomes standard. In VR/AR, we'll expect to push a button and have it function _on press_. Like your keyboard. Like an elevator button. Like squishing a bug. :)  To have actions happen on _release_ would be maddening!  

You, and I, and NewtonVR guys, and I assume many others are discovering that it doesn't seem to matter whether the element's appearance is flat or dimensional. In the real world -- and we can blame this on physics -- actions occur on _press_.  :D

**Comment by mattboy64** [comment]
I'm not sure if I understand correctly. Is the problem with the touchpad down/up? I did notice that for the bezier pointer, if I set the show/move both to the Touchpad it will use press down the activate the visual version and press up to do the actual move. If that a similar issue here then I would suggest separating it out to allow the user to select Touchpad_Down and Touchpad_Up. That way it can do it however it makes sense to you (as on release is sometimes valid too).

**Comment by thestonefox** [comment]
@mattboy64 the issue being raised is:

The "click" action on an UI element at the moment is done when you release whatever button you have assigned to click.

The suggestion is it should "click" as soon as you press down on the button.

**Comment by getwilde** [comment]
@thestonefox: that is correct.  

Incidentally, I watched another person struggle with this issue. It didn't help that she kept holding the trigger with index and middle finger. I thought to myself "She's not a gamer"... and then I realized this: Even if she _were_, gamepad actions happen on _press_, not _release_. It's just a really bad pattern in VR,

**Comment by thestonefox** [comment]
I have a branch up playing with switching it to on press down. It's not working properly yet though, i think i need to rework the logic.

**Comment by getwilde** [comment]
@thestonefox  Thank you for looking into this!

**Comment by thestonefox** [comment]
Made this an option so you can choose between Click on release or Click on press (PR coming soon!)

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/680

**Comment by getwilde** [comment]
Awesome.  I kinda' wondered if this would dovetail with issue #639.  👍
