### ISSUE TITLE
Expose Layers Instead of Hardcoding

### ISSUE THREAD

**Issue by aronschatz** [thestonefox/VRTK#543]
There are many times that the toolkit automatically assigns a specific layer to an object. For instance, in the pointers, the beams are ignoreraycast.

When using the touchpad movement, the HMD/rig is forced to another layer. This is a problem when we are using layers for culling or for triggers.

Two asks. First: Don't change layers on objects that VRTK isn't creating. This means that any controller/camerarig/hmd should remain the specific layer it has.

Two: Expose the layer that any newly created gameobject will have to the editor/script.

VRTK is great, though. I had to change the layers in the code to get it working with my new project.

**Comment by thestonefox** [comment]
Do you want to do a PR with your suggested idea?

**Comment by lucboudreau** [comment]
This is also causing me a lot of troubles. Why is VRTK putting SteamVR objects on the Ignore Raycast layer? Like this for example:

https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/VRTK_ControllerActions.cs#L420

@aronschatz Do you have a diff or something to share to help us out?

**Comment by thestonefox** [comment]
@lucboudreau the reason things are put on Ignore Raycast is so the raycast from controllers doesn't collide with the controller or the camera rig

I agree using layers would be a better way, but I could do with some help on this being implemented.

**Comment by lucboudreau** [comment]
I understand. Some other libraries use an arbitrary origin point just slightly in front of the controller. I'll take a look tonight if I can.

**Comment by thestonefox** [comment]
You can set the origin point though so that may further complicate things.

One solution may be when the camera rig is no longer tied to the vrtk objects.

**Comment by MarkTheLily** [comment]
I fixed it like this 
void Start ()
	{
		StartCoroutine ("test");
	
	}
	IEnumerator test(){

		yield return new WaitForSeconds (3f);

		gameObject.layer = 0;

	}

**Comment by thestonefox** [comment]
@MarkTheLily that won't fix the issue in why things are moved to the `Ignore Raycast` layer in the first place

The controllers, headset and body colliders would all now interact with the ray casts from things like the pointers or the headset rays that are cast, which would cause additional problems.

**Comment by thestonefox** [comment]
Should be resolved with https://github.com/thestonefox/VRTK/commit/39cf2fede029445a983acd85a6b40bb5e2c7c552
