### ISSUE TITLE
Disable SteamVR scripts if VR hardware not detected

### ISSUE THREAD

**Issue by phr00t** [thestonefox/VRTK#56]
I'd like to develop for both VR & non-VR systems at the same time. When I add the SteamVR Unity Toolkit to my project, I need to add multiple scripts to each object, across many objects specific to VR. However, if no VR equipment is attached, I get flooded with errors about controllers not found etc.

Is there a relatively easy way to disable the VR-specific scripts if SteamVR doesn't see any VR hardware? Maybe in Start(), it could check SteamVR.active boolean & disable itself across all the VR scripts?

**Comment by thestonefox** [comment]
Hmm maybe, I'll take a look

**Comment by phr00t** [comment]
I added a pull request to get this started:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/66

**Comment by thestonefox** [comment]
I may go through the files and do this when I'm doing https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/58

Because I'm going to have to go through every file anyway :(

**Comment by thestonefox** [comment]
@bddckr does the new SDK Manager stuff resolve this?

**Comment by bddckr** [comment]
Yes because you can now just use SDK Setups on the SDK Manager and even tell it to stop using any by loading a null SDK Setup via a script.  (There's an Unload button that does this on the SDK Manager's inspector when you're running the scene, too.)
