### ISSUE TITLE
Inconsistent behavior when using Track_Object Grab Attach Mechanic

### ISSUE THREAD

**Issue by punchesbears** [thestonefox/VRTK#565]
Grabbed object tracks just fine until you drop it and pick it up again.  Then it seems to go in slow motion.

Reproduce:
Open the 008_Controller_UsingAGrabbedObject scene
Select the gun and change the following in the gun script:
Grab Attach Mechanic: Track_Object

Press Play.
Pick up the gun...it should track just fine.
Drop the gun
Pick it up again...it should now be rotating and tracking position in slow motion.  This is unexpected behavior yes?

**Comment by punchesbears** [comment]
found the issue.  In VRTK_InteractGrab.cs, Lin 334. You're setting the rb.maxAngularVelocity = rb.angularVelocity.magnitude.  Disabling that makes it behave normally again. Not too sure what the purpose of setting that is, but if it's needed I think maybe the rb.maxAngularVelocity needs to get cranked back up to like 500 or something as soon as it's picked up again.

hope this makes sense.

**Comment by thestonefox** [comment]
Thanks for the heads up, I'll check into it in a bit and get a fix pushed out shortly

**Comment by punchesbears** [comment]
just fyi, when I do physics animations I always set the rb.maxAngularVelocity really high (500 typically) or else it rotates too slow.  I pretty much never touch it after that.  I suspect it's probably not necessary to cap that value during throw, unless you've seen instances where you throw something and it spins crazy fast for some reason.

**Comment by punchesbears** [comment]
also, being able to adjust the maxDistanceDelta in FixedUpdateTrackObject() in VRTK_InteractableObject.cs may be useful.  That value can make a huge difference how it feels to hold something.  The higher that value, the less "floppy" it will feel. I'm using a value of 100 right now which means if I'm holding a bat or something it will feel a lot more firm and less like I've got a really loose grip on the bat.

**Comment by thestonefox** [comment]
Looks like the `maxAngularVelocity` cap comes from the early days when it was just a fixed joint grab, which basically comes from the `SteamVR_TestThrow` script (line 55)

`rigidbody.maxAngularVelocity = rigidbody.angularVelocity.magnitude;`

Personally, I don't see the need to do this at all so I'm going to remove it completely and wait to see if someone complains :)

I've tested it without it in and it doesn't make much difference to the other grab mechanic types without it being there.

**Comment by punchesbears** [comment]
I'm using a higher maxDistanceDelta in this video.  it feels similar to a fixed joint except it has all the other benefits of using Track_Object
https://twitter.com/punchesbears/status/773738882366005248

**Comment by thestonefox** [comment]
Looks like NewtonVR have updated how they deal with the max distance delta by using `Time.fixedDeltaTime` and `Time.time` i wonder if that's a more appropriate solution rather than just an arbitrary number

**Comment by punchesbears** [comment]
yeah, the way they do it works well.  I agree, I don't like magic numbers either.
