### ISSUE TITLE
Intractable Object scripts not to scale with Position constraint

### ISSUE THREAD

**Issue by sjfricke** [thestonefox/VRTK#601]
I have a chair in my scene with a mesh collider and a constraint on Y-Axis position and all 3 rotation axis on the rigidbody so when I grab it I could move it around in a flat movement style. This works, but no matter which grab type you use the scaling is wrong. If grab a normal object and move my controller .2 meters to the right, so does the object, but with this when I move my controller .2 meters it will move like .6 meters and it looks weird how fast its moving around compared to where the controller is.

**Comment by thestonefox** [comment]
Would you be able to provide instructions of how to recreate this issue in one of the example scenes?

**Comment by sjfricke** [comment]
https://drive.google.com/file/d/0B46b_H3-cALrX01hdURpQ2tFSTA/view?usp=sharing

**Comment by thestonefox** [comment]
That's using a custom object, are you able to recreate the issue in one of the example scenes and provide instructions of how to do that so I can attempt to recreate the issue?
