### ISSUE TITLE
Integrate Immersive Movement Into VRTK

### ISSUE THREAD

**Issue by Highsight** [thestonefox/VRTK#602]
As the title says, I'm looking to integrate Immersive Movement into the VRTK as a seperate artifical locomotion option.

**Comment by thestonefox** [comment]
Before we integrate it, we should look at the common similarities between immersive movement and arm swinger.

Also, at present VRTK has a concept of how to deal with player presence, so does ArmSwinger and so does Immersive Movement.

I think it would be a good idea to ensure there is 1 consistent player presence concept that is compatible with any locomotion system.

I'm going to raise a ticket with some ideas, I'll link to the ticket when i've raised it.

**Comment by thestonefox** [comment]
https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/603
