### ISSUE TITLE
Re-implement player presence (Player Body Physics)

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#603]
Currently the Player Presence script works by attaching a variable height capsule collider and rigidbody to the player's headset position.

This way deals with how to apply gravity to the player (if they fall off something) and preventing them walking into walls and other objects.

It has the following issues:
- Walking into walls within the physical play space pushes the user back causing discomfort.
- Leaning over objects causes push back
- Leaning over drops causes falls even though your feet may still be over what you think is ground

ArmSwinger uses a collection of ray casts to determine the user's position, however this still suffers from push back on collision (albeit the collisions are not detected by a rigidbody and collider)

Immersive Movement uses a Character Controller, which is a souped up version of a capsule collider and rigid body.

I think the Character Controller is probably the best way forward, however with some restrictions such as:

The collider does not update position when the player is walking around in their physical play space, but cast a ray down and check for the difference in Y, if Y changes then update the collider position otherwise climbing stairs/slopes wouldn't work.

If the X/Z of the play area changes, (e.g. through touchpad walking) then the collider would update position to ensure the player can't slide through walls.

If the player walks into a wall (whilst walking in the play area space) then resolve it with another optional script (e.g. headset fade or a new position rewind script).

I also think the player presence should be usable without gravity (and replace the drop to nearest floor in height adjust teleport). This would basically use the raycast Y to determine the new floor Y and if gravity is turned off then you instantly appear at that new Y. Also keep a blink threshold setting to fade the headset on fall.

**Comment by thestonefox** [comment]
Issue with character controller is no gravity is applied, you have to calculate it yourself (it seems)

**Comment by thestonefox** [comment]
Perhaps it's better off using a rigidbody/capsule collider in conjunction with the headset ray cast to determine incline/decline.

**Comment by thestonefox** [comment]
Also, the capsule collider center should not be where the headset is, but should be an offset between the headset and the controllers (if the controllers are behind the headset)

**Comment by mattboy64** [comment]
Presence already has a different meaning in VR (feeling of being inside the game). This can lead to a bit of confusion on what this function actually does (does it make players feel like they're in the game more?). I'd suggest something more along the lines of VRTK_PlayerBodyPhysics to be more explicit.

**Comment by thestonefox** [comment]
yeah Body Physics seems a better name

**Comment by ajaxlex** [comment]
<img width="359" alt="screen shot 2016-10-05 at 2 18 13 pm" src="https://cloud.githubusercontent.com/assets/3699768/19125859/a0f9a992-8b06-11e6-9070-a6e0b2ba7363.png">

Is this the configuration you were thinking of?  Enough room to stand over and inspect or pick up an object, but tests for ledges, plus collider to keep yr head from hitting the floor or a wall ( and ok to be behind since player is rarely backing into things. )

**Comment by ajaxlex** [comment]
I saw some discussion about tagging and indicators about whether an item should be climbable or not.  this would certainly allow a solution between the "Climb Stairs" vs "Stand on thing I'm trying to grab" conundrum

**Comment by thestonefox** [comment]
@ajaxlex yeah that's pretty much my current implementation, however the problem is how do you then adjust to walk up stairs and make it feel as natural as possible.

The current issue i face is:

If you use a capsule collider (that's fixed to your headset position) when you hit a step the capsule collider (because it's curved) moves you up the step by sliding you up.

However, if you have the ray cast go "you're over a step, so turn on the collider" then the collider either just spangs out, resolves you immediately to the new height, or doesn't move you up at all.

The alternative solutions are:

If the new height has changed and you're moving up, then lerp to that new position (same as dash teleport), or just immediately snap to that new position (teleport without blink)

If you're moving down then then just turn on the rigidbody physics and let it make you fall.

**Comment by ajaxlex** [comment]
This is probably crazy, but what about a collider-aware motion, that uses a handful of raycasts to determine the geometry of the surface between the toes and the head-ray strike, and provides a series of points for a smarter 'shaped' dash.

**Comment by xEvoGx** [comment]
Hmmm I _collider aware motion?_  So, how about determining if the player is actually moving (>minVelocity) and adjust the capsule accordingly; you _lean_ slower (ideally) than you physically move. 

That or since leaning is an arc rotation, determine if the HMD is moving forward-only (moving +X) or both forward and downward (leaning = arc +X + -Y)? Rotation of the HMD  would only serve to fool the system since you could be looking down while moving forward so that wouldn't work. 

None of this sounds entirely workable but I wanted to sound it aloud...

...but Ajax's pic above, with the body collider slightly behind the HMD is exactly what I was talking about in #513 , and I'd wager that works quite well.

**Comment by thestonefox** [comment]
The collider being detached from the headset only works in certain situations, it's not without its own set of roadblocks

**Comment by xEvoGx** [comment]
Collider is still attached to the hmd, only it doesn't rotate. Essentially you track the joint (attachment point) and position the body but do not inherit the HMD's rotation.

Can you elaborate on the roadblocks?

**Comment by thestonefox** [comment]
If the collider is behind the player then what happens if you stand over a ledge, you stand in open space before taking another step and fall. Or if you're walking upstairs, it is playing catch up.

Or if you try and walk through a wall, you enter the wall but the collider is preventing you from going any further and potentially jitters the camera.

The raycast helps a bit but still doesn't give a decent solution.

**Comment by xEvoGx** [comment]
Yea that's true. Heck I'm a fan of holding the controller behind you to 'lean', but that too poses the same issue so this really isn't solvable without tracking the hips.

Hmmm...

**Comment by thestonefox** [comment]
Also, we're assuming the only case is leaning forward, what if you're leaning to look around a wall and there is a smaller wall to lean over.

it's such a bitch of a problem with no way of knowing where your actual waist is :(

**Comment by ajaxlex** [comment]
Use case doc:
https://docs.google.com/spreadsheets/d/16N72t5lIgxoUoBLCyOuq1pdJgw-_rqEa7o9jhC4kHKA/edit?usp=sharing

**Comment by Highsight** [comment]
The best idea I've been able to come up with so far involves monitoring the headset's angles, and the player's average standing height.  If we can guesstimate the player's normal standing height, based off of monitoring done over time, we could use it to notice if the player's looking slightly downward, and their height is a bit lower.  This would indicate someone is most likely leaning forward, and we should compensate by moving the player collider back a bit.  The same could theoretically be done with leaning left, right, and even backwards.  It wouldn't be a perfect system, but I think it has some potential.

**Comment by xEvoGx** [comment]
Yea that's what I was suggesting. So you found it works even in Stone's use-cases that could be problematic?

**Comment by Highsight** [comment]
Whoops, I opened this page WAY earlier in the day and didn't refresh, so I didn't see that part of the thread.  Yeah, those cases could present issues.  I'd need to do some prototyping though before I can say anything definitively.

**Comment by grendelbiter** [comment]
Sorry if this is a dumb suggestion I'm completely new. What if you would make 2 colliders for each object you don't want to collide with. One original sized that would be tagged or on a layer to not collide with the headset. Then another smaller collider in the middle of the object, untagged. That would leave you room to lean over the e.g. table but you couldn't outright walk through it. Likewise with ledges...just extend the navmesh a little over the ledge.

**Comment by CraigASanford** [comment]
I think this issue requires a mathematician that I am not. But from the sound of it I think it may be worth looking into what HindSight was mentioning with some changes. If player height is measured, as many games do, and we create 2 capsule colliders with a hinge or joint we may be able to get some kind of bend mechanic that works. If the HMDs rotation is such that its looking toward the floor and the height is < player height (give or take a bit) the bottom collider locks in place and the top collider bends at the joint. The only condition in which this wouldn't happen is when the player looks down to its feet and then squats or kneels. That could be found by checking the x/z coords offset from the orginal bottom colliders locked location. Even in the case TheStoneFox mentioned where you're leaning left or right and looking down (imagine standing on a ledge parallel to the edge and looking down over the ledge to see ground far below) the bottom capsule would still remain where the "feet" are. 

It's a pretty complex solution and it would need a lot work to fit in edge cases but It's the best I can come up with.

**Comment by thestonefox** [comment]
Done in https://github.com/thestonefox/VRTK/pull/729
