### ISSUE TITLE
Bezier pointer doesn't always hit the floor where its expected to hit

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#617]
Because of how the bezier pointer is generated by sending a ray forward and then straight down then generating a curve between the 3 points (controller -> front point -> down point) the curve can actually cut through platforms because the eventual target is determined by the ray casts only.

A solution would be to calculate the curve and then ray cast between the points of the curve looking for a collision within the curve. If one is found then re-calculate the curve based on the new positions.

**Comment by thestonefox** [comment]
![image](https://cloud.githubusercontent.com/assets/1029673/19016378/e6286502-880f-11e6-9d7e-1ce48b90772e.png)

**Comment by HyppoNymous** [comment]
Another very simple solution could be like Budget Cuts, you launch a physic glow ball , when it hits a layer floor object this becomes your new destination.

**Comment by thestonefox** [comment]
@HyppoNymous that would be a different solution all together though.

**Comment by thestonefox** [comment]
PR with a possible solution https://github.com/thestonefox/VRTK/pull/773

however it still has some issues, specifically when the collision happens through the edge of a floor object, in these regards it now teleports a ray down on collision to make sure it's not hitting an edge but it can cause somewhat erratic behaviour in certain scenarios.
