### ISSUE TITLE
Additive Velocity with Trackpad movement

### ISSUE THREAD

**Issue by kheckeroth** [thestonefox/VRTK#618]
When using VRTK_TouchpadWalking navigation, if you attempt to throw or drop a VRTK_InteractableObject while also in motion the object being thrown should have the [CameraRigs] velocity added to it.

**Comment by thestonefox** [comment]
I think at the moment the touchpad walking is moved around by updating the transform.position of the CameraRig, so it effectively has no velocity.

I think when the Player Presence script is re-written, the touchpad walking script should be moved potentially by adding velocity to it, to better deal with rigidbody physics.
