### ISSUE TITLE
UIPointer - Canvas "Box Collider" is not a trigger, resulting in it moving other objects

### ISSUE THREAD

**Issue by JamesHunter-DeepVoodoo** [thestonefox/VRTK#619]
When my menu visible there's a box collider attached to the canvas, but it's not set to "Trigger".

This means that when the controller menu / canvas is moved it will collide (and push) objects using the box collider that stretches off behind it.

From Slack:

thestonefox [11:35 AM]  
reason it's not a trigger is the pointer beam (not the UI Pointer) wouldn't collide with the canvas otherwise
killerjim [11:35 AM]  
In the short term - making it smaller in depth may help a little, does it have to be so deep?
thestonefox [11:36 AM]  
best solution would be to disable all collisions against it, except for the pointer beam (and have a way of registering other colliders)

**Comment by pargee** [comment]
I had this same issue and have been able to resolve this without problems by setting the canvas layer to a new one (UI) and disabling all collisions to it that may interfere (Default, etc). Everything has worked fine so far in doing so.

**Comment by CraigASanford** [comment]
if you put your own box collider on the menu and set the layer to UI and disabled collisions with everything you should be good. The one exception is that your raycast will have to be on a layer that collides with UI.

**Comment by thestonefox** [comment]
The UI Canvas already have a box collider on them (generated by the UIPointer) and as UI Canvases are already on the UI Layer you can solve this by just turning off collisions between the layer of your objects (usually Default) and UI.

So go to `Edit -> Project Settings -> Physics` and untick the `Default / UI` collision check:

![image](https://cloud.githubusercontent.com/assets/1029673/19469622/fbe75694-9513-11e6-9b79-bd99a3be9fe6.png)


The SimplePointer will still work as the Raycast will still hit the UI collider and shorten the beam, but all other objects will no longer collide.
