### ISSUE TITLE
VRTK_InteractableObject sets parent to null

### ISSUE THREAD

**Issue by TimothyFitz** [thestonefox/VRTK#627]
There are cases where VRTK_InteractableObject will LoadPreviousState() without having ever calling SaveCurrentState(). That will overwrite transform.parent with previousParent's null value.

To reproduce, create a VRTK_InteractableObject that on use sets itself or its parent inactive. If you then set the object to active again, it will see that forcedDropped is true and LoadPreviousState(). forcedDropped is true because ForceStopInteracting is called OnDisable, and it sees that it's currently touching the controller and so lists itself as forcedDropped.

This is fixed by adding SaveCurrentState() to the end of Awake, but that's probably not the right fix.

**Comment by thestonefox** [comment]
In cases like this you're probably best off extended the Interactable Object class and overriding the relevant methods to accommodate your logic
