### ISSUE TITLE
In VRTK_InteractableObject objectHighlighter is no more valid when a NetworkIdentity is attached

### ISSUE THREAD

**Issue by gpvigano** [thestonefox/VRTK#632]
With a `NetworkManager` active and if a `NetworkIdentity` component is added to the same game object holding `VRTK_InteractableObject`, then `VRTK_InteractableObject.objectHighlighter` is null the first time the object is touched.
With a `NetworkIdentity` attached, the script is correctly enabled and then disabled
(by `UnityEditor.NetworkScenePostProcess:OnPostProcessScene()`)
and then enabled again
(by `UnityEngine.Networking.NetworkServer:SpawnObjects ()`),
but when `ToggleHighlight()` is called `objectHighlighter` is destroyed.
It seems that `Utilities.GetActiveHighlighter()` returns a valid object in Enable(), but that object is no more valid when `ToggleHighlight()` is called.
I have no idea why this happens, but I tested this fix (PR #631) for a long time and it seems to solve the problem, I don't think this change can cause any side effect, anyway I it would be nice to discover the reason of that strange behaviour.

**Comment by thestonefox** [comment]
I've merged your PR on this, would you say that resolves this issue?

**Comment by gpvigano** [comment]
As far as I know it works, but I still wonder if any script that keeps a reference to the object returned by `Utilities.GetActiveHighlighter()` could be affected by this problem.
`Utilities.GetActiveHighlighter()` returns a valid object in the first call to Enable() (made by the network server), the same object is returned by second call, but that object should be no more valid (because it was destroyed in Disable()), thus I made this workaround to let `ToggleHighlight()` work anyway.
Maybe someone must tell  `Utilities.GetActiveHighlighter()` that the old highlighter is no more valid and must not be returned the next time (e.g.  `Utilities.GetActiveHighlighter()` should return null if the active highlighter was destroyed).
I hope this can help.
