### ISSUE TITLE
Warning:BoxColliders does not support negative scale or size.

### ISSUE THREAD

**Issue by luojc0517** [thestonefox/VRTK#638]
Warning:BoxColliders does not support negative scale or size.

**Comment by thestonefox** [comment]
Any chance of more information?

**Comment by JRRshockArch** [comment]
I was getting this while using the bezier pointer for teleporting, and also had the VRTK_PlayAreaCursor script added.
I removed the play area cursor script and the warning went away. 

![warning](https://cloud.githubusercontent.com/assets/26491625/24060307/135940e0-0b29-11e7-8e35-128f533e2ffd.JPG)
.

**Comment by thestonefox** [comment]
Ok there may be an issue with the play area height collider if you put your headset on the floor.

I'll take a look

**Comment by JRRshockArch** [comment]
I looked into this a little more and discovered that if you change the SteamVR_PlayArea size from one of the preset values to be Calibrated it corrects the issue and will draw the box on the ground. 
![capture](https://cloud.githubusercontent.com/assets/26491625/24312242/0470e030-10ae-11e7-96eb-05eff941313e.PNG)
Hope this helps.

**Comment by thestonefox** [comment]
This is an issue with SteamVR Unity Plugin not reporting the points on the play area vertices in the same position.

I've raised a bug with a fix over at their repo:

https://github.com/ValveSoftware/steamvr_unity_plugin/issues/25
