### ISSUE TITLE
Grabbed Objects collide with player collider when switched from hand to hand

### ISSUE THREAD

**Issue by grendelbiter** [thestonefox/VRTK#641]
To test load up 017 Camera  Rig Touchpadwalking. On the green box uncheck Hold Button to Grab, run the scene and grab the green box. Switch hands and bring it towards your body and it will fall to the floor. When the object doesn't have a rigidbody like in this example scene you can push yourself around with your held object (Very fast.)

**Comment by thestonefox** [comment]
fixed with https://github.com/thestonefox/VRTK/commit/7034181e4823145dde08d444eac948bf9a4e896c
