### ISSUE TITLE
Feature - VRTK should provide centralized mechanisms for Player Metrics

### ISSUE THREAD

**Issue by ajaxlex** [thestonefox/VRTK#648]
To allow a consistent approach to play behaviors and the player relation to the game world, VRTK should provide a convenient location for real-world properties associated with the player, including at least:
- player height
- arm length

The api should allow for manual setting of these vars, and also possibly methods for dynamic runtime establishment of baselines from best guesses

A sample scene that shows how the data can be captured and used should be created.

**Comment by ajaxlex** [comment]
Probably on player presence.

**Comment by thestonefox** [comment]
yeah this is an interesting idea.

Height can be just a normalized y from the headset to the floor. and the arm length....urm, what about you keep a check on the `max distance` between the headset and the controller?

**Comment by CraigASanford** [comment]
I implemented this in my game - Its a simple setup. Scaling the camera rig by the offset of player height and my avatar height or the "height" I want all players to view my game world from. Very simple.  Arm length is measured by having the players stand in a T pose and pull a trigger. It measures the distance between controllers and builds a ratio to scale in the x/z to fit my avatars arm distance. The height adjust works well. The arms... not so much... still working on that one.

**Comment by vrnow-org** [comment]
Hi guys I have been working away on  body proportion calculator from NASA biomechanics and other scientific data, it is in a rough draft but free to any who might find it useful. 

Code is on codeshare here...
https://codeshare.io/5ZQ0jQ

If the link expires drop me a pm :)

**Comment by WildStyle69** [comment]
Be great to include this into VRTK somehow, would make life easier. :)

**Comment by vrnow-org** [comment]
You are welcome to use it as it, and if stonefox want to roll it in he is most welcome to, but I am working on several more practical applications for it, such as automatically positioning touch menus and automatically adjusting interactables based on reach. 
So you may want to hang on a little while till we can show off some practical applications of it :)

All the best 
Don

**Comment by kristianpd** [comment]
I'm exploring this issue with VRTK and VRIK right now.  This seems like it will be very custom for each game.

https://www.youtube.com/edit?o=U&video_id=4vU_9SZBeAY

Should we close this?

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522 ?
