### ISSUE TITLE
how to teleport by code

### ISSUE THREAD

**Issue by wheatgrinder** [thestonefox/VRTK#651]
I need to teleport my player like a teleporter beam.  Trigger and action and move to the new predefined place.  

what I thought was a simple cameraRig.transform.position=newPosition did not work.  Should it?

Thanks

**Comment by thestonefox** [comment]
It depends if you're using the teleport script.

If you are then you're better off emitting a DestinationMarker to tell the teleporter your new destination.

Look at the model village example to see this working.
