### ISSUE TITLE
VRTK Find Device make IndexOutOfRangeException When Initialization

### ISSUE THREAD

**Issue by DianFeng123** [thestonefox/VRTK#653]
If not specify the Left Controller and Right Controller device number ,It will report the following error
IndexOutOfRangeException: Array index is out of range.

SteamVR_Controller.Input (Int32 deviceIndex) (at Assets/SteamVR/Scripts/SteamVR_Controller.cs:151)
VRTK.VRTK_ControllerEvents.OnDisable () (at Assets/SteamVR_Unity_Toolkit/Scripts/VRTK_ControllerEvents.cs:468)
UnityEngine.GameObject:SetActive(Boolean)
SteamVR_ControllerManager:OnEnable() (at Assets/SteamVR/Scripts/SteamVR_ControllerManager.cs:47)

**Comment by thestonefox** [comment]
What version of the toolkit are you using?

The code on line 468 of VRTK_ControllerEvents is a blank line.
