### ISSUE TITLE
Making a gun slider with the VRTK_Slider?

### ISSUE THREAD

**Issue by Bugzoo** [thestonefox/VRTK#654]
Does this work or is there a way to do this? I tried it but then the gravity doesn't work

**Comment by 10FingerArmy** [comment]
I suspect you want to pull the slider and upon releasing it should go back to its original position? The slider control would probably give you the ability to move the gun slider and get nice events when the "reload" position was reached, but it will not move back as of now automatically.

My guess would be it's probably easier to use a manual setup with a spring joint here for now but it might be worth looking into it and extending the control with another one that uses the "spring slider" setup.

**Comment by Bugzoo** [comment]
I have kindof got something working, but the slider just floats in mid-air, and doesn't follow the gun. Rigidbodys dont even work on VRTK_Sliders

**Comment by 10FingerArmy** [comment]
Some more details would be great or even better a reproduction setup/scene.

**Comment by pargee** [comment]
stonefox committed this earlier today :)
https://github.com/thestonefox/VRTK/pull/666/commits/c1b65bb95651d8444bdfe3093a5932a66b4cea2b

**Comment by thestonefox** [comment]
I was about to say what @pargee  said but yeah I added a gun with a configurable joint slider :)

**Comment by Bugzoo** [comment]
i love you
