### ISSUE TITLE
Interactable Object requires Defensive Check For ToggleHighlight

### ISSUE THREAD

**Issue by ajaxlex** [thestonefox/VRTK#655]
The objectHighlighter may not exist if the object has been deactivated.

modify ToggleHighlight to check both objectHighlighter and highlightOnTouch 

if (objectHighlighter && highlightOnTouch)
{
    Color color = ...

**Comment by thestonefox** [comment]
Resolved with https://github.com/thestonefox/VRTK/commit/4217b75fc5cff8d7bd9a2ee40523f75c81d3f97c
