### ISSUE TITLE
Name the Pig Competition - Prize for the **Winner**

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#659]
So we now have a new official logo for VRTK thanks to dedication of the VRTK community.

We went through many months of ideas and iterations and finally settled on the idea of rather than looking for a cool, high tech logo, we'd go for something fun and memorable. The idea of an animal mascot was born.

Eventually the Pig rose to the top and has become the founding part of the logo and our new mascot.

![image](https://cloud.githubusercontent.com/assets/1029673/19416008/4778e490-937c-11e6-8cc1-f8d11b580db6.png)

We don't want to keep calling our beloved VR mascot "Pig" so let's have a competition to name the little chap!
---
# Competition Rules
## The name that is the favourite will be the name of the pig and the first person who posted that name in this issue will be the winner and win a prize of a Steam Game up to the value of $30.00 _(You will get to choose any game on Steam up to that value and it will be gifted to your Steam account)._

> Any offensive names such as curse words, inappropriate words, racism, sexism or any form of discrimination will not be eligible for the competition and the comment to the issue will be deleted. If your comment gets deleted then this is because it was not deemed appropriate for the competition, that decision is final so please don't moan about it :)

**Comment by BuxtonWater** [comment]
John, because I have no imagination.

**Comment by frozenMeatpopsicle** [comment]
Pig in Dutch or Afrikaans is Varken or Vark, respectively. Something along those lines that could work since they've both got V and R in them, also the K in VRTK.

Could combine all that to make a name like Vartken? Or maybe Vortken(almost sounds like pork)?

I think I'll continue playing with it.

**Comment by JoeHart** [comment]
Great logo!

My submission: Vera

So it's kinda like VR, get it? It's early and I haven't had coffee yet...

**Comment by subnet-** [comment]
Chris P. Bacon /s

**Comment by 10FingerArmy** [comment]
I as well like names with VR in them, especially in the beginning and end, so here's my short list by personal preference:

VictoR (cool since it also sounds like victory)
ValdemaR
VladimiR

**Comment by Dal1Dal** [comment]
I feel the most simple name is always the best so I would just call the pig.....Pinky.

**Comment by HenryGarle** [comment]
Cyril 😄

**Comment by Timjobb** [comment]
Pork Mcgogglesface

**Comment by deedgeoakley** [comment]
Thad O'Toole

Think about it....

**Comment by deedgeoakley** [comment]
Chops

**Comment by ciwolsey** [comment]
Pudgy

**Comment by Militonius** [comment]
Pig in my language (Maltese) is Hanzir but that would be weird to pronounce in other languages so
name it Hanzo

**Comment by MichaelStahre** [comment]
Well, you asked the internet. So I'm suggesting Piggy McPigface.

**Comment by Sir-Viver** [comment]
The first name that popped into my head was "Wishy", Wishy the Pig, WishyPig, or Wishpig.

**Comment by SimplicityCompass** [comment]
Love the new logo. My suggestion...

Oink

**Comment by blinz117** [comment]
Vernon Rutherford Theston Ketterhingham (the Fourth?)

or, Vern for short

(also, get it? KetteringHAM? Anybody? Oh, nevermind...)

**Comment by thebigman433** [comment]
Porkalini, Porkchop, Pug

**Comment by jeremymccurdy** [comment]
Combining themed words can often work well:
Swive (Swine + Vive)
Pive (Pig + Vive)
Virtuaswine (Virtual + Swine)
Vhog (Virtual + Hog)
Vibacon (Virtual + Bacon)

**Comment by StoneyCoder23** [comment]
Hamlet
Picarus (Pigarus?)

**Comment by thatserafimkid** [comment]
Cupig

**Comment by CharlotteGore** [comment]
I realise I posted in the wrong place, so here's my suggestion. I thought long and hard about this, weighing all sorts of factors. This pig's name has to be Piggy McPigface.

**Comment by cd109876** [comment]
The VR Tool Pig. Or toolpig. Or VRTP.

**Comment by OMGsus** [comment]
Virtie

Or Virty

Or Virty K.

Or just Virty. K?

**Comment by SaxOps1** [comment]
Victor the VR Pig!

**Comment by JDelekto** [comment]
VoRTeKs

**Comment by tntfoz** [comment]
Darth Pig

**Comment by WildStyle69** [comment]
Not seeing Jim's (jimthegrim) pig name here... so am throwing that in the hat on his behalf. ;)

'Vernon the Wonderpig'

**Comment by Bugzoo** [comment]
tom

**Comment by getwilde** [comment]
Tessa

**Comment by MrSteenky** [comment]
Wilbvr

**Comment by Podgkin** [comment]
[That'll do pig](https://www.youtube.com/watch?v=rjQtzV9IZ0Q)

**Comment by gpvigano** [comment]
This logo is the worst I ever seen, am I the only one who with this opinion?
I am sorry I missed last comments in #292 , but I really dislike this logo, any other logo proposed before would be really better. A pig is often related to rubbish, not suitable to a valuable software toolkit like VRTK.
(About the name of the pig: don't call him, just shoo him.)

**Comment by WildStyle69** [comment]
"Dirk Piggler"

**Comment by MrJimbones** [comment]
Vernon the Wonder Pig

**Comment by JoshGalvin** [comment]
+1 to Piggy McPigface

**Comment by Overswarm** [comment]
Gaben

**Comment by xEvoGx** [comment]
Virgil

**Comment by CraigASanford** [comment]
Olivr... I dunno. I think a pig named Oliver is nice - and if you remove the e it has VR in the name... so yeah... that's my creative contribution.

**Comment by StoneyCoder23** [comment]
@CraigASanford please sir, may I have some more vr games?

**Comment by robmerki** [comment]
Vertik. 

(VRTK -> Vertik)

**Comment by WildStyle69** [comment]
"Davros"

**Comment by Highsight** [comment]
"WillVR"

**Comment by thestonefox** [comment]
No more entries now please.

Anything below this comment won't be considered, so don't waste your time ;)

**Comment by thestonefox** [comment]
The finalists have been chosen: you can vote on your favourite here:

http://www.strawpoll.me/11517646

**Comment by thestonefox** [comment]
The results are now in, the Pig's name is....................

# Hamlet

![image](https://cloud.githubusercontent.com/assets/1029673/20050683/9911e1ce-a4c2-11e6-94c1-146cebbaa128.png)


Congratulations to @StoneyCoder23  you are the winner! I'll be in touch about your prize!

**Comment by xEvoGx** [comment]
Hamlet?  Sigh Olivr is absolutely perfect on both levels... 😞

**Comment by getwilde** [comment]
Agreed.  Hamlet's not bad but I loved Olivr.

**Comment by tntfoz** [comment]
His middle name could be Olivr and every one calls him that because there's two Hamlets in the family? :)

**Comment by thestonefox** [comment]
I don't see any protesting in the streets, so it can't be that bad! :p ;)

**Comment by getwilde** [comment]
Maybe he goes by Hamlet, but that's actually his surname, while only his closest (600) friends even know his first name.

**Comment by StoneyCoder23** [comment]
`piggywig`
