### ISSUE TITLE
Player Presence broken when Height Adjust Teleport USE GRAVITY enabled

### ISSUE THREAD

**Issue by wheatgrinder** [thestonefox/VRTK#674]
Steps to reproduce:
add VRTK_HeightAdjustTeleport to CameraRig prefab, configure pointers etc.
in VRTK_HeightAdjustTeleport inspector set "Use Gravity to "on"
Add VRTK_PlayerPresense script to CameraRig prefab. 
In VRTK_PlayerPresense inspector set "Falling Physics only" to "Off"
Push Play in editor.
Expected Results "player presence" should work.  (cant walk through objects)

Actual Results.
In the inspector the "Falling Physics Only" is automatically turned "on" and player presence does not work,  Example. I CAN walk through walls\objects.

The same behavior can occur if using VRTK_PlayerClimb script which also has a Use Gravity option.

Work Around:
If in the VRTK_HeightAdjustTeleport inspector we set the "Use Gravity" to "Off" everything woks as expected.  This is not a great work around as falling now is not based on gravity and thus is too fast.  This is worst when using the VRTK_PlayerClimb script, as falling is near instantaneous.

**Comment by thestonefox** [comment]
@mattboy64  can you chime in on this one?

**Comment by mattboy64** [comment]
HeightAdjustTeleport and PlayerPresence do similar things but in a different way. PlayerPresence (PlayerBodyPhysics) is the physics based world interaction and physics based gravity. HeightAdjustTeleport  is a raycast based gravity system. In other words, HeightAdjustTeleport is an absolute placement system and PlayerPresence is a physics based one. The gravity toggle allows HeightAdjustTeleport to _sometimes_ be physics based, but only when it is in a "falling" state. I think @thestonefox has plans to rework this a bit, but a solution might be to have a Gravity dropdown instead where you could choose **Falling Only** and **Always**. The first would force **Falling Physics Only** to true and **Always** would force it off.

**Comment by thestonefox** [comment]
What @mattboy64 said...

This is going to need a refactor..

I'm going to remove all of the constant height adjustment stuff out of the height adjust teleporter (the drop player to floor stuff).

So the height adjust teleporter is just changing your Y value when you teleport only.

Then a new script will deal with the constant height adjustment (perhaps the new player body physics script).

**Comment by thestonefox** [comment]
I'm going to close this and merge it into 

https://github.com/thestonefox/VRTK/issues/603
