### ISSUE TITLE
Implement Drag & Drop mechanic for Canvas UI elements.

### ISSUE THREAD

**Issue by tntfoz** [thestonefox/VRTK#675]
Provision of drag & drop functionality with Canvas UI elements to allow:

- Selection of a GUI element (e.g. an image) with the controller by touching the element (to highlight it).
- Holding the trigger could then select the element and allow it to be dragged with the controller.
- Releasing the trigger would drop the element at that position in the canvas.
- Snap functionality would then re-position the element to the nearest snap point (e.g. another GUI element).

The above could perhaps be an extension to the functionality between the controller and GUI elements discussed in issue #639.

**Comment by getwilde** [comment]
@tntfox.  Thanks for logging this.  How timely! @thestonefox and I literally just chatted about whether there's a need to grab GUI elements.  I remarked that it's probably corner-case.  But i may have been wrong; I see value in what you're suggesting.

From a UX perspective, *GUI elements* versus *mesh objects* should be purely an implementation detail (something that only devs must worry about).  For users, if they see something within arms length, and expect to interact with it, they should be able to, in a consistent manner, regardless of how it was built/implemented.**

With #639, VRTK _mostly_ achieves "interaction parity" between *GUI elements* and *mesh objects*:  Users can hover/touch/highlight on both; Users can click/use on both.  But, while users can _grab_ mesh objects, they can't grab GUI elements.  This enhancement would achieve true parity.

_** There may be cases where developers deliberately force users to differentiate but I think that's the exception?_

**Comment by thestonefox** [comment]
there are two things in dragging and dropping i'm thinking.

1: you can drag a 2d UI element in a canvas and drop it somewhere else in that canvas (or in another canvas maybe?)

2: you can take a 3d element and drop it onto a canvas and it turns into a 2d ui element (don't hold your breath for this though)

**Comment by getwilde** [comment]
In my scenes, I've started using a single worldspace Canvas at (or near) the top of my Heirarchy.  It simplfies things; I can just display UI elements wherever I need to in my world.  I'd be curious to know if others are doing that in VR, and whether it's at all common?  

So, from that perspective. could VRTK somehow leverage the snapping behavior that you recently introduced for 3D mesh objects, but applied to GUI elements? Is that what you had in mind?  (If so, that's yet another nice step towards "interaction parity" between GUI elements and 3D mesh objects.)

**Comment by thestonefox** [comment]
@getwilde yeah pretty much the 3d object touches the canvas has a special script on it that says "i can be dropped into a canvas" where you have to apply an image sprite, then on drop, the 3d object is deactivated and a UI image is created with the given sprite image within the canvas.

**Comment by tntfoz** [comment]
@getwilde and @thestonefox thanks for looking into this!

My personal usage case for this is to have a selection of items represented by canvas UI buttons (or sprites/images, whatever will work best) that can be dragged by the player onto one of a dozen "portals" (which are just more UI buttons).

The portals represent places on a map that you can assign the items to.

I'm not sure how precise the dragging & dropping can be, so I'm thinking there could be a "near enough" zone around the portal buttons which if the player releases an item within, then the item would snap to the portal. In the case where a portal is disabled (due to the item selected not being compatible for example) then releasing the item would just snap it back to its original position from where it was dragged.

All the above would be ideal but I'm obviously happy to change the mechanics around at my end to fit with what is actually possible.

Do you guys think this is doable?

**Comment by thestonefox** [comment]
Ok I've made a new Issue for the 2d/3d dragging: https://github.com/thestonefox/VRTK/issues/686

Then we can focus this issue on the ability to drag 2d elements around a canvas.


So this issue is simply that, you can select a 2d element then drag it around the canvas with some options:

* Free drag, you can drag and drop it into any precise location on the canvas
* Snap drag, you can drag it and drop it only into valid snap locations, if you drop it in an invalid location then it snaps back to it's original location.

**Comment by getwilde** [comment]
That sounds slick!

**Comment by tntfoz** [comment]
Sounds great @thestonefox - thanks for this.
