### ISSUE TITLE
InteractableObject Use error if used object destroys player

### ISSUE THREAD

**Issue by Blueteak** [thestonefox/VRTK#676]
Line 853 in `VRTK_InteractableObject` can throw an error if previousController is being destroyed that frame (something that is very possible when switching scenes, swapping to multiplayer, etc) On-Use.

Fix would be to ensure that `previousController != null` before continuing (always good to do extra checks if using IEnumerators.

**Comment by thestonefox** [comment]
line `853` is an else keyword in `VRTK_InteractableObject`. I'm guessing you're on an older version and you mean line `958` :)

anywhos yeah you're right, i added the check to make sure `previousController` was still a thing

https://github.com/thestonefox/VRTK/commit/21219d2e5fe1331f115925c98253c601da73884a
