### ISSUE TITLE
Ability to move objects with pointer tip

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#683]
At the moment, it's possible to interact with objects with the WorldPointers (e.g. Simple Pointer).

But on grab the item just snaps to the controller attach point (which is part of the controller) so it's as if the item is magically teleported to your hand.

A nice feature would be the item on grab (when touched by a pointer) would be the object is grabbed to the pointer then moved around with the pointer.

The solution is to update the controller attach point the the pointer tip when the grab with pointer option is set and the pointer is active and then reset the controller attach point back to the original when the pointer is deactivated.

Also, the pointer length should not exceed the length it is at the point of grab otherwise the pointer can shoot off into the distance and lose the object.

It probably also needs to have the grabbed object ignore the pointer ray so the pointer length can become shorter so it's easier to move objects closer.

**Comment by mstergtr** [comment]
Is there any chance that this feature will be implemented with the suggested solution in the future? 

"A nice feature would be the item on grab (when touched by a pointer) would be the object is grabbed to the pointer then moved around with the pointer" 

Thanks!

**Comment by thestonefox** [comment]
This feature was implemented

**Comment by bddckr** [comment]
@mstergtr What @thestonefox said. You can see this on this webpage as GitHub lists:

> thestonefox closed this in f911709 on Nov 7, 2016
