### ISSUE TITLE
Controller rigidbody/collider as separate tracked object

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#687]
At the moment the controller rigidbody is attached to the controller so when it's active and it touches another rigidbody, the real world physics of the controller supersede game physics meaning the player can force the rigidbody through the other rigidbody (because the controller is updated with transform.position)

This can cause issues where the other item (e.g. if it's using joints) goes crazy in the games physics engine.

One solution is to have the controller a track_object so it's moved by it's rigidbody using velocity in the game world, however this has the issue that the controller model can become detached from the real world controller position and look jarring.

Another solution discussed in the slack channel was to have the rigidbody and colliders to be a separate track object that follow the controller model, but whereas now the rendered model can still pass through things to keep the 1:1 position lock with the real controller, however the colliders and rigidbody always adhere to game physics.

So if you pushed a button, your controller would pass through it with enough force but the rigidbody would stop at the full depress of the button (meaning it wouldn't snap through and provide force on the underside of the button)

**Comment by hcorion** [comment]
IMO (and I believe this was the conclusion) the second option is much better. The first option sounds like what NewtonVR is doing, which definitely has it's pros but It doesn't seem like that is the direction VRTK wants to go.

**Comment by thestonefox** [comment]
yeah the first option is what NewtonVR does. However it can leave you in a situation where you can lose your controller behind an object (or even lock it in a drawer then it can't find it's way to snap back to the real position of the actual controller)

**Comment by hcorion** [comment]
It seems you could do the same with the second option as well, except the collider and rigid body would be stuck and the player would have no idea where they went, so I assume some kind of timed/distance based snapping mechanism would need to be put into place.

**Comment by thestonefox** [comment]
Yeah exactly, a distance based reset (like what there already is on the Track Object)

So if you get too far away then the rigidbody snaps back to the controller.

However, this then has the issue again if you pass the object through something and the rigidbody exceeds the distance and snaps back then again it can apply force from the other side of the object.

It's an annoying trade off between losing synchronisation between the game controller and real world controller and not unduly applying forces to things

**Comment by Igameart** [comment]
Did we ever get anywhere on this? The transform.position nature of the controller makes it impossible for me to swing a bat and hit a ball, my bat just passes through the ball every single time. It's a shame because there are so many great features to this engine, but without s solution i'm literally at a stand still on production.

**Comment by hcorion** [comment]
@Igameart I think NewtonVR sounds like a good solution for you, have you tried it? It was built from the ground up for that kind of physical interaction.

**Comment by Igameart** [comment]
@hcorion I had originally looked into that one but liked the extra goodies that this came with. After running into this issue though, i've started digging into NewtonVr a bit deeper. Just gotta add some locomotion and I think i'll be able to suffice with it. Thanks!

**Comment by thestonefox** [comment]
@Igameart @hcorion You want to use the `Track Object` grab mechanic if you want objects to move around with velocity rather than positional updates.

This is the same mechanic that NewtonVR uses.

This issue is about the controller colliders, not grabbed object colliders.

**Comment by thestonefox** [comment]
Can achieve this with an update to the Rigidbody Follow script.

I have a plan!

**Comment by thestonefox** [comment]
The rigidbody that is applied to the controller should never be used as a physics collider.

I propose removing the `enable rigidbody on grab` mechanic from the InteractGrab script and never have the controller colliders turn to non trigger (and the rigidbody non-kinematic).

In place I suggest a new script that enables a rigidbody with a set of controller colliders that follows the controller around.

It can have an activation button to enable the rigidbody and colliders that are tracking the controller. Also have the option to 1:1 track (which would just use the `Set` option on the rigidbody follow script).

**Comment by thestonefox** [comment]
https://github.com/thestonefox/VRTK/pull/1592
