### ISSUE TITLE
Controller-Hide issue on Use

### ISSUE THREAD

**Issue by Tom-LeFx** [thestonefox/VRTK#688]
Hello there, 

I discovered some Controller-Hide issues with an InteractableObject, when grabbing and using it with the same Controller-Button (in my case it's TriggerHairline for both Grabbing and Using). Even though I set "Hide Controller on Grab" and "Hide Controller on Use" to "Override Hide", the Controller will only be hidden, while using the InteractableOject. Does anyone had that issue before or already know a solution for this?

That issue is reproducable with your example-scene "008_Controller_UsingAGrabbedObject" and the InteractableObjectSettings as shown in the screenshot.
![hideissue_inspectorsettings](https://cloud.githubusercontent.com/assets/13467945/19640598/be20335c-99dd-11e6-9c2f-70e5c0a49cf3.png)

**Comment by thestonefox** [comment]
It seems to be more fundamental than just the controller visibility issue.

It seems if you set the same button for both grab and use, then on pressing it, grab is triggered, use is triggered but then Unuse is triggered straight away.

I'll need to look in to why that is and hopefully fixing that will fix the other issue too.

**Comment by thestonefox** [comment]
Try this Pull Request and see if it resolves your issue: 

https://github.com/thestonefox/VRTK/pull/694

Let me know if it works for you and I'll look to merge it with the master branch

**Comment by Tom-LeFx** [comment]
Thanks, we are trying it today/tomorrow and will let you know

**Comment by Tom-LeFx** [comment]
We tried it today (took a while, because we had to compensate for the changes you made with the dropzones)...unfortunately it doesn't seem to help. The controller is still visible when picking up the object and only hides, while using it.

**Comment by thestonefox** [comment]
Not sure i understand, but your settings you posted above grab and use at the same time.

are you using it with different settings from the ones you posted in the screenshot? if so can you post the updated settings.

**Comment by thestonefox** [comment]
Also, separate grab and use buttons with Override Hide on both grab and use works fine for me.

**Comment by Tom-LeFx** [comment]
We use the same buttons to grab and use, as this projects needs to be as simple as possible.
We don't really understand, why the object isn't hidden, when both (grab and use) set "Override hide" as a mode

**Comment by thestonefox** [comment]
but with this pull request it's working (for me) as you would expect.

did you download the pull request from:
https://github.com/thestonefox/VRTK/pull/694

and try that code?

Also, when you say the "object isn't hidden" you mean the controller right?

**Comment by thestonefox** [comment]
Ok try the updated PR

https://github.com/thestonefox/VRTK/pull/694

**Comment by Tom-LeFx** [comment]
Fix works like a charm now.
Thanks for the fast implementation :+1:
