### ISSUE TITLE
Steam VR Toolkit "Quation"

### ISSUE THREAD

**Issue by Thaeba** [thestonefox/VRTK#689]
Hello, 

we are working in research project at the Berlin University of the Arts Chair VPT (Building Physics and Building Services Engineering). Parallel to our research, we try to visualise the project with unity 5 and also with Steam VR (HTC vive headset). During the working process some quastions appear. i downloaded your steam VR package to interact some objects in your model and tryed with the HTC vive glasses. the problem was, that no one of the interaction worked. Even your examples. i wonder, if i done every thing right (i followed also your interdutions on youtube) but i dose not work. what cat be the generall problem? 

i apologise for my english, i hoppe you unterstand my situation. 

kind regards
Thaeba

**Comment by grendelbiter** [comment]
Have you downloaded and imported Steam VR?

Hast du Steam VR downgeloadet und installiert?

**Comment by Thaeba** [comment]
hey, 

yes i did. and tried to make a door openable but there was no reaction. i followed your interdution on youtube. 
below two screenshots. 

![dooropen_1](https://cloud.githubusercontent.com/assets/23034391/19811993/06d68908-9d34-11e6-8d66-f3f482db4bcc.png)
![dooropen_2](https://cloud.githubusercontent.com/assets/23034391/19812004/139d1544-9d34-11e6-9335-89ad0ff9d61d.png)

**Comment by grendelbiter** [comment]
You need to delete the main camera.
