### ISSUE TITLE
Running in place locomotion

### ISSUE THREAD

**Issue by RoccoGD** [thestonefox/VRTK#69]
I have tried the demo and it works for me, so when this system is well polished it could be a good alternative to teleport, like the swing arm locomotion.
http://smirkingcat.software/ripmotion/

**Comment by xEvoGx** [comment]
That's a good fucking workout! 

I saw this a couple weeks back and neglected to check it out...glad I did.

What he's doing is checking for a 'bob' on the HMD (Y axis?). Meaning you don't even have to _Run_ in place, rather all you need to do is bounce a little. The *Left Controller* is merely a pointer, so if you instead hold it in your hand, you can use it to move forward and/or strafe just by rotating it slightly (no luck quickly going backwards unless you can turn your wrist as such hehe).

Pretty neat and interestingly, other than nearly losing my balance (funny that, your brain), I didn't feel any sensation that would lead to nausea (that my body is wont to do in VR).

**Comment by thestonefox** [comment]
I've seen this video, it's a pretty unique way of movement.

Yeah I think you're right @xEvoGx I think they're just using the controller position as a pedometer, check the shake on the axis and move accordingly based on the ferocity of the shake.

**Comment by xEvoGx** [comment]
Well the HMD...the controller is nothing more than a pointer...but yes shaking your head up and down furiously is an alternative to bouncing or running in place lol! :)

**Comment by RoccoGD** [comment]
Well as far as i understand it is like stonefox mentioned, i think he describes his method here a little better -> 

**Why put the tracking pucks on hips and not feet?**

While it's very likely possible for this to work by tracking your feet, it would definitely be harder. This is because feet can move in less constrained ways (open or closed stance while running, ability to kick and move around wildly) which means that just like tracking the head, there is a lot more noise to have to be filtered as opposed to using the hips. That being said, there are definite benefits to including feet for additional input (kicking things, virtual leg representation, etc).

**Comment by xEvoGx** [comment]
Nope it's the Headset, promise. 

You don't have to put the left controller on your hips. I thought the way you guys did, and was hammering on the left controller, thrusting it up and down, side to side, jogging in place, nothing. Then I inadvertently 'bobbled' my head, and I started moving a tiny bit. So there's your eureka moment. The only thing the left controller does is 'point' you where you're going to go...when you bobble your head.

Great idea, but does become a bit much with the HMD flopping around, never mind how tiring it can be!

That being said YES, you do want pucks or such on your hips, though then you couldn't do the bounce trick as easily (you'd more than likely have to actually run in place).

Anyway you guys should give it a go to see what I'm talking about.

**Comment by xEvoGx** [comment]
Just so you guys don't think I'm a crazy person! :)

[https://www.youtube.com/watch?v=HO_JGtub5T8](url)

Scroll down a couple Comment trees:

**alexinaboxx** 1 month ago
_Question. Is the speed handled by the controllers vertical motion? As in 'bounce'?﻿
Reply_     

**deprecatedcoder** 1 month ago
_+alexinaboxx Just HMD movement.  Controller is all about direction._﻿

**Comment by thestonefox** [comment]
That makes sense, so you can run in one direction but turn your head to look in another direction

**Comment by annabel82** [comment]
Would like to vote this up please

**Comment by baemoth** [comment]
Would it work well to get the direction from the controller but having the controller more in a horizontal position relative to the ground so you could turn it in your hand without twisting your wrist? I know I tried a demo for something that did this mixed with touchpad moving and it worked well.

**Comment by thestonefox** [comment]
I think there are quite a few variations that could be played with here..

Any takers for someone to mock something up? :)

**Comment by annabel82** [comment]
I will help in any way I can but I can barely program C#

**Comment by thestonefox** [comment]
@annabel82 You can test the running then :)

**Comment by annabel82** [comment]
Sounds good :)

**Comment by thestonefox** [comment]
Just as side note for people, if you're interested in testing things then it's worth dropping into the slack channel (https://vrtk-slack-invite.herokuapp.com/) we're always looking for people to help out with ideas and testing. It's a good mix of skills and people in there.

**Comment by annabel82** [comment]
It says invite limit reached :)

**Comment by thestonefox** [comment]
@annabel82 if you email me the email address you want to be invited on I can do a manual invite.

my email is thestonefox at gmail dot com

(i'm guessing the invite limit has been reached for the day)

**Comment by thestonefox** [comment]
Will be resolved by

https://github.com/thestonefox/VRTK/issues/602
