### ISSUE TITLE
[perf] MaterialColorSwapHighlighter is instancing materials

### ISSUE THREAD

**Issue by fight4dream** [thestonefox/VRTK#691]
Use MaterialPropertyBlock to animate material color instead

**Comment by thestonefox** [comment]
Not sure what you mean. Could you provide more information or perhaps a pull request with your suggested fix?

**Comment by fight4dream** [comment]
Yes, fight4dream have it done before the highlighter refractored and it worked. We will have a pull request soon for you to review. 

More info: It can be used in place of using .material(s) to animate a material property such as Color. Can preserve dynamic batching (only 1 material is used), reduce memory (due to instanced material) and rendering time (draw call overhead)

Reference: 
http://thomasmountainborn.com/2016/05/25/materialpropertyblocks/

**Comment by thestonefox** [comment]
Isn't the issue with using `MaterialPropertyBlock` that objects need to apply a custom shader that can work with the method?

**Comment by fight4dream** [comment]
[PerRendererData] tags a Texture property and is mainly used by MaterialPropertyDrawer to show the overrided texture.

Other than that, it is not required. 

https://docs.unity3d.com/Manual/SL-Properties.html
https://docs.unity3d.com/ScriptReference/MaterialProperty.PropFlags.html

**Comment by fight4dream** [comment]
Further investigation on MaterialColorSwapHighlighter related code suggested that:

- it has a specialization to highlight controllers using "resetMainTexture" (can be done by MaterialPropertyBlock)

- it has a specialization to change also the appearance using "customMaterial" (cannot be done by MPB)

This highlighter is not simple as its description suggested and is used by several default use cases.
Until it is refactored into proper classes, I would suggest to add one MPB highlighter only for Color, instead of modifying the current one.

Could you suggest a name for this color highlighter?
VRTK_BasicColorHighlighter
VRTK_SimpleColorHighlighter
VRTK_ColorSwapMaterialPropertyBlockHighlighter

**Comment by thestonefox** [comment]
`VRTK_ColorSwapMaterialPropertyBlockHighlighter` seems to be the most appropriate in relation to the other highlighter names.

But are you saying this highlighter won't work on the controllers?

**Comment by fight4dream** [comment]
We could preserve the "resetMainTexture" option. Will run a test to see if null works on _MainTexture override

**Comment by ssshake** [comment]
asdf

**Comment by ssshake** [comment]
I'm a little confused by the nature of this issue. I can't tell if it's related to my problem. For my problem I tried to report a new issue but github keeps 500'ing on me.

Material being unset after a Highlight on Touch object is dropped:

I'm loading textures into materials using Load.Resource(). This creates an instance of a material. When you enable Highlight on Touch, touch an object where this texture is a child, and then drop the object, the material in the mesh renderer's material array is reverted back to the prefab's default. Which could be None or in my case a blank placeholder image. 

![image](https://cloud.githubusercontent.com/assets/1675868/19878354/e1ce7e5e-9fbd-11e6-99bb-0da1eb789be4.png)

The result is that after dropping a card, the image that was one there suddenly isn't. This leads to a magenta box if the default for the prefab is set to None.

**Comment by fight4dream** [comment]
@ssshake Yes, the highlighter (whether the current one or the newer one we gonna PR) are restoring the material/texture to the point Initialize() is called, normally at InteractableObject starts.

@thestonefox I think this is a common usage to highlight/unhighlight back to where it is before, instead of back to where it initialized. what do you think?

**Comment by ssshake** [comment]
If it helps the decision, consider my use case. In my use case I'm rendering playing cards onto a templated prefab. The names of the textures which are loaded from Resource.Load are pulled from a database table. In this use case reverting to the material at initialize will never be what I want.

Understanding that my use case is specific, but this means that the use of Resource.Load cannot be used for any purpose on materials that use your highlighter code.

I've worked around this for now by using the highlight outline script as that doesn't modify the child textures.

**Comment by fight4dream** [comment]
You can try this one in PR https://github.com/thestonefox/VRTK/pull/704
