### ISSUE TITLE
Grabbing doesn't work unless Grab Override button is set

### ISSUE THREAD

**Issue by jlukose12** [thestonefox/VRTK#696]
Why does it require an override? For all objects, the basic grabbable doesn't allow them to be grabbed only after an override.

**Comment by thestonefox** [comment]
Could you provide more information. I'm not sure what your issue is.

**Comment by jlukose12** [comment]
When I am doing Example 005, The basic grabbing example, it doesn't allow me to use the trigger initially to grab the objects (it does allow and recognize touch) . It only allows me to grab once the grab override is set. Is this how the mechanic is set to be? If so, should it be called an override?

**Comment by thestonefox** [comment]
The trigger is not the default grab button set in the ControllerEvents script on the controller.

The default button is `Grip` you can change the default button to `Trigger` via the ControllerEvents script on the controller. If you change the `GrabAlias` to what you want then you don't need to use the overrides.

**Comment by jlukose12** [comment]
Good to know, I'll close this for now, I'll let you know if I run into any problems
