### ISSUE TITLE
Climbing does not support moving InteractableObjects

### ISSUE THREAD

**Issue by JoshGalvin** [thestonefox/VRTK#697]
When you grab a moving Interactable Object with the climb interaction it does not move the player alongside the IO. As a player I expect to move alongside the the IO as if I was attached to it.

**Comment by lucboudreau** [comment]
Hi, I didn't see yours but my code is done for this and can be found here.

https://github.com/thestonefox/VRTK/issues/716

Cheers!

**Comment by thestonefox** [comment]
Merge this in here https://github.com/thestonefox/VRTK/issues/716
