### ISSUE TITLE
Guided Snapping

### ISSUE THREAD

**Issue by xEvoGx** [thestonefox/VRTK#700]
So if I understand, we now have object snapping. In other words we can place one held object near a point in the world, and the held object will immediately snap to this point...

...what if the snapping wasn't immediate?

We could have a threshold (distance of the hand holding the object to snap to the snap point) that once entered, the object being held would begin to 'gravitate' towards the snap point. As you guide the holding-hand closer to the full snapping point, the object would take on more of the final transform until it's then fully snapped? 

The point of this would be to smooth the transition from holding the object to it being placed precisely where it needs to go.

Picture hold a wrench you would use to loosen bolts. Instead of having the wrench immediately appear on a bolt to which you then crank to loosen it, the wrench would start to be drawn to the bolt (magnetic if you will) until it finally settles into the position it needs to, all driven by the proximity of your hand to the bolt.

Make sense?! 😄

**Comment by thestonefox** [comment]
Would this cause an issue with the wrench (or any object) moving away from your grabbed controller feeling as if tracking of the controller has gone haywire?

**Comment by xEvoGx** [comment]
well now this may sound complicated (and perhaps it is) but I was thinking the wrench would still be held, but that it would start to point towards the snap point. 

This really could be difficult, or maybe all that's needed is a 'Look-At', with any given axis just aiming at the point it's going to snap.

Also does the wrench/bolt concept apply, where the snap point of the wrench is NOT the center of the object? That could be an issue too...

**Comment by cameronoltmann** [comment]
I think as long as the snap happens quickly it would be okay.  No slow drift.  Say it lerps there in 1/4 second or so, then lerps back when you leave the snap area.  This will also be less disorienting if you still have some indication of your hand (glove, ghostly outline, something).

Another possible option would be to only snap the object on release, and indicate that a snap would happen with a preview of a transparent/outlined instance of the object.  Eg enter snap zone with wrench, see a translucent green wrench appear in snap zone.  Exit snap zone, see preview object disappear.

**Comment by thestonefox** [comment]
@cameronoltmann the existing drop snap zone already does what you're section option is (if I'm reading it right).

When you place an object over a droppable area you get a highlight preview object

https://www.youtube.com/watch?v=d2PdHTPMYEg

**Comment by cameronoltmann** [comment]
Right, of course it does.  Sorry, my bad.

Yeah if the lerp is quick I don't think it will be disorienting

**Comment by xEvoGx** [comment]
More or less exactly what I was thinking Cameron. No slow drift, just continuity from the hand to the snap point. I likened it to the ease of which a magazine could be loaded into a weapon, but still giving a satisfying interaction 'visually'. Seeing the magazine go into the weapon while still being under your control. This smooths out interactions but not removing player input so we maintain a maximum amount of 'interaction'.

**Comment by thestonefox** [comment]
Gonna close this unless anyone really cares that much :p

**Comment by xEvoGx** [comment]
Well hell I do! 

I was playing around with VRweapons (which uses VRTK) and I didn't like that the magazines immediately snapped into the breach. This is only one example mind you, but otherwise it would just look nicer if there was a transition of the object to the snap point rather than it be immediate. :)

**Comment by thestonefox** [comment]
you can do magazine transition snapping already by just using the transitions on the snap drop zones.

You basically set your snap drop zone to have a transition time and then things would slide into place.

This initial issue (i believe) was about you would hold something and it would then gravitate to a specific location whilst you were still holding it and therefore it would have to become disjointed (or at least dis-oriented) from the grabbing controller.

**Comment by xEvoGx** [comment]
Correct and you know, I'm not certain transitions were in when I posted this, so yea that's most likely just fine. :)
