### ISSUE TITLE
Permit UI interaction on desktop display while using UI Pointer in VR.

### ISSUE THREAD

**Issue by jeremedia** [thestonefox/VRTK#705]
Currently interaction with a screen-space overlay canvas is disabled when the UI Pointer component is active as the UI Pointer disables the Standalone Input Module and enables the VRTK Event System VR Input. 

It is desirable to have mouse-based input remain available to users not in VR for a variety of reasons. Two examples: guided therapy applications where a facilitator controls the experience to support therapeutic goals, and "asymmetric" games where local players compete or collaborate with different views and inputs within a shared world.

In a conversation on the Unity forums concerning how Unity's EventSystem currently supports only one active Input Module a user shares a solution:

https://forum-old.unity3d.com/threads/multiple-processing-inputmodules.369578/#post-2611925

Does this look viable to in the context of VRTK's approach?

**Comment by thestonefox** [comment]
You could just disable the `VRTK_UICanvas` and the `VRTK_UIPointer` scripts at runtime which sets the event system back to the defaults.

Perhaps you could listen for a mouse move event and disable the relevant scripts, then re-enable them back on when the mouse is no longer moving?

This is a work around, I'm not sure how much work is involved in getting the UI to be compatible with varying inputs.

**Comment by GloryFish** [comment]
I'd like to add a comment to this to mention that I'm running into this issue with my game in development. It's a multiplayer game with desktop and VR players. I want either player to be able to set up their characters and Ready up via the UI simultaneously. 

Unfortunately I'm having to build the VR Interface as an entirely separate construction without using Unity GUI. I really wish I could just hang the desktop UI in front of the VR player for now while the game is in early development and come back to the custom interface later.

**Comment by bddckr** [comment]
PR trying to fix this: #927.
