### ISSUE TITLE
Pointer not hitting object once it is grabbed

### ISSUE THREAD

**Issue by jlukose12** [thestonefox/VRTK#706]
I have an object with a mesh collider as the collider object. I have a Simple Pointer on my right controller, which doesn't allow teleport and is strictly used as a pointer(like during a presentation).  However, when I grab the object and I pick it up, I cannot point at this object anymore and have the simple pointer see it as a hit (It will go through the object). I tried it with a cube and a mesh collider and I am able to point my right controller and see it as a hit (while it is being grabbed). 

Any suggestions? Ideas?

**Comment by jlukose12** [comment]
Update, so I included exclude teleport onto the objects and now it doesn't allow me to use my right controller as a pointer(it will not see it as a valid hit, probably due to exclude teleport).

**Comment by thestonefox** [comment]
Are you saying the simple pointer is hitting your object when you've grabbed it?

If so, try putting your object on the `Ignore Raycast` layer then the pointer wont consider it a target.

**Comment by jlukose12** [comment]
No, the simple pointer is not hitting it once I've grabbed the object. I want it to hit the object. Possible?

**Comment by thestonefox** [comment]
So you have the object in your hand and the simple pointer (on the same controller that is grabbing the object) is projected through the object?

**Comment by jlukose12** [comment]
I grab an object with my left hand and want to use my right controller to point at parts of it.
