### ISSUE TITLE
VRTK_UICanvas should consider canvas scale, pivot, etc

### ISSUE THREAD

**Issue by getwilde** [thestonefox/VRTK#708]
If the canvas has a pivot other than 0,0, or has a scale larger than 0.005 (or so), UICanvas creates colliders that are in the wrong position and/or oversized.

The following script will correctly position `frontTrigger`.  
```
Vector2 pivot = canvas.GetComponent<RectTransform>().pivot;
Vector3 localPos = new Vector3(canvasSize.x / 2 - canvasSize.x * pivot.x, canvasSize.y / 2 - canvasSize.y * pivot.y);
frontTrigger.transform.localPosition = localPos;
```
The same essential code can be used to position `canvasBoxCollider`

Incidentally, I also noticed that in current code, if a dev has a canvas set at a scale of, say "1, 1, 1", then VRTK_UICanvas will add `canvasBoxCollider` that's 10 meters deep(!), with z center at 5 meters.

**Comment by thestonefox** [comment]
wanna whack your fix in a pull request?

**Comment by getwilde** [comment]
I'm not very familiar with git. I can give it a shot in after my project deadline has passed (couple of weeks). Or someone else is free to make the change.

**Comment by isaklilja** [comment]
Please make a pull request :)

**Comment by thestonefox** [comment]
@getwilde check out this PR it should fix your issues
https://github.com/thestonefox/VRTK/pull/785

lemme know!

**Comment by getwilde** [comment]
@thestonefox Thank you for this!
