### ISSUE TITLE
Setup Play Space Falling ONLY

### ISSUE THREAD

**Issue by wheatgrinder** [thestonefox/VRTK#709]
Is there anyway to setup play space falling ONLY.  I like the falling, but the automatic "teleporting on top" of stuff doesnt feel good for my game.   Is there anyway to simply disable the HALF of the functionality?  Or maybe override the behavior in some other way?

Thanks

**Comment by thestonefox** [comment]
This is all being re-written soon to make it more customisable.

**Comment by wheatgrinder** [comment]
cool, cant wait.  In the meantime, Im in the middle of a couple week game jam.  Any pointers to where I can hack this in the code directly?  I just want to disable the auto teleport ontop of stuff...

**Comment by thestonefox** [comment]
You can turn that off in the HeightAdjustTeleport script. Play Space Falling is the option i think.

**Comment by wheatgrinder** [comment]
Just FYI for anyone looking for an easy tweak to disable auto teleporting onto things.. 

In the VRTK_HeightAdjustTeleport script inside the DropToNearestFloor sub just comment out one line of code ... 


` private void DropToNearestFloor(bool withBlink, bool useGravityFall)
        {
            if (enableTeleport && eyeCamera.transform.position.y > transform.position.y)
            {
                Ray ray = new Ray(eyeCamera.transform.position, -transform.up);
                RaycastHit rayCollidedWith;
                bool rayHit = Physics.Raycast(ray, out rayCollidedWith);
                float hitFloorY = eyeCamera.transform.position.y - rayCollidedWith.distance;

                if (ValidDrop(rayHit, rayCollidedWith, hitFloorY))
                {
                    if (initialFloorDrop && hitFloorY < previousFloorY && ControllersStillOverPreviousFloor())
                    {
                        return;
                    }
              
                    if (UsePhysicsFall(useGravityFall, hitFloorY))
                    {
                       playerPresence.StartPhysicsFall(Vector3.zero);
                    }
                    else
                    {
                        //comment out the next line of code to prevent auto teleporting up onto stuff. 
                        //TeleportFall(withBlink, hitFloorY, rayCollidedWith);
                    }
                    initialFloorDrop = true;
                }
                previousFloorY = hitFloorY;
            }
        }`

**Comment by thestonefox** [comment]
Just to give you a heads up on this.

All that play space falling stuff is going to be removed from the teleporter code.

Teleporting will just be about moving your position from one location to another.

The player body physics (new version of player presence) will be responsible for things like dropping to nearest floor in the future.
