### ISSUE TITLE
[Suggestion] virtual to physical alignment

### ISSUE THREAD

**Issue by bcoyle** [thestonefox/VRTK#71]
Any thoughts on a system that could be implemented to align the virtual space with the physical? I've already got a few 3d models of various physical locations and would want to align a physical table or chair to a virtual one.

I'd imagine using movement based on the touchpad to move/rotate around to orient with the physical space as the easiest method. Using the passthrough camera to eyeball things.

Next would be a 2 point spacial picking with a controller. To get initial location and rotation, with only X & Z adjustable [Y is up/down, right?]. So you'd pick your physical option, two points like two chair legs or across the seat - then pick similar spots on the virtual object to get an alignment registered.

Anyone else have an interest in this? It'll be particularly cool for folks once it's easier for non 3d modeling folks to build virtual replicas of their play space. I'm also available to help anyone who wants to measure and photograph their play space.

**Comment by thestonefox** [comment]
I really like this concept, it's something I'd like to spend some time on, hopefully I'll get time soon :)

**Comment by bcoyle** [comment]
If you develop anything, I have little projects already that could take advantage of this. Which I can record and share :D

**Comment by bcoyle** [comment]
Any chance for this type of tool to be developed? I could put together a video of it being used once created - taking a 3d scanned room with a table and having it match a physical location. Which could allow for sitting at the table and interacting with objects on it.

**Comment by thestonefox** [comment]
I'd still like to look at this. But time is one of those things that seems to hate me :(

**Comment by kristianpd** [comment]
I think we should close this issue @thestonefox it may be a good idea but I think it's cluttering the list atm.

**Comment by dantman** [comment]
One relevant Steam VR + Vive (or other non-Oculus HMD with a front facing camera) specific trick that can add to whatever is implemented for this.

https://blogs.unity3d.com/2017/06/16/codesnippets-toggle-vives-front-facing-camera-and-tron-mode-at-run-time/

**Comment by reznovVR** [comment]
I would also suggest closing this old issue or possibly provide more information like an example video and more generic use cases. I get the idea but the need for this seems to be kinda limited(?)

**Comment by thestonefox** [comment]
Let's close until someone asks for something like this again.
