### ISSUE TITLE
Add VRTK_UICanvas to ConsoleViewerCanvas?

### ISSUE THREAD

**Issue by gpvigano** [thestonefox/VRTK#710]
I am widely using the `ConsoleViewerCanvas` prefab (an essential tool for debugging, especially on GearVR/Android) and after the latest changes to VRTK UI I had to add the `VRTK_UICanvas` script to it.
What about adding `VRTK_UICanvas` directly to the `ConsoleViewerCanvas` prefab?

**Comment by thestonefox** [comment]
Is the ConsoleViewerCanvas broken now then after that change?

If so I'll fix it.

**Comment by gpvigano** [comment]
It stopped responding to user interaction (like the other UI canvas in my scene). I made a "revert" in Unity inspector, but nothing changed. I had to add the `VRTK_UICanvas` script.

**Comment by gpvigano** [comment]
To banish all doubts: now (after adding `VRTK_UICanvas`) it works perfectly.
I can never thank you enough for this console prefab, it's my salvation...

**Comment by thestonefox** [comment]
Did you see the Unity Unite keynotes yesterday? Unity are bringing the default unity console into VR soon :)

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/386025f966c4d12528cd1304cf68fab8c930210a
