### ISSUE TITLE
PlayerGrab - A better version to support moving objects.

### ISSUE THREAD

**Issue by lucboudreau** [thestonefox/VRTK#716]
Hi everyone.

I've worked on a subclass of the PlayerGrab script that I believe would be of interest to others and probably the core team. 

This subclass supports objects that are moving and rotating, as well as keeping track of the precise snap point through world space. I needed this because I have a) moving objects that I want to climb and b) this script does not need the creating of multiple colliders all over the anchor object. Using it, one can simply add the InterractableObject to any big structure, add this script to the player (like you'd do with PLayerGrab) and set the objects to be Climbable with a precision snap.

That's it. You can now hold on and grab to gigantic objects. 

I had to cheat however, and make a couple members of PlayerClimb public. I figured you'd want to use the algorithm in the core class anyways, so I didn't bother refactoring it into a pull request. I'll let you guys implement this the way you want it, plus there's some of my own code which I'm snipping clumsily in this message, so I'm sure I broke it.

But the essential is there. Thanks for a good VR toolkit. Some stuff works better than others, but overall it helped me a lot. Cheers!

```
namespace VRTK
{
    using UnityEngine;

    public class ShipPlayerClimb : VRTK_PlayerClimb
    {
        private Vector3 MyStartPosition = Vector3.zero;
        private Vector3 AnchorStartPosition = Vector3.zero;
        private Quaternion AnchorStartRotation = Quaternion.identity;

        void Start()
        {
            base.PlayerClimbStarted += new PlayerClimbEventHandler(MyPlayerClimbStarted);
        }

        new public void Update()
        {
            if (isClimbing)
            {
                Vector3 AnchorNewPosition = climbingObject.transform.position;
                Vector3 AnchorDelta = AnchorNewPosition - AnchorStartPosition;
                startPosition = MyStartPosition + AnchorDelta;

                base.Update();
                
                Quaternion AnchorNewRotation = climbingObject.transform.rotation;
                Quaternion RotationDelta = AnchorNewRotation * Quaternion.Inverse(AnchorStartRotation);

                Vector3 DeltaNewAnchorToMyNewPosition = transform.position - AnchorNewPosition;
                Vector3 RotatedVector = RotationDelta * DeltaNewAnchorToMyNewPosition;

                Vector3 Target = AnchorNewPosition + RotatedVector;

                transform.position = Vector3.Slerp(transform.position, Target, Time.deltaTime * 100f);
            }
            
        }
        
        void MyPlayerClimbStarted(object sender, PlayerClimbEventArgs e)
        {
            MyStartPosition = transform.position;
            AnchorStartPosition = e.target.transform.position;
            AnchorStartRotation = e.target.transform.rotation;
        }
    }
}
```

**Comment by thestonefox** [comment]
Maybe @mattboy64 can look at this and see if it's something he can weave into the standard player climb stuff?

**Comment by thestonefox** [comment]
This has been merged with another issue
