### ISSUE TITLE
ForceStopping Interactions still leaves a "link" to the used object

### ISSUE THREAD

**Issue by Tom-LeFx** [thestonefox/VRTK#717]
I'm having issues with "Force-Stopping" object-interactions. I want remove an object from my hand, as soon as i enter some trigger, so i use forcestopinteraction ontriggerenter....that works, but leaves me puzzeled, because when you hide the controller for a while (e.g. put it somewhere the lightposts can't see), the object get's "respawned" at the last known position of the controller. The issue there seems to be, that you somehow call "ForceStopAllInteractions" on some last frame (it's a subroutine), probably when the system looses track of the controllers. This unfortunately seems to have some kind of memory about it's last used object.
The forceStopInteraction should - as far as i understand it - cut all ties between controllers and InteractableObject....AFAIK it does not do that, at the moment...

Is there some way to completely break the ties? Because this is causing a whole lot of issues here atm.

I'd like some simple, clean way to break all bonds, remove the object from the "claws" of VRTK, as soon as it enters some trigger-area....once and for all. Any hints for me?

**Comment by thestonefox** [comment]
Are you saying that if you `ForceStopInteracting` on an object and then straight away hide the controller, then when you re-show the controller, the object that you force stopped on is being grabbed again?

**Comment by Tom-LeFx** [comment]
No, even more strange:Forcestop interaction, put the real controller somewhere the Lightposts can't see, wait a few seconds (10-15) till steamvr deactivates the tracking (shown by the fact that at least one controller becomes invisible in the scene) and then take them back into the tracking zone. In 9 out of 10 cases the formerly force stopped object got reattached to the controller. Sent from mobile.-------- Originalnachricht --------Betreff: Re: [thestonefox/VRTK] ForceStopping Interactions still leaves a "link" to the used object (#717)Von: StoneFox An: thestonefox/VRTK Cc: Tom-LeFx ,Author Are you saying that if you ForceStopInteracting on an object and then straight away hide the controller, then when you re-show the controller, the object that you force stopped on is being grabbed again?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thestonefox/VRTK","title":"thestonefox/VRTK","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thestonefox/VRTK"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thestonefox in #717: Are you saying that if you `ForceStopInteracting` on an object and then straight away hide the controller, then when you re-show the controller, the object that you force stopped on is being grabbed again?"}],"action":{"name":"View Issue","url":"https://github.com/thestonefox/VRTK/issues/717#issuecomment-259009982"}}}

**Comment by Tom-LeFx** [comment]
Ok - added a workaround on our end (don't know if this is, how it should be done and DEFINITELY needs more testing):

After breaking the interaction with ForceStopInteracting, we get the grabbed/touched/used Component of the according controller and apply the respective ForceStop-method on each one as well. Then (to be double sure) we destroy the interactable_object-component on the dropped object. This works for our scenario, but is definitely not a working fix for everyone. It helps, if you only want to pick up and drop an object once, as it cuts all ties when dropping once and for all.
