### ISSUE TITLE
[suggestion/question] Blink between scenes with loading screens

### ISSUE THREAD

**Issue by rmoussawi** [thestonefox/VRTK#72]
Is there a way to move from one scene to another using the blink system? Also I've noticed a lot of applications that will go back to the steamVR scene while loading between scenes. Is there a way to avoid that and use a loading scene in between (similar to what is done with any Lab experiences)

**Comment by xEvoGx** [comment]
Ah I wasn't sure that was a _SteamVR_ thing or _Dev's Choice_...

...I definitely agree with this suggestion

**Comment by thestonefox** [comment]
There is a way of turning off the SteamVR scene between loading levels. I do it in Holodaze.

I wonder if you can stitch a custom image in at that point too? I'll take a look and see.

**Comment by thestonefox** [comment]
@rmoussawi Just to let you know there is stuff in the SteamVR library that lets you change the compositor.

Look in:

 SteamVR.instance.compositor.

(this isn't part of my toolkit, it's part of the SteamVR Unity Plugin)

There is:

 SteamVR.instance.compositor.SetSkyboxOverride

Which takes some VR textures and I'm guessing it replaces the skybox in the compositor with whatever texture you want.

**Comment by thestonefox** [comment]
Also, It's worth looking at

SteamVR_LoadLeve.cs and SteamVR_Skybox.cs in the SteamVR Unity Plugin.

They seem to handle this without needing to delve into the SteamVR library

**Comment by thestonefox** [comment]
I'm not sure if I should address this as part of the toolkit, It seems the SteamVR plugin does a pretty good job at implementing it.

Maybe I'll do an example to show how to implement their work (as they seem to suck at documentation)

**Comment by rmoussawi** [comment]
Sounds like a plan, an example would be great :) :+1:
