### ISSUE TITLE
[Bug] Snap doesn't work on object with only child colliders

### ISSUE THREAD

**Issue by quintesse** [thestonefox/VRTK#723]
When you have a snappable object that has the `VRTK_InteractableObject` script but no Collider and it contains several child objects that *do* have Colliders then you can't do a `ForceSnap()` on it.

This is basically because in several parts of the code it's assumed that for a call to `ForceSnap(objectToSnap)` the following holds true:

    objectToSnap.GetComponentInChildren<Collider>().gameObject == objectToSnap

Which obviously is false in this case.

Relevant code is (in VRTK_SnapDropZone):

        private void AttemptForceSnap(GameObject objectToSnap)
        {
            //force snap settings on
            willSnap = true;
            currentValidSnapObject = objectToSnap;
            //Force touch one of the object's colliders on this trigger collider
            OnTriggerStay(objectToSnap.GetComponentInChildren<Collider>());
        }

and:

        private void OnTriggerStay(Collider collider)
        {
            [snip]
            //if the current colliding object is the valid snappable object then we can snap
            if (currentValidSnapObject == collider.gameObject)

But these aren't the only places.

**Comment by thestonefox** [comment]
Would be helpful to list all the places it is affected if you know where they are.

**Comment by quintesse** [comment]
Well I tried fixing it in `OnTriggerStay()` and then it failed in the next method `SnapObject()` so it probably just goes down the chain :)
I can look at it some more, maybe even come up with a patch, but tonight perhaps, no time now.

**Comment by thestonefox** [comment]
I think this has been resolved

**Comment by KospY** [comment]
I get the same thing with the last version of VRTK. 
The problem doesn't seem to be fixed for me.

**Comment by thestonefox** [comment]
@KospY can you provide steps to reproduce in an example scene? if so, I can re-open the issue.
