### ISSUE TITLE
Access to the Vive front facing camera?

### ISSUE THREAD

**Issue by monodavids** [thestonefox/VRTK#724]
Now that VIVE allows us to turn the camera on and we can see it through Dasboard. Is there any way to access it in Unity3d with VRTX?
kind regards
dave

**Comment by bddckr** [comment]
Have a look at the sample scene that's provided in the SteamVR plugin, [`SteamVR_TestTrackedCamera.unity`](https://github.com/ValveSoftware/openvr/tree/master/unity_package/Assets/SteamVR/Extras).

**Comment by austinmao** [comment]
Here is some good stuff: https://www.reddit.com/r/Unity3D/comments/5l5irg/heres_a_tiny_vive_camera_stream_as_a_texture/

**Comment by reznovVR** [comment]
Shouldn't this old issue be closed as it's not really a generic feature due being limited to a single headset at the moment? for accessing camera there are already several examples including the SteamVR extras or a official blog post by Unity.
