### ISSUE TITLE
FramesPerSecondViewer wrong fps?

### ISSUE THREAD

**Issue by michidk** [thestonefox/VRTK#725]
Hi,
I just noticed that the FramesPerSecondViewer displays a total different FPS than unity.
Why is that? And which FPS count is more accurate?

![unity_2016-11-13_17-42-20](https://cloud.githubusercontent.com/assets/3979930/20247278/acd27ac4-a9c8-11e6-9815-157b6bee2b9f.png)

**Comment by bddckr** [comment]
AFAIK Unity just calculates the max possible frames/second based on its measurements to its subsystems. You can see it in the screenshot: Unity just takes the 8.2ms of the main thread on the CPU. `1 / 8.2ms * 1000 = 121.95fps`

`FramesPerSecondViewer` accumulates the frames in `Update` which is run every frame. So `FramesPerSecondViewer` is more accurate.

**Comment by michidk** [comment]
Thanks for the clarification!
