### ISSUE TITLE
FramesPerSecondViewer

### ISSUE THREAD

**Issue by michidk** [thestonefox/VRTK#726]
If you just use the prefab and assign the camera as shown in the video, the FPS text will look very weird. The example will work though.

That is because on the prefab the camera on the Canvas component is not set at first (which makes sense) and the plane distance field is hidden. As soon as you drag a camera into that field, the "Plane Distance" field will appear. Its default value seems to be 0.1, which wont work for VR. So you have to set it manually to the value from the example, which is 0.5. 

## How to fix this?
Just change the script so, that it will change the plane distance of the canvas component to 0.5 in Awake.

**Comment by thestonefox** [comment]
Done in commit https://github.com/thestonefox/VRTK/pull/729/commits/9f11d0ac1cf6f9941998ba7039293be663ead0db

But the PR isn't merged just yet,

**Comment by thestonefox** [comment]
Fixed in https://github.com/thestonefox/VRTK/pull/729
