### ISSUE TITLE
A moving SnapDropZone leaves object behind during drop.

### ISSUE THREAD

**Issue by arthur5005** [thestonefox/VRTK#732]
Hey guys, was using the `VRTK_SnapDropZone`, (great stuff as always) but had an issue with it today.

Specifically found it in the `UpdateTransformDimensions` method coroutine. 

Because my player is in a vehicle, and they're flying through space pretty quick, during a drop onto the zone in the cockpit, the object gets dropped and left behind a bit before it finishes it's drop. There's no public method to force the position of the snap without running it through a coroutine again.

It's clear this is caused by the support for `snap duration`, which attempts a lerp on the transform values of the object you're dropping and that the drop zone transform values are stale  (even if snap duration is 0)

I've written my own fix for the time being that immediately applies the transform if your snap duration is 0. This fixes the problem in my case, but obviously with this we lose support for snap duration in moving vehicles. Any thoughts on how to properly do this? I don't mind opening a PR for a proper fix.

**Comment by thestonefox** [comment]
I'm aware of the issue. it is worse when using the lerp duration and using parenting as the snap type.

I will look at a fix when I get chance.

**Comment by xdxttt** [comment]
@arthur5005 @thestonefox 

Here is my code to fix this bug. it works in my project.
            
```
private IEnumerator UpdateTransformDimensions(VRTK_InteractableObject ioCheck, Transform end, Vector3 endScale, float duration)`
       {
            var elapsedTime = 0f;
            var ioTransform = ioCheck.transform;
            var startPosition = ioTransform.position;
            var startRotation = ioTransform.rotation;
            var startScale = ioTransform.localScale;
            var storedKinematicState = ioCheck.IsKinematic();
            ioCheck.ToggleKinematic(true);
            while (elapsedTime <= duration)
            {
                elapsedTime += Time.deltaTime;
                ioTransform.position = Vector3.Lerp(startPosition, end.position, (elapsedTime / duration));
                ioTransform.rotation = Quaternion.Lerp(startRotation, end.rotation, (elapsedTime / duration));
                ioTransform.localScale = Vector3.Lerp(startScale, endScale, (elapsedTime / duration));
                yield return null;
            }
            //Force all to the last setting in case anything has moved during the transition
            ioTransform.position = end.position;
            ioTransform.rotation = end.rotation;
            ioTransform.localScale = endScale;
            ioCheck.ToggleKinematic(storedKinematicState);
            SetDropSnapType(ioCheck);
        } 

```

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/ec3e21b02dae790cd1b584b5701f6665c4abcdc3
