### ISSUE TITLE
How to adjust  character height in  walking scene。

### ISSUE THREAD

**Issue by singlewj** [thestonefox/VRTK#741]

**Comment by thestonefox** [comment]
You will need to provide more details regarding your issue otherwise it will be closed.

Also, for general help it's more appropriate to use the slack channel at http://invite.vrtk.io

**Comment by singlewj** [comment]
Get My Invite? I Can not enter this   http://invite.vrtk.io

**Comment by singlewj** [comment]
Thank you for your invitation
