### ISSUE TITLE
005_Controller_BasicObjectGrabbing doesn't grab objects

### ISSUE THREAD

**Issue by kotAPI** [thestonefox/VRTK#744]
I just started using VRTK, I might be lost, but I've tried the 005_Controller_BasicObjectGrabbing scene to grab the objects on the table, they seem to be changing their color on hovering but I'm not able to pick up any of them up with either of the controllers . Am I missing something?

**Comment by thestonefox** [comment]
Best to ask for help like this in the slack channel http://invite.vrtk.io
