### ISSUE TITLE
Being able to call StartUsing twice and StopUsing once

### ISSUE THREAD

**Issue by knexator** [thestonefox/VRTK#748]
When grabbing an interactable object that doesn't require being grabbed for being used (like the guns in scene 13) and touching it with both controllers at the same time, pressing the 'Use' button on one and the the other will cause 'start using' to be called twice, as expected. However, when releasing one and then the other, 'stop using' will only be called once, when the use button is pressed in the second place is released

**Comment by thestonefox** [comment]
Is this still an issue? a lot of work has been done on these areas
