### ISSUE TITLE
VRTK_InteractTouch returns reference to Interactable_Object that's being held. 

### ISSUE THREAD

**Issue by talothman** [thestonefox/VRTK#749]
`GetTouchedObject()` in `VRTK_InteractTouch` returns reference to GameObject being held. Does this make sense? What if one say wanted to be able to grab multiple items?

**Comment by thestonefox** [comment]
`GetTouchedObjected()` returns a reference to the game object being touched `touchedObject`

this isn't the item being held.

**Comment by thestonefox** [comment]
Also, holding multiple items isn't supported.

**Comment by talothman** [comment]
Once grabbed, does `GetTouchedObject()` still return that object that is grabbed? Say for example that grabbed object is attached to ControllerAttachPoint and the controller and the grabbed object do not overlap, does `GetTouchedObject()` still return the grabbed object?

I'm working on multi grab. I have something that's really messy and all over the place but it seems to be working.

**Comment by talothman** [comment]
Example:
https://gfycat.com/UglySpecificGuillemot

**Comment by virror** [comment]
Looks nice : )
