### ISSUE TITLE
The variable controllerAttachPoint of VRTK_InteractGrab has not been assigned

### ISSUE THREAD

**Issue by Bugzoo** [thestonefox/VRTK#753]
It doesn't matter what version of VRTK I use, the error wont go away. Non of the examples work either

**Comment by thestonefox** [comment]
Have you tried in a fresh download and new project in unity?

**Comment by Bugzoo** [comment]
Yep. No matter what project I'm in it's the same error

**Comment by Bugzoo** [comment]
Holy shit!? I had a controller model with custom animations. I switched it back to the normal controller model and now everything works fine. That is weird

**Comment by thestonefox** [comment]
If you have a custom model, then it may have different sub elements and the SDK cannot find the default attach point. In these cases you'll need to manually specify the controller attach point on the `InteractGrab` script parameter.
