### ISSUE TITLE
I'm having an issue with collisionfade/headsetfade

### ISSUE THREAD

**Issue by MarkTheLily** [thestonefox/VRTK#757]
I made  NPC, which uses cone collider as trigger like a vision.
But when I step into the cone collider, even though its not rendered it detects collision and activates headsetfading function.

I'm trying to use VRTK climbing but, it makes character ignore raycast, I have to turn it off, after I launched the game, I need it to be in default, for my NPCs code to work.

VRTK_HeightAdjustTeleport works on none rendered objects, I have a simple trigger on the door and as I move over it it blinks Y on top of invisible item. I managed to fix this by adding tags on triggers.

I really need help I'm stuck on this same problem for a week now.
I can figure out raycast, but if we cant fix headset fading can you help me turn it off?
Thank you.

**Comment by thestonefox** [comment]
You can use a policy list on the headset collision script to ignore objects that have a specific tag, script or are on a specific layer.

If you set your policy list on the headset collider script to ignore your objects that are causing unwanted fading then it will no longer fade.

This is the same for the height adjust teleporter, you can exclude locations from being teleportable.

**Comment by MarkTheLily** [comment]
Climb script adds headset collision + fade on its own to [camera rig]'s eye, after You start the game.
Should I add the headset collision script on eye myself?

**Comment by thestonefox** [comment]
The latest version of VRTK on github master should no longer auto add the headset collision or fade script, you're expected now to add them manually.

**Comment by ymarzack** [comment]
Nice !
