### ISSUE TITLE
[Camera Rig ] automatically changes layer to Ignore raycast.

### ISSUE THREAD

**Issue by MarkTheLily** [thestonefox/VRTK#759]
I use VRTK_climbing and VRTK_heightadjustment.
When I start the game the [Camera rig] changes from Default layer to Ignore Raycast.
Does anyone know how keep it in default layer? So it will be affected by raycast from npcs
I'm pretty sure Player_Presence is doing it.

**Comment by thestonefox** [comment]
duplicate of https://github.com/thestonefox/VRTK/issues/543
