### ISSUE TITLE
VRTK_UIGraphicRaycaster Being Disabled inside VRTK_UICanvas + Fix/Solution

### ISSUE THREAD

**Issue by DenverCoulson** [thestonefox/VRTK#760]
VRTK_UIGraphicRaycaster gets disabled if defaultRaycaster (as in the original GraphicRaycaster) doesn't exist. This is because VRTK_UIGraphicRaycaster inherits GraphicRaycaster thus it is assigned as defaultRaycaster.

Switching
`if (defaultRaycaster && defaultRaycaster.enabled)` 
to 
`if (defaultRaycaster && defaultRaycaster.enabled && !(defaultRaycaster is VRTK_UIGraphicRaycaster ))`
fixes this issue.

Original Code Below
`
if (defaultRaycaster && defaultRaycaster.enabled && !(defaultRaycaster is VRTK_UIGraphicRaycaster))
{
                     customRaycaster.ignoreReversedGraphics = defaultRaycaster.ignoreReversedGraphics;
                     customRaycaster.blockingObjects = defaultRaycaster.blockingObjects;
                     defaultRaycaster.enabled = false;
}`

**Comment by thestonefox** [comment]
How have you got into a situation where the original GraphicRaycaster doesn't exist? This should be automatically created on any UI Canvas added to the scene.
