### ISSUE TITLE
VRTK_UICanvas Destroying Colliders it did not create

### ISSUE THREAD

**Issue by DenverCoulson** [thestonefox/VRTK#761]
OnEnable() properly checks if a BoxCollider already exists and doesn't create one if it does. However, it doesn't keep that as a reference to later Destroy for OnDisable() (inside of RemoveCanvas()).

Because of this, if you disable and re-enable a VRTK_UICanvas, it will destroy a BoxCollider it did not create. 

VRTK_UICanvas::RemoveCanvas() Line 156
```
 var canvasBoxCollider = canvas.gameObject.GetComponent<BoxCollider>();
 if (canvasBoxCollider)
 {
  Destroy(canvasBoxCollider);
 }
```

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/49ccf2746c43318cb5cfcb9d80aa018fbb63d3f6
