### ISSUE TITLE
Support Oculus Avatar when using the Oculus SDK

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#765]
At the moment the Oculus SDK support offers basic OVRCameraRig support

It would also be good to provide additional customisations if the Oculus Avatar package is also installed.

**Comment by Igameart** [comment]
I got Avatar support added int manually, it's quite easy to do honestly.

**Comment by thestonefox** [comment]
@Igameart yeah avatar support is easy enough, but it requires some additional niceties like custom collider shapes for the controllers and auto populating the model parameters in the SDK Manager.

The rest of it is just a case of docs on how to set up Avatars with Unity.
