### ISSUE TITLE
Ragdolls + Grab Interactions

### ISSUE THREAD

**Issue by SpencerMalone** [thestonefox/VRTK#768]
Hey, I've been trying to figure out how to get ragdolls working as interactable objects. Specifically, I've been having trouble with the grab interactions. My hope was that we could come up with a way to support the ragdolls generated by Unity's ragdoll wizard? I know one hurdle is changing it so that we look at the children's rigidbodies as well as the object itself, but even after that I still can't get any of the different object tracking methods to work.

**Comment by lacvapps** [comment]
One solution is to have an empty parent that has a kinematic rigid body and is the interactable object I have been doing this with success using puppet master

**Comment by thestonefox** [comment]
@SpencerMalone let me know if @lacvapps solution works, if so we can close this issue.
