### ISSUE TITLE
Swinging objects pass through others

### ISSUE THREAD

**Issue by Igameart** [thestonefox/VRTK#770]
Just as described, item picked up with motion controller, specifically in my case an oculus touch controller, while moved even slowly toward an object will pass into it, and when swung quickly will completely bypass the collision event and just go right through it. I've enabled continuous collision checking and that still doesnt improve the physical interactions.

**Comment by Igameart** [comment]
Are grabbed items being "teleported" to the hand location or physically being moved there? This teleporting can cause things to not act properly when held items are moved towards them.

**Comment by thestonefox** [comment]
@Igameart objects are not teleported, they are moved depending on the grab mechanic you use.

For your case, you're better off with the `Track Object` grab mechanic

as mentioned in this issue: https://github.com/thestonefox/VRTK/issues/687#issuecomment-255572015
