### ISSUE TITLE
Path constraints?

### ISSUE THREAD

**Issue by MarkTheLily** [thestonefox/VRTK#775]
I want to move object on single path, like in 3ds max path constraints.
There are some versions of path constraints that you can incorporate in Unity.
But most of them are oriented for NPC movements.
how does Hot Dogs, Horseshoes & Hand Grenades dev make the weapon attachments attach to specific path which is positioned on objects?
If you know easy path constraint asset or code I would love to hear about it.

**Comment by thestonefox** [comment]
This isn't really a VRTK issue.

I'd recommend asking in the VRTK slack channel for more generic game related issues: http://invite.vrtk.io
