### ISSUE TITLE
Radial Menu Offset not working correctly

### ISSUE THREAD

**Issue by AMessVR** [thestonefox/VRTK#784]
Hi there!

First of all THANK YOU for this awesome piece of work! This really helped me a lot!

I'm using the radial menu on the touchpad to do some selection menues and I came across a bug:
When I use the offset option for let's say 30° the buttons are visually moving to the right for 30° but the touch is moving 30° to the opposite direction.

I tried to just change the offset by multiplying it with -1 but nothing really changes... Any suggestions?

**Comment by thestonefox** [comment]
Can you provide some screenshots maybe of the issue you're seeing?

**Comment by thestonefox** [comment]
Check this fix, see if it works for you: 

https://github.com/thestonefox/VRTK/pull/789

**Comment by thestonefox** [comment]
should be fixed with https://github.com/thestonefox/VRTK/pull/789
