### ISSUE TITLE
VRTK Body Physics doesn't allow for moving floors

### ISSUE THREAD

**Issue by sbmhome** [thestonefox/VRTK#794]
When making a simple cube or bucket (made out of multiple cubes) and I place the camera rig or play area in there, there doesn't seem to be proper collisions for moving the player up.

The old "Player Presence" handled this pretty good, but seems that the "VRTK Body Physics" doesn't allow moving floors such as elevators.

**Comment by thestonefox** [comment]
So you're putting the camera rig on a platform and moving the platform upwards?

How are you moving the platform upwards? with `transform.position`? or with rigidbody movement?

**Comment by sbmhome** [comment]
i have a platform (a simple flat cube), that the player can walk on. 

When the player walks on the platform, they push a button that then moves the platform up, by the platforms transform.position.

Since the camera rig has a capsule collider, the platform should raise the camera rig, but it's going thru it. 

Note: I've made sure it's not an issue with layers.

**Comment by sbmhome** [comment]
Just thought I would add, I'm moving the platforms rigidbody using  Dotween.

**Comment by thestonefox** [comment]
I've tried moving a platform up and down with both `transform.position` and adding a rigidbody to the platform and moving it with `rigidbody,MovePosition` and both time the player collider moves up and down correctly with the platform.

**Comment by sbmhome** [comment]
This can be closed out.

I've just tried in a empty scene and got it to work. There must be an issue with my setup.

**Comment by sbmhome** [comment]
Ok, I've found out more info on this and can better replicate the issue.

It seems that if the headset is moving, then the platform will go thru the Camerarig collider.

**Comment by thestonefox** [comment]
that's because if you move around the body physics disables the rigidbody to allow you to walk through walls (and not create push back)

You could try decreasing the `movementThreshold` when you're standing on a lift to 0, so whenever you move the headset updates.

(i think reducing the number is the correct way, it could be increasing it, but either way that should help)

**Comment by sbmhome** [comment]
Just tied increasing and decreasing the movementThreshold to various values (from 0 to 100). Nothing seems to work 100% of the time.

If I keep my headset still before moving the platform, even if isMoving is forced always be false, the platform will just go thru the rigid body.

When I turn my head, it seems to work ok at first but then 1/2 way up on the platform, the platform goes thru the rigid body of the player.

I've got this issue even within a stripped down scene.

**Comment by sbmhome** [comment]
I can stay on the platform if I walk around using touchpad walking....once I stop walking it sometimes goes thru the players rigidbody.

**Comment by sbmhome** [comment]
Would it be helpful to make a video showing the issue?

**Comment by thestonefox** [comment]
No, it's ok. I'll try and recreate the issue today.

**Comment by thestonefox** [comment]
Actually yes it may be worthwhile making a video

**Comment by thestonefox** [comment]
I had another go at recreating the issue. I was able to create a lift that moved me up and down without using a rigidbody on the lift/elevator.

Here is a video showing what I've done:

https://www.youtube.com/watch?v=p5Y0Ean8Iis

**Comment by sbmhome** [comment]
Got it. I'll make one later on today when I get to my computer.

**Comment by sbmhome** [comment]
Here is a video. I was able to replicate the issue even without removing Height Adjust Teleport....but that seems to make it happen easier.

The key seems to be to move headset around, then stay extremely still.


http://www.youtube.com/watch?v=vXOKTaAGUww

**Comment by sbmhome** [comment]
As I mentioned  in the video...the capsule collider on the playArea is going kinematic when the issue happens.

**Comment by thestonefox** [comment]
@sbmhome do you need the rigidbody on your lift?

(I haven't attempted to recreate the issue yet, but that's just a thought)

**Comment by sbmhome** [comment]
I do not need the rigidbody and have tried it with and without it, but get the same result.

**Comment by thestonefox** [comment]
And how does the lift get moved up and down? with transform.position? or is it an animation? (which i guess translates into a transform.position)

**Comment by sbmhome** [comment]
I'm using "Dotween" tweening to move it. It is using the transform position.

**Comment by sbmhome** [comment]
If you disable Height Adjust Teleport, that makes it easier to see the issue

**Comment by thestonefox** [comment]
Do you need the height adjust teleporter disabled? That's the thing keeping you tracking on your y position

**Comment by sbmhome** [comment]
I just changed the "snap to floor settings" in body physics to "ignore everything ".. it was previously set to 1 layer (Ignore raycast).

That seems to have fixed the issue. Ill continue to test.

**Comment by sbmhome** [comment]
I thought the Height Adjust Teleport was only if you use teleporting....I re-enabled that well.

**Comment by thestonefox** [comment]
The height adjust teleporter will work in conjunction with the body physics script to keep you snapping to the nearest Y floor. it helps for smoothing out crazy physics.

**Comment by sbmhome** [comment]
We can close this one out. 

The solution was change the ignore layers to Everything from ignore Raycast
