### ISSUE TITLE
ToggleBeam(false) not working with Bezier pointers

### ISSUE THREAD

**Issue by broehl** [thestonefox/VRTK#797]
ToggleBeam(true) works fine, and displays the Bezier pointer.

ToggleBeam(false) does not work -- the cursor and the curved arc remain visible in space.

In glancing through the code, I notice that in VRTK_BasePointer.cs, the DisablePointerBeam() method just calls TurnOffBeam(), which is the same method that ToggleBeam(false) calls, so it works fine. 

However, in VRTK_BezierPointer.cs the overridden DisablePointerBeam() method also calls TogglePointerCursor(false) and curvedBeam.TogglePoints(false), neither of which get called when ToggleBeam(false) is used.

Maybe override TurnOffBeam() in VRTK_BezierPointer, instead of overriding DisablePointerBeam()?  Not sure if that's the cleanest solution or not.

**Comment by thestonefox** [comment]
PR to resolve the issue: https://github.com/thestonefox/VRTK/pull/798
