### ISSUE TITLE
Not able to toggle UIPointer on and off

### ISSUE THREAD

**Issue by isaklilja** [thestonefox/VRTK#799]
I'm missing a way to toggle the UIPointer on and off. When I simply disable and enable the script, I get the following error: `InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.Collections.Generic.List1+Enumerator[VRTK.VRTK_UIPointer].VerifyState () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:778)
System.Collections.Generic.List1+Enumerator[VRTK.VRTK_UIPointer].MoveNext () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:784)
VRTK.VRTK_EventSystemVRInput.Process () (at Assets/VRTK/Scripts/Internal/VRTK_EventSystemVRInput.cs:19)
UnityEngine.EventSystems.EventSystem.Update () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/EventSystem.cs:287)`

When I comment out `cachedEventSystemInput.pointers.Remove(this);` in the OnDisable method in the UIPointer script, it works fine. However, I suspect that this line is there for a reason.

**Comment by thestonefox** [comment]
What version of unity are you using and what version of VRTK are you using (one from Unity Asset Store or the latest master from github?)

I've just tried disabling the UIPointer script in the example scene `034_Controls_InteractingWithUnityUI` and I am not getting any issues.

**Comment by isaklilja** [comment]
Latest master from GitHub and Unity version 5.5.0f3

I trigger UIPointer.enabled = false when I click an UI button. The point is to disable the user from interacting with the UI before another action is performed.

**Comment by thestonefox** [comment]
You can't disable the pointer at the point a UI button is clicked because the EventSystem is still active during that frame and the pointer is a required object.

You can run your disable code at the end of the frame using a Coroutine and yield on `WaitForEndOfFrame`

This will ensure the event system has finished it's processing before you disable the pointer.
