### ISSUE TITLE
Pointer Origin Transform help.

### ISSUE THREAD

**Issue by maxkofford** [thestonefox/VRTK#800]
So i wanted to rotate the pointer origin for the simple pointer (so its oriented pointing straight down from the controller instead of pointing towards the front) but i cant figure out how to get it to work.  Whenever i set a empty game object as the "Pointer Origin Transform" in the VRTK_Simple_Pointer script, it doesnt appear to do anything (the pointer continues to point in the same direction).  It also says it uses the transform the script is attached to as the new origin by default, but its transform seems to get reset back to position 0,0,0 rotation 0,0,0 when it gets auto attached to the controller by the sdk manager as the script alias for the controller.  I didnt seem to find a tutorial anywhere on how to use this one specific part of the pointer script and i was wondering if anyone had a tip of how to get it working?

**Comment by thestonefox** [comment]
Try the latest version on github master, an  issue with this was fixed today

**Comment by maxkofford** [comment]
Ah yea the latest version does seem to fix this.
