### ISSUE TITLE
Permit instantiation of VRTK_Control objects at run-time.

### ISSUE THREAD

**Issue by jeremedia** [thestonefox/VRTK#801]
It does not appear that VRTK_Control objects, buttons particularly, are designed to support run-time instantiation.

- The code technique used to enable UnityEvents on controls prohibit subscription to instantiated controls as the intended events are always null.
- Use of Awake to call CreateTriggerVolume results in buttons that do not respond to interactions. 

Run-time instantiation of controls is important for data-driven VR applications, more so than experiences or games. Would you be interested in a PR that addresses these issues?

**Comment by thestonefox** [comment]
Always worth raising a PR if you have ideas or suggestions, even if a PR isn't merged it's always a good way to start a discussion.

**Comment by jeremedia** [comment]
Great, will do.
