### ISSUE TITLE
Improve documentation of enums

### ISSUE THREAD

**Issue by bddckr** [thestonefox/VRTK#804]
If we name enums `LikeThis` instead of `Like_This` they show up way better in the inspector:
`Like This` instead of `Like_This`.
To document enum cases the documentation should be done on the case itself. This probably means to update the doc generator for this. We get no documentation in IDEs otherwise. :disappointed:
The contributing document should probably be updated to name the new enum convention.

From
```C#
/// <summary>
/// Allowed controller type.
/// </summary>
/// <param name="Both">Both controllers are allowed to interact.</param>
/// <param name="Left_Only">Only the left controller is allowed to interact.</param>
/// <param name="Right_Only">Only the right controller is allowed to interact.</param>
public enum AllowedController
{
	Both,
	Left_Only,
	Right_Only
}
```

To
```C#
/// <summary>
/// Allowed controller type.
/// </summary>
public enum AllowedController
{
	/// <summary>
	/// Both controllers are allowed to interact.
	/// </summary>
	Both,
	/// <summary>
	/// Only the left controller is allowed to interact.
	/// </summary>
	LeftOnly,
	/// <summary>
	/// Only the right controller is allowed to interact.
	/// </summary>
	RightOnly
}
```

I'll take a stab at creating a PR for this soon. 😄

**Comment by thestonefox** [comment]
PR with fix https://github.com/thestonefox/VRTK/pull/1465
