### ISSUE TITLE
SetWorldCanvas removed in 3.0, causing old bug to happen again

### ISSUE THREAD

**Issue by AzzyDude24601** [thestonefox/VRTK#806]
I upgraded to 3.0 and it has caused a previously resolved bug to start occurring for me again. 

Here is a link to the previous issue: https://github.com/thestonefox/VRTK/issues/679#issuecomment-255418427

SetWorldCanvas does not seem to exist in 3.0. Is there a new method of calling SetWorldCanvas or is it supposed to happen automatically now?

**Comment by thestonefox** [comment]
You no longer need to set canvases, as any VRTK canvas now should contain a VRTK_UICanvas script on them.

If you want the canvas to not be interactable then you can simply disable that script.

**Comment by AzzyDude24601** [comment]
Oh, I see. I didn't notice that in the new documentation. Thank you.

**Comment by AzzyDude24601** [comment]
Just while I have your attention. Is there a place you've documented how to re-write your code to work in 3.0? 

For example, all the different 'grab attach mechanics' have separate scripts now, so I'm unsure how to set them on my Interactable Objects. Is this explained somewhere?

**Comment by thestonefox** [comment]
I've put it all in a video on the new youtube channel:

https://www.youtube.com/watch?v=tMz04CqAYjw&t=1s

**Comment by AzzyDude24601** [comment]
Aha, I was looking at TheStoneFox channel. Thanks again.
