### ISSUE TITLE
VRTK_TouchpadWalking doesn't add a rigid body.

### ISSUE THREAD

**Issue by jostster** [thestonefox/VRTK#810]
Adding the VRTK_Touchpad Walking script to the [CameraRig] will not generate a rigid body on play. This allows for the camera to run through objects.

**Comment by thestonefox** [comment]
It's not supposed to. If you want a rigid body you have to add the body physics script as well. Check the touchpad walking example scene for more details

**Comment by jostster** [comment]
That worked. Sorry was going based on your youtube video which said to just use the Touchpad script. One issue I did notice though is when stopping by letting off the touchpad you slow down then stop, however, you will slowly drift in a random direction sometimes very slowly. I can open an issue for this later if I can get more info on it.
