### ISSUE TITLE
SteamVR Plugin 1.2.0 has been changed SteamVR_Utils

### ISSUE THREAD

**Issue by gaozhe3321** [thestonefox/VRTK#811]
SteamVR Plugin 1.2.0 has been changed SteamVR_Utils
there is no SteamVR_Utils.event any more

**Comment by thestonefox** [comment]
* Replaced SteamVR_Utils.Event with SteamVR_Events.<EventName> to avoid runtime memory allocation associated with use of params object[] args.
* Added SteamVR_Events.<EventName>Action to make it easy to wrap callbacks to avoid memory allocation when components are frequently enabled/disabled at runtime.

**Comment by gaozhe3321** [comment]
So.
How to Fix Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs(732,27): error CS0117: `SteamVR_Utils' does not contain a definition for `Event'

**Comment by thestonefox** [comment]
I dont know yet. I haven't looked into it

**Comment by thestonefox** [comment]
PR to attempt to fix the issue: 
https://github.com/thestonefox/VRTK/pull/812

**Comment by thestonefox** [comment]
Dont close it yet, this may not be the final solution  :)

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/53dc577ee9e4e85ba555e82890422e4f1ced2111

**Comment by jostster** [comment]
@thestonefox can you update the Unity Asset Store when you get a chance?

**Comment by thestonefox** [comment]
@jostster version 3.0.1 has already been pushed to the Unity Asset Store, it just takes a few days for Unity to review things.
