### ISSUE TITLE
Assets/VRTK/SDK/SteamVR/SDK_SteamVRController.cs(732,27): error CS0117: `SteamVR_Utils' does not contain a definition for `Event'

### ISSUE THREAD

**Issue by futer24** [thestonefox/VRTK#822]
Unity 5.5.0f3
SteamVR 1.2.0

**Comment by futer24** [comment]
Fixed with the following lines:

SteamVR_Events.System("TrackedDeviceRoleChanged").Listen(OnTrackedDeviceRoleChanged);
private void OnTrackedDeviceRoleChanged(VREvent_t   args)

**Comment by thestonefox** [comment]
Also fixed by using version 3.0.1 of vrtk

Check the FAQs

 https://vrtoolkit.readme.io/docs/frequently-asked-questions
