### ISSUE TITLE
Some Controller Events not fired in Simulator and controller-finding inconsistent

### ISSUE THREAD

**Issue by burnedikt** [thestonefox/VRTK#832]
When trying to develop without any VR-Hardware, the simulator comes in really handy. However, I noticed that some events on the simulator (e.g. touchdown, touchup, touched on any buttons) are never fired. While it makes sense to not fire those events from a technical perspective (since we cannot distinguish between press and touch on a keyboard) it makes developing a whole lot harder, since a developer potentially has to use different types of events during development (Simulator) and in production (HMD). 

Furthermore, the Simulator SDK right now does not allow for finding script alias controllers. Whenever the calls to get a controller (e.g. `GetControllerLeftHand` or `GetControllerByIndex`) are used, the boolean `actual` parameter is simply ignored and the actual controllers are always returned. This is not in line with the base implementation or the implementation for SteamVR.

To mitigate both problems I've put up a PR [here](https://github.com/thestonefox/VRTK/pull/831).

**Comment by thestonefox** [comment]
The fix is definitely a ❤️ 

The touch implementation i'm still unsure of whether separate keymaps for the touch events would be better? thoughts :)

**Comment by burnedikt** [comment]
Moved the discussion to https://github.com/thestonefox/VRTK/pull/831
