### ISSUE TITLE
SimplePointer starts and stops interacting with objects repeatedly

### ISSUE THREAD

**Issue by aantn** [thestonefox/VRTK#833]
When the "Interact With Objects" option is enabled on SimplePointer the events InteractableObjectTouched and InteractableObjectUntouched are often repeatedly called one after another when the pointer remains on the same object. If you add a highlighter to the object, you can see it flicker as a result of this.

**Comment by thestonefox** [comment]
What version of vrtk are you using? Also did you get it from git hub or unity asset store. Also what version of unity are you on?

Finally are you able to recreate the issue in a vrtk  example scene and provide steps on how to recreate?

**Comment by aantn** [comment]
I'm using the released zip for 3.0.1, Unity version 5.5.0f3, and the latest version of SteamVR. Here are steps for reproducing this:

1. Edit WhirlyGig.cs and add a print statement to the beginning of the StartUsing function.
2. Open scene 019_ControllerInteractingWithPointer.
3. Activate the pointer and point it at Whirlygig(2) for several seconds.
4. Check the debug console. In my testing, StartUsing is called continuously for as long as you point at the Whirlygig(2) with the pointer.

**Comment by thestonefox** [comment]
@aantn confirmed bug thanks for the steps to reproduce.

I'll look at fixing it tomorrow!

**Comment by thestonefox** [comment]
PR to fix https://github.com/thestonefox/VRTK/pull/837

Let me know if it's working for you and I'll merge it if it's all good

**Comment by aantn** [comment]
That was fast :)
I won't be able to check until Friday. I'll update you then.

**Comment by aantn** [comment]
Thanks, that fixes the double calls to StartUsing.

**Comment by aantn** [comment]
Hey, I'm still experiencing a similar issue where objects are touched/untouched repeatedly. The best way I can reproduce this is by enabling the highlighter on relatively distant objects and pointing at them with the pointer so that they are highlighted. The highlight (sometimes) flickers incessantly.

I can't reproduce this reliably in the same scenes - I've seen it happen there once or twice, but I can't determine what triggers the bug. I'll keep trying to reproduce this reliably.
