### ISSUE TITLE
VRTK broken with new SteamVR Plugin version

### ISSUE THREAD

**Issue by Torlig** [thestonefox/VRTK#834]
Console outputs "SDK_SteamVRController.cs(732,27): error CS0117: `SteamVR_Utils' does not contain a definition for `Event'" and the fallback headset, controller and boundaries are used by the SDK manager.

**Comment by Vytek** [comment]
Please download and use last version of VRTK from Github. SteamVR 1.2 with VRTK 3.0.1

**Comment by xEvoGx** [comment]
Just delete the SteamVR folder before upgrading it. I ran into this problem myself and it was merely an unnecessary script...

**Comment by thestonefox** [comment]
@Torlig it's worth searching the github issues before posting and it's also worth reading the FAQ at

https://github.com/thestonefox/VRTK/blob/master/FAQ.md

To save yourself time in fixing a common issue.
