### ISSUE TITLE
Ensure Unity magic methods are all `protected virtual` in VRTK scripts

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#835]
https://docs.unity3d.com/ScriptReference/MonoBehaviour.html

If any VRTK script uses a MonoBehaviour method and is set to private, it then means it's not possible to override that method.

**Comment by quintesse** [comment]
Yes please!
I was setting them to `protected virtual` myself in my local copy :)

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/863
