### ISSUE TITLE
Can't Select Objects Properly w/ Oculus SDK

### ISSUE THREAD

**Issue by Exguardi** [thestonefox/VRTK#836]
Steps to reproduce are:
1) Import OVR SDK + Avatar SDK
2) Import VRTK
3) Create a new scene
4) Drop OVRCameraRig and LocalAvatar prefabs into the scene
5) Drop VRTK Manager, PlayArea, LeftController, and RightController into the scene
6) Configure as per Oculus VRTK set-up video, set "interact with objects" on SimplePointer
7) Create a plane and a cube with InteractableObject and a rigidbody on the cube, set "grabbable" and highlight yellow
8) Notice that the cube does not highlight except at certain angles when the beam is pointed at it

Optional:
1) Attach a simple locomotion script to the OVRCameraRig, move its transform on keypress
2) Notice that the controllers "jump" visibly in place when movement starts
3) Notice that the cube's highlighting works properly only while moving the transform forward

**Comment by thestonefox** [comment]
I've got a fix for the highlight issue.

I've not noticed any issues with moving the camera rig

**Comment by thestonefox** [comment]
PR for fix: https://github.com/thestonefox/VRTK/pull/841

**Comment by Exguardi** [comment]
Unfortunately I am still getting the same issue after pulling in the fix.

If I drop an interactable cube into my scene, I can target "some" sides of it but not others; but the second I use a locomotion script, -only while in the middle of moving forward- I can target the entire cube.

**Comment by thestonefox** [comment]
Check in the scene inspector how big the object objector collider is. It should be slightly larger than the pointer tip

**Comment by Exguardi** [comment]
It appeared to be a merge issue; once I got the correct file, I can now select things properly.

However I now "occasionally" get the following error after grabbing an object with the pointer beam and ending Play mode (doesn't seem to matter if I am still holding the object or not)--

`MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
VRTK.VRTK_SimplePointer.ResizeObjectInteractor () (at Assets/VRTK/Scripts/Pointers/VRTK_SimplePointer.cs:209)
VRTK.VRTK_SimplePointer.TogglePointer (Boolean state) (at Assets/VRTK/Scripts/Pointers/VRTK_SimplePointer.cs:202)
VRTK.VRTK_BasePointer.DisableBeam () (at Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs:523)
VRTK.VRTK_BasePointer.OnDisable () (at Assets/VRTK/Scripts/Pointers/VRTK_BasePointer.cs:141)
VRTK.VRTK_SimplePointer.OnDisable () (at Assets/VRTK/Scripts/Pointers/VRTK_SimplePointer.cs:52)`

**Comment by thestonefox** [comment]
Ok cool, I'll update the PR with that addition.

Do you think it's ready to merge the PR after that extra check?
