### ISSUE TITLE
Replace usage of Follow class with VRTK_ObjectFollow

### ISSUE THREAD

**Issue by bddckr** [thestonefox/VRTK#839]
The existing class `Follow` does the exact same thing as `VRTK_ObjectFollow`. After #796 is merged usage of `Follow` should be replaced with `VRTK_ObjectFollow`.

I think `Follow` is only used in the archery example scene.

**Comment by thestonefox** [comment]
I've done this sneakily in https://github.com/thestonefox/VRTK/pull/852

as I had to update all the scenes anyway

**Comment by thestonefox** [comment]
Resolved with https://github.com/thestonefox/VRTK/commit/b94b98126c36411b7371a242a9b654eb4e83718d
