### ISSUE TITLE
Simulator SDK's reported angularVelocity values are broken

### ISSUE THREAD

**Issue by bddckr** [thestonefox/VRTK#840]
It looks like the Simulator SDK reports too big values for the angular velocity of the headset and always zero for the controllers. (Compared to the only SDK we know of that reports *correct* values: SteamVR.)

Also: Because the Oculus SDK is broken in regards to its reported angular velocities we calculate the angular velocities ourselves in that SDK, too. It would make sense to extract the above Simulator SDK fix into `VRTK_SharedMethods` (or a new helper class that goes into the `Internal` folder) and use that one in all the SDKs.

Possible angular velocity calculation links:
http://answers.unity3d.com/answers/890259/view.html
https://forum.unity3d.com/threads/manually-calculate-angular-velocity-of-gameobject.289462/#post-2710972
Averaging Quaternions:
http://wiki.unity3d.com/index.php/Averaging_Quaternions_and_Vectors

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/pull/1217
