### ISSUE TITLE
Improve SDK button mapping

### ISSUE THREAD

**Issue by bddckr** [thestonefox/VRTK#842]
After some discussion on Slack about the current state of button mapping in VRTK, SteamVR, OpenVR and Unity it looks like there is a problem with the current button mapping somewhere because a button is mapped "wrong" when using SteamVR vs. Oculus SDK.

That discussion led to an idea by @BenWoodford:

> what like Button1 has a list (or mask so it uses Unity's multi select stuff?) you can add SDK buttons to? And each SDK in the project (I guess you'd have to have a list of SDKs in the VRTK manager script that you can select which ones you want to use from)
>
> At a higher level, VRTK_SDKManager would give you a list of SDKs (in an ideal world, it wouldn't be a hardcoded list so you could drop in something like a PS4 easily, idk how possible that is though)
> And you check the SDKs you want to use
> Then there's a list of Button Aliases, and you can select which buttons from each SDK apply to each alias
> So you could set Button1 to be App menu on Vive, X or whatever on Touch, X on PSVR
> etc
>
> Hell, you could make X and Square on PSVR the same button then
> Ah yeah, a section for each SDK may be a bit cleaner than having every button from every SDK under one Bitmask selector for each alias.
>
> Like I said, bonus points if you can make the whole SDK process plugin-based so that us PSVR registered folk could write a PSVR plugin that VRTK doesn't need to know about (and shouldn't, as you wouldn't be able to bundle it I suspect, worth checking with Sony though)
> It could just be a List<SDK_BaseSystem> for that though, and you add the relevant SDKs to that from what the user has in their library

Some ideas...
Change the base SDK:
- Add `abstract string name` that identifies the SDK.
- Add `abstract Type buttonEnumType` that returns the type of the custom SDK button enum (which uses an `int` as the underlying type).

On every editor script compile (and once in a build at runtime) get every type, search for subclasses of the base SDK. Cache the base SDK subclasses by name in a `Dictionary<string, Type>`.

Now for the button alias stuff in VRTK you replace it with something like `Dictionary<string, int>` which maps the buttons to use to the SDK name.
That will get a custom editor inspector that uses the above cached dictionary so you don't type in the SDK name. You select the SDK from a dropdown instead.

At runtime the button alias thing will be used by looking up the SDK and using the provided enum bitmask value...

Things to use to make this work:
https://docs.unity3d.com/ScriptReference/Callbacks.DidReloadScripts.html
https://docs.unity3d.com/ScriptReference/InitializeOnLoadMethodAttribute.html
https://docs.unity3d.com/ScriptReference/ExecuteInEditMode.html
https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html

**Comment by thestonefox** [comment]
@bddckr  Would the new InputAction/Action<> stuff override this?

**Comment by bddckr** [comment]
@thestonefox Yes, I think so: Any SDK would just provide `Action<>`s. Just need to figure out a way to handle if that SDK is not installed.

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1523
