### ISSUE TITLE
Allow Rotation of 3D Sliders

### ISSUE THREAD

**Issue by BioeJD** [thestonefox/VRTK#843]
If a 3D slider GameObject is rotated, it will no longer slide along its axis or work much at all. I assume there's some conflict in the frozen axis movement and local vs. world axes. This issue is present whether or not you have the slider as a child of a parent object that you'd like to rotate, and keeps you from being able to reorient sliders once you've created them.

**Comment by thestonefox** [comment]
Some of the controls have a "Connected To" option to allow them to rotate. If the slide doesn't have that option then it should be added to resolve this.

**Comment by BioeJD** [comment]
At this point, I'm not really sure what the actual cause is anymore. Originally, when I rotated everything back to (0,0,0), it had solved the slider issue. I just made multiple attempts to make a new slider in the same way, and it hasn't worked. The slider is flickering back and forth between the start and end points (up next to the frame) and doesn't start at its default location.

**Comment by BioeJD** [comment]
After making a bunch of sliders in one scene, in various configurations, the ones that don't work are the ones oriented along the world z-axis.

**Comment by thestonefox** [comment]
So is this recreatable in Example scene 25 if one of the sliders was re-oriented along the z-axis?

**Comment by BioeJD** [comment]
Yes, the same issue is recreatable in Example scene 25.

To recreate, I rotated the horizontal slider (currently aligned along the x-axis) from Y = 90.0 to Y = 0, so that it is now along the z-axis. After doing so, the slider flickers back and forth (perhaps every frame) from the min to max value and back.

**Comment by thestonefox** [comment]
I've recreated the issue.

If @10FingerArmy doesn't get chance to look at it (as I know he's pre-occupied at the moment) then I'll try and take a look at the issue in the week.

**Comment by thestonefox** [comment]
PR to resolve this issue: https://github.com/thestonefox/VRTK/pull/882

The slider has been rebuilt using joints, which should resolve the issue,
