### ISSUE TITLE
Update InteractHaptics and InteractControllerAppearance to make it clearer the scripts go on the interactable object

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#848]
There may be some confusion to where the haptics and appearance script are applied.

They are supposed to be applied to the gameobject that has the interactable object script on it.

The documentation should be updated to make this clearer, but maybe also a debug warning error if they are attempted to be used in the wrong place.

**Comment by quintesse** [comment]
Would it perhaps be an idea to change the name of scripts like this to make this dependency more clear?
Ie name all interact scripts that go on the controller `InteractXxxx` while all that go on objects `InteractableXxxx`, so `VRTK_InteractControllerAppearance` would become `VRTK_InteractableControllerAppearance`.

**Comment by thestonefox** [comment]
PR https://github.com/thestonefox/VRTK/pull/854
