### ISSUE TITLE
Determine correct paths and collider models in SteamVR when not using Vive Wand

### ISSUE THREAD

**Issue by thestonefox** [thestonefox/VRTK#849]
If the rift and touch are used under SteamVR then you get a different model meaning the SteamVR SDK defaults are incorrect.

Need to detect the headset being used with SteamVR and load the appropriate model stuff.

**Comment by thestonefox** [comment]
https://docs.unity3d.com/ScriptReference/VR.VRDevice.html

**Comment by bddckr** [comment]
> Need to detect the headset being used with SteamVR and load the appropriate model stuff.
Maybe this functionality should go into `DeviceFinder`. It would be handy for runtime-SDK-switching.

**Comment by thestonefox** [comment]
yeah perhaps, but it's just a `UnityEngine.VR.VRDevice` that returns a string

I'm going to do it basic on this, then we can refactor in the future somewhere more generic if we need it.

**Comment by thestonefox** [comment]
PR to fix https://github.com/thestonefox/VRTK/pull/852

**Comment by thestonefox** [comment]
Resolved with https://github.com/thestonefox/VRTK/commit/b94b98126c36411b7371a242a9b654eb4e83718d
