### ISSUE TITLE
Secondary pointer when grabing empty space

### ISSUE THREAD

**Issue by jbat100** [thestonefox/VRTK#851]
I've been working on a project where I need to have both teleport functionality and the option to create markers instead of teleporting (using two different pointer types). The only way I've found to do this currently is to have the two controllers configured separately. It would be nice to have one controller be able to trigger both actions (say one with touchpad, the other with trigger), by giving the option to resolve the grab action to a secondary pointer action when the user is grabing empty space. I may have just missed something obvious but it seems to me that one pointer type per controller is currently enforced quite strongly by the framework.

Thanks for a great project, it's been really helpful.

**Comment by thestonefox** [comment]
I'll try re-explain what you've written to make sure I'm understanding correctly (let me know if this is right!)

You want on one controller (say the Right hand controller) two pointer beams (pointer A is green, pointer B is blue)

Pointer A (Green) can be activated by pressing the touchpad, and pointing it somewhere will teleport you to that location. You cannot interact with objects with this pointer.

Pointer B (Blue) can be activated by pressing the trigger, and pointing it at something interacts with that object (e.g. grab, use). You cannot teleport with this pointer.

Is that what you're after?

**Comment by thestonefox** [comment]
This commit may help you
https://github.com/thestonefox/VRTK/commit/d0bc44dad580804cdf8a10a1ad933dce6c166286

you can now override the BasePointer script and replace the AliasRegistration

so you could extend your own SimplePointer and just override the AliasRegistration to listen to another button event.

In the future i think an inspector option that allows you to provide an override button for the events would also be good.

**Comment by jbat100** [comment]
Great, thanks a lot!
