### ISSUE TITLE
ForceSnap() in VRTK_SnapDropZone does not save parent transform of game object.

### ISSUE THREAD

**Issue by Pjchardt** [thestonefox/VRTK#855]
Steps In Example scene 041_Controller_ObjectSnappingToDropZones

1. On Start(), ForceSnap object "Sphere_NoHightlightOnTouch" to "Sphere_SnapDropZoneMain"
2. Grab "Sphere_NoHightlightOnTouch", remove from SnapDropZone collider area.
3. Release "Sphere_NoHightlightOnTouch".
4. Notice in hierarchy "Sphere_NoHightlightOnTouch" is not parented to anything anymore.

**Comment by thestonefox** [comment]
PR to fix issue: https://github.com/thestonefox/VRTK/pull/860
