### ISSUE TITLE
VRTK_Interact_Use on GameObject causes 'No model container could be found' SDK Manager error

### ISSUE THREAD

**Issue by keironwaites** [thestonefox/VRTK#862]
I have dragged VRTK_Interact_Use on to a game object.

I also have VRTK_SDK Manager set up with SDK Selection = Simulator for all. Auto Populate Linked Objects has been clicked and has worked.

On play in Unity I get the following error once:

```
No model container could be found. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.VRTK_ControllerActions:GetElementTransform(String) (at Assets/Third Party/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:510)
VRTK.<WaitForModel>c__Iterator0:MoveNext() (at Assets/Third Party/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:444)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
VRTK.VRTK_ControllerActions:OnEnable() (at Assets/Third Party/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:439)
```

Followed by the following error continuously:

```
No model container could be found. Have you selected a valid Controller SDK in the SDK Manager? If you are unsure, then click the GameObject with the `VRTK_SDKManager` script attached to it in Edit Mode and select a Controller SDK from the dropdown.
UnityEngine.Debug:LogError(Object)
VRTK.VRTK_ControllerActions:GetElementTransform(String) (at Assets/Third Party/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:510)
VRTK.<WaitForModel>c__Iterator0:MoveNext() (at Assets/Third Party/VRTK/Scripts/Interactions/VRTK_ControllerActions.cs:444)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

I have attached an example scene of this happening.

[VRTK_Interact_Use_Simulator_Bug.zip](https://github.com/thestonefox/VRTK/files/721421/VRTK_Interact_Use_Simulator_Bug.zip)

**Comment by thestonefox** [comment]
Is this still an issue?

I've just tried the simulator in `008_Controller_UsingAGrabbedObject` and it works as expected.

When you say you are putting `VRTK_InteractUse` on a GameObject do you mean it's on the controller? Because InteractUse goes on the controller script gameobject alias.

**Comment by keironwaites** [comment]
I am not wanting to grab the object first, I am just wanting to use it.

I am playing with 008_Controller_UsingAGrabbedObject now and looking for an example that shows use without requiring grab.

**Comment by keironwaites** [comment]
I am working on a light switch so I do not want to grab it, just use it.

**Comment by thestonefox** [comment]
So you're saying that in `008_Controller_UsingAGrabbedObject` if you untick `Is Grabbable` on the WhirlyGig object then it doesn't allow you to use it?

**Comment by keironwaites** [comment]
I just tested and this works.

The error is coming from the next step where I am attempting to call my own Unity Event on Use/Unuse. I am attempting to do this by applying `VRTK_InteractUse_UnityEvents` to Whirlygig.

Clicking play after doing this is showing the errors described in the bug report.

**Comment by thestonefox** [comment]
Ok i can recreate the issue now

**Comment by thestonefox** [comment]
Actually hang on. you're adding the `VRTK_InteractUse_UnityEvents` to the WhirlyGig?

That's the problem InteractUse is a controller script not an interactable object script

**Comment by keironwaites** [comment]
I can confirm this was a misunderstanding rather than a bug - it is now working in my code.

Thank you.
