### ISSUE TITLE
Proposal | Interactable Objects: Custom check for disableWhenIdle

### ISSUE THREAD

**Issue by burnedikt** [thestonefox/VRTK#866]
**Current State:**
Objects which are marked as `disableWhenIdle` currently are disabled when they are 

* neither touched
* nor grabbed
* nor used

However, some interactable objects might want to make use of this feature but have different conditions on when they are considered idle. E.g. a Basketball is an Interactable Object which can be thrown and needs to stay enabled until it no longer moves so that other scripts (e.g. the hoop) can interact with it while still moving. 

**Desired State**
Provide an overridable function which determines the idle state of an object. Default behaviour stays the same (neither touched, nor grabbed, nor used) but more complex and specific conditions can be provided. 

Sample-PR: https://github.com/thestonefox/VRTK/pull/865

If there's a better way to do this, plese let me know :)

**Comment by thestonefox** [comment]
Seems like a decent enough idea. I'll check over the PR
