### ISSUE TITLE
Issue: feat(Interaction): generic use of outline copy highlighter

### ISSUE THREAD

**Issue by gpvigano** [thestonefox/VRTK#868]
The outline copy highlighter was primarily added to highlight objects on
touch, but it can be useful in many other ways, for example to highlight
the collision between two moving objects, using a proper custom script.
![vrtk_collision_outline](https://cloud.githubusercontent.com/assets/20297129/22204863/82c8c2cc-e174-11e6-90ef-0445f3ded5b2.png)
With this usage some changes are needed, because if also the parent game
object (of the colliding objects) has its own outline copy highlighter,
the highlighters of the colliding objects are destroyed as soon as the
ResetHighlighter() method is called (DeleteExistingHighlightModels()).

**Comment by thestonefox** [comment]
May be worth having a custom highlighter for this, or extending the current highlighters to have additional options on them that do the alternative setup

**Comment by gpvigano** [comment]
...or even using another solution like "Outline Effect" freely available on the Asset Store (https://www.assetstore.unity3d.com/en/#!/content/78608). I wonder if it's a good idea to put everything into VRTK (even if it should be nice...).
P.S. In any case the question raised by the last comment to my PR #850 is still pending.

**Comment by thestonefox** [comment]
resolved with https://github.com/thestonefox/VRTK/pull/850
