### ISSUE TITLE
Excluding children from Interactable Object Grab?

### ISSUE THREAD

**Issue by LordHorusNL** [thestonefox/VRTK#870]
I have a item that is set up as a Interactable Object (a Sword) that has a few children attached, the pickup schript works on all the colliders. However i want it setup so that the player can only pickup the sword by it's hilt and not lets say the blade.

Is there currently a way to exclude certain colliders on an object from being interacted with? maybe the policy list? or setting a tag or something.

**Comment by bddckr** [comment]
Can't you just set it up so only your hilt game object has an interactable object script attached?

**Comment by LordHorusNL** [comment]
This does not work, the script interacts with all the colliders of all the children of the object with the interactable script.

**Comment by bddckr** [comment]
Yeah exactly. It uses the **children**. I meant to only add `VRTK_InteractableObject` to your hilt game object, not the sword parent.

So instead of
```
Sword (InteractableObject)
- Child
- Child 2
  - Child 3
- Hilt
```
you do
```
Sword
- Child
- Child 2
  - Child 3
- Hilt (InteractableObject)
```

**Comment by jeremedia** [comment]
I've got the same problem. 

A workaround using the sword example:

1. Add `VRTK_InteractableObject` to both the sword and the hilt, with the hilt as a sub-class.
2. Set both as **not** grab-able.
3. Set the hilt as usable.
4. In the hilt sub-class' used event handler, tell sword object to force grab, using the technique shown in the `VRTK_ObjectAutoGrab` script.

Not ideal, but it works. Seems to me that `VRTK_InteractableObject` needs a Policy List option as well.

**Comment by LordHorusNL** [comment]
Not ideal, but definitely something i can try, thanks as a temporary fix.

Thanks

**Comment by thestonefox** [comment]
I think i have a solution for this, I'll raise a PR and see what people think

**Comment by thestonefox** [comment]
PR that should fix this issue: 
https://github.com/thestonefox/VRTK/pull/962

**Comment by andrew-raphael-lukasik** [comment]
I've came across this issue but in very different situation (colliders+UI) where list of ignored colliders was clearly not enough (due to ui colliders being added/destroyed on the fly). Also, I think this feels little like a hack / workaround tbh.

**Comment by andrew-raphael-lukasik** [comment]
Mentioned changeset in form of PR: https://github.com/thestonefox/VRTK/pull/1809
