### ISSUE TITLE
Using VRTK with Leap Motion

### ISSUE THREAD

**Issue by ludos1978** [thestonefox/VRTK#871]
Hi, I'm trying to get VRTK working with the leap motion. Specifically i am working on UI inteaction. I have figured out that VRTK_UIGraphicRaycaster does not work with the Leap motion interaction system. Enabling the graphicsraycaster make it work again. I wonder if it's normal that a input module will not work with the  VRTK_UIGraphicRaycaster, or if it should work and more likely is a problem in the leap sdk.

Another idea is to make leap working using the vrtk ui interaction system and use it's touch and interaction methods to control the ui. But i am unsure how much work this would be.

**Comment by thestonefox** [comment]
The custom graphics raycaster that VRTK uses is required to allow the 3d worldspace objects to cast rays and connect with UI elements. As the normal raycaster uses screen space this is no good for 3d world objects.

**Comment by ludos1978** [comment]
The leap motion sdk does this as well, but i think (not having the code with me right now) it's doing it in the input module. That makes the setup a bit easier (no need to attach a script to change graphicsraycasters) but i think it suffers from a problem that the input module cant handle multiple inputs simultanously. But i'm not sure about the multiple input part, i just had lots of problems activating leap, gaze and vive at the same time.

I think i will try to get leap working with VRTK to solve my problem. I hope the touch input is exact enough for this use (leap activates buttons on dragging the finger out of the ui element).

thanks & keep up your work!

**Comment by bddckr** [comment]
Maybe #927 is fixing this?

**Comment by linojon** [comment]
Once you get this working, I’d love to see a sample project, article with a walkthrough how to set this up :)
