### ISSUE TITLE
Can anyone please help on VRTK pointers

### ISSUE THREAD

**Issue by davidevansbailey** [thestonefox/VRTK#873]
Hi

I have successfully got the pointers working using the controllers and they put out the green beam which when it hits something with a collider gets a dot. But I am not experienced enough to know how I can get something to respond to that.

It's really simple what I want to do. I have an object and within that it has two buttons that push in and out. The button push in and out is done with an action. All I want to do is when the pointer is pointed at the button and clicks on it then the button gets pressed. And then I want another script to start a timer and then conversely with the other button press in and stop a timer.

I have looked at all the tutorials but I cannot figure out how to make this work. I am sure it's simple if you know how, it's the knowing how that is the difficult bit. I can program in c# and I've been using Unity for about a year so I am reasonably experienced but am frustrated at not being able to get something like this going and it's for a pretty important project I am working on.

Any help or advice would be gratefully received.

Thanx in advance.

**Comment by thestonefox** [comment]
Take a look at example scene `019_Controller_InteractingWithPointer` It has a cube menu (that appears when you press the application menu button) and you can interact with things on it with the pointer of the other controller.
