### ISSUE TITLE
Support for multiple outline highlighters

### ISSUE THREAD

**Issue by Thumann** [thestonefox/VRTK#879]
I made a model with 2 handles, I wanted only the handles to be highlighted when the controller enters the item.

VRTK_OutlineObjectCopyHighlighter only has support for one game object, and adding 2 of the scripts do not work.

It would be nice to have support for multiple game objects.

**Comment by thestonefox** [comment]
Resolved with https://github.com/thestonefox/VRTK/pull/935 ?
