### ISSUE TITLE
VRTK_BasicTeleporter: destination marker registration timing issue

### ISSUE THREAD

**Issue by cameronoltmann** [thestonefox/VRTK#884]
Due to the delay in registration with destination markers, if a teleporter is disabled during its first tick, it registers with all listeners at the end of the frame even though it's supposed to be deregistered.  This causes trouble with, for example, having multiple teleporters and swapping between them at runtime via enabling/disabling the components.  The timing issue can be resolved by changing the init coroutine as follows:

```c#
private IEnumerator InitListenersAtEndOfFrame()
{
    yield return new WaitForEndOfFrame();
    if (enabled)
    {
        InitDestinationMarkerListeners(true);
    }
}
```

**Comment by thestonefox** [comment]
how does that co-routine even run if the teleporter script is disabled?

**Comment by cameronoltmann** [comment]
It's already started when the script gets disabled.  The other answer is "Unity"

**Comment by thestonefox** [comment]
Oh right, so the teleport script is enabled on start, you disable it via a script also on start, but because it started enabled it will still cause the co-routine? is that right?

**Comment by cameronoltmann** [comment]
Yup.  And the enabled check fixes the issue.  Another thing that would work is putting `StopAllCoroutines()` in `OnDisable`

**Comment by thestonefox** [comment]
I think both are valid. No harm in double checking :)

**Comment by cameronoltmann** [comment]
True that

**Comment by thestonefox** [comment]
PR to fix the issue: https://github.com/thestonefox/VRTK/pull/889
