### ISSUE TITLE
Getting controller that grabbed or used a GameObject

### ISSUE THREAD

**Issue by aaronn** [thestonefox/VRTK#885]
I'm calling a function via OnUse (InteractableObjectUnityEvents) and would like to get the controller that triggered the OnUse event in the function that it calls. Is there a way to do this in VRTK?

**Comment by thestonefox** [comment]
I'm not sure about the Unity Events (maybe someone else can jump in?)

But if you use the c# delegates then you not only get the `ControllerIndex` in the payload but you also get the sender object (the script that sent the event).

I think that same payload is passed into the Unity Event, I'm just not sure how you access it via Unity.
