### ISSUE TITLE
Unintentional: Cloning objects on VRTK_Object Auto Grab script

### ISSUE THREAD

**Issue by Firebug2030** [thestonefox/VRTK#886]
When using the above script, if you go to the object it's referencing (IE sword in the example) and change the Valid Drop value to Drop_Anywhere (haven't tested snap zone), then every time you click the SteamVR menu button (button under touchpad on the Vive) and then unpause, you'll have floating clones of whatever was in your hand!

**Comment by bddckr** [comment]
That's just a quirk of SteamVR where it disables the controllers when you press the system button to bring up the dashboard I think. I think there's a setting to disable that behavior. Drag in the `[SteamVR]` prefab from the SteamVR plugin and check those settings.

**Comment by thestonefox** [comment]
They probably shouldn't be floating clones though. I'll look into it

**Comment by thestonefox** [comment]
@Firebug2030 what version of VRTK are you using (Unity Asset Store/Github) if it's Github then are you on the latest version of the master branch. I believe the issue you're talking about has been fixed in the latest version on Github Master

**Comment by Firebug2030** [comment]
@thestonefox I've been using the Unity Asset Store version, but if that's the case I'll swap to the Github version :) Did a quick look at the page here and couldn't see it mentioned, so I thought I'd let you know! 
As someone who has no idea what he's doing with unity or coding in general, VRTK is awesome and thank you for making it available :)
