### ISSUE TITLE
Highlighter objects remain highlighted if disabled when highlighted

### ISSUE THREAD

**Issue by JonDadley** [thestonefox/VRTK#895]
Highlighted objects that are disabled while highlighted will appear highlighted when re-enabled even if they aren't actually being highlighted. 

The simple solution to this is to drop this into VRTK_BaseHighlighter:

`        void OnDisable()
        {
            Unhighlight();
        }
`

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/ad9f6b97bfc7db61e58ff189886e8cf6ff5eeeb1
