### ISSUE TITLE
SimplePointer fails to interact with UI_Canvas if Vive controllers swap mid-game (ver: 3.0.1)

### ISSUE THREAD

**Issue by AzzyDude24601** [thestonefox/VRTK#896]
Frequently when starting a game, SteamVR will load the left and right Vive controllers, only for them to suddenly swap after a few seconds of gameplay. I suspect this is a bug with SteamVR as it has been happening since I first started using the Vive. 

However, when this issue does occur, the VRTK_SimplePointer script attached to your Vive controller will stop interacting with your VRTK_UICanvas. The pointer will still work, but it will pass right through the canvas, ignoring it completely, even though it worked perfectly prior to the swap. 

I will submit the issue to SteamVR, but if there was a simple way to address this in VRTK, that would be quite helpful for developers I think.

**Comment by bddckr** [comment]
That's probably no bug in SteamVR since SteamVR assigns the left/right indexes based on where the controllers are when you turn them on in relation to the HMD. What you probably are seeing is that the new SteamVR plugin version initially assigns an index for the controllers so they show up immediately. It then will figure out left/right and swap accordingly, if needed.

**Comment by AzzyDude24601** [comment]
Oh, was that change in the recent update for SteamVR? Because I don't remember it happening much prior to updating SteamVR so that would make sense if it was.

**Comment by benmcnelly** [comment]
I have noticed this as well, but only after the latest Steam VR update. Its pretty apparent in the editor but when you launch the game from steam (or locally w/e) it has time to set them up before you see them.

**Comment by AzzyDude24601** [comment]
> I have noticed this as well, but only after the latest Steam VR update. Its pretty apparent in the editor but when you launch the game from steam (or locally w/e) it has time to set them up before you see them.

Yeah, that has been pretty much my exact experience too.

**Comment by dantman** [comment]
If this is only actually a issue during development, could we instead introduce some sort of "loading" state for the controllers where they display differently while we're waiting for the Steam VR plugin to finish setting them up.

**Comment by thestonefox** [comment]
This may have been because the UI Pointer was not updating the index at runtime. This should be fixed in the latest version of github master
