### ISSUE TITLE
VRTK_ChildOfControllerGrabAttach does not snap correctly

### ISSUE THREAD

**Issue by alex-bluetrain** [thestonefox/VRTK#897]
I'm using VRKT 3.0.1

and it seems there's a bug in SnapObjectToGrabToController / SetSnappedObjectPosition
it only works as long as the grabbedSnapHandle rotation is Vector3.zero;
otherwise the local position of the grabbedSnapHandle will also be rotated and won't match

example:

1) set the snap empty gameobject to position 1,2,3 (relative to the VRTK_InteractableObject of course) with a rotation of 0,0,0

2) grab the VRTK_InteractableObject and see it's relative position and rotation to the attach point: it will read position (-1,-2,-3) rotation: (0,0,0)

3)  now try the same setup, but changing the rotation of the snap empty gameobject to any non-zero value, for example: position 1,2,3 rotation 45,0,0

4) now try grabbing the VRKT_InteractableObjetc and check the relative position/rotation: it will be something like : (-1, 0.7071075, -3.535534) rotation: (45,0,0)  where I was expecting:  (-1,-2,-3) and (45,0,0)

is there any logic behind the snap object local position being inverted AND rotated incorrectly?
I was expecting a behaviour like this instead:
https://www.hastebin.com/ebajizetoh.cs

**Comment by thestonefox** [comment]
Can you provide steps to reproduce using one of the existing example scenes and explain which object you're changing

**Comment by alex-bluetrain** [comment]
I think Snapping object doesn't work as I expected it, but it's not a bug.

let me explain:

I have a hand and a gun model, and I know exactly how much the gun should be moved and rotated so it fits into the hand.

all I wanted is to input those values in the grab object, and the grabbed object to read and copy them.

so I got around it by patching my own version of VRTK_ChildOfControllerGrabAttach which replaces the SetSnappedObjectPosition with this, which is pretty straighforward for my workflow of setting up the grab points
```

        private void SetSnappedObjectPosition(GameObject obj)
        {
            obj.transform.parent = controllerAttachPoint.transform;
            if (grabbedSnapHandle == null)
            {
                obj.transform.position = Vector3.zero;
            }
            else
            {
                obj.transform.localRotation = grabbedSnapHandle.transform.localRotation;
                obj.transform.localPosition = grabbedSnapHandle.transform.localPosition;
            }
        }
```

**Comment by thestonefox** [comment]
Don't patch `VRTK_ChildOfControllerGrabAttach` because that will break for you in future updates.

Create your own script called something like `VRTK_ChildOfControllerGrabAttachCustom` and just have your own logic. Then that way your customisations wont break updates in the future.

**Comment by alex-bluetrain** [comment]
that's exactly what I did, it was misleading to call it "patch my own version of..." hehe, thanks anway ;)
