### ISSUE TITLE
Detect controller input

### ISSUE THREAD

**Issue by philmennie** [thestonefox/VRTK#901]
Hey, I'm kind of new to this so sorry if I'm writing in the wrong place - let me know and I'll move / delete this comment. I'm currently having issues detecting controller input while using VRTK. For example, when I have a collision between two objects, I want to be able to detect what buttons are being pressed on the controllers but can't seem to work out how I can do this. Also, I have implemented the Interact Use functionality but I'm struggling to work out how to make two buttons do different actions. For example, once I grab an object with the simple pointer I want one button to bring the object closer and another to move it away, but I've only managed to implement one or the other. Any suggestions? I've looked everywhere in the docs, examples and Google and can't seem to find anything. Any help would be MUCH appreciated! Pulling my hair out here!

**Comment by thestonefox** [comment]
Github issues is only for feature requests and raising bugs.

If you would like further help with using the toolkit then try the slack channel at http://invite.vrtk.io or post on Stackoverflow.com using the tag `vrtk`.
