### ISSUE TITLE
Issues dragging items off their original canvas

### ISSUE THREAD

**Issue by narfanator** [thestonefox/VRTK#910]
### Environment

 * Source of VRTK: GitHub clone
 * Version of VRTK: 787550e8a0be0ab7cb469a80db6c1117e57c4bc8
 * Version of Unity3D: 5.4.4f1

### Steps to reproduce

- Example scene 34
- Pick up either "Drag Me On Here" or "Drag Me Anywhere"
- Flick your wrist to get fast movement off original canvas (while dragging)
- Release
- Attempt to pick up & drag objects again

### Expected behavior

- "Drag Me On Here" should stop at canvas edge
- Both objects should continue to "terminate" the UI ray (green ray with the little dot where it hits stuff instead of red)
- Off-canvas drag should function

### Current behavior

- "Drag Me On Here" can be dragged off canvas
- Ray stays red
- Off-canvas drag results in tiny spurts of motion vaguely corresponding to controller motion. (Note: Dragging _back_ onto the canvas works well, only continuing to drag off / away results in this)

You can drag things that aren't supposed to leave the canvas off the canvas. When you do that, dragging doesn't really work, even when it's supposed to (for objects that can leave the canvas).

**Comment by narfanator** [comment]
Okay, traced down a fix. Not sure why what's happening results in the observed behavior, but basically there's no detection for a drag end off any canvas at all. To mimic other "invalid drag end" behavior, when this happens, my fix has the component reseting (return to pre-drag location).

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/aec9aec6db5cd86c8b7a8ce100605544bfd8da66
