### ISSUE TITLE
Objects highlighted with pointer are intermittently un-highlighting / flickering

### ISSUE THREAD

**Issue by JonDadley** [thestonefox/VRTK#911]
### Environment

 * Github
 * Latest Github release but have been seeing this issue from version 3.0.1 up to latest Github.
 * Unity 5.6b3 - b6

### Steps to reproduce

1. Open example scene 003_Controller_SimplePointer
2. Expand the world WorldObjects object in the hierarchy and select the Person object
3. On the Person root object, add a Box Collider and change the bounds to generously surround the Person (Size 1.35, 2.8, 1.25 will do)
4. On the Person root also add a VRTK_InteractbleObject component. Give it a visible Touch Highlight colour. Also add a VRTK_MaterialColorSwapHighlighter component.
5. Expand the [VRTK] heirarchy object and on one of the controllers add a VRTK_InteractTouch component. On the Simple Pointer component, turn on the 'Interact With Objects' option and set Pointer Visibility to Always_On.
6. Press play and point the pointer at the Person object. Move the pointer across the object and notice how the highlight regularly flickers on and off as the object is rapidly selected and deselected even though the pointer remains in continuous contact with it.

This also affects the objects 'use' state meaning if you want to 'use' the object it becomes very hard as it is only intermittently selected.

### Expected behavior

Item remains highlighted and useable while the pointer is in contact with it's box collider. 

### Current behavior

Item is only intermittently selected and highlightable.

**Comment by aantn** [comment]
I've experienced this too in my own scenes.

**Comment by thestonefox** [comment]
PR to fix the issue https://github.com/thestonefox/VRTK/pull/913

**Comment by aantn** [comment]
This definitely did not fix the issue for me. If anything the flickering is worse.

**Comment by thestonefox** [comment]
@aantn if you can provide steps to reproduce the issue you're having in an example scene then it can be looked into

**Comment by JonDadley** [comment]
Interestingly this completely resolves the issue in the example scene for me but it's still just as broken in my actual scene. I'm going to investigate the differences between my scene and the example scene for differences.

**Comment by JonDadley** [comment]
@thestonefox @aantn I've found out why this fix works in the example scene but not in my scene. My camera rig has a Y Rotation of 180 on the transform component. If I remove this, the fix works perfectly. Additionally, if I put a Y Rotation of 180 on the transform of the rig in the example scene, the issue appears there also! I suppose this allows us to 'fix' around the issue in our scenes but it'd be useful to be able to set the initial camera rotation in the scene.

**Comment by aantn** [comment]
Thanks I'll check if that fixes it for me. (Sorry about the delay... I have
finals.)

**Comment by thestonefox** [comment]
@JonDadley I'll take a look at why there is an issue on rig rotation.

I'm guessing it's to do with the forward direction affecting the shape of the collider.

**Comment by thestonefox** [comment]
@JonDadley  @aantn try this PR instead

https://github.com/thestonefox/VRTK/pull/921

**Comment by aantn** [comment]
It works perfect now. Thanks.

**Comment by JonDadley** [comment]
Yep that seems to work better for me too
