### ISSUE TITLE
Dash teleport not working if controller was not already turned on

### ISSUE THREAD

**Issue by UnoQualunque** [thestonefox/VRTK#914]
I've encountered the following problem:
the dash teleport works fine, but if I enter into Play Mode with a controller switched off and then I switch the controller on, the beam of the teleport appears (and apparently the data in the debug inspector are updated), the teleport events are sent, but the character doesn't move at all, as if he was glued to the starting point

**Comment by thestonefox** [comment]
I've just tried this in the example scene `038_CameraRig_DashTeleport` and I can start with out the controllers turned on, then when I turn the controller on after the scene has loaded I can still dash around correctly.

Using Unity 5.4.4f1 and latest version of VRTK Github master (commit:  https://github.com/thestonefox/VRTK/commit/d533b5e2307eaa9eccd9ceeeacc089c803cb214f)

**Comment by UnoQualunque** [comment]
Mmmh I really do not understand why, but disabling and enabling again the dash teleport script on the cameraRig make things work again. I haven't touched anything in those scripts, but I'm using the AssetStore version. In any case there's no need for further investigation, I imagine that must be my fault.  Thanks for the speed in your answer.

**Comment by thestonefox** [comment]
Try upgrading to the latest github master and see if it fixes your issues.
