### ISSUE TITLE
Grab delta while climbing does not respect parent rotation

### ISSUE THREAD

**Issue by leonsbuddydave** [thestonefox/VRTK#917]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 3.0.1
 * Version of Unity3D: 5.5.0f3

### Steps to reproduce

In the **037_CameraRig_ClimbingFalling** example scene:

1. Create an empty GameObject and put the [CameraRig] and [VRTK] objects inside:
[Empty GameObject]
-- [CameraRig]
-- [VRTK]
In my case the purpose of this was to create a prefab for these components.

2. Set the Rotation Y of the parent object to 90.
3. Play the scene and try to climb something. While hanging onto the wall, try moving close to and away from the wall, or side to side - the transform between the player and the wall is incorrect.

I have fixed the problem locally by changing this line to rotate the delta, but I'm not sure whether it's an actual solution or whether it just happens to fix my use case:
https://github.com/thestonefox/VRTK/blob/e1e7f700238af2106324a05c73711ce7762341f3/Assets/VRTK/Scripts/Locomotion/VRTK_PlayerClimb.cs#L74

`playArea.position = startPosition - (GetPosition(grabbingController.transform) - startControllerPosition);`

to

`playArea.position = startPosition - **transform.rotation** * (GetPosition(grabbingController.transform) - startControllerPosition);`

If this is the correct solution I can submit a pull request for it.

**Comment by thestonefox** [comment]
Doesn't this PR resolve this issue?

https://github.com/thestonefox/VRTK/pull/903
