### ISSUE TITLE
UI Pointer events stop passing to UI elements

### ISSUE THREAD

**Issue by nvisionGeo** [thestonefox/VRTK#924]
### Environment

 * commit hash 787550e8a0be0ab7cb469a80db6c1117e57c4bc8 (jan 31)
 * Unity 5.5.1f1

Using a UI Pointer / laser.. and when clicking on a button, it takes you to another menu. This instantly deactivates the current menu objects and activates new ones. Then, in EventSystemVRInput.cs line 109 .. even though the laser pointer finds the new button, it doesn't pass the UI events to that button or any other in the new menu. Upon tracing, I found that it returns from Hover after failing the Valid test. It was still holding on to the deactivated button. So I changed it to this
```
                CheckPointerHoverClick(pointer, results);
                if (!ValidElement(pointer.pointerEventData.pointerEnter))
                {
                    pointer.pointerEventData.pointerEnter = null;
                    return;
                }
```
clearing out the old data. And it fixed my issue.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/ac0b8c79a835bd0d28f2bbe4228d351498cf8cbd
