### ISSUE TITLE
Draggable Canvas GameObject causes problems in Canvas Layout Groups

### ISSUE THREAD

**Issue by nvisionGeo** [thestonefox/VRTK#925]
This is a simple issue. The VRTK Canvas adds a child to itself, which, if its a layout group will actually insert a ghost element and shift all the intended elements down.

One suggestion is to add a checkbox to the VRTK Canvas to allow/disallow making this Draggable Canvas object. Haven't looked into what it does, so my suggestions are limited.

**Comment by roskelld** [comment]
This was also causing me issues, both with messing up the button grid layout as well as preventing interacting with buttons that were in the region of the generated canvas.

As a work around to I added a bool to the code (default on) and disabled the feature for the instances where I want to use the grid layout.

`public bool draggableCanvas = true;`
...
`if (canvas && draggableCanvas && !canvas.transform.FindChild(CANVAS_DRAGGABLE_PANEL))`

**Comment by bddckr** [comment]
That is a nice fix @roskelld and it is probably a good idea to allow the users of VRTK to specify whether or not they actually need that dragging support in a canvas. So one could improve performance a bit by not even creating that "helper game object".

I'm currently having a look at solving this problem without that option, though. I think Unity allows to ignore UI elements for layout purposes. That should fix this issue.
