### ISSUE TITLE
Error CS0101 namespace

### ISSUE THREAD

**Issue by SolVR** [thestonefox/VRTK#926]
Hi ! Since I update VRTK and Unity, I have an error.

**Assets/VRTK/SDK/VRTK_SDK_Bridge.cs(6,18): error CS0101: The namespace `VRTK' already contains a definition for `VRTK_SDK_Bridge'**

Do you have an idea for a solution ? I'm completly lost :/

Thanks !

**Comment by thestonefox** [comment]
Try deleting your VRTK and SteamVR directories from your project completely then re-importing them.

Unity does not handle updating very well.

**Comment by SolVR** [comment]
Did it and unfortunetly it didn't work

**Comment by thestonefox** [comment]
Then I'd check your directory structure for another definition of `VRTK_SDK_Bridge` as you have two.

**Comment by SolVR** [comment]
When I'm watching in VRTK directory I found 2 same files VRTK_SDK_Bridge in two different folders.

One in : Assets > VRTK > SDK 
Second one in : Assets > VRTK > SDK > SteamVR

It come form there ?

**Comment by thestonefox** [comment]
This is because Unity has messed up your update.

If you delete the `VRTK` directory and clear your unity download cache, then redownload again it will work

**Comment by SolVR** [comment]
Thanks you ! Now I have some other error, but it's in my code ^^
