### ISSUE TITLE
[Meta] Funding / improvement of VRTK beyond hobby contributions

### ISSUE THREAD

**Issue by dantman** [thestonefox/VRTK#930]
The Kickstarter has ended now and didn't reach the funding goal; though there was a notable amount of support suggesting some room for improvement to VRTK besides spare-time contributions. The grand goals for improvement the Kickstarter had was admirable, but doesn't seem attainable at the immediate moment. However £32,000 pledged and support from devs using the toolkit is not insignificant. It may not be enough for grand improvements, but it does suggest there is room to start with smaller incremental improvements to the toolkit beyond just the spare-time contributions individuals make.

Some ideas for funding part-time/full-time development:
* As suggested as an alternative during the Kickstarter, Patreon
* Small contracts from multiple individual VR devs for working on specific VRTK issues that might be of benefit to those devs or expand VRTK enough for a non-VRTK game dev to start using VRTK
* General grants if possible + R&D grants and credits (In Canada we have things like SR&ED, which provides tax incentives for R&D that a good portion of work on VRTK could technically qualify for and partially covers the development cost)

The biggest issue of course is that the sources of funding at least initially aren't reliable enough to support full-time work on VRTK; so @thestonefox and other contributors with normal full-time jobs are only able to contribute as a hobby. I think the answer to that is starting out with contributors who are able to do sporadic part-time work without negatively affecting their jobs.

For example, we can start by cataloging a list of contributors who do freelance work, contract work, or have a job like mine where their employer primarily does client work and could take on VRTK contract work on behalf of the contributor. Contributors in any of these lines of work can simply take on VRTK tasks as part of their normal job and be unaffected during the period of time we're waiting for the VRTK funding to build up again to employ more VRTK improvements.

Other ideas and discussion on how we could slowly start larger improvements to VRTK are welcome.

**Comment by thestonefox** [comment]
Patreon is live now! https://www.patreon.com/vrtk

**Comment by dantman** [comment]
Idea for how to prioritize and run the patreon while dishing out contracts/grants/freelance work to part-time developers:

* Allow patrons to make posts or comments nominating a VRTK issue (either nomination comments in periodic nomination posts or community posts nominating an issue that other patrons can like)
* Periodically, whenever there are available funds, compile a list of issues that have got nominations (and have an available developer capable of tackling the issue and able to take a grant to work on it) and post a 'priorities' post letting patrons vote on the priority of the selected issues

**Comment by thesbros** [comment]
BountySource works like that - you could use some of the funds as a bounty on issues which have garnered lots of attention/support.

**Comment by dantman** [comment]
@thesbros Adding BountySource integration would be a good extra addition. (@thestonefox [see this](https://webapps.stackexchange.com/questions/84152/how-to-enable-bountysource-plugin-on-github-to-have-integration-with-issues))

Doing it as part of the patreon has the advantages of being curated (bounties not being split up amongst issues that have no bounty-capable developers to handle it) and paying for proper part-time work (instead of a bounty that only comes on completion and may not actually cover the work hours put in to solve the issue). Contract work can also fuse together patreon funding, direct support from a selection of indie devs, and grants/R&D incentives.

However also supporting bounties has the advantage that a few issues that affect a lot of people can get pledges from a a larger selection of indie devs that don't engage directly with the patreon contracts.

**Comment by thestonefox** [comment]
Lets close this off and continue discussions in slack.
