### ISSUE TITLE
Player Body Direction

### ISSUE THREAD

**Issue by SK83RJOSH** [thestonefox/VRTK#941]
Valve's interaction system has a pretty handy `Player` class which has a few methods I'd love to see exposed in VRTK in some way.

Though at this point in time the main method I'm interested is `Player.bodyDirectionGuess`:

```C#
var bodyDirection = playAreaTransform.forward;
if (hmd)
{
	Vector3 direction = Vector3.ProjectOnPlane(hmd.forward, trackingOriginTransform.up);
	if (Vector3.Dot(hmd.up, trackingOriginTransform.up) < 0.0f)
	{
		// The HMD is upside-down. Either
		// -The player is bending over backwards
		// -The player is bent over looking through their legs
		direction = -direction;
	}
	return direction;
}
return trackingOriginTransform.forward;
```

This is a pretty easy thing to implement ourselves but it seems like it would be a useful addition to the toolkit.

We have some classes which offer similar functionality (such as `VRTK_MoveInPlace`, and I believe `VRTK_UIPointer` as well) but those are pretty specialized unfortunately.

With that said, I'm wondering if having a similar "Player Utilities" class might be useful? It could be something that piggy backs off of `VRTK_DeviceFinder` and offers some basic methods such as this, or perhaps it could be apart of  `VRTK_DeviceFinder` directly (though I'm not sure if that would really make sense)?

**Comment by xEvoGx** [comment]
Agreed

**Comment by thestonefox** [comment]
What would be the benefit to know if the headset is upside down?

**Comment by SK83RJOSH** [comment]
This is a snippet from SteamVR, but it's presumably so that your forward vector is still "forward" if you're leaning very far forwards / backwards (which isn't all that common, but is a perfectly valid edge case).

**Comment by thestonefox** [comment]
Linked to https://github.com/thestonefox/VRTK/issues/1522
