### ISSUE TITLE
Always On UI Pointer always Scrolling

### ISSUE THREAD

**Issue by lacvapps** [thestonefox/VRTK#943]
### Environment
Latest Master Branch 
Unity 5.5.1f1
### Steps to reproduce
1) Open scene 034
2) Set VRTK_UI Pointer Activation Mode to Always On
 (Optional set Straight Pointer Renderer Visibility to Always On)
3) Try scrolling the Example Scroll View Canvas

### Expected behavior

When the user scrolls the touchpad the scroll view should move up/down while they are scrolling and stop when they are done.

### Current behavior

If you touch the touchpad it will scroll according to where you have touched indefinitely, it will not stop when you are done pressing the touchpad and does not take into consideration swiping only the position pressed.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/de2e410906c10df3dbd79c4949d0f82a809a2f7b
