### ISSUE TITLE
Destination Points behave strangely if controllers are connected mid-session

### ISSUE THREAD

**Issue by SK83RJOSH** [thestonefox/VRTK#947]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: fdb24039c3f0b2e4b75f8c59bb4911e810045498
 * Version of Unity3D: 5.5.1f1

### Steps to reproduce

* Open VRTK/Examples/044_CameraRig_RestrictedTeleportZones.unity
* Turn off both of your Vive Controllers
* Enter play mode
* Turn on one of your Vive Controllers
* Attempt to teleport to a destination point

### Expected behavior

Each destination point should disable the cursor crosshair, and show / hide the relevant gameobjects as they would normally.

### Current behavior

The pointer is never hidden, and the destination points do not respond to player input. Teleporting to them works, but all destination options are ignored.

**Comment by thestonefox** [comment]
The version you've listed has borked the toggle-ability of the pointers. @bddckr  is working on a fix right now!

**Comment by thestonefox** [comment]
This is still an issue after the fix so I'll raise it as a bug

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/09be398dafb42ad714f266b50bc3283bca7512cc
