### ISSUE TITLE
DestinationPoint doesn't implement DestinationMarkerEnter/Exit events

### ISSUE THREAD

**Issue by SK83RJOSH** [thestonefox/VRTK#948]
For my project I'd love to be able to use Unity Events on my Destination Points, however, the only event currently implemented SetDestination.

**Comment by thestonefox** [comment]
You can use SetDestination with Unity events, you just need to use the UnityEventHelper for Destination Marker found in `Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_DestinationMarker_UnityEvents`

**Comment by SK83RJOSH** [comment]
I'm currently using DestinationMarkerSet, but I'd like to do some more complex behaviors on hover (other than just showing / hiding GameObjects). I noticed the Pointer objects use these events, but it would be somewhat backwards to listen to these events only on the controllers. 😄

**Comment by thestonefox** [comment]
Are you wanting events on the destination markers? So when they are hovered/unhovered/actvated they emit an event?

**Comment by SK83RJOSH** [comment]
Yeap, that's exactly what I'm thinking of. I assumed that's what the DestinationMarkerEnter/Exit events were for, but I suppose those are rather specific to pointers.

**Comment by thestonefox** [comment]
yeah the destination marker events are for the marker creating the destination.

The destination point is something that receives a destination marker.

I'll have a look at adding some more events to the points.

**Comment by thestonefox** [comment]
@SK83RJOSH I think you're right, may as well just implement the Enter/Exit events

https://github.com/thestonefox/VRTK/pull/964

Does everything you really need to know the hover state. Let me know what you think, and if it's ok I'll merge it.

**Comment by SK83RJOSH** [comment]
LGTM 👍 

I'll make sure to let you know if I come across anything else 😄

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/0a0ef5313bdb9f75fa0517bf55e57683eb7ee0d3
