### ISSUE TITLE
VRTK_ControllerEvents.GetTouchpadAxis() - Returning 0 every other frame.

### ISSUE THREAD

**Issue by treefortress** [thestonefox/VRTK#955]
Querying this in Update/FixedUpdate, and am getting a 0 every other frame. Can anyone confirm? 

` var touchAxis = controllerEvents.GetTouchpadAxis();
 print("GetTouchpadAxis().y: " + touchAxis.y);`

Log output:
http://i.imgur.com/b6HsoGq.png

This seems to have been introduced in the last 2 weeks.

**Comment by thestonefox** [comment]
i can confirm

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/79a19724465e420bf8a19550e934678acb4fbb4d
