### ISSUE TITLE
Null Reference Exception in VRTK_DestinationPoint.OnDisable()

### ISSUE THREAD

**Issue by SK83RJOSH** [thestonefox/VRTK#956]
### Environment

 * Source of VRTK: Github
 * Version of VRTK: 1fb9016accb2dcf84c58065de4dc7a554d330b70
 * Version of Unity3D: 5.5.1f1

### Steps to reproduce

Clone VRTK, ensure you have all dependencies
Open example 44
Start the level
Stop the level

### Expected behavior

The level should exit cleanly and without errors.

### Current behavior

You receive the following error:

`NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_DestinationPoint.ManageDestinationMarkerListeners (UnityEngine.GameObject markerMaker, Boolean register) (at Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs:145)
VRTK.VRTK_DestinationPoint.ManageDestinationMarkers (Boolean state) (at Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs:134)
VRTK.VRTK_DestinationPoint.OnDisable () (at Assets/VRTK/Prefabs/Resources/Scripts/VRTK_DestinationPoint.cs:76)`

**Comment by SK83RJOSH** [comment]
Sorry for all the destination point related issues, I'm using them quite extensively in my project right now. 😅

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/ad5ba0a940cffa063a06f7d1a6eedfa0df4f9309

Glad they're getting battle tested :)
