### ISSUE TITLE
Highlight Object disappears when using adjacent SnapZone

### ISSUE THREAD

**Issue by zerpy** [thestonefox/VRTK#958]
### Environment

VRTK GitHub - Latest version (3.0.1+) Feb 23 2017
Unity 5.5.0f3

### Steps to reproduce

Example Scene: 041_Controller_ObjectSnappingToDropZones

* Copy SnapZoneGroup and Cube_NoHighlightOnTouch.
* Activate "Highlight Always Active" on both Cube_SnapDropZone objects.
* Place copied SnapZoneGroup directly beside the original. 
* Run.

* When placing Cube_NoHighlightOnTouch into one SnapZone the other SnapZone's Highlight Object will disappear when object is snapped.
* If another object (copy of Cube_NoHighlightOnTouch) is passed through the missing Object Highlight it reappears (even without placing the object in the snapzone).

### Expected behavior

Only the SnapZone which is receiving an object should have the Highlight Object disappear, not adjacent ones.

### Current behavior

Adjacent SnapZone's Object Highlight disappears if object is touching when being placed in another Snap Zone.

Example Gif: https://media.giphy.com/media/mGawg5xVcXnO0/giphy.gif

**Comment by thestonefox** [comment]
Ok i can recreate it.

A work around would be not to have the snap drop zone colliders overlap each other. I'll look for a more permanent fix

**Comment by thestonefox** [comment]
nevermind it's a easy fix. i'll post a PR now

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/e765255b08bb22fc4bad33cb40438c046d9c5dc8
