### ISSUE TITLE
VRTK_InteractableObject_UnityEvents Use not working?

### ISSUE THREAD

**Issue by LordHorusNL** [thestonefox/VRTK#979]
I'm using InteractableObject_UnityEvents on a object "gun" and can not get any response from the On Use event! I'm trying to trigger a playmaker event btw.

This works perfectly with the On Grab/On Ungrab and On Touch/On Untouch events, however On Use does not seem to do anything, even when just checking the use state via a script.

I'm using the latest VRTK from github and Unity 5.5.2f1 and have Is Usable checked on the object offcourse.

**Comment by bddckr** [comment]
Is your `VRTK_InteractableObject_UnityEvents` added to the same game object that the `VRTK_InteractableObject` is attached to?

**Comment by LordHorusNL** [comment]
Yes, like i said it's only the On Use events that don't seem to do anything, On Grab and Touch work just fine.

**Comment by thestonefox** [comment]
Works for me.

Steps to reproduce:

 * Open `008_Controller_UsingAGrabbedObject`
 * Select `ExampleObjects -> WhirlyGig`
 * Add the `VRTK_InteractableObject_UnityEvents` script to the `WhirlyGig` object
 * Add a Unity event in the `OnUse` by clicking the plus
 * Target the `Gun` object and set the action to `GameObject.SetActive` and have the checkbox as false.
 * Add a Unity event in the `OnUnuse` by clicking the plus
 * Target the `Gun` object and set the action to `GameObject.SetActive` and have the checkbox as true.
 * Run the scene.
 * Put controller into `Whirlygig` object and press the default use button which is `Trigger`.
 * Whilst the object is being used the gun disappears, stop using the gun reappears.

**Comment by LordHorusNL** [comment]
Works fine for me to in 008_Controller_UsingAGrabbedObject just not in my scene on any object using the On Use event.

I probally unchecked something on accident, i'll setup my VRTK Camerarig from scratch again and see if that fixed the problem.

**Comment by LordHorusNL** [comment]
Ok it seems like you can only target a single playmaker script from VRTK_InteractableObject_UnityEvents.
If you target a different script for use than for grab it won't work. So Solved.

I noticed something else, on a VRTK_InteractableObject with **Is Usable** and **Use Only if Grabbed** set to true, the controller not holding the object can still trigger the Use event? when touching the collider.

Shouldn't the controller holding the object "gun" be the only one able to use "fire" it?

Maybe add another option under **Allowed Use Controllers**, something like "Grabbing Controller".

**Comment by thestonefox** [comment]
I think the solution to the second issue mentioned is the suggested `Grabbing Controller Only` option.

**Comment by LordHorusNL** [comment]
If you get a chance to add this in the future, it would be very much appreciated.

**Comment by thestonefox** [comment]
The `Grabbing Controller Only` option on reflection doesn't seem like a great solution as it's somewhat confusing.

If you grab an object with two hands, then should the second controller be allowed to use as it's a grabbing object?

We then get into the realms of multiple options.

The solution is to toggle the Usable controller on grab (like in the real gun example)

This basically says on grab, check the hand of the controller, if the hand is left then set the allowed use controller to left only. On ungrab set the use back to both.

You can also extend this further like in the real gun example where it says on grab with right then only the left controller can grab the slide.

I think this may be one of those areas where custom code is better than a generic solution that doesn't go far enough to solve the problem as a whole.

**Comment by LordHorusNL** [comment]
I'm sorry you lost me, isn't the idea behind VRTK to create a basis so that developers can easily implement basic gameplay elements without having to add custom code?

I'm not a coder myself and that's why i rely on playmaker for visual scripting, but not being able to choose which controller can "Use" an object being held, severely limits how i can use VRTK for object interaction.

It only seems logical to me as a non coder, that the only controller that can use an object, is the actual controller holding the object. that should be the default, not both controller being able to trigger "Is Usable"

But the help is still very much appreciated! and i do agree that you can't create a solution for every option.

**Comment by thestonefox** [comment]
A solution may be a separate helper script that does the switching, but it isn't something that should be an option in the Interactable Object.

The script isn't all that hard though, if you look at the real gun example:

This happens when you grab the gun:
https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Examples/Resources/Scripts/RealGun.cs#L61-L74

And this happens when you release it:
https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Examples/Resources/Scripts/RealGun.cs#L84-L88

**Comment by LordHorusNL** [comment]
I was able to do the above solution with a small playmaker script, works great now.

Thanks for the help!

**Comment by elwes** [comment]
I just noticed, that in the "VRTK_InteractableObject_UnityEvents" does not fire the "Use" and "UnUse" events by default. The example scene contains a custom script that triggers the events. Would come in handy, if the "VRTK_InteractableObject" would directly fire the events.

So I just made this minor change to get it going:

New script named "VRTK_InteractableObjectWithUse"

`namespace VRTK.Examples
{
    using UnityEngine;

    public class VRTK_InteractableObjectWithUse : VRTK_InteractableObject
    {
       
        public override void StartUsing(VRTK_InteractUse usingObject)
        {
            //Debug.Log("StartUsing");
            base.StartUsing(usingObject);
            
        }

        public override void StopUsing(VRTK_InteractUse usingObject)
        {
            //Debug.Log("StopUsing");
            base.StopUsing(usingObject);
           
        }

    }
}`

**Comment by elwes** [comment]
I just noticed, that in the "VRTK_InteractableObject_UnityEvents" does not fire the "Use" and "UnUse" events by default. The example scene contains a custom script that triggers the events. Would come in handy, if the "VRTK_InteractableObject" would directly fire the events.

So I just made this minor change to get it going:

New script named "VRTK_InteractableObjectWithUse"


```csharp

namespace VRTK.Examples
{
    using UnityEngine;

    public class VRTK_InteractableObjectWithUse : VRTK_InteractableObject
    {
       
        public override void StartUsing(VRTK_InteractUse usingObject)
        {
            //Debug.Log("StartUsing");
            base.StartUsing(usingObject);
            
        }

        public override void StopUsing(VRTK_InteractUse usingObject)
        {
            //Debug.Log("StopUsing");
            base.StopUsing(usingObject);
           
        }

    }
}
```

**Comment by bddckr** [comment]
@elwes `VRTK_InteractableObject_UnityEvents` has and emits the use/unuse events them: See [here](https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/Utilities/UnityEvents/VRTK_InteractableObject_UnityEvents.cs#L81-L89).

**Comment by elwes** [comment]
@bddckr 

``VRTK_InteractableObject`` does not trigger the events to ``VRTK_InteractableObject_UnityEvents``.

Reproduce:
1. Attatch to a Object `VRTK_InteractableObject`, `VRTK_InteractableObject_UnityEvents`, `VRTK_FixedJointGrabAttach`, `VRTK_SwapControllerGrabAction`

2. Enable "Is Usable" in `VRTK_InteractableObject`

3. Attatch the following script to the gameobject and populate all the events with the corresponding functions.

```csharp

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DebugLog : MonoBehaviour {

	// Use this for initialization
	//void Start () {
		
	//}
	
	// Update is called once per frame
	//void Update () {
		
	//}

    public void DebugInfo()
    {
        Debug.Log("Hello");
    }

    public void OnTouch()
    {
        Debug.Log("On Touch");
    }

    public void OnUnTouch()
    {
        Debug.Log("On UnTouch");
    }

    public void OnGrab()
    {
        Debug.Log("On Grab");
    }

    public void OnUnGrab()
    {
        Debug.Log("On UnGrab");
    }

    public void OnUse()
    {
        Debug.Log("On Use");
    }

    public void OnUnUse()
    {
        Debug.Log("On UnUse");
    }
}
```

At least on my end I get all functions to work exept the "use" and "unuse". But maybe I did something wrong? Not sure. When I replace the script with the one posted earlier, I get to all events. Not sure if I made a mistake or not. Will double check again.

**Comment by bddckr** [comment]
@elwes User error probably, works for me.

Are you missing `VRTK_InteractUse` on your script alias controller? Have you set the use button on the `VRTK_InteractUse` script? Also check the use override button on the `VRTK_InteractableObject`.

Additionally make sure you don't just add the `VRTK_FixedJointGrabAttach` and `VRTK_SwapControllerGrabAction` components, you also have to drag and drop them onto the respective field on the `VRTK_InteractableObject`!

With that in place it works just fine for me 😄 🤞 it does for you, too.

**Comment by elwes** [comment]
Everything is in place. It works with `VRTK_InteractableObjectWithUse` but not with `VRTK_InteractableObject`. But again. everything works with both scripts exept the use/unuse event that only works in the modified script. Puzzling.

**Comment by elwes** [comment]
@bddckr Now everything works just fine . Not sure what caused the problem. But everything works as expected now. Thanks for encouraging me to check again and again :) and sorry for fuzzing...

**Comment by ConeArtist** [comment]
I have the exact same problem. Use and unuse are not doing anything. I have tried everything on this page and it is still not working.

**Comment by thestonefox** [comment]
@ConeArtist do you have the InteractUse script on your controller script alias?

**Comment by ConeArtist** [comment]
@thestonefox I didn't have now but I have now. I get error that I don't have InteractTouch script and when I add that, I cannot grip the object anymore.

**Comment by thestonefox** [comment]
I think you probably need to look at how the example scenes are set up, seems like you're doing something wrong.

**Comment by bddckr** [comment]
Please hop onto the Slack chat to get help in a faster and easier way :)
http://invite.vrtk.io/
