### ISSUE TITLE
Activate canvas during runtime leads to incorrect focus (multiple canvases)

### ISSUE THREAD

**Issue by jayadee** [thestonefox/VRTK#982]
I'm using VRTK 3.1.0 from Unity Asset Store and Unity 5.5.0f3
UPDATE: Also verified using the latest version from GitHub master.

I've created a unity scene containing two UI Canvas elements (also applied VRTK_UICanvas).
The background canvas contains a Scroll View and in the view a single button (B1).
The foreground canvas contains a Panel with a single button (B2). It is not active at startup and is activated by a click with the UIPointer using this command:
canvas2.gameObject.SetActive(true).
The canvas correctly appears in the foreground.
When I click on the button B2 nothing happens (color does not change and no click event is fired).
Instead when I point to the Scroll View on the background canvas looking through the foreground 
canvas and begin dragging, the the Scroll View actually moves. The pointer terminates correctly on the canvas in the foreground.

What I was expecting is that the panel in the foreground would receive events and fire a click event when I attempt to click on the button.

The scene behaves correctly, if the foreground canvas is already active before starting the scene.

[scrollviewTest.zip](https://github.com/thestonefox/VRTK/files/818779/scrollviewTest.zip)

**Comment by bddckr** [comment]
There have been various fixes to the pointer, canvas and event system stuff in VRTK since the last Asset Store release. Try using the latest version from the GitHub master.
You can find the changes from the last Asset Store version [here](https://github.com/thestonefox/VRTK/compare/3.1.0...master).

**Comment by jayadee** [comment]
I tested the scene with the master release from GitHub.
I had to update the SDK Selection in the VRTK SDK Manager.
Sadly enough it doesn't make any difference to the issue I have.

**Comment by bddckr** [comment]
Can you reproduce the issue in one of the example scenes (I think 043 is the UI scene)?

**Comment by dotlaura** [comment]
I'm having the same issue with turning on/off multiple panels with scroll rects causes the UI pointer to appear behind or under the canvas.

**Comment by thestonefox** [comment]
@dotlaura can you provide steps to reproduce the issue in the example scene (34)

**Comment by mjkaiser** [comment]
I'm able to reproduce a similar issue in Example Scene 34, if I parent a new canvas to the controller and try to interact with it over other world-space canvases. 

I've found that if I don't parent it to the controller, and instead use the VRTK_TransformFollow script to tell it to follow the controller, it works as expected.

**Comment by mjkaiser** [comment]
Actually, it still may have an issue with multiple overlapping canvas...

**Comment by bddckr** [comment]
Voting to close, solution found in the Unity forums:

> Root canvas's (canvas's that dont have a parent canvas) are not ordered by the hierarchy as the data to do that just doesnt exist. So if you notice on each canvas there is a Order value (screen space camera and world space also have a layer value). These are what get used to determine the absolute ordering. 0 is the lowest any higher number will get drawn on top.
>
> https://forum.unity.com/threads/multiple-canvases-rendering-order-issue-bug.374982/#post-2429962

If someone has the same kinda issue on a single canvas I suggest fixing the child object order, as that is what Unity uses. So one can easily get tricked by what is seen vs. what the order actually is.

**Comment by maddscientistt** [comment]
I have a similar issue, I have the event manager as parent and tried making it as a child to canvas but still dint work, I'm using 2 canvas one for joysticks and other for UI, joystick works fine initially, after the player dies and when reload button is pressed. Scene reloads perfectly but Joystick doesn't work,
Please help me fix the problem

**Comment by Kinggrass** [comment]
Bug still exist, child reorder or reorder in general does not fix it.
The behaviour should be the same as the VRTK_UICanvas component is not applied. So like Unity is handling the order.

To Reproduce:
Open [007 - Interactions] InteractionHelpers and duplicate UICanvas set the Z-Position of UICanvas (1) to 0.235
Try to interact in Play Mode with UICanvas (wich is in front). you can only interact with the UI behind it.
I would suggest it is a order problem what is determined the "nearest". 

This is also the case if more than 2 duplicates are made and are set behind in row.
