### ISSUE TITLE
Button Direction Autodetect Not Working

### ISSUE THREAD

**Issue by robnewton** [thestonefox/VRTK#987]
### Environment

 * Unity Asset Store
 * 3.1.0
 * Unity 5.5.1f1

### Steps to reproduce

Create a button control and set the direction property to autodetect. Console gets spammed with the following error message:

```
NullReferenceException: Object reference not set to an instance of an object
VRTK.VRTK_Button.FixedUpdate () (at Assets/VRTK/Scripts/Controls/3D/VRTK_Button.cs:291)
```

The problem appears to be in DetectSetup() which is called twice. The first time through it's not hitting line 159 because Application.IsPlaying == false leaving buttonJoint null. The second time through it's also never getting to line 159 because the direction property is set to autodetect which causes it to exit early with a return false.

```
if (Application.isPlaying)
            {
                buttonJoint = GetComponent<ConfigurableJoint>();
```

```
if (finalDirection == ButtonDirection.autodetect)
            {
                activationDir = Vector3.zero;
                return false;
            }
```

### Expected behavior

The autodetect should detect the direction of the button automatically and not cause errors to come to the console.

### Current behavior

The console is filled each frame with the error message listed above which causes the FPS to drop considerably due to the high volume of console messages.

**Comment by thestonefox** [comment]
Try updating to the github master version. I cannot recreate the issue on github master

**Comment by robnewton** [comment]
Will do
