### ISSUE TITLE
TrackedController Index for Oculus Touch are set to uint.max, not allowing button presses to work

### ISSUE THREAD

**Issue by kendrome** [thestonefox/VRTK#989]
### Environment

 * Source of VRTK (Github)
 * Version of VRTK (c31cc32)
 * Version of Unity3D (Unity 5.5.0f3)

### Steps to reproduce

Import OculusUtilites
Drag OVRCameraRig into Scene
Set VRKT_SDK Manager to OculusVR

### Expected behavior

Button presses work on Oculus Touch Controllers

### Current behavior

Button presses are not working because the TrackedController.index is set to uint.max

Tracked the issue to commit 8d5e856

It looks like it might be caused by the Update function getting called before Enable

A temporary solution I have done is moving line 95
`            index = currentIndex;`
to inside the previous IF block

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/e4e5b58d8f72c42a6ca9f2085471db1f89bbf86f
