### ISSUE TITLE
Where is the GameObject with the VRTK_SDKManager script attached to it?

### ISSUE THREAD

**Issue by danksky** [thestonefox/VRTK#990]
Assuming I'm starting from a brand new SteamVR project and building with VRTK from the ground up, where is the GameObject with the VRTK_SDKManager script attached to it?

_Taken from VRTK "Getting Started":_
Import the [SteamVR Plugin] from the Unity Asset Store.
Drag the [CameraRig] prefab from the SteamVR plugin into the
scene.
Check that Virtual Reality Supported is ticked in the
Edit -> Project Settings -> Player menu.
Ensure that OpenVR is added in the Virtual Reality SDKs list
in the Edit -> Project Settings -> Player menu.
**Select the GameObject with the VRTK_SDKManager script attached
to it.**
Select Steam VR for each of the SDK Choices.
Click the Auto Populate Linked Objects button to find the
relevant Linked Objects.
Optionally, browse the Examples scenes for example usage of the
scripts.

**Comment by thestonefox** [comment]
You just create a game object and add the SDK Manager script to it.

Check this video https://www.youtube.com/watch?v=EH_rB8aoeM4&feature=youtu.be&t=145
