### ISSUE TITLE
VRTK_DestinationPoint.currentDestinationPoint never unset

### ISSUE THREAD

**Issue by SK83RJOSH** [thestonefox/VRTK#993]
I'm currently using this to check whether or not a destination point is in use. However it appears that once this value is set it's never properly unset (unless you teleport to another Destination Marker -- which may not be the case if you're mixing destination points with standard mesh teleportation).

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/5841ec358f2fea065423151dff47cdc3ed08fb66
