### ISSUE TITLE
Null controllerPointer crash in BasePointerRenderer

### ISSUE THREAD

**Issue by phr00t** [thestonefox/VRTK#996]
### Environment

Master branch, current release.
Unity 5.5.2p2

### Steps to reproduce

Use the BenzierPointerRenderer & VRTK Pointer, likely a problem with other pointer renderers.

### Expected behavior

Not crash.

### Current behavior

In this line:

https://github.com/thestonefox/VRTK/blob/master/Assets/VRTK/Scripts/Pointers/PointerRenderers/VRTK_BasePointerRenderer.cs#L291

... it is referencing controllingPointer.customOrigin, but on the following line, checks to see if controllingPointer is not null. If it was null, which happened in my testing, the function will bomb out with a NullReference exception on line 291.

I have a VTRK_Pointer on the same gameObject.

I wasn't able to test this pointer functionality at all due to this crash. Has it been working, or is it still an experimental change?

**Comment by thestonefox** [comment]
Are you setting the `VRTK_Pointer` Pointer Renderer field to the Beizier Pointer Render script?

If you look at one of the example scenes you'll see it working.

**Comment by phr00t** [comment]
Nope, fixed that.

However, it still looks a bit silly in the code, since why would be you be checking if controllerPointer is not null on line 292, if it would crash on 291 if that was the case?

**Comment by thestonefox** [comment]
So are you saying now that the pointer is working for you, but you think it shouldn't crash if it's not been set up correctly?

**Comment by phr00t** [comment]
I have yet to test if it works (which it probably does), but trying to trace back the problem led me to code that isn't structured correctly, which makes it appear a problem with VRTK, not my setup. If controllerPointer should never be null, then it is confusing when the code sometimes checks for null status improperly.

**Comment by thestonefox** [comment]
If you look at one of the pointer examples, you should see that they work without crashing. Which would suggest that if they are set up as expected then no crash would occur.

**Comment by phr00t** [comment]
Yes, I get that. I should be setup fine now. The code is still sloppy in that section (e.g. doing a null check *after* referencing it). You are even setting the gameObject active depending on if it is null or not, which if should always be setup properly & non-null, makes me wonder why you are doing it regularly in FixedUpdate.

**Comment by thestonefox** [comment]
if you have thoughts on a better way and can raise a pull request then that would be good.

**Comment by bddckr** [comment]
The things you see are because that code is moved over from the old Simple/BezierPointer. If you happen to have time to clean stuff up or fix it would be great if you can do a PR.

**Comment by bddckr** [comment]
Setting the game object active or disabling it is what I've done in the old pointer scripts and should probably be added to the new ones. The idea is to only add and enable the smoothing helper game objects if needed.

**Comment by phr00t** [comment]
I don't fully understand the pointer system as a whole, like you guys do, to feel confident in making the changes myself. I did make this change in my local project:

`        protected virtual void UpdatePointerOriginTransformFollow()
        {
            pointerOriginTransformFollow.enabled = controllingPointer != null;
            if (pointerOriginTransformFollow.enabled) {
                pointerOriginTransformFollow.gameObjectToFollow = (controllingPointer.customOrigin == null ? transform : controllingPointer.customOrigin).gameObject;
                pointerOriginTransformFollowGameObject.SetActive(true);

                pointerOriginTransformFollow.smoothsPosition = pointerOriginSmoothingSettings.smoothsPosition;
                pointerOriginTransformFollow.maxAllowedPerFrameDistanceDifference = pointerOriginSmoothingSettings.maxAllowedPerFrameDistanceDifference;
                pointerOriginTransformFollow.smoothsRotation = pointerOriginSmoothingSettings.smoothsRotation;
                pointerOriginTransformFollow.maxAllowedPerFrameAngleDifference = pointerOriginSmoothingSettings.maxAllowedPerFrameAngleDifference;
            } else if( pointerOriginTransformFollowGameObject != null ) {
                pointerOriginTransformFollowGameObject.SetActive(false);
            }
        }`

... which should clean up the null checking, but I'm not sure if it is a good solution for the whole process. I have still yet to test.

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/4e483f5512fdd517b6951c8f7d9a17b03f540111
