### ISSUE TITLE
VRTK_Slider Minimum/Maximum Limits ignored when "connectedTo" is non-null

### ISSUE THREAD

**Issue by smithmj5** [thestonefox/VRTK#997]
Using Unity 5.5.0f3, VR Toolkit version 3.1.0 from Unity Asset Store.

 * Open VR Toolkit example scene 025_Controls_Overview.
 * Select ExampleObjects/Sliders/SliderGroup - XAxis-MinMax/Slider.
 * Drag any GameObject (I used "ExampleObjects") into the "Connected To" field of the VRTK_Slider component.
 * Run the scene.

Note that the Minimum and Maximum Limit are now ignored - you can freely drag the slider outside of the track that it is on. Unassign the "Connected To" GameObject and run the scene again, and the slider will correctly be limited by the Minimum and Maximum Limit again.

**Comment by thestonefox** [comment]
The min/max limits are not ignored.

If you connect it to ExampleObjects then it will have just a huge range because of the object you've connected it to.

Try building the object with an appropriate connected to (like the Grabbable Slider does) and it will work.
