### ISSUE TITLE
Oculus Support Broken

### ISSUE THREAD

**Issue by mattboy64** [thestonefox/VRTK#998]
Grabbed latest on GitHub and Oculus support seems to be completely broken. Interactions no longer work and the hands are not tracking properly (looks like their root object (LocalAvatar) is getting reset or something).

Tried in example scene 17. The above issue happens. I attempted to debug to see why input wasn't working and didn't see any Y thumbstick pressure being applied. Disabling VRTK fixed the hand position.

Example Scenes 1-3 seemed to have proper hand positioning, but no input worked on any of them (not sure what 2 is supposed to do, but 3 didn't have a pointer).

Not sure if it's related but the Model Alias Left/Right Controllers don't seem to be getting assigned in the SDK Manager either.

Unity Version 5.5.1p2
VRTK Hash: cd7fea9e15c27e1903a12a72034e4d96994c89cc

**Comment by mattboy64** [comment]
@bddckr

**Comment by bddckr** [comment]
>Not sure if it's related but the Model Alias Left/Right Controllers don't seem to be getting assigned in the SDK Manager either.

Of course it's related?! Did you set them manually? It won't work without them set :smile: Is your SDK manager set up correctly for the Rift?

Also: Sounds like you're also using Oculus Avatar SDK, I think you have to do something else to support that, there's a video on that IIRC.

I have no Rift, so someone else will have to test and confirm the issue.

Paging @thestonefox :P

**Comment by mattboy64** [comment]
They used to get set with the auto-assign stuff, but don't seem to be getting caught anymore. I'm not sure what the aliases are used for. Yes, I assigned them myself and it didn't seem to help.

**Comment by thestonefox** [comment]
Maybe this is related too: https://github.com/thestonefox/VRTK/issues/989

I'll plug my rift in today and go through everything and fix any issues

**Comment by thestonefox** [comment]
Fixed with https://github.com/thestonefox/VRTK/commit/e4e5b58d8f72c42a6ca9f2085471db1f89bbf86f
